### ISSUE TITLE
Elasticsearch stoped working: After update from 1.4 to 1.5 

### ISSUE THREAD

**Issue by Johannes-GitHub** [zammad/zammad#1037]
Same like in #673 
The old hints doesn´t help...

**Comment by Johannes-GitHub** [comment]
`sudo service elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendo
   Active: failed (Result: exit-code) since Thu 2017-05-04 12:19:00 CEST; 5min a
     Docs: http://www.elastic.co
  Process: 56879 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_D
  Process: 56876 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd
 Main PID: 56879 (code=exited, status=1/FAILURE)

May 04 12:18:45 ZA01 systemd[1]: Starting Elasticsearch...
May 04 12:18:45 ZA01 systemd[1]: Started Elasticsearch.
May 04 12:19:00 ZA01 systemd[1]: elasticsearch.service: Main process exited, cod
May 04 12:19:00 ZA01 systemd[1]: elasticsearch.service: Unit entered failed stat
May 04 12:19:00 ZA01 systemd[1]: elasticsearch.service: Failed with result 'exit
lines 1-13/13 (END)
`

**Comment by monotek** [comment]
Whats in the elasticsearch log?

**Comment by Johannes-GitHub** [comment]
How can i find the log?

**Comment by monotek** [comment]
Have a look into /var/log/elasticsearch

**Comment by Johannes-GitHub** [comment]
Hi, 
thanks a lot, the log from yesterday: 

/var/log/elasticsearch# dir
elasticsearch-2016-12-22.log  elasticsearch-2017-03-06.log
elasticsearch-2016-12-23.log  elasticsearch-2017-03-08.log
elasticsearch-2016-12-26.log  elasticsearch-2017-03-10.log
elasticsearch-2016-12-27.log  elasticsearch-2017-03-11.log
elasticsearch-2016-12-28.log  elasticsearch-2017-03-13.log
elasticsearch-2016-12-29.log  elasticsearch-2017-03-16.log
elasticsearch-2016-12-31.log  elasticsearch-2017-03-17.log
elasticsearch-2017-01-01.log  elasticsearch-2017-03-20.log
elasticsearch-2017-01-02.log  elasticsearch-2017-03-23.log
elasticsearch-2017-01-09.log  elasticsearch-2017-04-10.log
elasticsearch-2017-01-16.log  elasticsearch-2017-04-13.log
elasticsearch-2017-01-17.log  elasticsearch-2017-04-19.log
elasticsearch-2017-01-24.log  elasticsearch-2017-04-20.log
elasticsearch-2017-01-29.log  elasticsearch-2017-04-22.log
elasticsearch-2017-01-30.log  elasticsearch-2017-04-23.log
elasticsearch-2017-02-03.log  elasticsearch-2017-04-24.log
elasticsearch-2017-02-06.log  elasticsearch-2017-04-25.log
elasticsearch-2017-02-07.log  elasticsearch-2017-05-02.log
elasticsearch-2017-02-09.log  elasticsearch-2017-05-04.log
elasticsearch-2017-02-10.log  elasticsearch_deprecation.log
elasticsearch-2017-02-16.log  elasticsearch_index_indexing_slowlog.log
elasticsearch-2017-02-17.log  elasticsearch_index_search_slowlog.log
elasticsearch-2017-02-21.log  elasticsearch.log
root@ZA01:/var/log/elasticsearch# vi elasticsearch-2017-05-05.log
root@ZA01:/var/log/elasticsearch# vi elasticsearch-2017-05-04.log
 .lang.IllegalStateException: unable to upgrade the mappings for the index [[zammad_production/Z0bDfJj4RwqjF6tGsMe3TQ]]
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:158) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:86) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.gateway.GatewayMetaState.upgradeMetaData(GatewayMetaState.java:245) ~[elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:89) [elasticsearch-5.3.1.jar:5.3.1]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_121]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_121]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_121]
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:825) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:50) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:825) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:50) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:191) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:183) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:183) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:173) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:161) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:96) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:43) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.node.Node.<init>(Node.java:489) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.node.Node.<init>(Node.java:242) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.3.1.jar:5.3.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.3.1.jar:5.3.1]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [Ticket]: No handler for type [attachment] declared on field [attachment]
2017-05-04T12:18:54,553][INFO ][o.e.e.NodeEnvironment    ] [eNHUjJI] using [1] data paths, mounts [[/ (/dev/mapper/ZA01--vg-root)]], net usable_space [108.7gb], net total_space [119.9gb], spins? [possibly], types [ext4]
[2017-05-04T12:18:54,555][INFO ][o.e.e.NodeEnvironment    ] [eNHUjJI] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-05-04T12:18:54,606][INFO ][o.e.n.Node               ] node name [eNHUjJI] derived from node ID [eNHUjJIxTiWma-7nkizIpg]; set [node.name] to override
[2017-05-04T12:18:54,607][INFO ][o.e.n.Node               ] version[5.3.1], pid[56879], build[5f9cf58/2017-04-17T15:52:53.846Z], OS[Linux/4.4.0-75-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-05-04T12:18:57,091][INFO ][o.e.p.PluginsService     ] [eNHUjJI] loaded module [aggs-matrix-stats]
[2017-05-04T12:18:57,091][INFO ][o.e.p.PluginsService     ] [eNHUjJI] loaded module [ingest-common]
[2017-05-04T12:18:57,091][INFO ][o.e.p.PluginsService     ] [eNHUjJI] loaded module [lang-expression]
[2017-05-04T12:18:57,091][INFO ][o.e.p.PluginsService     ] [eNHUjJI] loaded module [lang-groovy]
[2017-05-04T12:18:57,091][INFO ][o.e.p.PluginsService     ] [eNHUjJI] loaded module [lang-mustache]
[2017-05-04T12:18:57,092][INFO ][o.e.p.PluginsService     ] [eNHUjJI] loaded module [lang-painless]
[2017-05-04T12:18:57,092][INFO ][o.e.p.PluginsService     ] [eNHUjJI] loaded module [percolator]
[2017-05-04T12:18:57,092][INFO ][o.e.p.PluginsService     ] [eNHUjJI] loaded module [reindex]
[2017-05-04T12:18:57,092][INFO ][o.e.p.PluginsService     ] [eNHUjJI] loaded module [transport-netty3]
[2017-05-04T12:18:57,092][INFO ][o.e.p.PluginsService     ] [eNHUjJI] loaded module [transport-netty4]
[2017-05-04T12:18:57,097][INFO ][o.e.p.PluginsService     ] [eNHUjJI] no plugins loaded
[2017-05-04T12:19:00,730][ERROR][o.e.g.GatewayMetaState   ] [eNHUjJI] failed to read local state, exiting...
       at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:183) [elasticsearch-5.3.1.jar:5.3.1]

**Comment by Johannes-GitHub** [comment]
Think this is the error:
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [Ticket]: No handler for type [attachment] declared on field [attachment]

**Comment by monotek** [comment]
Try:
* systemctl stop elasticsearch
* /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-attachments
* systemctl start elasticsearch

**Comment by Johannes-GitHub** [comment]
Hi, thanks a lot, after this and a reboot  is working :). 
But what is the different between both way´s ^^? 

I also tried before): 

sudo /usr/share/elasticsearch/bin/elasticsearch-plugin remove mapper-attachments
sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-attachments
sudo service elasticsearch start

Thanks
Have a nice weekend

**Comment by monotek** [comment]
The difference is that elasticsearch is stopped before the install of mapper-attachments.
