### ISSUE TITLE
DEB Installer issue: Access denied for user 'zammad'@'' to database 'zammad'

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#1077]
HI,

I'm having an issue with the DEB installer.  The database is MySQL (as that's the database I have most experience with).  Webserver is nginx.

### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: DEB
* Operating system: Debian 8 Jessie
* Browser + version: Firefox 50.1.0 

### Expected behavior:

Zammad configuration wizard(?) in browser visible.  Database zammad with content.

### Actual behavior:

Debian default Debian webserver homepage.  zammad database is empty

```
$ mysql -u dba -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 552
Server version: 5.5.55-0+deb8u1 (Debian)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use zammad;
Database changed
mysql> show tables;
Empty set (0.00 sec)

mysql> exit
$
```

### Steps to reproduce the behavior:

Run the installer (done as root).
```
$ apt-get install mysql-server nginx
  [...]
$ apt-get install zammad
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libpq5 libreadline5
The following NEW packages will be installed:
  libpq5 libreadline5 zammad
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 73.2 MB of archives.
After this operation, 244 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ftp.de.debian.org/debian/ jessie/main libpq5 amd64 9.4.11-0+deb8u2 [125 kB]
Get:2 http://ftp.de.debian.org/debian/ jessie/main libreadline5 amd64 5.2+dfsg-2 [151 kB]
Get:3 https://deb.packager.io/gh/zammad/zammad/ jessie/stable zammad amd64 1.5.0-1494543773.8b6e9c2.jessie [72.9 MB]
Fetched 73.2 MB in 58s (1,247 kB/s)                                                                                                        
Selecting previously unselected package libpq5:amd64.
(Reading database ... 34574 files and directories currently installed.)
Preparing to unpack .../libpq5_9.4.11-0+deb8u2_amd64.deb ...
Unpacking libpq5:amd64 (9.4.11-0+deb8u2) ...
Selecting previously unselected package libreadline5:amd64.
Preparing to unpack .../libreadline5_5.2+dfsg-2_amd64.deb ...
Unpacking libreadline5:amd64 (5.2+dfsg-2) ...
Selecting previously unselected package zammad.
Preparing to unpack .../zammad_1.5.0-1494543773.8b6e9c2.jessie_amd64.deb ...
Unpacking zammad (1.5.0-1494543773.8b6e9c2.jessie) ...
Setting up libpq5:amd64 (9.4.11-0+deb8u2) ...
Setting up libreadline5:amd64 (5.2+dfsg-2) ...
Setting up zammad (1.5.0-1494543773.8b6e9c2.jessie) ...
# (Re)creating init scripts
Created symlink from /etc/systemd/system/multi-user.target.wants/zammad.service to /etc/systemd/system/zammad.service.
Created symlink from /etc/systemd/system/zammad.service.wants/zammad-web.service to /etc/systemd/system/zammad-web.service.
Scaling up...
Created symlink from /etc/systemd/system/zammad-web.service.wants/zammad-web-1.service to /etc/systemd/system/zammad-web-1.service.
--> done.
Created symlink from /etc/systemd/system/zammad.service.wants/zammad-websocket.service to /etc/systemd/system/zammad-websocket.service.
Scaling up...
Created symlink from /etc/systemd/system/zammad-websocket.service.wants/zammad-websocket-1.service to /etc/systemd/system/zammad-websocket-1.service.
--> done.
Created symlink from /etc/systemd/system/zammad.service.wants/zammad-worker.service to /etc/systemd/system/zammad-worker.service.
Scaling up...
Created symlink from /etc/systemd/system/zammad-worker.service.wants/zammad-worker-1.service to /etc/systemd/system/zammad-worker-1.service.
--> done.
# Enabling Zammad on boot
# Stopping Zammad
# Installing zammad on mysql
# Creating zammad mysql db
# Creating zammad mysql user
# Grant privileges to new mysql user
# Updating database.yml
rake aborted!
Mysql2::Error: Access denied for user 'zammad'@'' to database 'zammad'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `connect'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `initialize'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:87:in `connection'
/opt/zammad/config/initializers/db_preferences_mysql.rb:8:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/opt/zammad/config/environment.rb:5:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
rake aborted!
Mysql2::Error: Access denied for user 'zammad'@'' to database 'zammad'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `connect'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:in `initialize'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:87:in `connection'
/opt/zammad/config/initializers/db_preferences_mysql.rb:8:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/opt/zammad/config/environment.rb:5:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:182:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:abort_if_pending_migrations => environment
(See full trace by running task with --trace)
# Starting Zammad
# Creating webserver bootstart
Synchronizing state for nginx.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d nginx defaults
Executing /usr/sbin/update-rc.d nginx enable
# Restarting webserver nginx
####################################################################################

Add your FQDN to servername directive in /etc/nginx/sites-enabled/zammad.conf
and restart your webserver if you're not testing locally
or open http://localhost/ in your browser to start using Zammad.

####################################################################################
Processing triggers for libc-bin (2.19-18+deb8u9) ...
$ 
```

The issues seems to be the `Mysql2::Error: Access denied for user 'zammad'@'' to database 'zammad'` in the upper part of the installation log.  The user seems to be installed, but has no access from localhost(?):

```
mysql> select User,Host,Password from mysql.user;
+------------------+-----------+-------------------------------------------+
| User             | Host      | Password                                  |
+------------------+-----------+-------------------------------------------+
| root             | localhost | *XXXXXXXXXXXX |
| root             | tbi-vm03  | *XXXXXXXXXXXX |
| root             | 127.0.0.1 | *XXXXXXXXXXXX |
| root             | ::1       | *XXXXXXXXXXXX |
| debian-sys-maint | localhost | *XXXXXXXXXXXX |
| dba              | localhost | *XXXXXXXXXXXX |
| zammad           |           | *XXXXXXXXXXXX |
+------------------+-----------+-------------------------------------------+
7 rows in set (0.00 sec)

mysql> 
```

Cheers
frank

**Comment by ukcb** [comment]
You can help with the MYSQL command:

`GRANT ALL PRIVILEGES ON zammad.* TO 'zammad'@'localhost' IDENTIFIED BY 'password' WITH GRANT OPTION;`

This will not help you because MYSQL is too old. In jessie is not a mysql 5.6+ at the time.
I just installed postgresql, which worked.

**Comment by fthommen** [comment]
ok I see.  It works with MariaDB 10.x from the standard repos.

I - probably too naively - assumed, that  "Debian 8 is supported" meant, that whatever version of prerequistes Debian provided from its standard repositories were supported..

**Comment by monotek** [comment]
Debian 8 uses MySQL 5.5 by default which is not supported. See: https://docs.zammad.org/en/latest/prerequisites-software.html#database-server

**Comment by thorsteneckel** [comment]
Hi @fthommen - you are right. A pull request at https://github.com/zammad/zammad-documentation/blob/master/install-debian.rst is highly appreciated to avoid this issue for other users in the future. Thanks!
