### ISSUE TITLE
Docker RailsServer restarted with errors

### ISSUE THREAD

**Issue by diegodorgam** [zammad/zammad#1082]
Hey guys, having some trouble with Zammad Docker-Compose version in rancher.

I've tried to create custom fields in Object ticket, and some error ocurred, I couldn't catch the log, but I tried then to restart the railsserver container and the role server stopped, so I reinitiated the server and everything comes up again, but railsserver is failing to start, here is the log output:

```
13/05/2017 15:24:35railsserver can access postgresql server now...
13/05/2017 15:24:39/home/zammad/app/models/store/provider/file.rb:32:in `get': ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371 (RuntimeError)
13/05/2017 15:24:39	from /home/zammad/app/models/store/file.rb:62:in `content'
13/05/2017 15:24:39	from /home/zammad/app/models/store.rb:147:in `content'
13/05/2017 15:24:39	from /home/zammad/lib/static_assets.rb:141:in `filename'
13/05/2017 15:24:39	from /home/zammad/lib/static_assets.rb:126:in `read'
13/05/2017 15:24:39	from /home/zammad/lib/static_assets.rb:164:in `sync'
13/05/2017 15:24:39	from /home/zammad/config/initializers/logo.rb:4:in `<top (required)>'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `call'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
13/05/2017 15:24:39	from /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
13/05/2017 15:24:39	from /home/zammad/config/environment.rb:5:in `<top (required)>'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:39	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:52:in `<top (required)>'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:90:in `runner'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
13/05/2017 15:24:39	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
13/05/2017 15:24:39	from bin/rails:4:in `require'
13/05/2017 15:24:39	from bin/rails:4:in `<main>'
13/05/2017 15:24:43creating db & searchindex...
13/05/2017 15:24:46zammad_production already exists
13/05/2017 15:24:50rake aborted!
13/05/2017 15:24:50ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371
13/05/2017 15:24:50/home/zammad/app/models/store/provider/file.rb:32:in `get'
13/05/2017 15:24:50/home/zammad/app/models/store/file.rb:62:in `content'
13/05/2017 15:24:50/home/zammad/app/models/store.rb:147:in `content'
13/05/2017 15:24:50/home/zammad/lib/static_assets.rb:141:in `filename'
13/05/2017 15:24:50/home/zammad/lib/static_assets.rb:126:in `read'
13/05/2017 15:24:50/home/zammad/lib/static_assets.rb:164:in `sync'
13/05/2017 15:24:50/home/zammad/config/initializers/logo.rb:4:in `<top (required)>'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
13/05/2017 15:24:50/home/zammad/config/environment.rb:5:in `<top (required)>'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:50/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
13/05/2017 15:24:50/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
13/05/2017 15:24:50/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
13/05/2017 15:24:50/usr/local/bin/bundle:22:in `load'
13/05/2017 15:24:50/usr/local/bin/bundle:22:in `<main>'
13/05/2017 15:24:50Tasks: TOP => db:migrate => environment
13/05/2017 15:24:50(See full trace by running task with --trace)
13/05/2017 15:24:53rake aborted!
13/05/2017 15:24:53ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371
13/05/2017 15:24:53/home/zammad/app/models/store/provider/file.rb:32:in `get'
13/05/2017 15:24:53/home/zammad/app/models/store/file.rb:62:in `content'
13/05/2017 15:24:53/home/zammad/app/models/store.rb:147:in `content'
13/05/2017 15:24:53/home/zammad/lib/static_assets.rb:141:in `filename'
13/05/2017 15:24:53/home/zammad/lib/static_assets.rb:126:in `read'
13/05/2017 15:24:53/home/zammad/lib/static_assets.rb:164:in `sync'
13/05/2017 15:24:53/home/zammad/config/initializers/logo.rb:4:in `<top (required)>'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
13/05/2017 15:24:53/home/zammad/config/environment.rb:5:in `<top (required)>'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:53/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
13/05/2017 15:24:53/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
13/05/2017 15:24:53/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:182:in `block (2 levels) in <top (required)>'
13/05/2017 15:24:53/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
13/05/2017 15:24:53/usr/local/bin/bundle:22:in `load'
13/05/2017 15:24:53/usr/local/bin/bundle:22:in `<main>'
13/05/2017 15:24:53Tasks: TOP => db:abort_if_pending_migrations => environment
13/05/2017 15:24:53(See full trace by running task with --trace)
13/05/2017 15:24:57rake aborted!
13/05/2017 15:24:57ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371
13/05/2017 15:24:57/home/zammad/app/models/store/provider/file.rb:32:in `get'
13/05/2017 15:24:57/home/zammad/app/models/store/file.rb:62:in `content'
13/05/2017 15:24:57/home/zammad/app/models/store.rb:147:in `content'
13/05/2017 15:24:57/home/zammad/lib/static_assets.rb:141:in `filename'
13/05/2017 15:24:57/home/zammad/lib/static_assets.rb:126:in `read'
13/05/2017 15:24:57/home/zammad/lib/static_assets.rb:164:in `sync'
13/05/2017 15:24:57/home/zammad/config/initializers/logo.rb:4:in `<top (required)>'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
13/05/2017 15:24:57/home/zammad/config/environment.rb:5:in `<top (required)>'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:24:57/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
13/05/2017 15:24:57/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
13/05/2017 15:24:57/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
13/05/2017 15:24:57/usr/local/bin/bundle:22:in `load'
13/05/2017 15:24:57/usr/local/bin/bundle:22:in `<main>'
13/05/2017 15:24:57Tasks: TOP => searchindex:rebuild => environment
13/05/2017 15:24:57(See full trace by running task with --trace)
13/05/2017 15:24:57starting zammad...
13/05/2017 15:24:57zammad will be accessable on http://localhost in some seconds
13/05/2017 15:24:58Puma starting in single mode...
13/05/2017 15:24:58* Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
13/05/2017 15:24:58* Min threads: 5, max threads: 30
13/05/2017 15:24:58* Environment: production
13/05/2017 15:25:01! Unable to load application: RuntimeError: ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371
13/05/2017 15:25:01bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
13/05/2017 15:25:01RuntimeError: ERROR: No such file /home/zammad/storage/fs/46f4/bbc1/1a20c/98d79/cbd1356/8769d0b/7a9a88643f12eb5c96b68d75a5c55371
13/05/2017 15:25:01  /home/zammad/app/models/store/provider/file.rb:32:in `get'
13/05/2017 15:25:01  /home/zammad/app/models/store/file.rb:62:in `content'
13/05/2017 15:25:01  /home/zammad/app/models/store.rb:147:in `content'
13/05/2017 15:25:01  /home/zammad/lib/static_assets.rb:141:in `filename'
13/05/2017 15:25:01  /home/zammad/lib/static_assets.rb:126:in `read'
13/05/2017 15:25:01  /home/zammad/lib/static_assets.rb:164:in `sync'
13/05/2017 15:25:01  /home/zammad/config/initializers/logo.rb:4:in `<top (required)>'
13/05/2017 15:25:01  /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:25:01  /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
13/05/2017 15:25:01  /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
13/05/2017 15:25:01  /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
13/05/2017 15:25:01  /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `call'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
13/05/2017 15:25:01  /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
13/05/2017 15:25:01  /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
13/05/2017 15:25:01  /home/zammad/config/environment.rb:5:in `<top (required)>'
13/05/2017 15:25:01  config.ru:3:in `require'
13/05/2017 15:25:01  config.ru:3:in `block in <main>'
13/05/2017 15:25:01  /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
13/05/2017 15:25:01  /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
13/05/2017 15:25:01  config.ru:in `new'
13/05/2017 15:25:01  config.ru:in `<main>'
13/05/2017 15:25:01  /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
13/05/2017 15:25:01  /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
13/05/2017 15:25:01  /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
13/05/2017 15:25:01  /usr/local/bundle/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
13/05/2017 15:25:01  /usr/local/bundle/bin/puma:17:in `load'
13/05/2017 15:25:01  /usr/local/bundle/bin/puma:17:in `<top (required)>'
```

after those logs, railsserver container just stops.. Any Ideas?

**Comment by thorsteneckel** [comment]
Hi @diegodorgam - please use the [Zammad Docker-Compose repository](https://github.com/zammad/zammad-docker-compose) for related issues. Thanks.
