### ISSUE TITLE
StatusCode: 500 `{"error":"Circular dependency detected while autoloading constant Service::GeoIp"}`

### ISSUE THREAD

**Issue by Linus2017** [zammad/zammad#1140]
Hello, 

after the login I get the following message:

StatusCode: 500
`{"error":"Circular dependency detected while autoloading constant Service::GeoIp"}`

What is the solution?

**Comment by martini** [comment]
Hi @Linus2017 

it seems to be a ruby issue (bug). Can you tell me how to reproduce hit? What Zammad version do you use?

 -Martin

**Comment by Linus2017** [comment]
Hi martini,

thank you for your feedback. This message occurs after login. The user who appears with this message is an administrator. What further information do you need?

Where can I find the Zammad version? Under Settings > Version only "This is Zammad version 1.5.x" is displayed. Do you still need the Ruby version?

**Comment by gerbsen** [comment]
Same issue here. Health status says:

```{
	"healthy": false,
	"message": "Channel: Email::Notification out  Can't use Channel::Driver::Smtp: #\u003cSocketError: getaddrinfo: Temporary failure in name resolution\u003e",
	"issues": [
	"Channel: Email::Notification out  Can't use Channel::Driver::Smtp: #\u003cSocketError: getaddrinfo: Temporary failure in name resolution\u003e"
	],
	"token": "789234jnsdfnjkhsdfhksdhjfhjshdafjhsajkhfjhsdfh"
}```

**Comment by jaykijay** [comment]
same here with 1.6.1-150099

**Comment by martini** [comment]
@jaykijay 
Is it reproducible? If yes, remote login would be very good (I can't reproduce it :-/).

**Comment by monclefu** [comment]
I got this error often after upgrade over APT. So Update -> reboot -> first logon -> this error.

**Comment by hanneshal** [comment]
Closed. 
Please reopen if the issue still exists in Version 2.0.

**Comment by em-ex** [comment]
Have just encountered this issue upon logging in as admin after **enabling SSL** in apache2 (Debian 9 x86, Zammad 2.0.0 from source). 

Immediately received "signin detected from a new device" email notification with "unknown" location.

log/production.log excerpt:

```
E, [2017-10-21T01:53:53.352412 #8974] ERROR -- : Circular dependency detected while autoloading constant Service::GeoIp (RuntimeError)
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:492:in `load_missing_constant'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/zammad/app/controllers/application_controller/has_user.rb:47:in `session_update'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:164:in `block in halting'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `block in call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `each'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/abstract_controller/callbacks.rb:19:in `process_action'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_controller/metal/rescue.rb:29:in `process_action'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `instrument'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/abstract_controller/base.rb:137:in `process'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionview-4.2.9/lib/action_view/rendering.rb:30:in `process'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_controller/metal.rb:196:in `dispatch'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_controller/metal.rb:237:in `block in action'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:30:in `each'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:30:in `serve'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:817:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/omniauth-1.6.1/lib/omniauth/builder.rb:63:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/conditionalget.rb:25:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/middleware/flash.rb:260:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/query_cache.rb:36:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/railties-4.2.9/lib/rails/rack/logger.rb:38:in `call_app'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/railties-4.2.9/lib/rails/rack/logger.rb:20:in `block in call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:68:in `tagged'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/railties-4.2.9/lib/rails/rack/logger.rb:20:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/actionpack-4.2.9/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/activesupport-4.2.9/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/railties-4.2.9/lib/rails/engine.rb:518:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/railties-4.2.9/lib/rails/application.rb:165:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2017-10-21T01:53:53.354998 #8974]  INFO -- : Completed 500 Internal Server Error in 131ms (Views: 0.7ms | ActiveRecord: 38.4ms)
```

Any thoughts how to fix GeoIP service? It worked fine with plain HTTP
