### ISSUE TITLE
Problem Pipe (Fetchmail)

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1145]
### Infos:

* Used Zammad version: cat /opt/zammad/VERSION 1.5.x
* Used Zammad installation source: (source, package, ...) Ubuntu DEB
* Operating system: cat /proc/version 
Linux version 4.4.0-78-generic (buildd@lgw01-11) (gcc version 5.4.0 20160609 (Ubuntu5.4.0-6ubuntu1~16.04.4) ) # 99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017

### Expected behavior:
I'm trying right now to get e-mails running and right at the start I get the following error.
```
 su - zammad
zammad@zammad:~$ cd /opt/zammad/
zammad@zammad:/opt/zammad$ cat test/fixtures/mail1.box | rails r 'Channel::Driver::MailStdin.new(trusted: true)'
/opt/zammad/config/environments/development.rb:37:in `block in <top (required)>': uninitialized constant Rack::LiveReload (NameError)
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `instance_eval'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `configure'
        from /opt/zammad/config/environments/development.rb:1:in `<top (required)>'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `each'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
        from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
        from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
        from /opt/zammad/config/environment.rb:5:in `<top (required)>'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:52:in `<top (required)>'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:90:in `runner'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
 
```

**Comment by martini** [comment]
Hi @MamoulianDelacroix 

you need to set your RAILS_ENV first.

`export RAILS_ENV=production`

then use:

`cat test/fixtures/mail1.box | rails r 'Channel::Driver::MailStdin.new(trusted: true)'`

And it will work.

PS: In case, try to use the Zammad OS packages. All these settings are set per default.


 -Martin

**Comment by MamoulianDelacroix** [comment]
Sadly, this didn't help 😢 
Then I did a complet fresh installation, like here described https://docs.zammad.org/en/latest/install-ubuntu.html, 
When I now run the commands I get the follwoing:
```
root@zammad:~# su - zammad
zammad@zammad:~$ cat test/fixtures/mail1.box | rails r 'Channel::Driver::MailStdin.new(trusted: true)'c^C
zammad@zammad:~$ cd /opt/zammad/
zammad@zammad:/opt/zammad$ cat test/fixtures/mail1.box | rails r 'Channel::Driver::MailStdin.new(trusted: true)'
Die Anwendung »rails« ist momentan nicht installiert. Um das Programm »rails« ausführen zu können, benötigen Sie das Paket »ruby-railties«. Bitten Sie gegebenenfalls den Systemverwalter, dieses Paket zu installieren.
```
So I installed that:
```
root@zammad:~# apt install ruby-railties
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  libgmp-dev libgmpxx4ldbl linux-headers-4.4.0-57 linux-headers-4.4.0-57-generic linux-headers-4.4.0-72 linux-headers-4.4.0-72-generic linux-image-4.4.0-57-generic linux-image-4.4.0-72-generic
  linux-image-extra-4.4.0-57-generic linux-image-extra-4.4.0-72-generic
Verwenden Sie »apt autoremove«, um sie zu entfernen.
Die folgenden NEUEN Pakete werden installiert:
  ruby-railties
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 23 nicht aktualisiert.
Es müssen 115 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 710 kB Plattenplatz zusätzlich benutzt.
Holen:1 http://de.archive.ubuntu.com/ubuntu xenial/universe amd64 ruby-railties all 2:4.2.6-1 [115 kB]
Es wurden 115 kB in 0 s geholt (359 kB/s).
Vormals nicht ausgewähltes Paket ruby-railties wird gewählt.
(Lese Datenbank ... 184400 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../ruby-railties_2%3a4.2.6-1_all.deb ...
Entpacken von ruby-railties (2:4.2.6-1) ...
ruby-railties (2:4.2.6-1) wird eingerichtet ...
```
And tried it again:
```
root@zammad:~# su - zammad
zammad@zammad:~$ cd /opt/zammad/
zammad@zammad:/opt/zammad$ cat test/fixtures/mail1.box | rails r 'Channel::Driver::MailStdin.new(trusted: true)'
Could not find json-1.8.6 in any of the sources
Run `bundle install` to install missing gems.
```
I tried to install that:
```
zammad@zammad:/opt/zammad$ bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Using rake 11.2.2
Using i18n 0.8.1
Fetching json 1.8.6
Using minitest 5.10.1
Using thread_safe 0.3.6
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 1.6.4
Using mime-types-data 3.2016.0521
Using arel 6.0.3
Using thor 0.19.1
Using concurrent-ruby 1.0.2
Using bundler 1.15.0
Using multi_json 1.12.1
Fetching mysql2 0.4.4
Fetching pg 0.18.4
Installing json 1.8.6 with native extensions
Installing pg 0.18.4 with native extensions
Installing mysql2 0.4.4 with native extensions
Using sass 3.4.22
Using tilt 2.0.5
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using eco-source 1.1.0.rc.1
Using multipart-post 2.0.0
Using jwt 1.5.4
Using oauth 0.5.1
Using hashie 3.4.4
Using multi_xml 0.5.5
Using addressable 2.4.0
Using buftok 0.2.0
Fetching unf_ext 0.0.7.2
Using equalizer 0.0.10
Using http-form_data 1.0.1
Fetching http_parser.rb 0.6.0
Using naught 1.1.0
Using simple_oauth 0.3.1
Using netrc 0.11.0
Using dnsruby 1.59.3
Using htmlentities 4.3.4
Using clavius 1.0.2
Using daemons 1.2.4
Using simple-rss 1.3.1
Using libv8 3.16.14.15 (x86_64-linux)
Using ref 2.0.0
Using net-ldap 0.15.0
Fetching ffi 1.9.14
Installing http_parser.rb 0.6.0 with native extensions
Installing unf_ext 0.0.7.2 with native extensions
Installing ffi 1.9.14 with native extensions
Using writeexcel 1.0.5
Using icalendar 2.4.1
Using browser 2.2.0
Using slack-notifier 1.5.1
Using nestful 1.1.1
Using inflection 1.0.0
Using scrub_rb 1.0.1
Fetching eventmachine 1.2.0.1
Using diffy 3.1.0
Fetching puma 3.6.0
Installing puma 3.6.0 with native extensions
Installing eventmachine 1.2.0.1 with native extensions
Fetching kgio 2.11.0
Installing kgio 2.11.0 with native extensions
Fetching raindrops 0.17.0
Using tzinfo 1.2.2
Using memoizable 0.4.2
Fetching nokogiri 1.7.1
Using rack-test 0.6.3
Using mime-types 3.1
Using sprockets 3.7.0
Installing raindrops 0.17.0 with native extensions
Installing nokogiri 1.7.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /opt/zammad/vendor/bundle/ruby/2.3.0/gems/pg-0.18.4/ext
/usr/bin/ruby2.3 -r ./siteconf20170529-3289-c0lyoo.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /opt/zammad/vendor/bundle/ruby/2.3.0/gems/pg-0.18.4 for inspection.
Results logged to /opt/zammad/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.18.4/gem_make.out

An error occurred while installing pg (0.18.4), and Bundler cannot continue.
Make sure that `gem install pg -v '0.18.4'` succeeds before bundling.

In Gemfile:
  pg
zammad@zammad:/opt/zammad$ gem install pg -v '0.18.4'
Fetching: pg-0.18.4.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
zammad@zammad:/opt/zammad$ sudo gem install pg -v '0.18.4'
[sudo] Passwort für zammad:
Building native extensions.  This could take a while...
ERROR:  Error installing pg:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/pg-0.18.4/ext
/usr/bin/ruby2.3 -r ./siteconf20170529-3424-2151i7.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/pg-0.18.4 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.18.4/gem_make.out
```
And now, my zammad doesn't work anymore. I get a bad:
```
502 Bad Gateway
nginx/1.10.0 (Ubuntu)
```
So I reinstalled zammad from scratch again.
As soon as I try to 
```root@zammad:~# su - zammad
zammad@zammad:~$ cd /opt/zammad/
zammad@zammad:/opt/zammad$ cat test/fixtures/mail1.box | rails r 'Channel::Driver::MailStdin.new(trusted: true)'
Could not find json-1.8.6 in any of the sources
Run `bundle install` to install missing gems.
```
And then try to do
```
zammad@zammad:/opt/zammad$ bundle install
```
my zammad installation is gone again.

**Comment by martini** [comment]
I see, it's all rails install/setup issues. What is the reason why not installing den Zammad OS Ubuntu packages? Then you can skip all this issue (all is done automatically for you - including upgrade procedures).

**Comment by martini** [comment]
Sorry, I see you did install the package?

> Then I did a complet fresh installation, like here described https://docs.zammad.org/en/latest/install-ubuntu.html,... 

If you did, use:

`root@host> zammad run cat test/fixtures/mail1.box | rails r 'Channel::Driver::MailStdin.new(trusted: true)'`

In case of installing the Zammad OS package, you always need to use `zammad run`, see also: https://docs.zammad.org/en/latest/admin-console.html

Is that working? 

PS: If you use the Zammad OS package you never need to install any package/gem or ruby version. It's all included.

**Comment by MamoulianDelacroix** [comment]
aaahhh 😃 
that's looks a bit better
```
root@zammad:~# zammad run cat test/fixtures/mail1.box | rails r 'Channel::Driver::MailStdin.new(trusted: true)'
Usage:
  rails new APP_PATH [options]

Options:
  -r, [--ruby=PATH]                                      # Path to the Ruby binary of your choice
                                                         # Default: /usr/bin/ruby
  -m, [--template=TEMPLATE]                              # Path to some application template (can be a filesystem path or URL)
      [--skip-gemfile], [--no-skip-gemfile]              # Don't create a Gemfile
  -B, [--skip-bundle], [--no-skip-bundle]                # Don't run bundle install
  -G, [--skip-git], [--no-skip-git]                      # Skip .gitignore file
      [--skip-keeps], [--no-skip-keeps]                  # Skip source control .keep files
  -O, [--skip-active-record], [--no-skip-active-record]  # Skip Active Record files
  -S, [--skip-sprockets], [--no-skip-sprockets]          # Skip Sprockets files
      [--skip-spring], [--no-skip-spring]                # Don't install Spring application preloader
  -d, [--database=DATABASE]                              # Preconfigure for selected database (options: mysql/oracle/postgresql/sqlite3/frontbase/ibm_db/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
                                                         # Default: sqlite3
  -j, [--javascript=JAVASCRIPT]                          # Preconfigure for selected JavaScript library
                                                         # Default: jquery
  -J, [--skip-javascript], [--no-skip-javascript]        # Skip JavaScript files
      [--dev], [--no-dev]                                # Setup the application with Gemfile pointing to your Rails checkout
      [--edge], [--no-edge]                              # Setup the application with Gemfile pointing to Rails repository
      [--skip-turbolinks], [--no-skip-turbolinks]        # Skip turbolinks gem
  -T, [--skip-test-unit], [--no-skip-test-unit]          # Skip Test::Unit files
      [--rc=RC]                                          # Path to file containing extra configuration options for rails command
      [--no-rc], [--no-no-rc]                            # Skip loading of extra configuration options from .railsrc file

Runtime options:
  -f, [--force]                    # Overwrite files that already exist
  -p, [--pretend], [--no-pretend]  # Run but do not make any changes
  -q, [--quiet], [--no-quiet]      # Suppress status output
  -s, [--skip], [--no-skip]        # Skip files that already exist

Rails options:
  -h, [--help], [--no-help]        # Show this help message and quit
  -v, [--version], [--no-version]  # Show Rails version number and quit

Description:
    The 'rails new' command creates a new Rails application with a default
    directory structure and configuration at the path you specify.

    You can specify extra command-line arguments to be used every time
    'rails new' runs in the .railsrc configuration file in your home directory.

    Note that the arguments specified in the .railsrc file don't affect the
    defaults values shown above in this help message.

Example:
    rails new ~/Code/Ruby/weblog

    This generates a skeletal Rails installation in ~/Code/Ruby/weblog.
    See the README in the newly created application to get going.

```

**Comment by MamoulianDelacroix** [comment]
Oh, I see I didn't something wrong above.
I executed the command from /root/ instead from /opt/zammad/
When I switch to the correct folder I get this:
```
root@zammad:/opt/zammad# zammad run cat test/fixtures/mail1.box | rails r 'Channel::Driver::MailStdin.new(trusted: true)'
Could not find json-1.8.6 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by MamoulianDelacroix** [comment]
Ok, I found kind a solution:
```
root@zammad:/opt/zammad# cat test/fixtures/mail1.box | zammad run rails r 'Channel::Driver::MailStdin.new(trusted: true)'
```
This did the trick.
