### ISSUE TITLE
Problem sending e-mails / e-mail relaying

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1154]
Hello, hello ^^

since our zammad-system finally can receive e-mail via fetchmail ( #1145).
I'm now trying to get my e-mail sending done.
Right now, the e-mail notification via postfix is working fine 🤞 
![screenshot_6](https://cloud.githubusercontent.com/assets/4436931/26631352/e9258a3c-460a-11e7-8c17-37fa99510ac1.jpg)

But when I try to reply to a customer-request, I get the following
![screenshot_4](https://cloud.githubusercontent.com/assets/4436931/26631391/120a22d2-460b-11e7-880a-96fe3fdd4bbe.jpg)
Which is totally correct, since I don't have any E-Mail-Accounts configerd
![screenshot_5](https://cloud.githubusercontent.com/assets/4436931/26631420/2f163302-460b-11e7-8417-cbfffff5d5f0.jpg)

Since I'm useing fetchmail I hoped this wouldn't be necessary. So is there a way to use the internal postfix for that, which already is sending the notification or can I use a SMTP-Relay-Server? Or did I mixed up / miss something?

**Comment by thorsteneckel** [comment]
Hihi ;)

What is configured in your Users group?

<img width="715" alt="bildschirmfoto 2017-05-31 um 15 38 01" src="https://cloud.githubusercontent.com/assets/3873515/26634511/34941dce-4617-11e7-9a88-f0f325397229.png">

**Comment by thorsteneckel** [comment]
Ok this is empty because of the missing email account configuration as you stated in your initial post / screenshot. You have to configure a new account. You can use the same as for your notifications but you need to configure it as an outgoing email account.

**Comment by MamoulianDelacroix** [comment]
Well, I think, that's the problem.
I don't need any account to send my e-mails via local postfix. 

![screenshot_9](https://cloud.githubusercontent.com/assets/4436931/26637716/840b7bd2-4620-11e7-889f-e70059ce454b.jpg)

my postfix is just allowd to send emails

```
"cat /etc/postfix/main.cf"
```
![screenshot_10](https://cloud.githubusercontent.com/assets/4436931/26637809/c704295c-4620-11e7-80a8-b5b83d400965.jpg)

**Comment by thorsteneckel** [comment]
Thanks! Now I get it. Sadly I have no solution for this... @martini ?

**Comment by MamoulianDelacroix** [comment]
I found a quick and dirty workaround for my problem.
On my zammad-server I installed dovecot-imapd and created an empty dummy mailbox for zammad.
After I integrated that to zammad, I could change the email-address to the fetchmail one.
And now everything is working like intended in my test-environment.

But still, it would be nice if there was a possible to use postfix directly for sending.

**Comment by MrGeneration** [comment]
By now it's possible to workaround this with an outbound only channel.
This is described here: https://admin-docs.zammad.org/en/latest/channel-email/sendmail.html

I'll thus be closing this issue, because I believe that this is solved by the above (even though you got a workaround).

If you feel this is wrong, please let me know!

**Comment by NeoLegends** [comment]
Sorry for replying to this long closed ticket, but is it also possible to configure an outbound-only SMTP channel? Reason being I'd like to receive emails via a GSuite channel but send out the replies via SendGrid.

I tried

```
rails r "Channel.create(area: 'Email::Account', options: {inbound: {adapter:'null', options: {}}, outbound: {adapter: 'smtp', options:{host: 'smtp.sendgrid.net', port: 587, user: 'apikey', password: 'my sendgrid key', ssl_verify: true}}})"
```

but got

```
/usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': PG::NotNullViolation: ERROR:  null value in column "updated_by_id" of relation "channels" violates not-null constraint (ActiveRecord::NotNullViolation)
DETAIL:  Failing row contains (4, null, Email::Account, ---
inbound:
  adapter: 'null'
  options: {}
outbound:
  adapter..., t, null, null, null, null, null, null, null, 2024-11-05 12:06:25.951, 2024-11-05 12:06:25.951).

	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `block (2 levels) in exec_no_cache'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql_adapter.rb:767:in `block in exec_no_cache'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract_adapter.rb:752:in `block in log'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract_adapter.rb:743:in `log'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql_adapter.rb:766:in `exec_no_cache'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql_adapter.rb:745:in `execute_and_clear'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/database_statements.rb:132:in `exec_insert'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:88:in `exec_insert'
	from /usr/local/bundle/gems/composite_primary_keys-14.0.9/lib/composite_primary_keys/connection_adapters/abstract/database_statements.rb:6:in `insert'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/persistence.rb:496:in `_insert_record'
	from /usr/local/bundle/gems/composite_primary_keys-14.0.9/lib/composite_primary_keys/persistence.rb:77:in `_create_record'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/counter_cache.rb:166:in `_create_record'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/locking/optimistic.rb:84:in `_create_record'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/attribute_methods/dirty.rb:222:in `_create_record'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/callbacks.rb:459:in `block in _create_record'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:107:in `run_callbacks'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:929:in `_run_create_callbacks'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/callbacks.rb:459:in `_create_record'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/timestamp.rb:108:in `_create_record'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/persistence.rb:1069:in `create_or_update'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/callbacks.rb:455:in `block in create_or_update'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:107:in `run_callbacks'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:929:in `_run_save_callbacks'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/callbacks.rb:455:in `create_or_update'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/timestamp.rb:126:in `create_or_update'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/persistence.rb:615:in `save'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/validations.rb:47:in `save'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/transactions.rb:298:in `block in save'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	from /usr/local/bundle/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/transactions.rb:298:in `save'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/suppressor.rb:50:in `save'
	from /usr/local/bundle/gems/activerecord-7.0.8.4/lib/active_record/persistence.rb:38:in `create'
	from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/commands/runner/runner_command.rb:46:in `<main>'
	from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/commands/runner/runner_command.rb:46:in `eval'
	from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/commands/runner/runner_command.rb:46:in `perform'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/command/base.rb:87:in `perform'
	from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/command.rb:48:in `invoke'
	from /usr/local/bundle/gems/railties-7.0.8.4/lib/rails/commands.rb:18:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:5:in `<main>'
```

**Comment by MrGeneration** [comment]
@NeoLegends please do not abuse already closed issues with your technical questions.
Technical questions belong into our community: https://community.zammad.org

Thank you.
