### ISSUE TITLE
Rest API-Request

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1188]
Hello,

I'm just trying to test the Rest API, but I'm stucked right now. Probalby I'm doing something wrong, but I don't know why.
I simple just want to see all tickets from a group.
```
curl -k -H "Authorization: Token token=hwZSvIkum1xZaSo5KQ5XWnIFkGV1ikxygRdCSCmeEhEe6M2NHZJ_QMkapGnbriiZ" "https://zammad-server/api/v1/tickets/search?group=Kunde-A&limit=3"
```
And everytime I send this request, I get the three newest tickets in our system.
I'm frusted right now 😞

**Comment by martini** [comment]
> I'm frusted right now 😞

Me too.

Did you see https://docs.zammad.org/en/latest/api-ticket.html

What if you use the query param?

```GET /api/v1/tickets/search?query=what&limit=10```

**Comment by martini** [comment]
A short feedback if it works with query param would be fine. Thanks!

**Comment by MamoulianDelacroix** [comment]
Hi,

I was on my way out of office when I wrote my post.
When I run your command
```
curl -k -H "Authorization: Token token=hwZSvIkum1xZaSo5KQ5XWnIFkGV1ikxygRdCSCmeEhEe6M2NHZJ_QMkapGnbriiZ" "https://zammad-server/api/v1/tickets/search?query=what&limit=10"
```
I get this:
```
{"tickets":[],"tickets_count":0,"assets":{}}
```

**Comment by martini** [comment]
@MamoulianDelacroix If you have no ticket wicht content "what" it's ok.

One more note, if you want to search von certain queries like "attribute:value" you need to use elastic search. Did you install elasticsearch?

In case you did it, your query can look like this `/api/v1/tickets/search?query=group%3Asome_group&limit=10` (%3A is just url encoding and means just one ":")

References: Search Cheat Sheet https://docs.zammad.org/en/latest/general-search.html

One more note, in case you can also use `expand=true` to get the result as array set

`/api/v1/tickets/search?query=group%3Asome_group&limit=10&expand=true`

**Comment by MamoulianDelacroix** [comment]
@martini Yes I had no Ticket with "what" in it. For testing purpose I added that to two tickets and I get these tickets back, when I run 
```
/api/v1/tickets/search?query=what&limit=10
```
but when I run 
```
/api/v1/tickets/search?query=group_name%3Atest&limit=10
```
I get none. But I have a group called "test" and it has a ticket.
Regarding elastic search, I installed zammad out of your repository. Does it contain elasticsearch?

**Comment by martini** [comment]
> Regarding elastic search, I installed zammad out of your repository. Does it contain elasticsearch?

No. You need to do it as additional step (because of external elastic repo):

https://docs.zammad.org/en/latest/install-elasticsearch.html

**Comment by MamoulianDelacroix** [comment]
Thanks @martini .
I'm just trying to install Elasticsearch according your guid but I'm running into some trouble at the end.
```
root@itszammad:/opt/zammad# zammad run rake searchindex:rebuild --trace
** Invoke searchindex:rebuild (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute searchindex:rebuild
** Execute searchindex:drop
drop indexes...
** Execute searchindex:create
create indexes...
rake aborted!
Unable to process PUT at http://127.0.0.1:9200/zammad_production
#<UserAgent::Result:0x0055e95906e5d0 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:9200 (Connection refused - connect(2) for \"127.0.0.1\" port 9200)>">
/opt/zammad/lib/search_index_backend.rb:62:in `index'
/opt/zammad/lib/tasks/search_index_es.rake:19:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/opt/zammad/lib/tasks/search_index_es.rake:60:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => searchindex:rebuild
```

**Comment by martini** [comment]
What if your try it with:

`zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"`

Seems to be a network config issue.

**Comment by MamoulianDelacroix** [comment]
Runs just like fine
```
root@itszammad:/opt/zammad# zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"
root@itszammad:/opt/zammad#
```

**Comment by martini** [comment]
Good. Then you need to index your elastic search. Is this now working?

`zammad run rake searchindex:rebuild`

**Comment by MamoulianDelacroix** [comment]
Hmmm my elasticsearch keeps stop working somehow
```
root@itszammad:/opt/zammad# /etc/init.d/elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Di 2017-06-20 09:55:30 CEST; 1min 16s ago
     Docs: http://www.elastic.co
  Process: 31226 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet -Edefault.path.logs=${LOG_DIR} -Edefault.path.data=${DATA_DIR} -Edefault.path.conf=${CONF_DIR} (code=killed, signal=KILL)
  Process: 31217 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
 Main PID: 31226 (code=killed, signal=KILL)

Jun 20 09:54:39 itszammad systemd[1]: Starting Elasticsearch...
Jun 20 09:54:40 itszammad systemd[1]: Started Elasticsearch.
Jun 20 09:55:30 itszammad systemd[1]: elasticsearch.service: Main process exited, code=killed, status=9/KILL
Jun 20 09:55:30 itszammad systemd[1]: elasticsearch.service: Unit entered failed state.
Jun 20 09:55:30 itszammad systemd[1]: elasticsearch.service: Failed with result 'signal'.
root@itszammad:/opt/zammad# /etc/init.d/elasticsearch start
[ ok ] Starting elasticsearch (via systemctl): elasticsearch.service.
root@itszammad:/opt/zammad# zammad run rake searchindex:rebuild --trace
** Invoke searchindex:rebuild (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute searchindex:rebuild
** Execute searchindex:drop
drop indexes...
** Execute searchindex:create
create indexes...
rake aborted!
Unable to process PUT at http://localhost:9200/zammad_production
#<UserAgent::Result:0x005561be61fb78 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::EADDRNOTAVAIL: Failed to open TCP connection to localhost:9200 (Cannot assign requested address - connect(2) for \"localhost\" port 9200)>">
/opt/zammad/lib/search_index_backend.rb:62:in `index'
/opt/zammad/lib/tasks/search_index_es.rake:19:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/opt/zammad/lib/tasks/search_index_es.rake:60:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => searchindex:rebuild
root@itszammad:/opt/zammad# /etc/init.d/elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Di 2017-06-20 09:58:02 CEST; 2min 56s ago
     Docs: http://www.elastic.co
  Process: 31376 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet -Edefault.path.logs=${LOG_DIR} -Edefault.path.data=${DATA_DIR} -Edefault.path.conf=${CONF_DIR} (code=killed, signal=KILL)
  Process: 31372 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
 Main PID: 31376 (code=killed, signal=KILL)

Jun 20 09:57:06 itszammad systemd[1]: Starting Elasticsearch...
Jun 20 09:57:07 itszammad systemd[1]: Started Elasticsearch.
Jun 20 09:58:02 itszammad systemd[1]: elasticsearch.service: Main process exited, code=killed, status=9/KILL
Jun 20 09:58:03 itszammad systemd[1]: elasticsearch.service: Unit entered failed state.
Jun 20 09:58:03 itszammad systemd[1]: elasticsearch.service: Failed with result 'signal'.
```

**Comment by martini** [comment]
>  Main PID: 31376 (code=killed, signal=KILL)

Seems to get killed by your os. Usually because of memory issue (too less memory).

What is the size of your ram?

**Comment by MamoulianDelacroix** [comment]
2 GB

**Comment by martini** [comment]
New es versions take more memory. :-/ For testing use 6 GB. If it works fine, 4 GB should work too.

**Comment by MamoulianDelacroix** [comment]
Ok, now I have 6 GB, but still not working 😞 
```
root@itszammad:/opt/zammad# zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"
root@itszammad:/opt/zammad# zammad run rake searchindex:rebuild --trace
** Invoke searchindex:rebuild (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute searchindex:rebuild
** Execute searchindex:drop
drop indexes...
** Execute searchindex:create
create indexes...
rake aborted!
Unable to process PUT at http://localhost:9200/zammad_production
#<UserAgent::Result:0x00564d47bed580 @success=false, @body=nil, @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">
/opt/zammad/lib/search_index_backend.rb:62:in `index'
/opt/zammad/lib/tasks/search_index_es.rake:19:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/opt/zammad/lib/tasks/search_index_es.rake:60:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => searchindex:rebuild
root@itszammad:/opt/zammad# /etc/init.d/elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Di 2017-06-20 10:19:22 CEST; 2min 58s ago
     Docs: http://www.elastic.co
  Process: 1241 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
 Main PID: 1268 (java)
    Tasks: 38
   Memory: 2.3G
      CPU: 21.139s
   CGroup: /system.slice/elasticsearch.service
           └─1268 /usr/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server -Xss1m -Dj...

Jun 20 10:19:21 itszammad systemd[1]: Starting Elasticsearch...
Jun 20 10:19:22 itszammad systemd[1]: Started Elasticsearch.
```

**Comment by martini** [comment]
What is the output of:

`sudo /usr/share/elasticsearch/bin/elasticsearch-plugin list`

**Comment by MamoulianDelacroix** [comment]
```
root@itszammad:/opt/zammad# sudo /usr/share/elasticsearch/bin/elasticsearch-plugin list
root@itszammad:/opt/zammad#
```

**Comment by martini** [comment]
That is the problem. Pls follow the installation steps of elasticsearch https://docs.zammad.org/en/latest/install-elasticsearch.html (PS: Web also have excellent support contracts for self hosted https://zammad.com/pricing#selfhosted / https://zammad.com/de/preis#selfhosted)

Here you can see the need elasticsearch plugin "mapper-attachments". You *need* to install it too. Zammad is also indexing attachments. 

Please install the plugin, restart elasticsearch and try "zammad run rake searchindex:rebuild" again.

**Comment by MamoulianDelacroix** [comment]
Ah, I forgot 
```
sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-attachments
```
Now the rebuilding seems fine
```
root@itszammad:/opt/zammad# zammad run rake searchindex:rebuild --trace
** Invoke searchindex:rebuild (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute searchindex:rebuild
** Execute searchindex:drop
drop indexes...
** Execute searchindex:create
create indexes...
** Execute searchindex:reload
reload data...
 reload Ticket
  - started at 2017-06-20 08:58:02 UTC
  - took 3 seconds
 reload Organization
  - started at 2017-06-20 08:58:05 UTC
  - took 0 seconds
 reload User
  - started at 2017-06-20 08:58:06 UTC
  - took 0 seconds
```
But still I get no results for 
```
/api/v1/tickets/search?query=group_name%3Atest&limit=10
```

**Comment by martini** [comment]
Please use "attribute:value", in this case:

`/api/v1/tickets/search?query=group%3Atest&limit=10&expand=true`

References: https://docs.zammad.org/en/latest/general-search.html -> Ticket Attributes

**Comment by MamoulianDelacroix** [comment]
Sorry, my mistake I did copy the wrong command:
I also did try
```
/api/v1/tickets/search?query=group%3Atest&limit=10
```
and
```
/api/v1/tickets/search?query=group:test&limit=10
```
everytime the same output
```
{"tickets":[],"tickets_count":0,"assets":{}}
````

**Comment by martini** [comment]
Hi @MamoulianDelacroix 

on my local instance:

**Ticket create:**

Payload:
`curl -u master@example.com:test -H "Content-Type: application/json" -X POST -d '{"title": "Help me!","group": "Users","article": {"subject": "some subject","body": "some message","type": "note","internal": false},"customer":"nicole.braun@zammad.org","note": "some note"}' http://localhost:3000/api/v1/tickets`

Response:
```
{"id":30,"group_id":1,"priority_id":2,"state_id":1,"organization_id":1,"number":"941027","title":"Help me!","owner_id":1,"customer_id":2,"note":"some note","first_response_at":null,"first_response_escalation_at":null,"first_response_in_min":null,"first_response_diff_in_min":null,"close_at":null,"close_escalation_at":null,"close_in_min":null,"close_diff_in_min":null,"update_escalation_at":null,"update_in_min":null,"update_diff_in_min":null,"last_contact_at":null,"last_contact_agent_at":null,"last_contact_customer_at":null,"create_article_type_id":10,"create_article_sender_id":1,"article_count":1,"escalation_at":null,"pending_time":null,"type":null,"time_unit":null,"preferences":{},"updated_by_id":3,"created_by_id:3","created_at":"2017-06-20T10:03:17.365Z","updated_at":"2017-06-20T10:03:17.648Z"}
```

**Ticket search:**

Payload:
`curl -u master@example.com:test 'http://localhost:3000/api/v1/tickets/search?query=group%3AUsers&limit=1&expand=true'`

Response:
`[{"id":30,"group_id":1,"priority_id":2,"state_id":1,"organization_id":1,"number":"941027","title":"Help me!","owner_id":1,"customer_id":2,"note":"some note","first_response_at":null,"first_response_escalation_at":null,"first_response_in_min":null,"first_response_diff_in_min":null,"close_at":null,"close_escalation_at":null,"close_in_min":null,"close_diff_in_min":null,"update_escalation_at":null,"update_in_min":null,"update_diff_in_min":null,"last_contact_at":null,"last_contact_agent_at":null,"last_contact_customer_at":null,"create_article_type_id":10,"create_article_sender_id":1,"article_count":1,"escalation_at":null,"pending_time":null,"type":null,"time_unit":null,"preferences":{},"updated_by_id":3,"created_by_id":3,"created_at":"2017-06-20T10:03:17.365Z","updated_at":"2017-06-20T10:03:17.648Z","article_ids":[34],"group":"Users","ticket_time_accounting":[],"organization":"Zammad Foundation","state":"new","priority":"2 normal","owner":"-","customer":"nicole.braun@zammad.org","created_by":"master@example.com","updated_by":"master@example.com","create_article_type":"note","create_article_sender":"Agent"}]`

All looks fine as it should be. 

Please check also the Zammad scheduler process (script/scheduler.rb) which is processing background jobs like indexing elasticsearch. This means it this is not working, you will not file objects in elasticsearch (until all background jobs are processed or rake searchindex:rebuild is executed).

From here I can do more. For me it seems to be a local setup issue with integration of elasticsearch.

I can recommend you the Zammad services to get if done fast (https://zammad.com/pricing#selfhosted / https://zammad.com/de/preis#selfhosted)

Greetings,

 -Martin

**Comment by MamoulianDelacroix** [comment]
@martini thanks a lot for your help.
in some way somehow it works now.
I used
```
/api/v1/tickets/search?query=group_id%3A2
```
with that, I get my desired information. With 
```
/api/v1/tickets/search?query=group%3Atest
```
which is the same group, I get no results.

**Comment by martini** [comment]
> in some way somehow it works now.

Congrats! 🎉 Welcome in the Zammad lord cycle. 🤡

> ...which is the same group, I get no results

That's really strange. If your want to trace that down, do an direct query to elasticsearch and check what content for group is saved. I never have had this kind of issues with elasticsearch.

Good luck anyway! 😎
