### ISSUE TITLE
After system upgrades, failures with openssl

### ISSUE THREAD

**Issue by rixx** [zammad/zammad#1195]
```
LoadError: /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/x86_64-linux/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference - /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/x86_64-linux/openssl.so
```

On a current Debian system, after updating the system, zammad (manually installed, not docker) fails to start with the above error message. `libssl-dev` is installed and up to date, aswell.

**Comment by rixx** [comment]
D'oh, more things were broken on that system. Not a zammad issue, sorry.

**Comment by martini** [comment]
@rixx 

Thanks for feedback anyway! 🙏

> ...manually installed...

Just one note, I recommend to install Zammad via OS packages for CentOS, Debian, ... her you get the whole ruby env. No manual maintenance needed. Just my 2 cents.

**Comment by rixx** [comment]
Nah, I installed via system packages! But even those rely on a working openssl being present, and apparently we managed to mangle that (on a new Ubuntu OS, don't ask me how).

**Comment by monotek** [comment]
Hmmm... we had some issues on the debian based docker containers to. 
Build environment needed libssl from backports repo to build. 
Maybe you problem is related. Here you can see how we fixed it: https://github.com/monotek/pkgr-docker-compose/blob/master/containers/pkgr/Dockerfile

**Comment by derN3rd** [comment]
Getting the same error on Ubuntu Server 16.04.
After fixing my repo with #1294 today and doing an update I'm not getting it to run, even with all the thinks posted here...

Log:
```
root@company-zammad:~# sudo dpkg-reconfigure zammad
# (Re)creating init scripts
Nothing to do.
Nothing to do.
Nothing to do.
# Enabling Zammad on boot
# Stopping Zammad
# database.yml found. Updating db...
rake aborted!
LoadError: /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/x86_64-linux/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference - /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/x86_64-linux/openssl.so
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/key_generator.rb:2:in `require'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/key_generator.rb:2:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:5:in `require'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:5:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails.rb:11:in `require'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails.rb:11:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/all.rb:1:in `require'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/all.rb:1:in `<top (required)>'
/opt/zammad/config/application.rb:3:in `require'
/opt/zammad/config/application.rb:3:in `<top (required)>'
/opt/zammad/Rakefile:5:in `require'
/opt/zammad/Rakefile:5:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/opt/zammad/bin/bundle:3:in `load'
/opt/zammad/bin/bundle:3:in `<main>'
(See full trace by running task with --trace)
# Starting Zammad
# Creating webserver bootstart
Synchronizing state of nginx.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable nginx
# Restarting webserver nginx
####################################################################################

Add your FQDN to servername directive in /etc/nginx/sites-enabled/zammad.conf
and restart your webserver if you're not testing locally
or open http://localhost/ in your browser to start using Zammad.

####################################################################################
```

Really need some help here, please

**Comment by rixx** [comment]
In my case it turned out that I had installed from Debian package sources while running Ubuntu. (I know, I know.) So maybe make sure that your sources are those for Ubuntu?

**Comment by derN3rd** [comment]
@rixx thanks man, thats it. But after switching pkg sources, I can't reinstall now.

How did you fixed that?

```
root@company-zammad:~# sudo apt-get install --reinstall zammad
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Reinstallation of zammad is not possible, it cannot be downloaded.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by rixx** [comment]
Didn't run into that issue. Uninstall, reinstall, re-check pkg sources?

**Comment by derN3rd** [comment]
Do I loose my data when in uninstall and reinstall?

**Comment by monotek** [comment]
As with standard settings everything is saved in the database you don't have be worried about reinstalling, if you have the backup files available.

Follow these steps:
* remove Zammad
* Install again 
* create a new backup of the fresh installation
* Start restore
* when asked for filebackup date choose the one of the fresh installation
* When asked for DB backup date give the one of the old installation

That's it. You should be up and running again :-)
