### ISSUE TITLE
OTRS import fails for attributes containing null bytes strings on PostgreSQL

### ISSUE THREAD

**Issue by scimitar4444** [zammad/zammad#1200]
Hi,
I wanted to transfer tickets from OTRS 5.0.18 to Zammad 1.6 (develop). Unfortunately, the import always aborts. We have a few tickets in OTRS. About 16,000.
The last is in the log. Then he quits the Linux Promt.

```
9fb5c683dbc03380a0d29b6f0f6e434748d80cb97f1c150b1f3f4b5 (file-2)... Queue: [4].
thread#1: add Ticket.find_by(id: 6697)
thread#3: ERROR: Can't extract customer from Article
thread#3: add Ticket.find_by(id: 6334)
thread#4: Ticket 6790, Article 30789 - Finished import for fingerprint 7bf3499099fb5c683dbc03380a0d29b6f0f6e434748d80cb97f1c150b1f3f4b5 (file-2)... Queue: [4].
thread#5: Ticket 6606, Article 29899 - Starting import for fingerprint 986b4b8e04b96a2e4c3eac27347e873149feee978d7dff8929937647b725602b (file-2)... Queue: [5].
thread#1: add Ticket::Article.find_by(id: 30275)
thread#5: Ticket 6606, Article 29899 - Finished import for fingerprint 986b4b8e04b96a2e4c3eac27347e873149feee978d7dff8929937647b725602b (file-2)... Queue: [5].
thread#3: add Ticket::Article.find_by(id: 28872)
thread#4: add Ticket::Article.find_by(id: 30790)
thread#8: add Ticket.find_by(id: 6230)
thread#5: add Ticket::Article.find_by(id: 29902)
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared': string contains null byte (ArgumentError)
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:192:in `exec_insert'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation.rb:64:in `insert'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/persistence.rb:524:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/counter_cache.rb:139:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/locking/optimistic.rb:75:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/callbacks.rb:306:in `block in _create_record'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/callbacks.rb:306:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/timestamp.rb:57:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/persistence.rb:504:in `create_or_update'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/callbacks.rb:302:in `block in create_or_update'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/callbacks.rb:302:in `create_or_update'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/persistence.rb:120:in `save'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:37:in `save'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/attribute_methods/dirty.rb:21:in `save'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:286:in `block in save'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:285:in `save'
        from /opt/zammad/lib/import/otrs/article.rb:64:in `create'
        from /opt/zammad/lib/import/otrs/article.rb:49:in `create_or_update'
        from /opt/zammad/lib/import/otrs/article.rb:37:in `import'
        from /opt/zammad/lib/import/otrs/article.rb:31:in `initialize'
        from /opt/zammad/lib/import/base_factory.rb:37:in `new'
        from /opt/zammad/lib/import/base_factory.rb:37:in `create_instance'
        from /opt/zammad/lib/import/base_factory.rb:11:in `block in import_action'
        from /opt/zammad/lib/import/base_factory.rb:41:in `each'
        from /opt/zammad/lib/import/base_factory.rb:41:in `import_loop'
        from /opt/zammad/lib/import/base_factory.rb:9:in `import_action'
        from /opt/zammad/lib/import/otrs/ticket.rb:40:in `import'
        from /opt/zammad/lib/import/otrs/ticket.rb:30:in `initialize'
        from /opt/zammad/lib/import/base_factory.rb:37:in `new'
        from /opt/zammad/lib/import/base_factory.rb:37:in `create_instance'
        from /opt/zammad/lib/import/base_factory.rb:11:in `block in import_action'
        from /opt/zammad/lib/import/base_factory.rb:41:in `each'
        from /opt/zammad/lib/import/base_factory.rb:41:in `import_loop'
        from /opt/zammad/lib/import/base_factory.rb:9:in `import_action'
        from /opt/zammad/lib/import/otrs.rb:147:in `import_action'
        from /opt/zammad/lib/import/otrs.rb:137:in `imported?'
        from /opt/zammad/lib/import/otrs.rb:101:in `block (3 levels) in threaded_import'
        from /opt/zammad/lib/import/otrs.rb:95:in `loop'
        from /opt/zammad/lib/import/otrs.rb:95:in `block (2 levels) in threaded_import'
```

**Comment by thorsteneckel** [comment]
Hi @scimitar4444 - thanks for reporting this. I created an OTRS debug script before diving to deep into the import logic. The output may help me to reproduce this in our test environment. Please do the following.


1.) Create a file called `zammad.Issue1200.pl` in your OTRS script path (usually `/opt/otrs/bin`)
2.) Run the file from your Zammad directory via `perl -I Kernel/cpan-lib bin/zammad.Issue1200.pl`
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `zammad.Issue1200.pl` file

```perl
#!/usr/bin/perl

use strict;
use warnings;

use File::Basename;
use FindBin qw($RealBin);
use lib dirname($RealBin);
use lib dirname($RealBin) . '/Kernel/cpan-lib';
use lib dirname($RealBin) . '/Custom';

use Getopt::Long;

use Kernel::System::ObjectManager;

use Kernel::System::VariableCheck qw(:all);

local $Kernel::OM = Kernel::System::ObjectManager->new(
    'Kernel::System::Log' => {
        LogPrefix => 'OTRS-zammad.Issue1200.pl',
    },
);

my $TicketObject = $Kernel::OM->Get('Kernel::System::Ticket');
my $JSONObject   = $Kernel::OM->Get('Kernel::System::JSON');

my @ArticleIDs = ('29902', '28872', '30790', '30275');

for my $ArticleID (@ArticleIDs) {
    my %Article = $TicketObject->ArticleGet(
        ArticleID     => $ArticleID,
        DynamicFields => 1,
        UserID        => 1,
    );

    print $JSONObject->Encode(
        Data => \%Article,
    );

    print "\n\n";
}

exit 0;

1;
```

**Comment by scimitar4444** [comment]
Hi Thorsten,

I sent it to the support EMail.

Christian

**Comment by thorsteneckel** [comment]
Hi @scimitar4444 - Thanks for your fast response. The send data helped me to find the cause for this. Could you please verify my fix by doing the following:

1.) Setup a new system
2.) Create a backup of the file `lib/import/otrs/requester.rb`
3.) Replace the file `lib/import/otrs/requester.rb` with the unzipped one attached
4.) Start the import

This is caused by a constellation of PostgreSQL and a null byte string which causes trouble.

[requester.rb.zip](https://github.com/zammad/zammad/files/1108555/requester.rb.zip)

Thanks!

**Comment by scimitar4444** [comment]
Hello,

The fix works and the import has been successful! Many Thanks!

**Comment by thorsteneckel** [comment]
Great! Thanks for your feedback. The fix is done via the commits above. This will be available in all packages in about 30 minutes from now 🚀
