### ISSUE TITLE
Cant send automated email ... 

### ISSUE THREAD

**Issue by XL-Maggus** [zammad/zammad#1214]
Hi , 

zammad will no longer automatically answer emails ... 

this is the error from zammad log: 

```
I, [2017-06-29T10:41:49.305776 #12252]  INFO -- : fetching imap 
I, [2017-06-29T10:41:50.741174 #12252]  INFO -- :  - message 1/1
E, [2017-06-29T10:41:51.199673 #12252] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//b306a22ba305e153035ea6107508049b.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2017-06-29T10:41:51.199801 #12252] ERROR -- : uninitialized constant Channel::Filter::ReplyToBasedSender (NameError)
/opt/zammad/app/models/channel/email_parser.rb:447:in `const_get'
/opt/zammad/app/models/channel/email_parser.rb:447:in `block in _process'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/zammad/app/models/channel/email_parser.rb:446:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:418:in `process'
/opt/zammad/app/models/channel/driver/imap.rb:188:in `block in fetch'
/opt/zammad/app/models/channel/driver/imap.rb:168:in `each'
/opt/zammad/app/models/channel/driver/imap.rb:168:in `fetch'
/opt/zammad/app/models/channel.rb:62:in `fetch'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:176:in `eval'
/opt/zammad/app/models/scheduler.rb:176:in `_start_job'
/opt/zammad/app/models/scheduler.rb:143:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:142:in `loop'
/opt/zammad/app/models/scheduler.rb:142:in `block in start_job'
I, [2017-06-29T10:41:51.479249 #12252]  INFO -- : done
```

### Infos:

* Used Zammad version: Latest Ubuntu Stable
* Used Zammad installation source: deb package
* Operating system: Ubuntu 16.4 
* Browser + version: any

**Comment by martini** [comment]
Hi @XL-Maggus 

what Zammad version do you use?

 -Martin

**Comment by martini** [comment]
Please reopen on feedback. Thanks.
