### ISSUE TITLE
Error on creation of Elasticsearch index

### ISSUE THREAD

**Issue by Fotho** [zammad/zammad#1215]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: Debian Package
* Operating system: Debian 8
* Browser + version: Chrome 58.0.3029.110 (64-bit)

### Expected behavior:

* lightning fast search in zammad

### Actual behavior:

* no search at all

### Steps to reproduce the behavior:

I'm using zammad a few month and i didn't configure elasticsearch although i used the search field a lot.
Now i'm trying to get elasticsearch working.
I used the official guide on [https://docs.zammad.org/en/latest/install-elasticsearch.html](https://docs.zammad.org/en/latest/install-elasticsearch.html)
I did also the optional settings.
Maybe you can explain what the optinal settings exactly do.
```
zammad run rails r "Setting.set('es_user', 'elasticsearch')"
zammad run rails r "Setting.set('es_password', 'zammad')"
zammad run rails r "Setting.set('es_index', Socket.gethostname + '_zammad')"
```

Elasticsearch works fine i guess
```
{
  "name" : "refqRJP",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "Tsy6lNS7QF60sgOr7eSvwQ",
  "version" : {
    "number" : "5.4.3",
    "build_hash" : "eed30a8",
    "build_date" : "2017-06-22T00:34:03.743Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.1"
  },
  "tagline" : "You Know, for Search"
}
```
But when i start the creation of the Elasticsearch index i get an error.
```
 zammad run rake searchindex:rebuild --trace
** Invoke searchindex:rebuild (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute searchindex:rebuild
** Execute searchindex:drop
drop indexes...
** Execute searchindex:create
create indexes...
rake aborted!
Unable to process PUT at http://127.0.0.1:9200/ZAMMAD_zammad_production
#<UserAgent::Result:0x0055e713d0c690 @success=false, @body=nil, @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">
/opt/zammad/lib/search_index_backend.rb:62:in `index'
/opt/zammad/lib/tasks/search_index_es.rake:19:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/opt/zammad/lib/tasks/search_index_es.rake:60:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => searchindex:rebuild
```

Now when i want search something in zammad i get nothing.
Error in production.log.
```
ERROR -- : ERROR: POST on http://127.0.0.1:9200/ZAMMAD_zammad_production/Ticket/_search
#<UserAgent::Result:0x007f8c90151890 @success=false, @body=nil, @data=nil, @code="404", @content_type=nil, @error="No such file http://127.0.0.1:9200/ZAMMAD_zammad_production/Ticket/_search, 404!">
```

I tried it with localhost instead of 127.0.0.1.
Reinstalled mapper-attachments.
But nothing worked for me.

The only difference i could find was the additional "ZAMMAD" in the URL of the error messages when trying to create the index or searching something in zammad compared to others who had problems to create the Elasticsearch index.
`http://127.0.0.1:9200/ZAMMAD_zammad_production`
`http://127.0.0.1:9200/zammad_production`

**Comment by martini** [comment]
Hi @Fotho 

anything in the elasticsearch.log ?

 -Martin

**Comment by Fotho** [comment]
Hello @martini 

No log entries when i try to create the index, but there is a warning regarding the "mapper-attachments" when i restart elasticsearch.
```
[2017-06-29T11:30:35,304][INFO ][o.e.n.Node               ] [refqRJP] stopping ...
[2017-06-29T11:30:35,381][INFO ][o.e.n.Node               ] [refqRJP] stopped
[2017-06-29T11:30:35,382][INFO ][o.e.n.Node               ] [refqRJP] closing ...
[2017-06-29T11:30:35,411][INFO ][o.e.n.Node               ] [refqRJP] closed
[2017-06-29T11:30:41,158][INFO ][o.e.n.Node               ] [] initializing ...
[2017-06-29T11:30:41,425][INFO ][o.e.e.NodeEnvironment    ] [refqRJP] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [69.2gb], net total_space [75.3gb], spins? [unknown], types [rootfs]
[2017-06-29T11:30:41,427][INFO ][o.e.e.NodeEnvironment    ] [refqRJP] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-06-29T11:30:41,450][INFO ][o.e.n.Node               ] node name [refqRJP] derived from node ID [refqRJP1T3WmL3TpGgAP0Q]; set [node.name] to override
[2017-06-29T11:30:41,452][INFO ][o.e.n.Node               ] version[5.4.3], pid[2839], build[eed30a8/2017-06-22T00:34:03.743Z], OS[Linux/3.16.0-4-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-06-29T11:30:41,452][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2017-06-29T11:30:44,043][INFO ][o.e.p.PluginsService     ] [refqRJP] loaded module [aggs-matrix-stats]
[2017-06-29T11:30:44,044][INFO ][o.e.p.PluginsService     ] [refqRJP] loaded module [ingest-common]
[2017-06-29T11:30:44,045][INFO ][o.e.p.PluginsService     ] [refqRJP] loaded module [lang-expression]
[2017-06-29T11:30:44,048][INFO ][o.e.p.PluginsService     ] [refqRJP] loaded module [lang-groovy]
[2017-06-29T11:30:44,048][INFO ][o.e.p.PluginsService     ] [refqRJP] loaded module [lang-mustache]
[2017-06-29T11:30:44,049][INFO ][o.e.p.PluginsService     ] [refqRJP] loaded module [lang-painless]
[2017-06-29T11:30:44,049][INFO ][o.e.p.PluginsService     ] [refqRJP] loaded module [percolator]
[2017-06-29T11:30:44,049][INFO ][o.e.p.PluginsService     ] [refqRJP] loaded module [reindex]
[2017-06-29T11:30:44,049][INFO ][o.e.p.PluginsService     ] [refqRJP] loaded module [transport-netty3]
[2017-06-29T11:30:44,049][INFO ][o.e.p.PluginsService     ] [refqRJP] loaded module [transport-netty4]
[2017-06-29T11:30:44,052][INFO ][o.e.p.PluginsService     ] [refqRJP] loaded plugin [mapper-attachments]
[2017-06-29T11:30:44,399][WARN ][d.m.attachment           ] [mapper-attachments] plugin has been deprecated and will be replaced by [ingest-attachment] plugin.
[2017-06-29T11:30:50,200][INFO ][o.e.d.DiscoveryModule    ] [refqRJP] using discovery type [zen]
[2017-06-29T11:30:52,010][INFO ][o.e.n.Node               ] initialized
[2017-06-29T11:30:52,011][INFO ][o.e.n.Node               ] [refqRJP] starting ...
[2017-06-29T11:30:52,518][INFO ][o.e.t.TransportService   ] [refqRJP] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2017-06-29T11:30:55,777][INFO ][o.e.c.s.ClusterService   ] [refqRJP] new_master {refqRJP}{refqRJP1T3WmL3TpGgAP0Q}{F5xTnhxvRhKUHbkt4qWmMg}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-06-29T11:30:55,840][INFO ][o.e.h.n.Netty4HttpServerTransport] [refqRJP] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2017-06-29T11:30:55,850][INFO ][o.e.n.Node               ] [refqRJP] started
[2017-06-29T11:30:55,926][INFO ][o.e.g.GatewayService     ] [refqRJP] recovered [1] indices into cluster_state
```

**Comment by martini** [comment]
Hi @Fotho 

just tested it with brand new elasticsearch 5.4.3 and it works fine. 😵

Wenn I execute "zammad run rake searchindex:rebuild" I can see in elasticsearch.log:

```
[2017-06-29T13:46:23,422][INFO ][o.e.c.m.MetaDataCreateIndexService] [2UCYfJc] [zammad_development] creating index, cause [api], templates [], shards [5]/[1], mappings [Ticket]
```

For me your `@code="404"` sound strange. It seems that Zammad can not reach your elasticsearch. Maybe a proxy is used?

Anyway, it's not Zammad related. It's IMO an network issue. Please let us know if you found out what it is/was. Thanks in advance!

 -Martin

**Comment by monotek** [comment]
Ti me the indexname looks strange: ZAMMAD_zammad_production

**Comment by Fotho** [comment]
Yes, that's what i mentioned in my first post.
I don't know why it is with an extra ZAMMAD.

> The only difference i could find was the additional "ZAMMAD" in the URL of the error messages when trying to create the index or searching something in zammad compared to others who had problems to create the Elasticsearch index.
> http://127.0.0.1:9200/ZAMMAD_zammad_production
> http://127.0.0.1:9200/zammad_production

Proxy isn't in use.
It's all on the same host (zammad, nginx, elasticsearch).

Is there a possibility to revert back to normal "SQL-Search behavior" when i search in zammad?
Because right now i can not make any new ticket because i cannot select a customer in the customer filed

**Comment by martini** [comment]
Hi @Fotho 

the additional "ZAMMAD" is no problem. You can change the index name by:

`zammad run rails r "Setting.set('es_index', 'some_es_index_zammad')" `

If you want to disable elasticsearch integration, just use:

`zammad run rails r "Setting.set('es_url', '')" `

 -Martin

**Comment by Fotho** [comment]
I couldn't find the problem so i disabled elasticsearch.

Nevertheless thank you for your help.

**Comment by bc1000** [comment]
zammad run rails r "Setting.set('es_index', zammad') fixed it.

before my index was "HOSTNAME_zammad"

**Comment by antboll** [comment]
Hi Guys, I think I have a similiar problem.
After:
`zammad run rake searchindex:rebuild --trace`
I get an error:

> create indexes...
> rake aborted!
> Unable to process PUT at http://localhost:9200/_ingest/pipeline/zammad-attachment
> #<UserAgent::Result:0x005606521a74b8 @success=false, @body=nil, @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">
> /opt/zammad/lib/search_index_backend.rb:95:in `block (2 levels) in processors'
> /opt/zammad/lib/search_index_backend.rb:62:in `each'
> /opt/zammad/lib/search_index_backend.rb:62:in `block in processors'
> /opt/zammad/lib/search_index_backend.rb:59:in `each'
> /opt/zammad/lib/search_index_backend.rb:59:in `processors'
> /opt/zammad/lib/tasks/search_index_es.rake:68:in `block (2 levels) in <top (required)>'
> ...........
Can anyone help?

**Comment by jaeger13** [comment]
Which version of Elasticsearch are you using?

**Comment by thorsteneckel** [comment]
Same guess as @jaeger13 - should be 5.6 is probably 6. Please don't reply to long closed issues.
