### ISSUE TITLE
OTRS Import fails with "incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)"

### ISSUE THREAD

**Issue by ktwe** [zammad/zammad#1349]
### Infos:

* Used Zammad version: current master branch
* Used Zammad installation source: Ubuntu package
* Operating system: Ubuntu 16.04
* OTRS Version: 3.3

### Actual behavior:

* When importing data from OTRS (3.3.3) using Import::OTRS.start I get the following error message:
```
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/arel-6.0.4/lib/arel/collectors/bind.rb:32:in `join': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/arel-6.0.4/lib/arel/collectors/bind.rb:32:in `compile'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract_adapter.rb:128:in `compile'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:13:in `to_sql'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:107:in `insert'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation.rb:64:in `insert'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:524:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/counter_cache.rb:139:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/locking/optimistic.rb:75:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/callbacks.rb:306:in `block in _create_record'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:117:in `call'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/callbacks.rb:306:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/timestamp.rb:57:in `_create_record'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:504:in `create_or_update'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/callbacks.rb:302:in `block in create_or_update'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:117:in `call'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/callbacks.rb:302:in `create_or_update'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:120:in `save'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/validations.rb:37:in `save'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/attribute_methods/dirty.rb:21:in `save'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:220:in `transaction'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:286:in `block in save'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:285:in `save'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:34:in `create'
        from /opt/zammad/app/models/store.rb:50:in `add'
        from /opt/zammad/lib/import/otrs/article/attachment_factory.rb:38:in `block in import_single'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:220:in `transaction'
        from /opt/zammad/lib/import/otrs/article/attachment_factory.rb:37:in `import_single'
        from /opt/zammad/lib/import/otrs/article/attachment_factory.rb:21:in `block in perform_import'
        from /opt/zammad/lib/import/otrs/article/attachment_factory.rb:21:in `each'
        from /opt/zammad/lib/import/otrs/article/attachment_factory.rb:21:in `perform_import'
        from /opt/zammad/lib/import/otrs/article/attachment_factory.rb:15:in `import'
        from /opt/zammad/lib/import/otrs/article.rb:41:in `import'
        from /opt/zammad/lib/import/otrs/article.rb:31:in `initialize'
        from /opt/zammad/lib/import/base_factory.rb:37:in `new'
        from /opt/zammad/lib/import/base_factory.rb:37:in `create_instance'
        from /opt/zammad/lib/import/base_factory.rb:11:in `block in import_action'
        from /opt/zammad/lib/import/base_factory.rb:41:in `each'
        from /opt/zammad/lib/import/base_factory.rb:41:in `import_loop'
        from /opt/zammad/lib/import/base_factory.rb:9:in `import_action'
        from /opt/zammad/lib/import/otrs/ticket.rb:40:in `import'
        from /opt/zammad/lib/import/otrs/ticket.rb:30:in `initialize'
        from /opt/zammad/lib/import/base_factory.rb:37:in `new'
        from /opt/zammad/lib/import/base_factory.rb:37:in `create_instance'
        from /opt/zammad/lib/import/base_factory.rb:11:in `block in import_action'
        from /opt/zammad/lib/import/base_factory.rb:41:in `each'
        from /opt/zammad/lib/import/base_factory.rb:41:in `import_loop'
        from /opt/zammad/lib/import/base_factory.rb:9:in `import_action'
        from /opt/zammad/lib/import/otrs.rb:147:in `import_action'
        from /opt/zammad/lib/import/otrs.rb:137:in `imported?'
        from /opt/zammad/lib/import/otrs.rb:101:in `block (3 levels) in threaded_import'
        from /opt/zammad/lib/import/otrs.rb:95:in `loop'
        from /opt/zammad/lib/import/otrs.rb:95:in `block (2 levels) in threaded_import'
```

**Comment by hanneshal** [comment]
@ktwe 
Note: Would please be so kind and use our issue templates. We created them for a reason.

To you issue
Please tell us: 
- Which Zammad Version do you use
- Which database do you use in Zammad 
- Wich database do you use in OTRS

Thank you

**Comment by thorsteneckel** [comment]
Hi @ktwe - Seems there is an issue with an attachment. Could you please reset your system and then follow the steps and replace the `otrs_url` and `key` values with the ones of your system. This should print out the exact error that happens. Please provide it or the `log/production.log` file afterwards. Thanks!

1.) Create a file called `debug_1349.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via `zammad run rails r debug_1349.rb` or `rails r debug_1349.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `debug_1349.rb` file

```ruby
otrs_url = 'http://your.domain.tld'
key      = '*YourKeyHere*'


require 'import/otrs'
require 'import/otrs/article'
require 'import/otrs/article/attachment_factory'


module Import
  module OTRS
    class Article
      module AttachmentFactory

        def import_single(local_article, attachment)

          decoded_filename = Base64.decode64(attachment['Filename'])
          decoded_content  = Base64.decode64(attachment['Content'])
          # TODO: should be done by a/the Storage object
          # to handle fingerprinting
          sha = Digest::SHA256.hexdigest(decoded_content)

          retries = 3
          begin
            queueing(sha, decoded_filename)

            log "Ticket #{local_article.ticket_id}, Article #{local_article.id} - Starting import for fingerprint #{sha} (#{decoded_filename})... Queue: #{@sha_queue[sha]}."
            ActiveRecord::Base.transaction do
              Store.add(
                object:      'Ticket::Article',
                o_id:        local_article.id,
                filename:    decoded_filename,
                data:        decoded_content,
                preferences: {
                  'Mime-Type'           => attachment['ContentType'],
                  'Content-ID'          => attachment['ContentID'],
                  'content-alternative' => attachment['ContentAlternative'],
                },
                created_by_id: 1,
              )
            end
            log "Ticket #{local_article.ticket_id}, Article #{local_article.id} - Finished import for fingerprint #{sha} (#{decoded_filename})... Queue: #{@sha_queue[sha]}."
          rescue ActiveRecord::RecordNotUnique, ActiveRecord::StatementInvalid => e
            log "Ticket #{local_article.ticket_id} - #{sha} - #{e.class}: #{e}"
            sleep rand 3
            retry if !(retries -= 1).zero?
            raise
          rescue => e
            message = "Ticket #{local_article.ticket_id} - #{sha} - #{e}: #{attachment.inspect}"
            log message
            puts message
            raise
          ensure
            queue_cleanup(sha)
          end
        end
      end
    end
  end
end


endpoint = "#{otrs_url}/otrs/public.pl?Action=ZammadMigrator"

Setting.set('import_otrs_endpoint', endpoint)
Setting.set('import_otrs_endpoint_key', key)
Setting.set('import_mode', true)
Setting.set('system_init_done', false)


Import::OTRS.start
```

**Comment by ktwe** [comment]
Thanks for your feedback @thorsteneckel.

Here is the output from the debug run:
`Ticket 8553 - 6ecba4dd4013292b4cb43c9551ba20ee93901b89e24eb820997dcf2474f422af - incompatible character encodings: ASCII-8BIT and UTF-8: {"FilesizeRaw"=>"20703", "Filesize"=>"20.2 KBytes", "Filename"=>"MjAxNy0wOC0wOCAxMF8wN18wMS1SZW1vdGVWTV8xIFt3aXJkIGF1c2dlZsO8aHJ0XSAtIE9yYWNs\nZSBWTSBWaXJ0dWFsQm94LnBuZw==\n", "ContentType"=>"image/png; name=\"2017-08-08 10_07_01-RemoteVM_1 [wird ausgeführt] - Oracle VM VirtualBox.png\"", "ContentAlternative"=>nil, "ContentID"=>"<inline72190.9197351431.1502179454.9161798.18264737@***>", "Content"=>"***"}`

**Comment by thorsteneckel** [comment]
Thanks for your feedback!

Would it be possible to get the complete/"uncensored" output via mail to support@zammad.com? This would help me a lot. If so, please refer to this issue. Thanks!

**Comment by ktwe** [comment]
@thorsteneckel Done. Ticket is Ticket#107757. Thanks a lot!

**Comment by thorsteneckel** [comment]
Great! I'll have a look tomorrow and let you know what I've found out.

**Comment by thorsteneckel** [comment]
Hi @ktwe - Thanks to the provided data I was able to reproduce the issue and fix it with the commits  above. You can update your Zammad and restart the import. Feedback would be great!

**Comment by ktwe** [comment]
@thorsteneckel Thank you very much for the fast reponse time and the fix. I can confirm, that the bug has been fixed.
