### ISSUE TITLE
NoMemoryError in scheduler

### ISSUE THREAD

**Issue by dmvenzo** [zammad/zammad#1356]
### Infos:

* Used Zammad version: 1.5.0 (latest)
* Used Zammad installation source: source
* Operating system: Ubuntu 16.04.2 LTS

There is a problem in scheduler when an email has large attachment file (more than 20Mb):
```
(scheduler_err.log)

/opt/zammad/app/models/scheduler.rb:176:in `eval': failed to allocate memory (NoMemoryError)
	from /opt/zammad/lib/core_ext/string.rb:61:in `each'
	from /opt/zammad/lib/core_ext/string.rb:61:in `select'
	from /opt/zammad/lib/core_ext/string.rb:61:in `utf8_to_3bytesutf8'
	from /opt/zammad/app/models/application_model/checks_attribute_values_and_length.rb:50:in `block in check_attribute_values_and_length'
	from /opt/zammad/app/models/application_model/checks_attribute_values_and_length.rb:20:in `each'
	from /opt/zammad/app/models/application_model/checks_attribute_values_and_length.rb:20:in `check_attribute_values_and_length'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in `block in halting'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `_create_record'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/timestamp.rb:57:in `_create_record'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:504:in `create_or_update'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `create_or_update'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:120:in `save'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:37:in `save'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block in save'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:285:in `save'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:34:in `create'
	from /opt/zammad/app/models/store/provider/db.rb:9:in `add'
	from /opt/zammad/app/models/store/file.rb:32:in `add'
	from /opt/zammad/app/models/store.rb:40:in `add'
	from /opt/zammad/app/models/ticket/article.rb:205:in `save_as_raw'
	from /opt/zammad/app/models/channel/email_parser.rb:591:in `block (2 levels) in _process'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/locking/pessimistic.rb:72:in `block in with_lock'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:277:in `transaction'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/locking/pessimistic.rb:70:in `with_lock'
	from /opt/zammad/app/models/channel/email_parser.rb:569:in `block in _process'
	from /opt/zammad/app/models/transaction.rb:12:in `block in execute'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
	from /opt/zammad/app/models/transaction.rb:10:in `execute'
	from /opt/zammad/app/models/channel/email_parser.rb:484:in `_process'
	from /opt/zammad/app/models/channel/email_parser.rb:428:in `process'
	from /opt/zammad/app/models/channel/driver/imap.rb:188:in `block in fetch'
	from /opt/zammad/app/models/channel/driver/imap.rb:168:in `each'
	from /opt/zammad/app/models/channel/driver/imap.rb:168:in `fetch'
	from /opt/zammad/app/models/channel.rb:62:in `fetch'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
	from /opt/zammad/app/models/channel.rb:30:in `fetch'
	from (eval):1:in `_start_job'
	from /opt/zammad/app/models/scheduler.rb:176:in `eval'
	from /opt/zammad/app/models/scheduler.rb:176:in `_start_job'
	from /opt/zammad/app/models/scheduler.rb:143:in `block (2 levels) in start_job'
	from /opt/zammad/app/models/scheduler.rb:142:in `loop'
	from /opt/zammad/app/models/scheduler.rb:142:in `block in start_job'
```

**Comment by martini** [comment]
Hi @dmvenzo 

what is the RAM of your machine? And what database do your use?

 -Martin

**Comment by dmvenzo** [comment]
RAM 2Gb, 760Mb free

MySQL with option:
```
max_allowed_packet = 100Mb
```

**Comment by hanneshal** [comment]
Hi @dmvenzo 

can you monitor the memory during the upload please. We tried to reproduce it, but had no success.
Please monitor the values: before, during and after the upload.  Maybe we see something interesting there.

regards
Johannes

**Comment by dmvenzo** [comment]
Hi @hanneshal
I extended the RAM up to 4Gb and it was ok except memory consumption
Attachment - 23Mb

Before:
```
ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
zammad    3232  4.5  4.5 957400 184516 ?       Sl   18:57   0:09 scheduler
```
After:
```
ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
zammad    3232 14.6 50.3 2791344 2037316 ?     Sl   18:57   1:07 scheduler
```

**Comment by martini** [comment]
Hi @dmvenzo 

you have installed via source. Do you have bash environment settings for ruby gc?

```
echo $RUBY_GC_MALLOC_LIMIT
echo $RUBY_GC_MALLOC_LIMIT_MAX
echo $RUBY_GC_OLDMALLOC_LIMIT
echo $RUBY_GC_OLDMALLOC_LIMIT_MAX
```

They are empty?

How us the memory consuming after your set if to:

```
export RUBY_GC_MALLOC_LIMIT=1077216
export RUBY_GC_MALLOC_LIMIT_MAX=2177216
export RUBY_GC_OLDMALLOC_LIMIT=3000100
export RUBY_GC_OLDMALLOC_LIMIT_MAX=4000100
```

Feedback wis welcome!

 -Martin

**Comment by hanneshal** [comment]
Closed.
Please reopen when this issue still exists in 2.0.
