### ISSUE TITLE
Reindex elastic search not possible because of <null>/Twitter::NullObject

### ISSUE THREAD

**Issue by martini** [zammad/zammad#1394]
Reindex elastic search not possible because of null/Twitter::NullObject

```
RuntimeError: Unable to process POST at http://127.0.0.1:9200/production/Ticket/8386 (size: 0M)
#<UserAgent::Result:0x0000000712c0f8 @success=false, @body=nil, @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">
	from /home/zammad/lib/search_index_backend.rb:94:in `add'
	from /home/zammad/app/models/concerns/has_search_index_backend.rb:64:in `search_index_update_backend'
	from (irb):2
	from /usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.9/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.9/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.9/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by martini** [comment]
@hanneshal fixed.@hanneshal fixed with tests for Zammad 2.0 and above.
