### ISSUE TITLE
Reloop of zammad-worker-1.service & zammad-web-1.service after fresh installation on Debian 8

### ISSUE THREAD

**Issue by cvantum** [zammad/zammad#1416]
### Infos:

* Used Zammad version: 
`dpkg -l zammad
ii  zammad                                                2.0.0-1505227273.eb5fe7fd.jessie`
* Used Zammad installation source: package
* Operating system: Debian 8
* Browser + version: Firefox 55.0.3 ( Arch Linux)

### Expected behavior:

Hi there,

i have made a fresh installation of the current stable version of Zammad via your repository. I followed the instructions at your documentation ( https://docs.zammad.org/en/latest/install-debian.html#add-zammad-deb-repo-and-install ).

The installation runs without any problems.

### Actual behavior:

After i have edited the *nginx-conf*, i tried to access the frontpage and got a "Bad Gateway" message. As far as i was looking to resolve the issuse i have found the zammad-worker-1.service and zammad-web-1.service in reloop. 

**Extract of /var/log/syslog**

```
Sep 13 15:16:18 helpdesk systemd[1]: Starting zammad-web-1.service...
Sep 13 15:16:18 helpdesk systemd[1]: Started zammad-web-1.service.
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: bundler: failed to load command: script/scheduler.rb (script/scheduler.rb)
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: PG::ConnectionBad: could not connect to server: No such file or directory
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: Is the server running locally and accepting
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/composite_primary_keys-8.1.6/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:51:in `retrieve_c
onnection'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/composite_primary_keys-8.1.6/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:33:in `connection
'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/config/initializers/db_preferences_postgresql.rb:9:in `<top (required)>'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:652:in `block in load_config_initializer'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:166:in `instrument'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:651:in `load_config_initializer'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:615:in `each'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:615:in `block in <class:Engine>'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `each'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `tsort_each_child'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `call'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: /opt/zammad/config/environment.rb:5:in `<top (required)>'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: script/scheduler.rb:14:in `require'
Sep 13 15:16:20 helpdesk zammad-worker-1.service[25341]: script/scheduler.rb:14:in `<top (required)>'
Sep 13 15:16:20 helpdesk systemd[1]: zammad-worker-1.service: main process exited, code=exited, status=1/FAILURE
Sep 13 15:16:20 helpdesk systemd[1]: Unit zammad-worker-1.service entered failed state.
Sep 13 15:16:20 helpdesk systemd[1]: zammad-worker-1.service holdoff time over, scheduling restart.
Sep 13 15:16:20 helpdesk systemd[1]: Stopping zammad-worker-1.service...
Sep 13 15:16:20 helpdesk systemd[1]: Starting zammad-worker-1.service...
```

```
Sep 13 15:16:21 helpdesk systemd[1]: Started zammad-web-1.service.
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: bundler: failed to load command: script/websocket-server.rb (script/websocket-server.rb)
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: PG::ConnectionBad: could not connect to server: No such file or directory
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: Is the server running locally and accepting
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/composite_primary_keys-8.1.6/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:51:in `retriev
e_connection'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/composite_primary_keys-8.1.6/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:33:in `connect
ion'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/config/initializers/db_preferences_postgresql.rb:9:in `<top (required)>'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:652:in `block in load_config_initializer'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:166:in `instrument'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:651:in `load_config_initializer'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:615:in `each'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:615:in `block in <class:Engine>'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `each'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `tsort_each_child'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `call'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: /opt/zammad/config/environment.rb:5:in `<top (required)>'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: script/websocket-server.rb:14:in `require'
Sep 13 15:16:21 helpdesk zammad-websocket-1.service[25361]: script/websocket-server.rb:14:in `<top (required)>'
Sep 13 15:16:21 helpdesk systemd[1]: zammad-websocket-1.service: main process exited, code=exited, status=1/FAILURE
Sep 13 15:16:21 helpdesk systemd[1]: Unit zammad-websocket-1.service entered failed state.
Sep 13 15:16:21 helpdesk systemd[1]: zammad-websocket-1.service holdoff time over, scheduling restart.
Sep 13 15:16:21 helpdesk systemd[1]: Stopping zammad-websocket-1.service...
Sep 13 15:16:21 helpdesk systemd[1]: Starting zammad-websocket-1.service...

```

On the other hand all services seems to be running:

```
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled)
   Active: active (exited) since Wed 2017-09-13 14:54:10 CEST; 30min ago
 Main PID: 412 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/postgresql.service

Sep 13 14:54:10 helpdesk systemd[1]: Started PostgreSQL RDBMS.
```
```
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled)
   Active: active (running) since Wed 2017-09-13 15:00:37 CEST; 24min ago
  Process: 8118 ExecStop=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid (code=exited, status=0/SUCCESS)
  Process: 8122 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 8120 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
 Main PID: 8125 (nginx)
   CGroup: /system.slice/nginx.service
           ├─8125 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─8126 nginx: worker process
           ├─8127 nginx: worker process
           ├─8128 nginx: worker process
           └─8129 nginx: worker process

Sep 13 15:00:37 helpdesk systemd[1]: Starting A high performance web server and a reverse proxy server...
Sep 13 15:00:37 helpdesk systemd[1]: Failed to read PID from file /run/nginx.pid: Invalid argument
Sep 13 15:00:37 helpdesk systemd[1]: Started A high performance web server and a reverse proxy server.
```

```
● zammad.service
   Loaded: loaded (/etc/systemd/system/zammad.service; enabled)
   Active: active (running) since Wed 2017-09-13 15:00:37 CEST; 25min ago
 Main PID: 8009 (sleep)
   CGroup: /system.slice/zammad.service
           └─8009 /bin/sleep infinity

Sep 13 15:00:37 helpdesk systemd[1]: Started zammad.service.
```

In */var/log/nginx/zammad-error.log* i see that the connection to Port :3000 is refused.

TBH i don't know i i just run into an own mistake or this behaviour just happend because i forgot something. So i just hope to get some help to resolve my issue.

Thanks a lot and best regards
Carsten

**Comment by monotek** [comment]
Seems your database is not available: 
"PG::ConnectionBad: could not connect to server: No such file or directory"

**Comment by cvantum** [comment]
Hi,

thanks for your response. I've noticed also that there could be a problem with PostgresQL. But the system seems to be ok via *systemd*

```
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled)
   Active: active (exited) since Thu 2017-09-14 07:19:53 CEST; 20min ago
 Main PID: 407 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/postgresql.service

Sep 14 07:19:53 helpdesk systemd[1]: Started PostgreSQL RDBMS.
```

Even if there is no open port via `lsof -i` i just thought that the system still have configured himself. Because the installation forced no further interaction. I tried to reconfigure *PostgresQL* and *Zammad* via:
`dpkg-reconfigure postresql`
`dpkg-reconfigure zammad`

I looked at the manual installation instructions ( https://docs.zammad.org/en/latest/install-source.html ) to initialize the database on my own. But it seems that the commands aren't available. With installation of *zammad* there weren't installed too:

```
p   rake     - ruby make-like utility                                                                                                  
p   rake-compiler    - Rake-based Ruby Extension (C, Java) task generator 
```

```
p   bundler     - Manage Ruby application dependencies
```


Or are these packages not recommended for an installation via *apt-get*


Thanks for your help,

best regards
Carsten

**Comment by cvantum** [comment]
I've closed the issue. Made a fresh reinstallation of server and package and now everything works fine. 

Thanks for your support 👍
