### ISSUE TITLE
Deleting users not working

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1539]
### Infos:

* Used Zammad version: 2

### Expected behavior:

* Being able to delete users

### Actual behavior:

* I tried to delete multiple users but I get this error when using `User.find_by(email: 'user@name.com').destroy`:
```
irb(main):003:0> User.find_by(email: 'user@name.com').destroy
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`zammad`.`users`, CONSTRAINT `fk_rails_45307c95a3` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`)): DELETE FROM `users` WHERE `users`.`id` = 32
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.6/lib/mysql2/client.rb:120:in `_query'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.6/lib/mysql2/client.rb:120:in `block in query'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.6/lib/mysql2/client.rb:119:in `handle_interrupt'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.6/lib/mysql2/client.rb:119:in `query'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/mysql2_adapter.rb:246:in `exec_delete'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:119:in `delete'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation.rb:478:in `delete_all'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:487:in `destroy_row'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/counter_cache.rb:152:in `destroy_row'
... 9 levels...
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:281:in `block in destroy'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:220:in `transaction'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:281:in `destroy'
	from (irb):3
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/console.rb:110:in `start'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/console.rb:9:in `start'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands.rb:17:in `<top (required)>'
	from /opt/zammad/bin/rails:4:in `require'
	from /opt/zammad/bin/rails:4:in `<main>'
irb(main):004:0> 
```

### Steps to reproduce the behavior:

* I try to run the above mentioned command on a newly imported user that has no tickes or anything assigned to him.

**Comment by thorsteneckel** [comment]
Please see the provided error message:
```
Cannot delete or update a parent row: a foreign key constraint fails (`zammad`.`users`, CONSTRAINT `fk_rails_45307c95a3` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`)): DELETE FROM `users` WHERE `users`.`id` = 32
```

There is a user that was created by this user.

**Comment by passboltUser** [comment]
Yes, but the users are freshly imported and not used anywhere. How can I solve without screwing the database up again (screwed the db up already, so I'm a bit more careful this time).

**Comment by thorsteneckel** [comment]
This is a DB level check so there is no chance that there is an issue with Zammad itself. I would suggest do check the DB table `users` column `created_by_id` where the ID `32` is stored - as stated in the error message.

**Comment by passboltUser** [comment]
Is there a command/script which would automatically do this so that I only need to provide the email?
