### ISSUE TITLE
search broken after update

### ISSUE THREAD

**Issue by bc1000** [zammad/zammad#1651]
### Infos:

* Used Zammad version: zammad-2.1.0-1509630445.763fbd63.centos7.x86_64
* Used Zammad installation source: package
* Operating system: Centos 7.4
* Browser + version: 

### Expected behavior:

* after yum update to actual version, elasticsearch is broken, service is shutting down directly after startup.

### Actual behavior:

* elasticsearch.log
java.lang.IllegalArgumentException: plugin [mapper-attachments] is incompatible with version [5.6.4]; was designed for version [5.6.0]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:80) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.6.4.jar:5.6.4]
[2017-11-17T12:51:23,913][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: plugin [mapper-attachments] is incompatible with version [5.6.4]; was designed for version [5.6.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.4.jar:5.6.4]
Caused by: java.lang.IllegalArgumentException: plugin [mapper-attachments] is incompatible with version [5.6.4]; was designed for version [5.6.0]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:80) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.4.jar:5.6.4]
	... 6 more

### Steps to reproduce the behavior:

* yum update 
==========================================================================================================================================================================================================
 Package                                                Arch                              Version                                                      Paketquelle                                  Größe
==========================================================================================================================================================================================================
Aktualisieren:
 elasticsearch                                          noarch                            5.6.4-1                                                      elasticsearch-5.x                             32 M
 nginx                                                  x86_64                            1:1.12.2-1.el7                                               epel                                         529 k
 nginx-all-modules                                      noarch                            1:1.12.2-1.el7                                               epel                                          16 k
 nginx-filesystem                                       noarch                            1:1.12.2-1.el7                                               epel                                          17 k
 nginx-mod-http-geoip                                   x86_64                            1:1.12.2-1.el7                                               epel                                          23 k
 nginx-mod-http-image-filter                            x86_64                            1:1.12.2-1.el7                                               epel                                          26 k
 nginx-mod-http-perl                                    x86_64                            1:1.12.2-1.el7                                               epel                                          35 k
 nginx-mod-http-xslt-filter                             x86_64                            1:1.12.2-1.el7                                               epel                                          25 k
 nginx-mod-mail                                         x86_64                            1:1.12.2-1.el7                                               epel                                          53 k
 nginx-mod-stream                                       x86_64                            1:1.12.2-1.el7                                               epel                                          76 k
 zammad                                                 x86_64                            2.1.0-1510748077.44070687.centos7                            zammad                                        82 M

Transaktionsübersicht
==========================================================================================================================================================================================================
Aktualisieren  11 Pakete

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by monotek** [comment]
As mentioned in the docs (https://docs.zammad.org/en/latest/install-elasticsearch.html) Elasticsearch 5.6 is not supported. 

Reason: https://github.com/zammad/zammad/issues/599
