### ISSUE TITLE
Telegram bot error when exit and delete telegram group

### ISSUE THREAD

**Issue by muhammadn** [zammad/zammad#1732]
### Infos:

* Used Zammad version: 2.2.0
* Installation method (source, package, ..): source
* Operating system: Mac OS X High Sierra
* Database + version: PostgreSQL
* Elasticsearch version: 
* Browser + version: Chrome 63

### Expected behavior:

* Bot with no permissions to read group messages will be ignored

### Actual behavior:

* When the bot has no permissions to read group messages, the telegram API will send data and it ends up with an error:

``
D, [2018-01-03T16:33:43.147579 #19943] DEBUG -- :    (0.2ms)  ROLLBACK
E, [2018-01-03T16:33:43.147948 #19943] ERROR -- : invalid action (RuntimeError)
/Users/zaihan/Projects/zammad/lib/telegram.rb:527:in `to_article'
/Users/zaihan/Projects/zammad/lib/telegram.rb:587:in `block in to_group'
/Users/zaihan/Projects/zammad/app/models/transaction.rb:12:in `block in execute'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
``

**Example payload that leads to error**
``
I, [2018-01-03T16:33:43.085711 #19943]  INFO -- :   Parameters: {"update_id"=>42733637, "message"=>{"message_id"=>54, "from"=>{"id"=>544535412, "is_bot"=>false, "first_name"=>"Muhammad Nuzaihan", "language_code"=>"en-SG"}, "chat"=>{"id"=>-274088764, "title"=>"Zaihan test", "type"=>"group", "all_members_are_administrators"=>true}, "date"=>1514967301, "left_chat_participant"=>{"id"=>544535412, "is_bot"=>false, "first_name"=>"Muhammad Nuzaihan", "language_code"=>"en-SG"}, "left_chat_member"=>{"id"=>544535412, "is_bot"=>false, "first_name"=>"Muhammad Nuzaihan", "language_code"=>"en-SG"}}, "bid"=>"435791794", "callback_token"=>"JCDa2S1tXJvIYw"}
``

### Steps to reproduce the behavior:

* Create a group in telegram
* Add your bot into the group
* Chat in the group
* Exit and Delete group (in Info)
Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
Fixed in #1727.
