### ISSUE TITLE
Broken Exchange integration - Attribute 'found_ids' is used

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1803]
### Infos:

* Used Zammad version: 2.3
* Installation method (source, package, ..): git
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Exchange integration should work as expected.

### Actual behavior:

* Start of Exchange sync fails due to an error:

```
E, [2018-02-02T15:49:36.171488 #4235] ERROR -- : Attribute 'found_ids' is used in Unit 'Sequencer::Unit::Import::Ldap::User::Lookup::Attributes' (index: 10) but is not provided or given via initial parameters. (RuntimeError)
/opt/zammad/lib/sequencer/state.rb:234:in `block (2 levels) in initialize_parameters'
/usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/delegate.rb:83:in `each'
/usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
/opt/zammad/lib/sequencer/state.rb:221:in `block in initialize_parameters'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer/state.rb:219:in `initialize_parameters'
/opt/zammad/lib/sequencer/state.rb:16:in `initialize'
/opt/zammad/lib/sequencer.rb:79:in `new'
/opt/zammad/lib/sequencer.rb:79:in `state'
/opt/zammad/lib/sequencer.rb:62:in `block (2 levels) in process'
/opt/zammad/lib/sequencer/units.rb:29:in `block in each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer.rb:60:in `each_with_index'
/opt/zammad/lib/sequencer.rb:60:in `block in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:58:in `process'
/opt/zammad/lib/sequencer.rb:25:in `process'
/opt/zammad/lib/sequencer/unit/import/common/sub_sequence/mixin/base.rb:34:in `sequence_resource'
/opt/zammad/lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:46:in `block (2 levels) in paginated_item_sequence'
/opt/zammad/lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:44:in `each'
/opt/zammad/lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:44:in `block in paginated_item_sequence'
/usr/local/rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/core_ext/range/each.rb:5:in `each'
/usr/local/rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/core_ext/range/each.rb:5:in `each'
/opt/zammad/lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:30:in `paginated_item_sequence'
/opt/zammad/lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:17:in `block in process'
/opt/zammad/lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:15:in `each'
/opt/zammad/lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:15:in `process'
/opt/zammad/lib/sequencer/unit/base.rb:200:in `process'
/opt/zammad/lib/sequencer.rb:65:in `block (4 levels) in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:64:in `block (3 levels) in process'
/opt/zammad/lib/sequencer/state.rb:149:in `process'
/opt/zammad/lib/sequencer.rb:62:in `block (2 levels) in process'
/opt/zammad/lib/sequencer/units.rb:29:in `block in each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer.rb:60:in `each_with_index'
/opt/zammad/lib/sequencer.rb:60:in `block in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:58:in `process'
/opt/zammad/lib/sequencer.rb:25:in `process'
/opt/zammad/lib/import/mixin/sequence.rb:11:in `process'
/opt/zammad/lib/import/integration_base.rb:98:in `start'
/opt/zammad/app/models/import_job.rb:22:in `start'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/relation/delegation.rb:39:in `each'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/relation/delegation.rb:39:in `each'
/opt/zammad/app/models/import_job.rb:101:in `start'
/opt/zammad/app/models/import_job.rb:91:in `start_registered'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:226:in `eval'
/opt/zammad/app/models/scheduler.rb:226:in `_start_job'
/opt/zammad/app/models/scheduler.rb:205:in `block in start_job'
/usr/local/rvm/gems/ruby-2.4.2/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

### Steps to reproduce the behavior:

* Start an Exchange sync.

This bug was [introduced due to a change](https://github.com/zammad/zammad/commit/1ec2b514bb574937bc378f46fa922768a58d5dca) in the LDAP sync. The behavior and used attributes for the Sequencer Unit `Import::Ldap::User::Lookup::Attributes` changed. However, the original functionality was moved to the proper generic namespace `Import::Common::Model::FindBy::UserAttributes`. Because of the specific LDAP namespace the dependency in the Exchange integration was overlooked and therefore not migrated to the new proper Unit.

**Comment by thorsteneckel** [comment]
Fixed with the two commits above for stable and develop. Ready to install in ~30 min from now.
