### ISSUE TITLE
Zammad crashes after Update from 2.2.0 to 2.3.0

### ISSUE THREAD

**Issue by MacLemon** [zammad/zammad#1806]
### Infos:
* Used Zammad version: 2.2.0 -> 2.3.0
* Installation method (source, package, ..): source
* Operating system: FreeBSD 11.1p6
* Database + version: PostGreSQL 10.1
* Elasticsearch version: n/a not in use
* Browser + version: n/a doesn't affect GUI
* Ruby Version: 2.4.3 (from pkg)
* Installed Ruby Gems listed below

### Expected behavior:
* After updating from 2.2.0 to 2.3.0 following [Updating instructions](https://docs.zammad.org/en/latest/install-update.html) Zammad should successfully start.

### Actual behavior:
* Zammad doesn't start and crashes with a stack trace. (Shown below.)

### Steps to reproduce the behavior:
* Have a working installation of Zammad 2.2.0.
* Follow the [instructions for updating](https://docs.zammad.org/en/latest/install-update.html).
* Try to launch Zammad 2.3.0

### Workaround
* Rollback to 2.2.0

```
=> Booting Puma
=> Rails 5.1.4 application starting in production
=> Run `rails server -h` for more startup options
Exiting
/usr/home/zammad/zammad/lib/import/zendesk/async.rb:2:in `<module:Import>': Zendesk is not a module (TypeError)
from /usr/home/zammad/zammad/lib/import/zendesk/async.rb:1:in `<top (required)>'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:379:in `block in require_or_load'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:335:in `depend_on'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:251:in `require_dependency'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/engine.rb:475:in `each'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/engine.rb:475:in `block in eager_load!'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/engine.rb:473:in `each'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/engine.rb:473:in `eager_load!'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/engine.rb:354:in `eager_load!'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `each'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/application/finisher.rb:67:in `block in <module:Finisher>'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
from /usr/local/lib/ruby/2.4/tsort.rb:228:in `block in tsort_each'
from /usr/local/lib/ruby/2.4/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
from /usr/local/lib/ruby/2.4/tsort.rb:431:in `each_strongly_connected_component_from'
from /usr/local/lib/ruby/2.4/tsort.rb:349:in `block in each_strongly_connected_component'
from /usr/local/lib/ruby/2.4/tsort.rb:347:in `each'
from /usr/local/lib/ruby/2.4/tsort.rb:347:in `call'
from /usr/local/lib/ruby/2.4/tsort.rb:347:in `each_strongly_connected_component'
from /usr/local/lib/ruby/2.4/tsort.rb:226:in `tsort_each'
from /usr/local/lib/ruby/2.4/tsort.rb:205:in `tsort_each'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
from /usr/home/zammad/zammad/config/environment.rb:5:in `<top (required)>'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
from config.ru:3:in `block in <main>'
from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
from config.ru:in `new'
from config.ru:in `<main>'
from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:24:in `app'
from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
from /usr/local/lib/ruby/gems/2.4/gems/rack-2.0.3/lib/rack/server.rb:283:in `start'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:44:in `start'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:135:in `block in perform'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
from /usr/local/lib/ruby/gems/2.4/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
from /usr/local/lib/ruby/gems/2.4/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
from /usr/local/lib/ruby/gems/2.4/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
from /usr/local/lib/ruby/gems/2.4/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
from bin/rails:4:in `require'
from bin/rails:4:in `<main>'
```

Ruby Gems:
```
$ gem query --local

*** LOCAL GEMS ***

actioncable (5.1.4)
actionmailer (5.1.4)
actionpack (5.1.4)
actionview (5.1.4)
activejob (5.1.4)
activemodel (5.1.4)
activerecord (5.1.4)
activerecord-nulldb-adapter (0.3.7)
activerecord-session_store (1.1.0)
activesupport (5.1.4)
addressable (2.5.2)
arel (8.0.0)
argon2 (1.1.4)
autoprefixer-rails (7.1.6)
bindex (0.5.0)
biz (1.7.0)
browser (2.5.2)
buftok (0.2.0)
builder (3.2.3)
bundler (1.16.1)
byebug (9.1.0)
capybara (2.16.1)
childprocess (0.8.0)
clavius (1.0.3)
clearbit (0.2.8)
coffee-rails (4.2.2)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
composite_primary_keys (10.0.1)
concurrent-ruby (1.0.5)
crass (1.0.3)
daemons (1.2.5)
dalli (2.7.6)
delayed_job (4.1.3)
delayed_job_active_record (4.1.2)
diffy (3.2.0)
domain_name (0.5.20170404)
doorkeeper (4.2.6)
eco (1.0.0)
eco-source (1.1.0.rc.1)
em-websocket (0.5.1)
equalizer (0.0.11)
erubi (1.7.0)
eventmachine (1.2.5)
execjs (2.7.0)
faraday (0.12.2)
ffi (1.9.18)
ffi-compiler (0.1.3)
globalid (0.4.1)
hashie (3.5.6)
htmlentities (4.3.4)
http (3.0.0)
http-cookie (1.0.3)
http-form_data (2.0.0)
http_parser.rb (0.6.0)
httpclient (2.8.3)
i18n (0.9.1)
icalendar (2.4.1)
icalendar-recurrence (1.1.2)
ice_cube (0.16.2)
inflection (1.0.0)
jbuilder (2.7.0)
jquery-rails (4.3.1)
json (2.1.0)
json_pure (2.1.0)
jwt (1.5.6)
kgio (2.11.0)
koala (3.0.0)
libv8 (3.16.14.19 amd64-freebsd-11)
little-plugger (1.1.4)
logging (2.2.2)
loofah (2.1.1)
mail (2.7.0, 2.6.6)
memoizable (0.4.2)
method_source (0.9.0)
mime-types (2.99.3)
mini_mime (1.0.0)
mini_portile2 (2.3.0)
minitest (5.10.3)
multi_json (1.12.2)
multi_xml (0.6.0)
multipart-post (2.0.0)
naught (1.1.0)
nestful (1.1.3)
net-ldap (0.16.1)
netrc (0.11.0)
nio4r (2.2.0, 2.1.0)
nokogiri (1.8.1)
nori (2.6.0)
oauth (0.5.3)
oauth2 (1.4.0)
omniauth (1.7.1)
omniauth-facebook (4.0.0)
omniauth-github (1.3.0)
omniauth-gitlab (1.0.2)
omniauth-google-oauth2 (0.5.2)
omniauth-linkedin-oauth2 (0.2.5)
omniauth-microsoft-office365 (0.0.7)
omniauth-oauth (1.1.0)
omniauth-oauth2 (1.4.0)
omniauth-twitter (1.4.0)
omniauth-weibo-oauth2 (0.4.5)
pg (0.21.0)
pkg-config (1.2.8)
public_suffix (3.0.1)
puma (3.11.0)
rack (2.0.3, 1.6.8)
rack-test (0.8.2)
rails (5.1.4)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.3)
rails-observers (0.1.5)
railties (5.1.4)
raindrops (0.19.0)
rake (12.3.0)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
ref (2.0.0)
rest-client (1.8.0)
rubyzip (1.2.1)
sass (3.5.4, 3.5.3)
sass-listen (4.0.0)
sass-rails (5.0.7)
selenium-webdriver (3.8.0)
simple_oauth (0.3.1)
slack-notifier (2.3.1)
spring (2.0.2)
sprockets (3.7.1)
sprockets-rails (3.2.1)
sqlite3 (1.3.13)
telegramAPI (1.4.1)
therubyracer (0.12.3)
thor (0.20.0)
thread_safe (0.3.6)
tilt (2.0.8)
turbolinks (5.0.1)
turbolinks-source (5.0.3)
twitter (6.2.0)
tzinfo (1.2.4)
uglifier (3.2.0)
unf (0.1.4)
unf_ext (0.0.7.4)
unicorn (5.3.1)
valid_email2 (2.1.0)
viewpoint (1.1.0)
web-console (3.5.1)
websocket-driver (0.7.0, 0.6.5)
websocket-extensions (0.1.3)
writeexcel (1.0.5)
xpath (2.1.0)
zendesk_api (1.16.0)
```
Yes I'm sure this is a bug and no feature request or a general question.

**Comment by ktb92677** [comment]
I have a similar "TypeError: Zendesk is not a module" that pops up in /var/log/syslog when upgrading from 1.5.0 to 2.3.0.

Please help!

**Comment by nicostuhlfauth** [comment]
Same here. Upgrading from 2.2.0 to 2.3.0 on Ubuntu 16.04. Installed from Source. DB is MySQL. Is there already a workaround or is downgrading the only option?

**Comment by thorsteneckel** [comment]
It seems something went wrong in your update procedure. The file `lib/import/zendesk/async.rb` doesn't exist anymore in a Zammad 2.3 installation: https://github.com/zammad/zammad/tree/stable/lib/import/zendesk

Please make sure only Zammad 2.3 files are present in your working directory. For those with supported OSs: Use the provided packages to avoid such issues 👍
