### ISSUE TITLE
Elasticsearch should work

### ISSUE THREAD

**Issue by clicksports** [zammad/zammad#1817]
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): package
* Operating system: debian 8.10
* Database + version: Ver 15.1 Distrib 10.0.32-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
* Elasticsearch version: 6.2.0, Build: 37cdac1/2018-02-01T17:31:12.527918Z, JVM: 1.8.0_161
* Browser + version: Chrome + Version 64.0.3282.140 (Offizieller Build) (64-Bit)

### Expected behavior:

* Elasticsearch does not indexing

### Actual behavior:

* When the ElasticSearch index is rebuilt, the application crashes when indexing users.

### Steps to reproduce the behavior:

`zammad run rake searchindex:rebuild`

### Error Messages:

**> zammad run rake searchindex:rebuild --trace**
<pre>
** Invoke searchindex:rebuild (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute searchindex:rebuild
** Execute searchindex:drop
drop indexes...done
** Execute searchindex:drop_pipeline
delete pipeline (pipeline)... done
** Execute searchindex:create
create indexes...done
** Execute searchindex:create_pipeline
create pipeline (pipeline)... done
** Execute searchindex:reload
reload data...
 reload Ticket
  - started at 2018-02-08 09:25:56 UTC
  - took 57 seconds
 reload Chat::Session
  - started at 2018-02-08 09:26:54 UTC
  - took 0 seconds
 reload User
  - started at 2018-02-08 09:26:54 UTC
rake aborted!
Unable to send User.find(222).search_index_update_backend backend: #<RuntimeError: Unable to process POST at http://127.0.0.1:9200/zammad_production/User/222?pipeline=zammad767206091723 (size: 0M)
#<UserAgent::Result:0x000055d0cb31d250 @success=false, @body=nil, @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">>
/opt/zammad/app/models/concerns/has_search_index_backend.rb:138:in `rescue in block in search_index_reload'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:133:in `block in search_index_reload'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:130:in `each'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:130:in `search_index_reload'
/opt/zammad/lib/tasks/search_index_es.rake:156:in `block (3 levels) in <top (required)>'
/opt/zammad/lib/tasks/search_index_es.rake:152:in `each'
/opt/zammad/lib/tasks/search_index_es.rake:152:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/opt/zammad/lib/tasks/search_index_es.rake:167:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/opt/zammad/vendor/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/bin/rake:22:in `load'
/opt/zammad/vendor/bundle/ruby/2.4.0/bin/rake:22:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/opt/zammad/bin/bundle:3:in `load'
/opt/zammad/bin/bundle:3:in `<main>'

Caused by:
Unable to process POST at http://127.0.0.1:9200/zammad_production/User/222?pipeline=zammad767206091723 (size: 0M)
#<UserAgent::Result:0x000055d0cb31d250 @success=false, @body=nil, @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">
/opt/zammad/lib/search_index_backend.rb:191:in `add'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:64:in `search_index_update_backend'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:134:in `block in search_index_reload'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:130:in `each'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:130:in `search_index_reload'
/opt/zammad/lib/tasks/search_index_es.rake:156:in `block (3 levels) in <top (required)>'
/opt/zammad/lib/tasks/search_index_es.rake:152:in `each'
/opt/zammad/lib/tasks/search_index_es.rake:152:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/opt/zammad/lib/tasks/search_index_es.rake:167:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/opt/zammad/vendor/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/bin/rake:22:in `load'
/opt/zammad/vendor/bundle/ruby/2.4.0/bin/rake:22:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/opt/zammad/bin/bundle:3:in `load'
/opt/zammad/bin/bundle:3:in `<main>'
Tasks: TOP => searchindex:rebuild
</pre>

**/var/log/elasticsearch/elasticsearch.log:**
<pre>
[2018-02-08T10:27:36,153][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [F6Y3IyT] failed to put mappings on indices [[[zammad_production/0cJhvf_NTGy-_nEdRf6Rrg]]], type [User]
java.lang.IllegalArgumentException: Rejecting mapping update to [zammad_production] as the final mapping would have more than 1 type: [Ticket, User]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:501) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:285) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:313) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:566) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [elasticsearch-6.2.0.jar:6.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[2018-02-08T10:27:36,154][DEBUG][o.e.a.b.TransportShardBulkAction] [zammad_production][0] failed to execute bulk item (index) BulkShardRequest [[zammad_production][0]] containing [index {[zammad_production][User][227], source[{"country":"","note":"","firstname":"Anrika","city":"","created_at":"2018-02-08T09:18:42.000Z","login":"perz@anrika.de","role_ids":[3],"updated_at":"2018-02-08T09:21:01.159Z","web":"","street":"","permissions":["user_preferences.password","user_preferences.language","user_preferences.linked_accounts","user_preferences.avatar","ticket.customer"],"id":227,"fax":"","department":"","vip":false,"email":"perz@anrika.de","out_of_office":false,"out_of_office_start_at":null,"zip":"","preferences":{"tickets_open":0,"tickets_closed":1},"address":"","last_login":null,"mobile":"","verified":false,"active":true,"lastname":"Perz","out_of_office_end_at":null,"out_of_office_replacement_id":null,"phone":"","organization_id":null,"updated_by_id":3,"created_by_id":227}]}]
java.lang.IllegalArgumentException: Rejecting mapping update to [zammad_production] as the final mapping would have more than 1 type: [Ticket, User]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:501) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:285) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:313) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:566) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) ~[elasticsearch-6.2.0.jar:6.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[2018-02-08T10:27:36,245][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [F6Y3IyT] failed to put mappings on indices [[[zammad_production/0cJhvf_NTGy-_nEdRf6Rrg]]], type [User]
java.lang.IllegalArgumentException: Rejecting mapping update to [zammad_production] as the final mapping would have more than 1 type: [Ticket, User]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:501) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:285) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:313) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:566) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [elasticsearch-6.2.0.jar:6.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[2018-02-08T10:27:36,246][DEBUG][o.e.a.b.TransportShardBulkAction] [zammad_production][2] failed to execute bulk item (index) BulkShardRequest [[zammad_production][2]] containing [index {[zammad_production][User][163], source[{"country":"","note":"","firstname":"Michael","city":"","created_at":"2018-02-05T08:16:43.000Z","login":"michael.passing@novaconcept.de","role_ids":[3],"updated_at":"2018-02-05T13:40:53.833Z","web":"","street":"","permissions":["user_preferences.password","user_preferences.language","user_preferences.linked_accounts","user_preferences.avatar","ticket.customer"],"id":163,"fax":"","department":"","vip":false,"email":"michael.passing@novaconcept.de","out_of_office":false,"out_of_office_start_at":null,"zip":"","preferences":{"tickets_open":1,"tickets_closed":0,"locale":"de-de"},"address":"","last_login":null,"mobile":"","verified":false,"active":true,"lastname":"Passing","out_of_office_end_at":null,"out_of_office_replacement_id":null,"phone":"","organization_id":null,"updated_by_id":3,"created_by_id":3}]}]
java.lang.IllegalArgumentException: Rejecting mapping update to [zammad_production] as the final mapping would have more than 1 type: [Ticket, User]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:501) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:285) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:313) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:566) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) ~[elasticsearch-6.2.0.jar:6.2.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) ~[elasticsearch-6.2.0.jar:6.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
</pre>

**Comment by monotek** [comment]
Elasticsearch is currently only supported until version 5.6. 
See: https://docs.zammad.org/en/latest/install-elasticsearch.html
