### ISSUE TITLE
Mysql2::Error: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535.

### ISSUE THREAD

**Issue by benhartwich** [zammad/zammad#1824]
### Infos:

* Used Zammad version: 2.30..
* Installation method (source, package, ..): source
* Operating system: Debian 9
* Database + version: MariaDB 10.2
* Elasticsearch version: not installed yet
* Browser + version: Chrome

### Expected behavior:
I tried to migrate and seed the mysql database

### Actual behavior:
Migrate errors occurs: 
```
Mysql2::Error: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs: CREATE TABLE `http_logs` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `direction` varchar(20) NOT NULL, `facility` varchar(100) NOT NULL, `method` varchar(100) NOT NULL, `url` varchar(255) NOT NULL, `status` varchar(20), `ip` varchar(50), `request` varchar(10000) NOT NULL, `response` varchar(10000) NOT NULL, `updated_by_id` int, `created_by_id` int, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL) ENGINE=InnoDB
/usr/local/rvm/gems/ruby-2.4.2/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/usr/local/rvm/gems/ruby-2.4.2/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/usr/local/rvm/gems/ruby-2.4.2/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.4.2/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/usr/local/rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/usr/local/rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/usr/local/rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/usr/local/rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:212:in `execute'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/mysql/database_statements.rb:26:in `execute'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:288:in `create_table'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:363:in `create_table'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration/compatibility.rb:45:in `create_table'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration/compatibility.rb:91:in `create_table'
/opt/zammad/db/migrate/20120101000001_create_base.rb:689:in `up'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:795:in `exec_migration'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:1300:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/usr/local/rvm/gems/ruby-2.4.2/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
```

### Steps to reproduce the behavior:
Download the latest zammad, install rvm 2.4.2, try to migrate the database with mysql

**Comment by muhammadn** [comment]
@benhartwich Is this for a new installation or an upgrade?

**Comment by benhartwich** [comment]
A fresh installation. Works with postgresql from source, but I cannot set the application to production mode...

**Comment by martini** [comment]
What mysql/mariadb database charset for database is used? utf8 or utf8mb4?

**Comment by benhartwich** [comment]
I think I tried both. The default charset of my mariadb uft8.

**Comment by muhammadn** [comment]
@benhartwich I have tried using the stable and develop branches with MariaDB with:

```
export RAILS_ENV=production
rails db:drop && rails db:create && rails db:migrate && rails db:seed
```

No errors. By checking the charset by running this query:
```
SHOW VARIABLES LIKE  'char%';
```
It shows utf-8 so it is working fine.

**Comment by benhartwich** [comment]
Thanks, the variable shows the following:

```
character_set_client | utf8mb4
-- | --
character_set_connection | utf8mb4
character_set_database | latin1
character_set_filesystem | binary
character_set_results | utf8mb4
character_set_server | latin1
character_set_system | utf8
```

I´ve got it working with Postgresql

**Comment by muhammadn** [comment]
I think that is the problem.

My MariaDB character encoding is as follows:
```
mysql> SHOW VARIABLES LIKE  'char%';
+--------------------------+---------------------------------------------------------+
| Variable_name            | Value                                                   |
+--------------------------+---------------------------------------------------------+
| character_set_client     | utf8                                                    |
| character_set_connection | utf8                                                    |
| character_set_database   | utf8                                                    |
| character_set_filesystem | binary                                                  |
| character_set_results    | utf8                                                    |
| character_set_server     | utf8                                                    |
| character_set_system     | utf8                                                    |
| character_sets_dir       | /usr/local/Cellar/mariadb/10.2.12/share/mysql/charsets/ |
+--------------------------+---------------------------------------------------------+
8 rows in set (0.00 sec)
```

You can change it to utf-8 by adding/updating to my.cnf
```
default-character-set = utf8
```
to the client, mysqld_safe, mysqld and mysqldump _section_ of **my.cnf**

restart and run:

```
export RAILS_ENV=production
rails db:drop && rails db:create && rails db:migrate && rails db:seed
```

**Comment by martini** [comment]
@benhartwich the 4 byte utf8 chars was the final push why I moved from mariadb/mysql to postgresql 2 years ago. 

It's unbelievable the a database is only supporting emojis with massiv restriction to sizes of rows/indexes.

I have not regretted the change to PostgreSQL. ❤️

**Comment by benhartwich** [comment]
Thanks, I will run zammad with postgresql.

**Comment by monotek** [comment]
i've added the info to the docs: https://github.com/zammad/zammad-documentation/commit/8974151bdbe49223b2ac9ef7135cd65c3c085277

**Comment by jmptbl** [comment]
Another fix in case one does not want to modify their MySQL global config is to create Zammad's database manually like this:

`CREATE DATABASE zammad_prod CHARACTER SET utf8;`
