### ISSUE TITLE
Upgrade failed, scheduler does not start

### ISSUE THREAD

**Issue by wagnst** [zammad/zammad#1943]
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): source
* Operating system: Debian 3.16.51-3+deb8u1 
* Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

I upgraded zammad manually according to your wiki. After it ran through and i modified the systemd entries, rails and websocket is coming up. Unfortunately the scheduler crashes after several seconds.
I tried running it manually and i get this output:

```
$ bundle exec script/scheduler.rb start
bundler: failed to load command: script/scheduler.rb (script/scheduler.rb)
NameError: uninitialized constant Rack::LiveReload
  /home/zammad/config/environments/development.rb:37:in `block in <top (required)>'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:211:in `instance_eval'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:211:in `configure'
  /home/zammad/config/environments/development.rb:1:in `<top (required)>'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:599:in `each'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:599:in `block in <class:Engine>'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `each'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `tsort_each_child'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:415:in `call'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `call'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
  /home/zammad/config/environment.rb:5:in `<top (required)>'
  script/scheduler.rb:14:in `require'
  script/scheduler.rb:14:in `<top (required)>'
```

The processes itself are running:

```
zammad   25832     1  0 20:31 ?        00:00:00 /bin/sleep infinity
zammad   25834     1  3 20:31 ?        00:00:12 puma 3.11.3 (tcp://0.0.0.0:3000) [zammad]                                                                                                          
zammad   25835     1  3 20:31 ?        00:00:12 script/websocket-server.rb -b 0.0.0.0 -p 6042 start                                                                                                             
zammad   28948     1 74 20:38 ?        00:00:01 script/scheduler.rb start  
```

When I try to login to the portal it hangs with "Loading..."

![image](https://user-images.githubusercontent.com/7312523/38576706-32e3b040-3cff-11e8-8bb4-e4cc8a9c7ecd.png)

Can you give me some hints, what might cause this issue?

**Comment by wagnst** [comment]
Maybe some more info. In the log folder, the file `scheduler_err.log` contains the following info:

```
ActiveModel::UnknownAttributeError: unknown attribute 'error_message' for Scheduler.
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:39:in `each'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:297:in `block in update!'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
  /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:296:in `update!'
  /home/zammad/app/models/scheduler.rb:255:in `rescue in _start_job'
  /home/zammad/app/models/scheduler.rb:218:in `_start_job'
  /home/zammad/app/models/scheduler.rb:248:in `rescue in _start_job'
  /home/zammad/app/models/scheduler.rb:218:in `_start_job'
  /home/zammad/app/models/scheduler.rb:248:in `rescue in _start_job'
  /home/zammad/app/models/scheduler.rb:218:in `_start_job'
  /home/zammad/app/models/scheduler.rb:248:in `rescue in _start_job'
  /home/zammad/app/models/scheduler.rb:218:in `_start_job'
  /home/zammad/app/models/scheduler.rb:248:in `rescue in _start_job'
  /home/zammad/app/models/scheduler.rb:218:in `_start_job'
  /home/zammad/app/models/scheduler.rb:248:in `rescue in _start_job'
  /home/zammad/app/models/scheduler.rb:218:in `_start_job'
  /home/zammad/app/models/scheduler.rb:248:in `rescue in _start_job'
  /home/zammad/app/models/scheduler.rb:218:in `_start_job'
  /home/zammad/app/models/scheduler.rb:248:in `rescue in _start_job'
  /home/zammad/app/models/scheduler.rb:218:in `_start_job'
  /home/zammad/app/models/scheduler.rb:248:in `rescue in _start_job'
  /home/zammad/app/models/scheduler.rb:218:in `_start_job'
  /home/zammad/app/models/scheduler.rb:248:in `rescue in _start_job'
  /home/zammad/app/models/scheduler.rb:218:in `_start_job'
  /home/zammad/app/models/scheduler.rb:205:in `block in start_job'
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

```

**Comment by thorsteneckel** [comment]
Hi @wagnst - This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

As far as I can see the scheduler tries to start in the development environment.
`  /home/zammad/config/environments/development.rb:37:in `block in <top (required)>'`

This is why the dependency to `Rack::LiveReload` is missing. There are some [ENV vars](https://github.com/zammad/zammad/blob/develop/script/systemd/zammad.env) are missing when starting the scheduler manually via `bundle exec script/scheduler.rb start` as you did... Usually this should be done via a service script like [install-zammad-systemd-services.sh](https://github.com/zammad/zammad/blob/develop/script/systemd/install-zammad-systemd-services.sh#L18) as described here: https://docs.zammad.org/en/latest/install-source.html#starting-servers-with-systemd

**Comment by wagnst** [comment]
@thorsteneckel I understand - but I did this and the env and systemd entries are there. As said, the process (started via systemd) fails after ~30s and restarts all the time. I just tried manually starting it to see whats going on.

```
$ systemctl status zammad-scheduler.service 
● zammad-scheduler.service - Zammad
   Loaded: loaded (/etc/systemd/system/zammad-scheduler.service; enabled)
   Active: activating (start) since Tue 2018-04-10 21:57:59 CEST; 8s ago
 Main PID: 856 (code=exited, status=1/FAILURE);         : 866 (ruby)
   CGroup: /system.slice/zammad-scheduler.service
           └─866 script/scheduler.rb start

Apr 10 21:58:07 vir136 bash[866]: /home/zammad/lib/core_ext/fixnum.rb:1: warning: constant ::Fixnum is deprecated

```

```
$ cat /etc/zammad/zammad.env 
BUNDLE_BINARY=bundle
RAILS_ENV=production
ZAMMAD_BIND_IP=0.0.0.0
ZAMMAD_RAILS_PORT=3000
ZAMMAD_WEBSOCKET_PORT=6042
```

```
$ cat /etc/systemd/system/zammad-scheduler.service 
[Unit]
Description=Zammad
After=syslog.target
After=network.target
After=zammad.service
Requires=zammad.service

[Service]
Type=forking
EnvironmentFile=/etc/zammad/zammad.env
User=zammad
Group=zammad
Restart=always

WorkingDirectory=/home/zammad

ExecStart=/bin/bash -l -c "${BUNDLE_BINARY} exec script/scheduler.rb start"

[Install]
WantedBy=zammad.service
```

I'm pretty confident that the config and migration is done as desribed in your wiki...

**Comment by martini** [comment]
@wagnst 

1)
```
ActiveModel::UnknownAttributeError: unknown attribute 'error_message' for Scheduler.
  /home/zammad/vendor/bundle/ruby/2.4.0/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
```

Is the same as it is in #1944 - your database is not upgraded.

2) 
```
$ bundle exec script/scheduler.rb start
bundler: failed to load command: script/scheduler.rb (script/scheduler.rb)
NameError: uninitialized constant Rack::LiveReload
  /home/zammad/config/environments/development.rb:37:in `block in <top (required)>'
```

Means that you are in rails development environment (not production). 

 -> I recommend to use Zammad package installation to avoid this setup issue.

Greetings,

 -Martin
