### ISSUE TITLE
Zammad web interface crashes, maybe it's caused by Telegram Bot

### ISSUE THREAD

**Issue by Guglio95** [zammad/zammad#1999]
### Infos:

* Used Zammad version: latest, just compiled from "stable" branch 
* Installation method (source, package, ..):  Docker: https://github.com/Guglio95/zammad-docker-noElasticSearch  with provided docker-compose.yml 
* Operating system:  Description:	Ubuntu 16.04.3 LTS
* Database + version:  MariaDB 10.0.2 (https://hub.docker.com/_/mariadb/)
* Elasticsearch version:  Not installed
* Browser + version: Chrome (it's not relevant i think)

### Expected behavior:
Zammad should not crash

### Actual behavior:
Zammad stops being reachable from web interface, it must be re-started in order to get back online.
I think it's related to some non UTF8 characters in Telegram User's nickname:

`
Mysql2::Error: Incorrect string value: '\xC4\xA0\xC3\xBCgl...' for column 'firstname' at row 1: INSERT INTO `users` (`login`, `firstname`, `lastname`, `updated_by_id`, `created_by_id`, `created_at`, `updated_at`) VALUES ('*******', 'Ġüglíęlmõ', NULL, 1, 1, '2018-05-07 16:47:51', '2018-05-07 16:47:51.186000') (ActiveRecord::StatementInvalid)
`

I've tried to change the charset of mariaDB (which was created by zammad itself) with:

`ALTER TABLE users CONVERT TO CHARACTER SET utf8
`
Waiting to see if something changes.

### Steps to reproduce the behavior:
Don't know how to reproduce, after a while it's simply stopping to be available and gives back a 500 error.

[zammadLog.txt](https://github.com/zammad/zammad/files/1980765/zammadLog.txt)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Guglio95** [comment]
Still having problems with MySQL. I've tried to change to a brand new postgresql installation, still getting:

```
zammad_1    | 20:42:08 rails.1      | I, [2018-05-07T20:42:08.222647 #36]  INFO -- :   Rendering inline template
zammad_1    | 20:42:08 rails.1      | I, [2018-05-07T20:42:08.226486 #36]  INFO -- :   Rendered inline template (3.5ms)
zammad_1    | 20:42:08 rails.1      | I, [2018-05-07T20:42:08.226784 #36]  INFO -- : Completed 500 Internal Server Error in 139ms (Views: 7.0ms | ActiveRecord: 12.6ms)
zammad_1    | 20:42:08 proxy.1      | 172.26.0.1 - - [07/May/2018:20:42:08 +0000] "POST /api/v1/channels_telegram_webhook/zxxxxxxxxxxx?bid=4xxxxxx HTTP/1.0" 500 370 "-" "-"
zammad_1    | 20:42:08 rails.1      | I, [2018-05-07T20:42:08.492562 #36]  INFO -- : Started POST "/api/v1/channels_telegram_webhook/zxxxxxxxxx3Q?bid=4xxxxxxxxx" for 141.101.107.243 at 2018-05-07 20:42:08 +0000
zammad_1    | 20:42:08 rails.1      | I, [2018-05-07T20:42:08.502178 #36]  INFO -- : Processing by ChannelsTelegramController#webhook as HTML
zammad_1    | 20:42:08 rails.1      | I, [2018-05-07T20:42:08.503296 #36]  INFO -- :   Parameters: {"update_id"=>997950527, "message"=>{"message_id"=>4964, "from"=>{"id"=>xxxxxxx, "is_bot"=>false, "first_name"=>"✵➬ ͍͍͍͍͍ϛ͍͍͍͍α͍͍͍͍ℳ͍͍͍ ͍͍͍͍͍℘͍͍͍͍γ͍͍͍͍τ͍͍͍͍͍ο͍͍͍͍͍͍й͍͍͍͍͍ ͍͍͍͍͍ҡ͍͍͍͍α͍͍͍℘͍͍͍͍ℳ͍͍͍͍xxxxxx ͍͍➣✵", "username"=>"xxxxxx"}, "chat"=>{"id"=>xxxx, "first_name"=>"✵➬ ͍͍͍͍͍ϛ͍͍͍͍α͍͍͍͍ℳ͍͍͍ ͍͍͍͍͍℘͍͍͍͍γ͍͍͍͍τ͍͍͍͍͍ο͍͍͍͍͍͍й͍͍͍͍͍ ͍͍͍͍͍ҡ͍͍͍͍α͍͍͍℘͍͍͍͍ℳ͍͍͍͍xxxxx✵", "username"=>"xxxxxxxx", "type"=>"private"}, "date"=>1525721647, "text"=>"/start", "entities"=>[{"offset"=>0, "length"=>6, "type"=>"bot_command"}]}, "bid"=>"xxxxxxx", "callback_token"=>"xxxxx"}
zammad_1    | 20:42:08 rails.1      | E, [2018-05-07T20:42:08.622654 #36] ERROR -- : 403 Forbidden (RestClient::Forbidden)

```

**Comment by thorsteneckel** [comment]
Hi @Guglio95 - I think that there are at least two issues:

One is the charset issue you described above. Sadly you removed the interesting parts of the log file 🤓 Could you please provide the full traceback after the log line `Mysql2::Error: Incorrect string value` which looks like a list of file paths?

The other one is a permission issue: 

```
zammad_1   | 16:47:43 rails.1      | E, [2018-05-07T16:47:43.830450 #28] ERROR -- : 403 Forbidden (RestClient::Forbidden)
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
zammad_1   | 16:47:43 rails.1      | /usr/local/lib/ruby/2.4.0/net/http.rb:877:in `start'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient.rb:69:in `post'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/telegramAPI-1.4.1/lib/telegramAPI.rb:28:in `query'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/telegramAPI-1.4.1/lib/telegramAPI.rb:53:in `sendMessage'
zammad_1   | 16:47:43 rails.1      | /opt/zammad/lib/telegram.rb:216:in `message'
zammad_1   | 16:47:43 rails.1      | /opt/zammad/lib/telegram.rb:636:in `to_group'
zammad_1   | 16:47:43 rails.1      | /opt/zammad/app/controllers/channels_telegram_controller.rb:70:in `webhook'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:186:in `process_action'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:131:in `run_callbacks'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/notifications.rb:166:in `block in instrument'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/notifications/instrumenter.rb:21:in `instrument'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/notifications.rb:166:in `instrument'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/abstract_controller/base.rb:124:in `process'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionview-5.1.4/lib/action_view/rendering.rb:30:in `process'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_controller/metal.rb:189:in `dispatch'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_controller/metal.rb:253:in `dispatch'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:31:in `serve'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in `each'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/journey/router.rb:33:in `serve'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:834:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/omniauth-1.7.1/lib/omniauth/builder.rb:63:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/callbacks.rb:97:in `run_callbacks'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/railties-5.1.4/lib/rails/rack/logger.rb:36:in `call_app'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `block in call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/tagged_logging.rb:69:in `block in tagged'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/tagged_logging.rb:26:in `tagged'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/tagged_logging.rb:69:in `tagged'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/middleware/request_id.rb:25:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/cache/strategy/local_cache_middleware.rb:27:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `public_send'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `method_missing'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/puma-3.11.0/lib/puma/configuration.rb:225:in `call'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/puma-3.11.0/lib/puma/server.rb:624:in `handle_request'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/puma-3.11.0/lib/puma/server.rb:438:in `process_client'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/puma-3.11.0/lib/puma/server.rb:302:in `block in run'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
zammad_1   | 16:47:43 rails.1      | /usr/local/bundle/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```
Zammad get's an update from Telegram that there is a new message and tries to receive it. This fails because of wrong authentication credentials as stated by: `403 Forbidden`

Waiting for your feedback regarding the charset issue.

**Comment by Guglio95** [comment]
Hi: @thorsteneckel :vulcan_salute:  

Now I'm using postgresql without any charset issue, I'll try to switch back to MySQL in order to see what's going on after query error, yesterday logs are gone :cry: 

I'm not sure about Telegram's wrong authentication credentials... I just put my Telegram Bot Token into zammad's config page and it's sending/receiving messages without any issues.
I'm uploading postgresql-version log, this time non-utf8 characters are not causing any issue but web interface has crashed after some time and there's another "403 Forbidden" error
[zammadLog1.txt](https://github.com/zammad/zammad/files/1983187/zammadLog1.txt)

**Comment by rlue** [comment]
Also, are you able to reproduce the `Mysql2::Error: Incorrect string value` error in the Rails console?

That is, from `rails console --sandbox`, does the following produce the same error?

```ruby
>> Users.update(firstname: 'Ġüglíęlmõ')
```

I just installed MariaDB on my Debian machine, and was able to update the user record successfully without any errors. FWIW, my `database.yml` specifies `encoding: utf8`.

**Comment by rlue** [comment]
This issue is being closed due to inactivity, and may be reopened at any time at the original filer's request (or that of anyone who can help reproduce it).
