### ISSUE TITLE
No mime_type on nil message (no message body) / email will not be processed

### ISSUE THREAD

**Issue by dsukhin** [zammad/zammad#2087]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): source
* Operating system: n/a
* Database + version: mysql
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

* Emails without message bodies should still parse with empty string assumed as body.
* I think this broke after the recent `email_parser.rb` refactor; @rlue (c17a29c)

### Actual behavior:
```
#<NoMethodError: undefined method `mime_type' for nil:NilClass>
Can't process email, you will find it for bug reporting under /home/zammad/tmp/unprocessable_mail/xxx.eml, please create an issue at https://github.com/zammad/zammad/issues
undefined method `mime_type' for nil:NilClass (NoMethodError)
/home/zammad/app/models/channel/email_parser.rb:528:in `message_body_hash'
/home/zammad/app/models/channel/email_parser.rb:78:in `parse'
/home/zammad/app/models/channel/filter/bounce_follow_up_check.rb:17:in `block in run'
/home/zammad/app/models/channel/filter/bounce_follow_up_check.rb:12:in `each'
/home/zammad/app/models/channel/filter/bounce_follow_up_check.rb:12:in `run'
/home/zammad/app/models/channel/email_parser.rb:142:in `block in _process'
/home/zammad/app/models/channel/email_parser.rb:139:in `each'
/home/zammad/app/models/channel/email_parser.rb:139:in `_process'
/home/zammad/app/models/channel/email_parser.rb:107:in `process'
/home/zammad/app/models/channel/driver/imap.rb:298:in `block (2 levels) in fetch'
/home/zammad/app/models/channel/driver/imap.rb:276:in `each'
/home/zammad/app/models/channel/driver/imap.rb:276:in `block in fetch'
/home/zammad/app/models/channel/driver/imap.rb:250:in `each'
/home/zammad/app/models/channel/driver/imap.rb:250:in `fetch'
/home/zammad/app/models/channel.rb:61:in `fetch'
/home/.gem/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/home/.gem/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/home/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/home/zammad/app/models/scheduler.rb:274:in `eval'
/home/zammad/app/models/scheduler.rb:274:in `_start_job'
/home/zammad/app/models/scheduler.rb:237:in `block (2 levels) in start_job'
/home/zammad/app/models/scheduler.rb:236:in `loop'
/home/zammad/app/models/scheduler.rb:236:in `block in start_job'
/home/.gem/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

### Steps to reproduce the behavior:

* Try processing this email:
```
Return-Path: <person@zammad.com>
From: "Person" <person@zammad.com>
To: <email@zammad.com>
Subject: Unparseable email
Date: Mon, 16 Dec 2013 22:28:43 -0500
Message-ID: <DF35BF4D-4F92-4D42-9461-368A764727F2@zammad.com>
MIME-Version: 1.0
Content-Type: text/plain;
        charset="us-ascii"
Content-Transfer-Encoding: 7bit
X-Mailer: Microsoft Outlook 14.0
Thread-Index: MQLdZfMM3eblQw6fzOtQE1dV2us83Q==
X-OlkEid: ACC48547173A58DABEEF9544BE1A75F7C1C4CCBC


```
Fix is very simple but wanted to report it to the original committer since my PRs don't go through as fast.

**Comment by thorsteneckel** [comment]
@rlue - notice #2063 . We can convert the example into a test 👍

**Comment by martini** [comment]
@dsukhin thanks for you issue. It's fixed in develop and stable now.
