### ISSUE TITLE
Docker/Ubuntu Not starting postgresql-9.6 service

### ISSUE THREAD

**Issue by MarkusHackspacher** [zammad/zammad#213]
Hello,

I using Ubuntu 16.04 and Docker and have follow fault. Have docker pull zammad/zammad make now.

```
$ sudo docker run -ti -p 3001:80 zammad/zammad
Starting postgresql-9.6 service:                           [FAILED]
error: "Read-only file system" setting key "vm.max_map_count"
Starting elasticsearch:                                    [  OK  ]
Starting postfix:                                          [  OK  ]
Starting nginx: nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/conf.d/zammad.conf:27
                                                           [  OK  ]
[root@ed8956c19c49 zammad]# Puma starting in single mode...
* Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 30
* Environment: production
! Unable to load application: PG::ConnectionBad: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize': could not connect to server: No such file or directory (PG::ConnectionBad)
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
```

before I make the docker pull:

```
$ sudo docker run -ti -p 3001:80 zammad/zammad
[sudo] Passwort für zammad:
Starting postgresql service: /etc/init.d/postgresql: line 114: echo: write error: Permission denied
                                                           [FAILED]
error: "Read-only file system" setting key "vm.max_map_count"
Starting elasticsearch:                                    [  OK  ]
Starting postfix:                                          [  OK  ]
Starting nginx: nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/conf.d/zammad.conf:27
                                                           [  OK  ]
```

**Comment by thorsteneckel** [comment]
Hi @MarkusHackspacher - Thanks for reporting this. We'll take a look.

**Comment by thorsteneckel** [comment]
Hi @MarkusHackspacher - sorry but we can't reproduce this on a fresh Ubuntu 

![bildschirmfoto 2016-10-19 um 17 39 37](https://cloud.githubusercontent.com/assets/3873515/19526067/6dda7da2-9623-11e6-9f52-7fec71ada639.png)

**Comment by octomike** [comment]
Had the same issue.
You need more than 2GB main memory or modify /var/..some..where/pg-sql/9.6/postgresql.conf .

**Comment by senk** [comment]
Similar issues on OS X Docker:

```
➜  ~ docker run -ti -p 3001:80 zammad/zammad

Starting postgresql-9.6 service:                           [  OK  ]
error: "Read-only file system" setting key "vm.max_map_count"
Starting elasticsearch:                                    [  OK  ]
Starting postfix:                                          [  OK  ]
Starting nginx: nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/conf.d/zammad.conf:27
                                                           [  OK  ]
[root@65efcce9a874 zammad]# Puma starting in single mode...
* Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 30
* Environment: production
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize': FATAL:  the database system is starting up (PG::ConnectionBad)
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
	from /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_
...
...
```

**Comment by thorsteneckel** [comment]
Hi @senk - could you provide further information about your system / docker version?

**Comment by senk** [comment]
```
➜  ~ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
➜  ~ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: QG52:6FF2:WIGU:H56X:K4GW:KWKY:HMFE:NOR5:6LQL:W22Y:3TUP:2MZR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2016-10-19T16:15:01.280808667Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by thorsteneckel** [comment]
@senk - Thanks! Could you please provide additional information on your host system?

**Comment by senk** [comment]
OSX 10.12 latest docker version. strangely it works perfect on ubuntu 14.04 :-/

**Comment by thorsteneckel** [comment]
Thanks for the information. We'll try to reproduce it and let you know.

**Comment by thorsteneckel** [comment]
Hi @senk - maybe you could checkout our fresh out the oven synced docker repository at https://github.com/zammad/docker and change the https://github.com/zammad/docker/blob/master/scripts/run.sh with some sleeps / waits if it's the timing issue / race condition described in #215 .

**Comment by celevra** [comment]
here is a working single application docker image:
https://github.com/celevra/zammad-docker

**Comment by Julian0o** [comment]
Had the same Problem: https://github.com/zammad/zammad/issues/248

**Comment by thorsteneckel** [comment]
Hi @Julian0o - can you please provide further information on your operating system and docker version? We're currently not able to reproduce the behaviour.

**Comment by Julian0o** [comment]
I mentioned in https://github.com/zammad/zammad/issues/248 that i had not enough ram. Stopped the other docker containers and the system starts again. My System has only 4GB of ram. 

Using a Lime-Technologys Unraid NAS System with a docker feature. Don't know wich version.

**Comment by thorsteneckel** [comment]
Hi! Is there anything still open? Could increasing the RAM resolve the issue? I would like to handle docker issues in the repository https://github.com/zammad/zammad-docker/issues Would be great if you could open the issue there. We will handle them then.
