### ISSUE TITLE
Can't create tickets per mail - Database error

### ISSUE THREAD

**Issue by MrDigit** [zammad/zammad#2168]
Hello,

with fresh zammad 2.5 installation (with your "production docker" version) tried to setup "fetching mails". Did not work, zammad complains about violations regarding key constraints. Stacktrace below.

Any help appreciated.

MrDigit.

```
I, [2018-08-03T14:45:06.487625 #1]  INFO -- : fetching imap
I, [2018-08-03T14:45:06.672387 #1]  INFO -- :  - message 1/1
I, [2018-08-03T14:45:06.949057 #1]  INFO -- : Process email with msgid '<5ab916e3-5ba7-0efa-0c03-27653fb84310@anon>'
I, [2018-08-03T14:45:06.963263 #1]  INFO -- : set_attributes_by_x_headers header x-zammad-ticket-customer_id found. Assign customer_id=2
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/84d139bdec3c2c066a251797417c16c7.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  insert or update on table \"activity_streams\" violates foreign key constraint \"fk_rails_15ed0d0859\"\nDETAIL:  Key (activity_stream_type_id)=(3) is not present in table \"type_lookups\".\n: INSERT INTO \"activity_streams\" (\"activity_stream_type_id\", \"activity_stream_object_id\", \"permission_id\", \"group_id\", \"o_id\", \"created_by_id\", \"created_at\", \"updated_at\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING \"id\">"
E, [2018-08-03T14:45:06.986128 #1] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/84d139bdec3c2c066a251797417c16c7.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2018-08-03T14:45:06.986177 #1] ERROR -- : PG::ForeignKeyViolation: ERROR:  insert or update on table "activity_streams" violates foreign key constraint "fk_rails_15ed0d0859"
DETAIL:  Key (activity_stream_type_id)=(3) is not present in table "type_lookups".
: INSERT INTO "activity_streams" ("activity_stream_type_id", "activity_stream_object_id", "permission_id", "group_id", "o_id", "created_by_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id" (ActiveRecord::InvalidForeignKey)
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:616:in `async_exec'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:616:in `block (2 levels) in exec_no_cache'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:615:in `block in exec_no_cache'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:614:in `exec_no_cache'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `execute_and_clear'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:79:in `exec_query'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:102:in `exec_insert'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:113:in `exec_insert'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:133:in `insert'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `insert'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/relation.rb:61:in `insert'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/persistence.rb:585:in `_create_record'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/counter_cache.rb:178:in `_create_record'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/locking/optimistic.rb:76:in `_create_record'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/attribute_methods/dirty.rb:297:in `_create_record'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/callbacks.rb:340:in `block in _create_record'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/callbacks.rb:340:in `_create_record'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/timestamp.rb:95:in `_create_record'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/persistence.rb:559:in `create_or_update'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/callbacks.rb:336:in `block in create_or_update'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/callbacks.rb:336:in `create_or_update'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/persistence.rb:129:in `save'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/validations.rb:44:in `save'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/attribute_methods/dirty.rb:35:in `save'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:308:in `block (2 levels) in save'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:210:in `transaction'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:308:in `block in save'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:307:in `save'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/suppressor.rb:42:in `save'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/persistence.rb:34:in `create'
/opt/zammad/app/models/activity_stream.rb:77:in `add'
/opt/zammad/app/models/application_model/can_activity_stream_log.rb:45:in `activity_stream_log'
/opt/zammad/app/models/concerns/has_activity_stream_log.rb:21:in `activity_stream_create'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:511:in `block in invoke_after'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:511:in `each'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:511:in `invoke_after'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:132:in `run_callbacks'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/callbacks.rb:340:in `_create_record'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/timestamp.rb:95:in `_create_record'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/persistence.rb:559:in `create_or_update'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/callbacks.rb:336:in `block in create_or_update'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/callbacks.rb:336:in `create_or_update'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/persistence.rb:162:in `save!'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/validations.rb:50:in `save!'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:313:in `block in save!'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:210:in `transaction'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:313:in `save!'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/suppressor.rb:46:in `save!'
/opt/zammad/app/models/channel/email_parser.rb:641:in `block in _process'
/opt/zammad/app/models/transaction.rb:12:in `block in execute'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/transactions.rb:210:in `transaction'
/opt/zammad/app/models/transaction.rb:10:in `execute'
/opt/zammad/app/models/channel/email_parser.rb:565:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:508:in `process'
/opt/zammad/app/models/channel/driver/imap.rb:209:in `block in fetch'
/opt/zammad/app/models/channel/driver/imap.rb:187:in `each'
/opt/zammad/app/models/channel/driver/imap.rb:187:in `fetch'
/opt/zammad/app/models/channel.rb:61:in `fetch'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/usr/local/bundle/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:274:in `eval'
/opt/zammad/app/models/scheduler.rb:274:in `_start_job'
/opt/zammad/app/models/scheduler.rb:237:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:236:in `loop'
/opt/zammad/app/models/scheduler.rb:236:in `block in start_job'
/usr/local/bundle/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2018-08-03T14:45:07.067690 #1]  INFO -- : done
```

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question and you removed the mandatory information block. You can ask questions over at https://community.zammad.org/ - Closing now.

**Comment by MrDigit** [comment]
Foreign Key Constrain really looks like an issue. Thanks for fast repsonse, posting question in board.

**Comment by MrDigit** [comment]
https://community.zammad.org/t/cant-create-tickets-per-mail-database-error/1077
