### ISSUE TITLE
Unprocessable Mail if sender contains http.net@

### ISSUE THREAD

**Issue by membero** [zammad/zammad#2199]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): Debian Package
* Operating system: Debian 9
* Database + version: PostgreSQL 9.6
* Elasticsearch version: 5.6.10
* Browser + version: any

### Expected behavior:

* Email gets fetched and processed without error.

### Actual behavior:

* Error in processing, Email stored in /opt/zammad/tmp/unprocessable_mail/

### Steps to reproduce the behavior:

* Send an Email to Zammad with sendername (From or Return-Path) beginning with http.net@

The production.log says:

```
E, [2018-08-21T11:50:36.589229 #7023] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/aee1dc61294054b294acb6dc0eb57905.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2018-08-21T11:50:36.601469 #7023] ERROR -- : undefined method `match?' for nil:NilClass (NoMethodError)
/opt/zammad/lib/user_agent.rb:296:in `get_http'
/opt/zammad/lib/user_agent.rb:48:in `get'
/opt/zammad/app/models/avatar.rb:141:in `add'
/opt/zammad/app/models/avatar.rb:26:in `auto_detection'
/opt/zammad/app/models/user.rb:1138:in `avatar_for_email_check'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:511:in `block in invoke_after'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:511:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:511:in `invoke_after'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:132:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/callbacks.rb:340:in `_create_record'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/timestamp.rb:95:in `_create_record'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/persistence.rb:559:in `create_or_update'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/callbacks.rb:336:in `block in create_or_update'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:131:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/callbacks.rb:336:in `create_or_update'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/persistence.rb:162:in `save!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/validations.rb:50:in `save!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/attribute_methods/dirty.rb:43:in `save!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/transactions.rb:313:in `block in save!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/transactions.rb:210:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/transactions.rb:313:in `save!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/suppressor.rb:46:in `save!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/persistence.rb:51:in `create!'
/opt/zammad/app/models/channel/filter/identify_sender.rb:181:in `user_create'
/opt/zammad/app/models/channel/filter/identify_sender.rb:56:in `run'
/opt/zammad/app/models/channel/email_parser.rb:142:in `block in _process'
/opt/zammad/app/models/channel/email_parser.rb:139:in `each'
/opt/zammad/app/models/channel/email_parser.rb:139:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:107:in `process'
/opt/zammad/app/models/channel/driver/imap.rb:209:in `block in fetch'
/opt/zammad/app/models/channel/driver/imap.rb:187:in `each'
/opt/zammad/app/models/channel/driver/imap.rb:187:in `fetch'
/opt/zammad/app/models/channel.rb:61:in `fetch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:274:in `eval'
/opt/zammad/app/models/scheduler.rb:274:in `_start_job'
/opt/zammad/app/models/scheduler.rb:237:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:236:in `loop'
/opt/zammad/app/models/scheduler.rb:236:in `block in start_job'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2018-08-21T11:50:36.723637 #7023]  INFO -- : done
```

Here is the email that caused the error:

```
Return-Path: <http.net@http.net>
Delivered-To: xxx
Received: from xxx
        for <xxx>; Tue, 21 Aug 2018 09:49:58 +0000
To: xxx
From: "http.net" <http.net@http.net>
Subject: test
Message-ID: <xxx>
Date: Tue, 21 Aug 2018 11:49:57 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:xxx) Gecko/xxx
 Thunderbird/xxx
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit
X-Virus-Scanned: clamav-milter 0.100.1
X-Virus-Status: Clean

x
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rlue** [comment]
Thanks, @membero! This turned out to be an issue in the `Avatar` model, where it tries to tell the difference between an email and an HTTP URL by regex-matching against `/^http/`. A fix is in the works.
