### ISSUE TITLE
Unable to process email: `could not find a valid input encoding?

### ISSUE THREAD

**Issue by raphaelm** [zammad/zammad#2201]
### Infos:

* Used Zammad version: 2.6.0-1534819024.ea425d50.stretch
* Installation method (source, package, ..): Debian package
* Operating system: Debian stretch
* Database + version: MariaDB 10.2.17+maria~stretch

### Expected behavior:

* The email is parsed

### Actual behavior:

* The (spam) email causes a monitoring alert

### Log message
```
E, [2018-08-22T01:03:33.518721 #5093] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/2b9ca33d7f1c03c3ed53242886c6f944.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2018-08-22T01:03:33.518857 #5093] ERROR -- : could not find a valid input encoding (EncodingError)
/opt/zammad/lib/core_ext/string.rb:493:in `utf8_encode!'
/opt/zammad/lib/core_ext/string.rb:473:in `utf8_encode'
/opt/zammad/app/models/channel/email_parser.rb:73:in `parse'
/opt/zammad/app/models/channel/email_parser.rb:129:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:107:in `process'
/opt/zammad/app/models/channel/driver/imap.rb:209:in `block in fetch'
/opt/zammad/app/models/channel/driver/imap.rb:187:in `each'
/opt/zammad/app/models/channel/driver/imap.rb:187:in `fetch'
/opt/zammad/app/models/channel.rb:61:in `fetch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:274:in `eval'
/opt/zammad/app/models/scheduler.rb:274:in `_start_job'
/opt/zammad/app/models/scheduler.rb:237:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:236:in `loop'
/opt/zammad/app/models/scheduler.rb:236:in `block in start_job'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

### E-mail content

https://drop.rami.io/HvOP59

**Comment by raphaelm** [comment]
Sorry, apparent duplicate

**Comment by martini** [comment]
Thanks anyway!

**Comment by thorsteneckel** [comment]
For later: Duplicate of #2200
