### ISSUE TITLE
Empty user list with Elasticsearch enabled

### ISSUE THREAD

**Issue by Charburner** [zammad/zammad#2202]
Hey guys,

I just installed the latest Zammad release on CentOS 7 via rpm and as long as elasticsearch 5.6 is enabled, the user management page always shows "no entries".

`'es_url' = 'http://localhost:9200'`

When I disable elasticsearch by setting `'es_url' = ''`, users are listed as expected.

Other management pages like groups or roles are not broken though.

When I try to rebuild the searchindex as documentation mentions, this happens:

```
[root@zammad ~]# zammad run rake searchindex:rebuild
drop indexes...done
delete pipeline (pipeline)... done
create indexes...done
create pipeline (pipeline)... rake aborted!
Unable to process PUT request to elasticsearch URL 'http://127.0.0.1:9200/_ingest/pipeline/zammad585996485883'. Check the response and payload for detailed information:

Response:
#<UserAgent::Result:0x0000557a749b67b8 @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":\"parse_exception\",\"reason\":\"No processor type exists with name [attachment]\",\"header\":{\"processor_type\":\"foreach\"}}],\"type\":\"parse_exception\",\"reason\":\"No processor type exists with name [attachment]\",\"header\":{\"processor_type\":\"foreach\"}},\"status\":400}", @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">

Payload:
{:description=>"Extract zammad-attachment information from arrays", :processors=>[{:foreach=>{:field=>"article", :ignore_failure=>true, :processor=>{:foreach=>{:field=>"_ingest._value.attachment", :ignore_failure=>true, :processor=>{:attachment=>{:target_field=>"_ingest._value", :field=>"_ingest._value._content", :ignore_failure=>true}}}}}}]}

Payload size: 0M
/opt/zammad/lib/search_index_backend.rb:113:in `block (2 levels) in processors'
/opt/zammad/lib/search_index_backend.rb:73:in `each'
/opt/zammad/lib/search_index_backend.rb:73:in `block in processors'
/opt/zammad/lib/search_index_backend.rb:70:in `each'
/opt/zammad/lib/search_index_backend.rb:70:in `processors'
/opt/zammad/lib/tasks/search_index_es.rake:66:in `block (2 levels) in <top (required)>'
/opt/zammad/lib/tasks/search_index_es.rake:46:in `block (2 levels) in <top (required)>'
/opt/zammad/lib/tasks/search_index_es.rake:142:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
/opt/zammad/bin/bundle:3:in `load'
/opt/zammad/bin/bundle:3:in `<main>'
Tasks: TOP => searchindex:rebuild
(See full trace by running task with --trace)
```

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

However, it looks like the attachment plugin is missing: https://docs.zammad.org/en/latest/install-elasticsearch.html#generic-install-elasticsearch-5-6-ingest-attachment

**Comment by lpar** [comment]
So for the benefit of other people with user problems who end up here: I wasn't getting an empty user list, but I was getting users missing from the user list. Reinstalling the ingest-attachment Elasticsearch plugin fixed that, but not for some legacy users created while the problem was ongoing. I think what happened is that an ElasticSearch upgrade removed the plugin.

**Comment by Charburner** [comment]
That's true, I experienced the same thing, that ElasticSearch plugins were removed by updating.

As for the missing users, you might want to execute `zammad run rake searchindex:rebuild` if you still cannot see all users in the list.

**Comment by benjaoming** [comment]
I had this issue because I was running with too little memory and Elasticsearch was unable to start, evident from `/var/log/syslog`
