### ISSUE TITLE
Unable to modify tree_select attributes after upgrade to 2.6

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2205]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Be able to modify tree_select attributes via admin interface

### Actual behavior:

* After upgrade to 2.6 I get an error message

### Steps to reproduce the behavior:

* On Zammad 2.5 create a tree_select with Values A, B, C
* Upgrade to Zammad 2.6
* Open the tree_select field again and extend it with 2 sub categories for B
* save it
* try to execute changes you will get the following error:

````
I, [2018-08-23T07:40:45.878268 #12803]  INFO -- : Started POST "/api/v1/object_manager_attributes_execute_migrations" for 80.155.31.43 at 2018-08-23 07:40:45 +0200
I, [2018-08-23T07:40:45.885090 #12803]  INFO -- : Processing by ObjectManagerAttributesController#execute_migrations as JSON
E, [2018-08-23T07:40:45.891850 #12803] ERROR -- : no implicit conversion of Array into Hash (TypeError)
/home/zp_00002301/zammad/app/models/object_manager/attribute.rb:626:in `update'
/home/zp_00002301/zammad/app/models/object_manager/attribute.rb:626:in `block in migration_execute'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/home/zp_00002301/zammad/app/models/object_manager/attribute.rb:607:in `migration_execute'
/home/zp_00002301/zammad/app/controllers/object_manager_attributes_controller.rb:93:in `execute_migrations'
/usr/local/rvm/gems/ruby-2.4.4/gems/actionpack-5.1.5/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/usr/local/rvm/gems/ruby-2.4.4/gems/actionpack-5.1.5/lib/abstract_controller/base.rb:186:in `process_action'
/usr/local/rvm/gems/ruby-2.4.4/gems/actionpack-5.1.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/rvm/gems/ruby-2.4.4/gems/actionpack-5.1.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[...]
````

The reason is in `app/models/object_manager/attribute.rb:626`:

```
          historical_options = attribute.data_option[:historical_options] || {}
```

There is no historical_options in Zammad 2.5 fields and the new value is not has, tree_select is a array.

**Comment by SummerStorm** [comment]
Fixed by 9be7269646a8d09d8ec98e614f2f3384e09f33e6
