### ISSUE TITLE
ERROR: #<Encoding::ConverterNotFoundError: code converter not found (Windows-1258 to UTF-8)>

### ISSUE THREAD

**Issue by chesty** [zammad/zammad#2211]
### Infos:

* Used Zammad version: 2.6 (i think there was an update since this error)
* Installation method (source, package, ..): zammad-dcoker-compose

### Expected behavior:

* process email without error

### Actual behavior:

* I get the error
```
I, [2018-08-22T15:40:15.700325 #153]  INFO -- : Setting.set('product_logo', "3780274cc33c365e628f0e9d4b38fa0c.png")
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/e2906701d4d106e93a1e668672a4a629.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<Encoding::ConverterNotFoundError: code converter not found (Windows-1258 to UTF-8)>"
/opt/zammad/app/models/channel/email_parser.rb:123:in `rescue in process': #<Encoding::ConverterNotFoundError: code converter not found (Windows-1258 to UTF-8)> (RuntimeError)
/opt/zammad/lib/core_ext/string.rb:481:in `encode!'
/opt/zammad/lib/core_ext/string.rb:481:in `block in utf8_encode!'
/opt/zammad/lib/core_ext/string.rb:479:in `each'
/opt/zammad/lib/core_ext/string.rb:479:in `utf8_encode!'
/opt/zammad/lib/core_ext/string.rb:473:in `utf8_encode'
/opt/zammad/app/models/channel/email_parser.rb:535:in `body_text'
/opt/zammad/app/models/channel/email_parser.rb:516:in `message_body_hash'
/opt/zammad/app/models/channel/email_parser.rb:78:in `parse'
/opt/zammad/app/models/channel/email_parser.rb:129:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:107:in `process'
/opt/zammad/app/models/channel/email_parser.rb:467:in `block in process_unprocessable_mails'
/opt/zammad/app/models/channel/email_parser.rb:466:in `glob'
/opt/zammad/app/models/channel/email_parser.rb:466:in `process_unprocessable_mails'
/usr/local/bundle/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `perform'
/usr/local/bundle/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `eval'
/usr/local/bundle/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `perform'
/usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
/usr/local/bundle/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
/usr/local/bundle/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
        from /opt/zammad/app/models/channel/email_parser.rb:105:in `process'
        from /opt/zammad/app/models/channel/email_parser.rb:467:in `block in process_unprocessable_mails'
        from /opt/zammad/app/models/channel/email_parser.rb:466:in `glob'
        from /opt/zammad/app/models/channel/email_parser.rb:466:in `process_unprocessable_mails'
        from /usr/local/bundle/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `perform'
        from /usr/local/bundle/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `eval'
        from /usr/local/bundle/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `perform'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/local/bundle/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
        from /usr/local/bundle/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
        from /usr/local/bundle/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```
### Steps to reproduce the behavior:

* I'll email the eml file to support

**Comment by martini** [comment]
Hi @chesty 

thanks for you issue. I tried to reproduce it, but it worked fine on develop & stable.

We fixed a few email processing issues last week. So can I ask for your exact Zammad version?

Thanks!

 -Martin

**Comment by chesty** [comment]
I don't know how to get the exact version, zammad just says 2.6.x.
anyway, I updated and it is indeed fixed. Thanks and sorry for the noise.

**Comment by martini** [comment]
> I don't know how to get the exact version, zammad just says 2.6.x.

In your case the zammad package version or the zammad-dcoker-compose version. Anyway. Thanks for fast feedback!
