### ISSUE TITLE
zammad-web-1.service doesn't exit cleanly on upgrade

### ISSUE THREAD

**Issue by mweinelt** [zammad/zammad#2259]
### Infos:

* Used Zammad version: 2.6.0-1538108847.bed3e54d.jessie
* Installation method (source, package, ..): Package
* Operating system: Debian Jessie
* Database + version: 9.4.19-0+deb8u1
* Elasticsearch version: 5.6.12

### Expected behavior:

* When upgrading Zammad all services should terminate cleanly to not trigger monitoring alerts

### Actual behavior:

* On upgrades the `zammad-web-1.service` crashes and the systemd unit goes into a failed state until the upgrade finishes

```
systemd[1]: Stopping zammad-web-1.service...
zammad-web-1.service[10561]: - Gracefully stopping, waiting for requests to finish
zammad-web-1.service[10561]: === puma shutdown: 2018-09-29 21:42:24 +0200 ===
zammad-web-1.service[10561]: - Goodbye!
zammad-web-1.service[10561]: Exiting
zammad-web-1.service[10561]: bundler: failed to load command: script/rails (script/rails)
zammad-web-1.service[10561]: SignalException: SIGTERM
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/launcher.rb:397:in `block in setup_signals'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/single.rb:106:in `join'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/single.rb:106:in `run'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/launcher.rb:183:in `run'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/rack/handler/puma.rb:69:in `run'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/server.rb:297:in `start'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:44:in `start'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:135:in `block in perform'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `tap'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `perform'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
zammad-web-1.service[10561]: /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
zammad-web-1.service[10561]: script/rails:6:in `require'
zammad-web-1.service[10561]: script/rails:6:in `<top (required)>'
systemd[1]: zammad-web-1.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Stopped zammad-web-1.service.
systemd[1]: Unit zammad-web-1.service entered failed state.
```

### Steps to reproduce the behavior:

* `apt upgrade zammad`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @mweinelt - This looks like a general issue with packager.io and a Rails application. As you can see in the backtrace there is no Zammad code involved, just Rails and its dependencies running with Puma. We have no influence on that (as far as I know). Maybe @monotek has some more insights? Closing now as third party issue 🙍‍♂️
