### ISSUE TITLE
Missing table name quoting causes MySQL 8 incompatibility

### ISSUE THREAD

**Issue by lieszkol** [zammad/zammad#2418]
### Infos:

* Used Zammad version: latest
* Installation method (source, package, ..): ubuntu DEB
* Operating system: Ubuntu 18.04
* Database + version: Mysql 8.0.13
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

* After installation I am able to log in as an admin user

### Actual behavior:

* After installation I am not able to log in as an admin user. Ajax request to signin returns:
```
{"error":"Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups FROM `signatures` LEFT OUTER JOIN `groups` ON `groups`.`signature_id` = `' at line 1: SELECT groups.id AS groups FROM `signatures` LEFT OUTER JOIN `groups` ON `groups`.`signature_id` = `signatures`.`id` WHERE `signatures`.`id` = 1"}
```
Executing the quoted SQL returns syntax error on MySQL 8+ because "GROUPS" has become a reserved word: https://dev.mysql.com/doc/refman/8.0/en/keywords.html

Properly quoting the sql fixes the problem: 

```sql
SELECT `groups`.id AS `groups`
FROM `signatures` 
	LEFT OUTER JOIN `groups` ON `groups`.`signature_id` = `signatures`.`id` 
WHERE `signatures`.`id` = 1
```
### Steps to reproduce the behavior:

* Install Zammad on any OS with MYSql 8+ as the database layer, start it up, and register the admin user >> user is created in the database but the application shows the error. Try to log in with the newly created user >> application shows the error.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by hanneshal** [comment]
Hi @lieszkol can you post the complete traceback for this please. you can find it in the Zammad production log. 

Thanks in advance.
Hannes

**Comment by lieszkol** [comment]
I'm truly sorry but I've since installed postgresql, and purged and reinstalled zammad, and that seems to have wiped the previous log. If I have time I'll try to reinstall Zammad with MySQL 8 again. 

In any case it should not be difficult to reproduce this error. If you intend to support MySQL 8 then you'll have to set up an environment anyway and you'll run into the bug right after installation. 

Another reserved word to watch out for (from my own experience) is "system".

**Comment by hanneshal** [comment]
Never mind, we tried it ourselfs. 

```SQL
SELECT groups.id AS groups FROM `signatures` LEFT OUTER JOIN `groups` ON `groups`.`signature_id` = `signatures`.`id` WHERE `signatures`.`id` = 1
```
```
E, [2018-12-27T16:31:34.419658 #13247-46941739555580] ERROR -- : Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups FROM `signatures` LEFT OUTER JOIN `groups` ON `groups`.`signature_id` = `' at line 1: SELECT groups.id AS groups FROM `signatures` LEFT OUTER JOIN `groups` ON `groups`.`signature_id` = `signatures`.`id` WHERE `signatures`.`id` = 1 (ActiveRecord::StatementInvalid)
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:212:in `execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/mysql/database_statements.rb:26:in `execute'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:223:in `execute_and_free'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `exec_query'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:371:in `select'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:42:in `select_all'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `block in select_all'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/query_cache.rb:118:in `block in cache_sql'
/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/query_cache.rb:104:in `cache_sql'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/mysql/database_statements.rb:10:in `select_all'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/relation/calculations.rb:176:in `pluck'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/relation/calculations.rb:170:in `pluck'
/opt/zammad/app/models/application_model/can_associations.rb:144:in `attributes_with_association_ids'
/opt/zammad/app/models/application_model/can_assets.rb:31:in `assets'
/opt/zammad/app/controllers/sessions/collection_ticket.rb:36:in `block in session'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/relation/delegation.rb:39:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/relation/delegation.rb:39:in `each'
/opt/zammad/app/controllers/sessions/collection_ticket.rb:35:in `session'
/opt/zammad/lib/session_helper.rb:12:in `block in default_collections'
/opt/zammad/lib/session_helper.rb:10:in `each'
/opt/zammad/lib/session_helper.rb:10:in `default_collections'
/opt/zammad/app/controllers/sessions_controller.rb:43:in `create'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/abstract_controller/base.rb:186:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/notifications.rb:166:in `block in instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/notifications.rb:166:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/abstract_controller/base.rb:124:in `process'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.6.1/lib/action_view/rendering.rb:30:in `process'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal.rb:189:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal.rb:253:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/journey/router.rb:33:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/journey/router.rb:33:in `serve'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:844:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/builder.rb:63:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/callbacks.rb:97:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.1/lib/rails/rack/logger.rb:36:in `call_app'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.1/lib/rails/rack/logger.rb:24:in `block in call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.1/lib/rails/rack/logger.rb:24:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/static.rb:125:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.1/lib/rails/engine.rb:522:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/configuration.rb:225:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:624:in `handle_request'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:438:in `process_client'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:302:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2018-12-27T16:31:34.420413 #13247-46941739555580]  INFO -- : Completed 422 Unprocessable Entity in 528ms (Views: 0.2ms | ActiveRecord: 36.4ms)
I, [2018-12-27T16:31:38.088829 #13256-70276536638320]  INFO -- : Started job thread for 'Delete old stats store entries.' (StatsStore.cleanup)...
I, [2018-12-27T16:31:38.142132 #13256-70276536638320]  INFO -- : execute StatsStore.cleanup (try_count 0)...
I, [2018-12-27T16:31:38.152837 #13256-70276536638320]  INFO -- :  ...stopped thread for 'StatsStore.cleanup'
I, [2018-12-27T16:31:48.089131 #13256-46991739163500]  INFO -- : Started job thread for 'Cleanup HttpLog' (HttpLog.cleanup)...
I, [2018-12-27T16:31:48.129171 #13256-46991739163500]  INFO -- : execute HttpLog.cleanup (try_count 0)...
I, [2018-12-27T16:31:48.143918 #13256-46991739163500]  INFO -- :  ...stopped thread for 'HttpLog.cleanup'
I, [2018-12-27T16:31:48.256261 #13256-70276609763120]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2018-12-27T16:31:58.089503 #13256-46991736523040]  INFO -- : Started job thread for 'Cleanup Cti::Log' (Cti::Log.cleanup)...
I, [2018-12-27T16:31:58.141377 #13256-46991736523040]  INFO -- : execute Cti::Log.cleanup (try_count 0)...
I, [2018-12-27T16:31:58.153408 #13256-46991736523040]  INFO -- :  ...stopped thread for 'Cti::Log.cleanup'
 

```

**Comment by thorsteneckel** [comment]
This is fixed with the two commits above in `develop` and `stable`. Packages will be ready in about 30 minutes from now. Feedback is highly welcome. Thanks for the great team effort 💪 Closing now.
