### ISSUE TITLE
Mails send by older mailers with x-uuencode Content-Transfer-Encoding of attachments are not processable

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2464]
### Infos:

* Used Zammad version: 2.8
* Installation method (source, package, ..): nay
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* being able to import failed messages

### Actual behavior:

* failed messages (some) can't be imported

### Steps to reproduce the behavior:

* try to manually import a unprocessible mail:

```
[xx@xx]$ rails r 'Channel::EmailParser.process_unprocessable_mails'
"ERROR: Can't process email, you will find it for bug reporting under /xxx/xxxx/zammad/tmp/unprocessable_mail/f43b0086aadcc3ff1385e8f50e43a806.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<NoMethodError: undefined method `new' for Mail::Encodings::UnixToUnix:Module>"
/xxx/xxxx/zammad/app/models/channel/email_parser.rb:125:in `rescue in process': #<NoMethodError: undefined method `new' for Mail::Encodings::UnixToUnix:Module> (RuntimeError)
/usr/local/rvm/gems/ruby-2.4.4/gems/mail-2.6.6/lib/mail/encodings/transfer_encoding.rb:13:in `can_transport?'
/usr/local/rvm/gems/ruby-2.4.4/gems/mail-2.6.6/lib/mail/encodings/transfer_encoding.rb:36:in `get_best_compatible'
/usr/local/rvm/gems/ruby-2.4.4/gems/mail-2.6.6/lib/mail/body.rb:144:in `get_best_encoding'
/usr/local/rvm/gems/ruby-2.4.4/gems/mail-2.6.6/lib/mail/body.rb:157:in `encoded'
/xxx/xxxx/zammad/app/models/channel/email_parser.rb:589:in `get_attachments'
/xxx/xxxx/zammad/app/models/channel/email_parser.rb:575:in `block in collect_attachments'
/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/delegate.rb:341:in `each'
/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/delegate.rb:341:in `block in delegating_block'
/xxx/xxxx/zammad/app/models/channel/email_parser.rb:573:in `collect_attachments'
/xxx/xxxx/zammad/app/models/channel/email_parser.rb:529:in `message_body_hash'
/xxx/xxxx/zammad/app/models/channel/email_parser.rb:76:in `parse'
/xxx/xxxx/zammad/app/models/channel/email_parser.rb:131:in `_process'
/xxx/xxxx/zammad/app/models/channel/email_parser.rb:108:in `process'
/xxx/xxxx/zammad/app/models/channel/email_parser.rb:475:in `block in process_unprocessable_mails'
/xxx/xxxx/zammad/app/models/channel/email_parser.rb:474:in `glob'
/xxx/xxxx/zammad/app/models/channel/email_parser.rb:474:in `process_unprocessable_mails'
/usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `perform'
/usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `eval'
/usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `perform'
/usr/local/rvm/gems/ruby-2.4.4/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.4.4/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.4.4/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
/usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
/usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<main>'
        from /xxx/xxxx/zammad/app/models/channel/email_parser.rb:106:in `process'
        from /xxx/xxxx/zammad/app/models/channel/email_parser.rb:475:in `block in process_unprocessable_mails'
        from /xxx/xxxx/zammad/app/models/channel/email_parser.rb:474:in `glob'
        from /xxx/xxxx/zammad/app/models/channel/email_parser.rb:474:in `process_unprocessable_mails'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `perform'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `eval'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:37:in `perform'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'

```

Yes I'm sure this is a bug and no feature request or a general question.

This is handled in the internal issue #135 because of confidential user data.

**Comment by SummerStorm** [comment]
Fixed by ff0330d. Closing.
