### ISSUE TITLE
Elasticsearch throws error 500 when filtering for owner or custom dropdown-fields inside of report profiles

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2517]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1040382, #1040286 (#1043261), #1041524, #1047720, #1079579

### Expected behavior:

* When filtering for not set owners via reporting profiles, the reporting will return all tickets having no owner.

### Actual behavior:

* When filtering for not set owners via reporting profile, the reporting will show zero results and throw error 500. If configuring the reporting profile in the backend, Zammad will show you a correct preview without any error.

### Steps to reproduce the behavior:

* go to report profiles and create a new report profile
* set one of the following two conditions and save the profile:
  * owner is not set
  * owner is not not set
  * owner is current user
  * owner is not current user
* go to reporting and select your reporting profile that you just created
* error 500 appears

### How to fix

Please note the insights from [this comment](https://github.com/zammad/zammad/issues/507#issuecomment-484422456) on how a fix could look like.

### Screens

*Example for configuration that throws erorr*
![image](https://user-images.githubusercontent.com/6549061/54607077-c20bc800-4a4d-11e9-9f61-706d177c4fac.png)

### Logfile-Output

```
E, [2019-03-18T14:55:15.960768 #77856-47058397202100] ERROR -- : Unable to process GET request to elasticsearch URL 'http://localhost:9
200/zammad_production/Ticket/_search'. Check the response and payload for detailed information:
 
Response:
#<UserAgent::Result:0x00005599462ab518 @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\
":\"failed to create query: {\\n \\\"bool\\\" : {\\n \\\"must\\\" : [\\n {\\n \\\"term\\\" : {\\n \\\"state_id
\\\" : {\\n \\\"value\\\" : \\\"4\\\",\\n \\\"boost\\\" : 1.0\\n }\\n }\\n },\\n {\\n
\\\"range\\\" : {\\n \\\"created_at\\\" : {\\n \\\"from\\\" : \\\"2019-03-01\\\",\\n \\\"to\\\" :
\\\"2019-03-31\\\",\\n \\\"include_lower\\\" : true,\\n \\\"include_upper\\\" : true,\\n \\\"boost\\\"
: 1.0\\n }\\n }\\n }\\n ],\\n \\\"must_not\\\" : [\\n {\\n \\\"term\\\" : {\\n \\\"own
er_id\\\" : {\\n \\\"value\\\" : \\\"\\\",\\n \\\"boost\\\" : 1.0\\n }\\n }\\n },\\n {\
\n \\\"term\\\" : {\\n \\\"state\\\" : {\\n \\\"value\\\" : \\\"merged\\\",\\n \\\"boost\\\" : 1.
0\\n }\\n }\\n }\\n ],\\n \\\"disable_coord\\\" : false,\\n \\\"adjust_pure_negative\\\" : true,\\n \\
\"boost\\\" : 1.0\\n }\\n}\",\"index_uuid\":\"CWBVOpq0R2qkFn1ukXfA3Q\",\"index\":\"zammad_production\"}],\"type\":\"search_phase_execu
tion_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"zamm
ad_production\",\"node\":\"QqHtP0jpS8Cn0gVX2_tuZw\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"failed to create query:
{\\n \\\"bool\\\" : {\\n \\\"must\\\" : [\\n {\\n \\\"term\\\" : {\\n \\\"state_id\\\" : {\\n \\\"
value\\\" : \\\"4\\\",\\n \\\"boost\\\" : 1.0\\n }\\n }\\n },\\n {\\n \\\"range\\\" : {\\n
\\\"created_at\\\" : {\\n \\\"from\\\" : \\\"2019-03-01\\\",\\n \\\"to\\\" : \\\"2019-03-31\\\",\\n
\\\"include_lower\\\" : true,\\n \\\"include_upper\\\" : true,\\n \\\"boost\\\" : 1.0\\n }\\n
}\\n }\\n ],\\n \\\"must_not\\\" : [\\n {\\n \\\"term\\\" : {\\n \\\"owner_id\\\" : {\\n
\\\"value\\\" : \\\"\\\",\\n \\\"boost\\\" : 1.0\\n }\\n }\\n },\\n {\\n \\\"term\\\" : {\
\n \\\"state\\\" : {\\n \\\"value\\\" : \\\"merged\\\",\\n \\\"boost\\\" : 1.0\\n }\\n }
\\n }\\n ],\\n \\\"disable_coord\\\" : false,\\n \\\"adjust_pure_negative\\\" : true,\\n \\\"boost\\\" : 1.0\\n }\\n}
\",\"index_uuid\":\"CWBVOpq0R2qkFn1ukXfA3Q\",\"index\":\"zammad_production\",\"caused_by\":{\"type\":\"number_format_exception\",\"reas
on\":\"empty String\"}}}]},\"status\":400}", @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400
Bad Request readbody=true>!">
 
Payload:
{:query=>{:bool=>{:must=>[{:term=>{"state_id"=>"4"}}, {:range=>{"created_at"=>{:from=>"2019-03-01", :to=>"2019-03-31"}}}], :must_not=>[
{:term=>{"owner_id"=>""}}, {:term=>{"state"=>"merged"}}]}}, :size=>0, :aggs=>{:time_buckets=>{:date_histogram=>{:field=>"created_at", :
interval=>"day"}}}}
Payload size: 0M
E, [2019-03-18T14:55:15.961130 #77856-47058397202100] ERROR -- : Unable to process GET request to elasticsearch URL 'http://localhost:9
200/zammad_production/Ticket/_search'. Check the response and payload for detailed information:
 
Response:
#<UserAgent::Result:0x00005599462ab518 @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\
":\"failed to create query: {\\n \\\"bool\\\" : {\\n \\\"must\\\" : [\\n {\\n \\\"term\\\" : {\\n \\\"state_id
\\\" : {\\n \\\"value\\\" : \\\"4\\\",\\n \\\"boost\\\" : 1.0\\n }\\n }\\n },\\n {\\n
\\\"range\\\" : {\\n \\\"created_at\\\" : {\\n \\\"from\\\" : \\\"2019-03-01\\\",\\n \\\"to\\\" :
\\\"2019-03-31\\\",\\n \\\"include_lower\\\" : true,\\n \\\"include_upper\\\" : true,\\n \\\"boost\\\"
: 1.0\\n }\\n }\\n }\\n ],\\n \\\"must_not\\\" : [\\n {\\n \\\"term\\\" : {\\n \\\"own
er_id\\\" : {\\n \\\"value\\\" : \\\"\\\",\\n \\\"boost\\\" : 1.0\\n }\\n }\\n },\\n {\
\n \\\"term\\\" : {\\n \\\"state\\\" : {\\n \\\"value\\\" : \\\"merged\\\",\\n \\\"boost\\\" : 1.
0\\n }\\n }\\n }\\n ],\\n \\\"disable_coord\\\" : false,\\n \\\"adjust_pure_negative\\\" : true,\\n \\
\"boost\\\" : 1.0\\n }\\n}\",\"index_uuid\":\"CWBVOpq0R2qkFn1ukXfA3Q\",\"index\":\"zammad_production\"}],\"type\":\"search_phase_execu
tion_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"zamm
ad_production\",\"node\":\"QqHtP0jpS8Cn0gVX2_tuZw\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"failed to create query:
{\\n \\\"bool\\\" : {\\n \\\"must\\\" : [\\n {\\n \\\"term\\\" : {\\n \\\"state_id\\\" : {\\n \\\"
value\\\" : \\\"4\\\",\\n \\\"boost\\\" : 1.0\\n }\\n }\\n },\\n {\\n \\\"range\\\" : {\\n
\\\"created_at\\\" : {\\n \\\"from\\\" : \\\"2019-03-01\\\",\\n \\\"to\\\" : \\\"2019-03-31\\\",\\n
\\\"include_lower\\\" : true,\\n \\\"include_upper\\\" : true,\\n \\\"boost\\\" : 1.0\\n }\\n
}\\n }\\n ],\\n \\\"must_not\\\" : [\\n {\\n \\\"term\\\" : {\\n \\\"owner_id\\\" : {\\n
\\\"value\\\" : \\\"\\\",\\n \\\"boost\\\" : 1.0\\n }\\n }\\n },\\n {\\n \\\"term\\\" : {\
\n \\\"state\\\" : {\\n \\\"value\\\" : \\\"merged\\\",\\n \\\"boost\\\" : 1.0\\n }\\n }
\\n }\\n ],\\n \\\"disable_coord\\\" : false,\\n \\\"adjust_pure_negative\\\" : true,\\n \\\"boost\\\" : 1.0\\n }\\n}
\",\"index_uuid\":\"CWBVOpq0R2qkFn1ukXfA3Q\",\"index\":\"zammad_production\",\"caused_by\":{\"type\":\"number_format_exception\",\"reas
on\":\"empty String\"}}}]},\"status\":400}", @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400
Bad Request readbody=true>!">
 
Payload:
{:query=>{:bool=>{:must=>[{:term=>{"state_id"=>"4"}}, {:range=>{"created_at"=>{:from=>"2019-03-01", :to=>"2019-03-31"}}}], :must_not=>[
{:term=>{"owner_id"=>""}}, {:term=>{"state"=>"merged"}}]}}, :size=>0, :aggs=>{:time_buckets=>{:date_histogram=>{:field=>"created_at", :
interval=>"day"}}}}
 
Payload size: 0M (RuntimeError)
/opt/zammad/lib/search_index_backend.rb:508:in `selectors'
/opt/zammad/lib/report/ticket_generic_time.rb:45:in `aggs'
/opt/zammad/app/controllers/reports_controller.rb:34:in `block in generate'
/opt/zammad/app/controllers/reports_controller.rb:25:in `each'
/opt/zammad/app/controllers/reports_controller.rb:25:in `generate'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/abstract_controller/base.rb:186:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_act
ion'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/notifications.rb:166:in `block in instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/notifications.rb:166:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/abstract_controller/base.rb:124:in `process'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.6.1/lib/action_view/rendering.rb:30:in `process'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal.rb:189:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_controller/metal.rb:253:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/journey/router.rb:33:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/journey/router.rb:33:in `serve'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:844:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/callbacks.rb:97:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.1/lib/rails/rack/logger.rb:36:in `call_app'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.1/lib/rails/rack/logger.rb:24:in `block in call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.1/lib/rails/rack/logger.rb:24:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.6.1/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call
'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/static.rb:125:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.6.1/lib/rails/engine.rb:522:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/configuration.rb:225:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:624:in `handle_request'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:438:in `process_client'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/server.rb:302:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by TomFuch** [comment]
I have the exact same problem with filtering for Organisations.

![Bildschirmfoto 2019-04-01 um 16 25 02](https://user-images.githubusercontent.com/28782681/55335144-debaed80-549a-11e9-8bdb-dbe9f965c954.png)

**Comment by MrGeneration** [comment]
Please also see the screencast from issue 2679 which shows the behavior:
https://github.com/zammad/zammad/files/3432845/Report.zip

**Comment by rolfschmidt** [comment]
Hey guys,

i was able to reproduce #2517 and also the case of @TomFuch . But there is duplicate #2679 where the @gestoramd and @MadNBG provided a report about object manager attributes which are not restrictable in the report profiles. I tried to reproduce it but i was not able to reproduce the bug with a simple text field and not able to reproduce it with a select field. Also in the video of @gestoramd you can see a result with no error at 00:00:41. 

@gestoramd and @MadNBG:
Can you provide me a screenshot of a object attribute field configuration which does not work in reporting?

### My test

![grafik](https://user-images.githubusercontent.com/5445062/95351055-150fcf00-08c1-11eb-947b-40f555e43c46.png)

![grafik](https://user-images.githubusercontent.com/5445062/95351134-29ec6280-08c1-11eb-8a7a-a4a859c411fd.png)

![grafik](https://user-images.githubusercontent.com/5445062/95351164-340e6100-08c1-11eb-9eb7-ddeb30e51acd.png)

![grafik](https://user-images.githubusercontent.com/5445062/95351194-3e305f80-08c1-11eb-88e0-a8bc0e92d9c7.png)
