### ISSUE TITLE
Gitlab Login not working after upgrade to Zammad 3.x

### ISSUE THREAD

**Issue by DoktorAerzt** [zammad/zammad#2595]
### Infos:

* Used Zammad version: 3.x
* Installation method (source, package, ..): deb-package
* Operating system: Ubuntu 18.04.2 LTS
* Database + version: Installed with Package
* Elasticsearch version: 5.6.16
* Browser + version: All

### Expected behavior:

*Login in with Gitlab to an account

### Actual behavior:

*When i press "GitLab" on the login package i get an 500 Erro page. 

After i updated zammad from 2.9.x to 3.x the gitlab login no longer works. 

### Steps to reproduce the behavior:

* i don´t know

Yes I'm sure this is a bug and no feature request or a general question.

[production.log](https://github.com/zammad/zammad/files/3265079/production.log)

**Comment by DoktorAerzt** [comment]
[production.log](https://github.com/zammad/zammad/files/3265075/production.log)

**Comment by MrGeneration** [comment]
Super short:
This is a regression caused by:
https://github.com/zammad/zammad/commit/3acfa4a277c29a0eb3b7bff83fde1a60718a9746

### affected code

Affected Line *vendor/bundle/ruby/2.4.0/gems/omniauth-gitlab-2.0.0/lib/omniauth/strategies/gitlab.rb*
```ruby
uid { raw_info['id'].to_s }
```
When fiddling around, I learned that raw_info seems to be not set (`nil`)


*vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb*
```ruby
      def compile_stack(ancestors, method, context)
        stack = ancestors.inject([]) do |a, ancestor|
          a << context.instance_eval(&ancestor.send(method)) if ancestor.respond_to?(method) && ancestor.send(method)
          a
        end
        stack.reverse!
      end
```

### Logs
This happens during authentication on Gitlab-Site:
```
==> /var/log/gitlab/gitlab-rails/sidekiq_exporter.log <==
[2019-06-07 12:08:48] 127.0.0.1 - - [07/Jun/2019:12:08:48 CEST] "GET /metrics HTTP/1.1" 200 1727 "-" "Prometheus/2.8.1"

==> /var/log/gitlab/gitlab-rails/production_json.log <==
{"method":"GET","path":"/-/metrics","format":"html","controller":"MetricsController","action":"index","status":200,"duration":4.01,"view":0.32,"db":0.0,"time":"2019-06-07T10:08:59.669Z","params":[],"remote_ip":null,"user_id":null,"username":null,"ua":null,"queue_duration":null,"correlation_id":"eace0567-fd76-4cf8-a0b2-becf8edb5ecb"}

==> /var/log/gitlab/gitlab-rails/production.log <==
Started GET "/-/metrics" for 127.0.0.1 at 2019-06-07 12:08:59 +0200
Processing by MetricsController#index as HTML
Completed 200 OK in 3ms (Views: 0.3ms | ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)

==> /var/log/gitlab/gitlab-rails/production_json.log <==
{"method":"GET","path":"/oauth/authorize","format":"html","controller":"Oauth::AuthorizationsController","action":"new","status":302,"duration":10.31,"view":0.0,"db":1.85,"location":"http://172.16.16.3/auth/gitlab/callback","time":"2019-06-07T10:09:00.368Z","params":[{"key":"client_id","value":"4a8ce2ea1d3222446e44900357b4a68145581ec055a00d65ff09f03f589c68bb"},{"key":"redirect_uri","value":"http://172.16.16.3/auth/gitlab/callback"},{"key":"response_type","value":"code"},{"key":"state","value":"dd3e270cabc321a9ca33ab9029b1ab7af040550c779bbe3e"}],"remote_ip":null,"user_id":null,"username":null,"ua":null,"queue_duration":null,"correlation_id":"MouhutIO8K5"}
{"method":"POST","path":"/oauth/token","format":"*/*","controller":"Doorkeeper::TokensController","action":"create","status":200,"duration":20.61,"view":0.0,"time":"2019-06-07T10:09:00.474Z","params":[{"key":"client_id","value":"4a8ce2ea1d3222446e44900357b4a68145581ec055a00d65ff09f03f589c68bb"},{"key":"client_secret","value":"[FILTERED]"},{"key":"code","value":"[FILTERED]"},{"key":"grant_type","value":"authorization_code"},{"key":"redirect_uri","value":"http://172.16.16.3/auth/gitlab/callback"}],"remote_ip":null,"user_id":null,"username":null,"ua":null,"queue_duration":null,"correlation_id":"4mtGvUbBNJ4"}
{"method":"GET","path":"/user","format":"*/*","controller":"ApplicationController","action":"route_not_found","status":0,"duration":2.78,"view":0.0,"db":0.0,"time":"2019-06-07T10:09:00.522Z","params":[{"key":"unmatched_route","value":"user"}],"remote_ip":"172.16.16.3","user_id":null,"username":null,"ua":"Faraday v0.15.4","queue_duration":3.12,"correlation_id":"brk1Cx65Dq9"}
{"method":"GET","path":"/users/sign_in","format":"*/*","controller":"SessionsController","action":"new","status":200,"duration":117.18,"view":103.18,"db":1.1,"time":"2019-06-07T10:09:00.547Z","params":[],"remote_ip":"172.16.16.3","user_id":null,"username":null,"ua":"Faraday v0.15.4","queue_duration":2.67,"correlation_id":"ffB966eCPo8"}

==> /var/log/gitlab/gitlab-rails/production.log <==
Started GET "/oauth/authorize?client_id=4a8ce2ea1d3222446e44900357b4a68145581ec055a00d65ff09f03f589c68bb&redirect_uri=http%3A%2F%2F172.16.16.3%2Fauth%2Fgitlab%2Fcallback&response_type=code&state=dd3e270cabc321a9ca33ab9029b1ab7af040550c779bbe3e" for 192.168.2.122 at 2019-06-07 12:09:00 +0200
Processing by Oauth::AuthorizationsController#new as HTML
  Parameters: {"client_id"=>"4a8ce2ea1d3222446e44900357b4a68145581ec055a00d65ff09f03f589c68bb", "redirect_uri"=>"http://172.16.16.3/auth/gitlab/callback", "response_type"=>"code", "state"=>"dd3e270cabc321a9ca33ab9029b1ab7af040550c779bbe3e"}
Redirected to http://172.16.16.3/auth/gitlab/callback?code=cbb3d92fc720c2ad2179c3888b04585da03c7ec8ec01591f0f61ee6bca3c946c&state=dd3e270cabc321a9ca33ab9029b1ab7af040550c779bbe3e
Completed 302 Found in 10ms (ActiveRecord: 1.9ms | Elasticsearch: 0.0ms)
Started POST "/oauth/token" for 172.16.16.3 at 2019-06-07 12:09:00 +0200
Processing by Doorkeeper::TokensController#create as */*
  Parameters: {"client_id"=>"4a8ce2ea1d3222446e44900357b4a68145581ec055a00d65ff09f03f589c68bb", "client_secret"=>"[FILTERED]", "code"=>"[FILTERED]", "grant_type"=>"authorization_code", "redirect_uri"=>"http://172.16.16.3/auth/gitlab/callback"}
Completed 200 OK in 20ms
Started GET "/user" for 172.16.16.3 at 2019-06-07 12:09:00 +0200
Processing by ApplicationController#route_not_found as */*
  Parameters: {"unmatched_route"=>"user"}
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms)
Started GET "/users/sign_in" for 172.16.16.3 at 2019-06-07 12:09:00 +0200
Processing by SessionsController#new as */*
Completed 200 OK in 116ms (Views: 103.2ms | ActiveRecord: 1.1ms | Elasticsearch: 0.0ms)

==> /var/log/gitlab/gitlab-workhorse/current <==
2019-06-07_10:09:00.37995 172.16.16.7 127.0.0.1:0 - - [2019/06/07:12:09:00 +0200] "GET /oauth/authorize?client_id=4a8ce2ea1d3222446e44900357b4a68145581ec055a00d65ff09f03f589c68bb&redirect_uri=http%3A%2F%2F172.16.16.3%2Fauth%2Fgitlab%2Fcallback&response_type=code&state=dd3e270cabc321a9ca33ab9029b1ab7af040550c779bbe3e HTTP/1.1" 302 234 "http://172.16.16.3/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36" 0.016
2019-06-07_10:09:00.49629 172.16.16.7 127.0.0.1:0 - - [2019/06/07:12:09:00 +0200] "POST /oauth/token HTTP/1.1" 200 226 "" "Faraday v0.15.4" 0.028
2019-06-07_10:09:00.53624 172.16.16.7 127.0.0.1:0 - - [2019/06/07:12:09:00 +0200] "GET /user HTTP/1.1" 302 98 "" "Faraday v0.15.4" 0.036
2019-06-07_10:09:00.66704 172.16.16.7 127.0.0.1:0 - - [2019/06/07:12:09:00 +0200] "GET /users/sign_in HTTP/1.1" 200 11252 "" "Faraday v0.15.4" 0.129

==> /var/log/gitlab/nginx/gitlab_access.log <==
192.168.2.122 - - [07/Jun/2019:12:09:00 +0200] "GET /oauth/authorize?client_id=4a8ce2ea1d3222446e44900357b4a68145581ec055a00d65ff09f03f589c68bb&redirect_uri=http%3A%2F%2F172.16.16.3%2Fauth%2Fgitlab%2Fcallback&response_type=code&state=dd3e270cabc321a9ca33ab9029b1ab7af040550c779bbe3e HTTP/1.1" 302 234 "http://172.16.16.3/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
172.16.16.3 - - [07/Jun/2019:12:09:00 +0200] "POST /oauth/token HTTP/1.1" 200 226 "" "Faraday v0.15.4"
172.16.16.3 - - [07/Jun/2019:12:09:00 +0200] "GET /user HTTP/1.1" 302 98 "" "Faraday v0.15.4"
172.16.16.3 - - [07/Jun/2019:12:09:00 +0200] "GET /users/sign_in HTTP/1.1" 200 4310 "" "Faraday v0.15.4"
```

That's, from what I can tell, clean.


Zammad-Output: 
```
I, [2019-06-07T12:09:00.075160 #2321-47067990088920]  INFO -- : Started GET "/auth/gitlab" for 192.168.2.122 at 2019-06-07 12:09:00 +0200
I, [2019-06-07T12:09:00.105718 #2321-47067990088600]  INFO -- : Started GET "/auth/gitlab/callback?code=[FILTERED]&state=dd3e270cabc321a9ca33ab9029b1ab7af040550c779bbe3e" for 192.168.2.122 at 2019-06-07 12:09:00 +0200
F, [2019-06-07T12:09:00.390705 #2321-47067990088600] FATAL -- :
F, [2019-06-07T12:09:00.391162 #2321-47067990088600] FATAL -- : NoMethodError (undefined method `[]' for nil:NilClass):
F, [2019-06-07T12:09:00.391207 #2321-47067990088600] FATAL -- :
F, [2019-06-07T12:09:00.391242 #2321-47067990088600] FATAL -- : vendor/bundle/ruby/2.4.0/gems/omniauth-gitlab-2.0.0/lib/omniauth/strategies/gitlab.rb:11:in `block in <class:GitLab>'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:109:in `instance_eval'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:109:in `block in compile_stack'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:108:in `each'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:108:in `inject'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:108:in `compile_stack'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:102:in `uid_stack'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:332:in `uid'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:348:in `auth_hash'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:372:in `callback_phase'
vendor/bundle/ruby/2.4.0/gems/omniauth-oauth2-1.6.0/lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:238:in `callback_call'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:189:in `call!'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:25:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/cookies.rb:613:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:97:in `run_callbacks'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/ruby/2.4.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/ruby/2.4.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
vendor/bundle/ruby/2.4.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2019-06-07T12:09:02.051329 #2316-47004535240000]  INFO -- : Started job thread for 'Check Channels' (Channel.fetch)...
I, [2019-06-07T12:09:02.074486 #2316-47004535240000]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2019-06-07T12:09:32.092356 #2316-47004535240000]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2019-06-07T12:09:39.908185 #2321-47067990145160]  INFO -- : Started GET "/api/v1/cti/log?_=1559901763250" for 192.168.2.122 at 2019-06-07 12:09:39 +0200
I, [2019-06-07T12:09:39.913337 #2321-47067990145160]  INFO -- : Processing by CtiController#index as JSON
I, [2019-06-07T12:09:39.913396 #2321-47067990145160]  INFO -- :   Parameters: {"_"=>"1559901763250"}
I, [2019-06-07T12:09:39.921435 #2321-47067990145160]  INFO -- : Completed 200 OK in 8ms (Views: 0.2ms | ActiveRecord: 1.6ms)
I, [2019-06-07T12:09:43.499951 #2321-47067990089200]  INFO -- : Started GET "/api/v1/online_notifications/?full=true&_=1559901763251" for 192.168.2.122 at 2019-06-07 12:09:43 +0200
I, [2019-06-07T12:09:43.503566 #2321-47067990089200]  INFO -- : Processing by OnlineNotificationsController#index as JSON
I, [2019-06-07T12:09:43.503622 #2321-47067990089200]  INFO -- :   Parameters: {"full"=>"true", "_"=>"1559901763251"}

```

**Comment by thorsteneckel** [comment]
This reads like an issue in the `omniauth-gitlab` gem then 🤔 I'm wondering that no one complained about it by now. The last change to the gem was in the end of 2018.

**Comment by MrGeneration** [comment]
Look at https://github.com/zammad/zammad/commit/3acfa4a277c29a0eb3b7bff83fde1a60718a9746 it's a push from March after our valentines day update (2.9) :)

**Comment by thorsteneckel** [comment]
I've looked at that commit but all I can see is that we updated our dependencies including the `omniauth-gitlab` gem (from `1.0.2` to `2.0.0`). I can't find any code related changes to this. Do I look at the wrong place?

**Comment by MrGeneration** [comment]
Small sum up from our private chat (to keep it consistent):

No code change has been done, we just updated dependencies.

**Comment by DoktorAerzt** [comment]
I think the problem is [this change](https://github.com/linchus/omniauth-gitlab/commit/bb4cec2c9f8f067fdfe1f9aa219973e5d8e4a0a3)
And for my understanding of your codebase. You are using [the "old" way.](https://github.com/zammad/zammad/blob/76dfdbaf83d34499b9a2425432886a116e7b7d6c/config/initializers/omniauth.rb#L43)

**Comment by thorsteneckel** [comment]
Wow! Great catch! @DoktorAerzt is right. I was able to use the GitLab login with by configuring the URL `https://git.example.com/api/v4/` instead of `https://git.example.com` in Zammad – which the [placeholder](https://github.com/zammad/zammad/blob/80294b0b5165069bd02501456070268dde9f4a9e/db/seeds/settings.rb#L1453) indicated. Additionally [the documentation](https://admin-docs.zammad.org/de/latest/security-thirdparty/gitlab.html?highlight=gitlab#configure-zammad-as-gitlab-app) looks broken to me.

**Comment by MrGeneration** [comment]
Currently working on the documentation thirdparty stuff. Will update Google-Documentation and while I'm at it also update Gitlab.

**Comment by cyberrranger** [comment]
thx

**Comment by cyberrranger** [comment]
i use Zammad (docker-compose) with 3.0.x gitlab works with the the URL https://git.******.com/api/v4/ (@DoktorAerzt thx). 

Now i update to Zammad 3.1.x, and the Login with gitlab is with broken.

**Comment by MrGeneration** [comment]
Please note that this issue is not yet closed so the issue is not fixed within stable yet.

**Comment by thorsteneckel** [comment]
> i use Zammad (docker-compose) with 3.0.x gitlab works with the the URL https://git.******.com/api/v4/ (@DoktorAerzt thx).
> 
> Now i update to Zammad 3.1.x, and the Login with gitlab is with broken.

What exactly is broken @cyberrranger ? Please provide the log file of your Zammad. 

@MrGeneration we actually will only change the placeholder in Zammad. Let me know when the documentation is ready. We can then change the placeholder and close the issue.

**Comment by MrGeneration** [comment]
This has been addressed with PR - thanks to loads of help from @cyberrranger  :)

https://github.com/zammad/zammad-admin-documentation/pull/20

So from my side we could close this issue.

**Comment by cyberrranger** [comment]
@thorsteneckel sry for my long absence, I just tried again with VERSION = -3.1.0-28, the same error. Which logs do you need?

**Comment by MrGeneration** [comment]
@cyberrranger please follow this guide and try again.
https://admin-docs.zammad.org/en/latest/security-thirdparty/gitlab.html

If this still fails for you, please provide your production.log ( `/opt/zammad/log/` ) around the time you tried this.

**Comment by cyberrranger** [comment]
next try with a new install of Version 3.2.0 (https://github.com/zammad/zammad-docker-compose), with no data, and one user (me).

https://URL-ZAMMAD/#settings/security

i have active "Automatic account link on initial logon" yes
Authentication via Gitlab ON
App ID and App Secret
Site https://URL-GITLAB/api/v4/

on https://ticket2.saas.de/#profile/linked i select "Gitlab Add"

now I was forwarded on https://URL-ZAMMAD/auth/gitlab

the error site "422: The change you wanted was rejected." is open
![Screenshot 2019-12-05 09 37 25](https://user-images.githubusercontent.com/21671762/70218212-dc541600-1742-11ea-8bfa-ded00fc849ef.png)

docker-compose logs -f

```
zammad-railsserver_1    | I, [2019-12-05T08:44:03.755184 #1-47203323863220]  INFO -- : Started POST "/auth/gitlab" for 192.168.112.1 at 2019-12-05 08:44:03 +0000
zammad-railsserver_1    | I, [2019-12-05T08:44:03.761717 #1-47203323863220]  INFO -- omniauth: (gitlab) Request phase initiated.
zammad-railsserver_1    | F, [2019-12-05T08:44:03.762751 #1-47203323863220] FATAL -- :   
zammad-railsserver_1    | F, [2019-12-05T08:44:03.762837 #1-47203323863220] FATAL -- : ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
zammad-railsserver_1    | F, [2019-12-05T08:44:03.762868 #1-47203323863220] FATAL -- :   
zammad-railsserver_1    | F, [2019-12-05T08:44:03.762910 #1-47203323863220] FATAL -- : omniauth-rails_csrf_protection (0.1.2) lib/omniauth/rails_csrf_protection/token_verifier.rb:34:in `call'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:209:in `request_call'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:188:in `call!'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
zammad-nginx_1          | 192.168.112.1 - - [05/Dec/2019:08:44:03 +0000] "POST /auth/gitlab HTTP/1.1" 422 727 "https://ZAMMAD-URL/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
zammad-railsserver_1    | omniauth (1.9.0) lib/omniauth/builder.rb:64:in `call'
zammad-railsserver_1    | rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
zammad-railsserver_1    | rack (2.0.7) lib/rack/etag.rb:25:in `call'
zammad-railsserver_1    | rack (2.0.7) lib/rack/conditional_get.rb:38:in `call'
zammad-railsserver_1    | rack (2.0.7) lib/rack/head.rb:12:in `call'
zammad-railsserver_1    | actionpack (5.2.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
zammad-railsserver_1    | rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
zammad-railsserver_1    | rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
zammad-railsserver_1    | actionpack (5.2.3) lib/action_dispatch/middleware/cookies.rb:670:in `call'
zammad-railsserver_1    | actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
zammad-railsserver_1    | activesupport (5.2.3) lib/active_support/callbacks.rb:98:in `run_callbacks'
zammad-railsserver_1    | actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
zammad-railsserver_1    | actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
zammad-railsserver_1    | actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
zammad-railsserver_1    | railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
zammad-railsserver_1    | railties (5.2.3) lib/rails/rack/logger.rb:28:in `call'
zammad-railsserver_1    | actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
zammad-railsserver_1    | actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
zammad-railsserver_1    | rack (2.0.7) lib/rack/method_override.rb:22:in `call'
zammad-railsserver_1    | rack (2.0.7) lib/rack/runtime.rb:22:in `call'
zammad-railsserver_1    | activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
zammad-railsserver_1    | actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
zammad-railsserver_1    | rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
zammad-railsserver_1    | railties (5.2.3) lib/rails/engine.rb:524:in `call'
zammad-railsserver_1    | puma (3.12.1) lib/puma/configuration.rb:227:in `call'
zammad-railsserver_1    | puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
zammad-railsserver_1    | puma (3.12.1) lib/puma/server.rb:474:in `process_client'
zammad-railsserver_1    | puma (3.12.1) lib/puma/server.rb:334:in `block in run'
zammad-railsserver_1    | puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
zammad-railsserver_1    | logging (2.2.2) lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by cyberrranger** [comment]
Update:

on my gitlab installation i cant find any log entries on this moment

**Comment by thorsteneckel** [comment]
Hi @cyberrranger - this looks like an Zammad / Rails internal issue. I see a message stating `ActionController::InvalidAuthenticityToken` in your logs which checks the CSRF token (IIRC). This can have multiple roots but none are related to this issue here. Would you mind creating a topic over at the [community board](http://community.zammad.org/) and mention me? Please include a screenshot of the sent POST parameters from your browser console. And please check if it is related to [this](https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080/18) issue.
