### ISSUE TITLE
Binary encoded data in (cc) field fails mail processing

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2746]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1053678

### Expected behavior:

Zammad will decode TO, CC and FROM fields correctly and import the mail.

### Actual behavior:

In some special cases, processing of mails fail if TO, CC or FROM contains binary data and move the mail to `unprocessible_mails`.

### Log

```
E, [2019-09-18T11:38:01.789617 #1531-70079947099620] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /home/666/tmp/unprocessable_mail/2019-09-18T09:38:01Z_9c47d46c14b70987029c0f7859243f70.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2019-09-18T11:38:01.789646 #1531-70079947099620] ERROR -- : incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/encodings.rb:137:in `join'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/encodings.rb:137:in `value_decode'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/encodings.rb:109:in `decode_encode'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/fields/unstructured_field.rb:84:in `do_decode'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/fields/unstructured_field.rb:62:in `decoded'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/mail-9265cf75bbe3/lib/mail/field.rb:239:in `method_missing'
/home/666/app/models/channel/email_parser.rb:514:in `rescue in block in message_header_hash'
/home/666/app/models/channel/email_parser.rb:505:in `block in message_header_hash'
/home/666/app/models/channel/email_parser.rb:504:in `map'
/home/666/app/models/channel/email_parser.rb:504:in `message_header_hash'
/home/666/app/models/channel/email_parser.rb:81:in `parse'
/home/666/app/models/channel/email_parser.rb:136:in `_process'
/home/666/app/models/channel/email_parser.rb:115:in `block in process'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
/home/666/app/models/channel/email_parser.rb:114:in `process'
/home/666/app/models/channel/driver/imap.rb:264:in `block in fetch'
/home/666/app/models/channel/driver/imap.rb:212:in `each'
/home/666/app/models/channel/driver/imap.rb:212:in `fetch'
/home/666/app/models/channel.rb:56:in `fetch'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/home/666/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/home/666/app/models/scheduler.rb:286:in `eval'
/home/666/app/models/scheduler.rb:286:in `_start_job'
/home/666/app/models/scheduler.rb:239:in `block (2 levels) in start_job'
/home/666/app/models/scheduler.rb:237:in `loop'
/home/666/app/models/scheduler.rb:237:in `block in start_job'
/usr/local/rvm/gems/ruby-2.5.5/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

```

### Steps to reproduce the behavior:

Put the following mail in a file:
```
Mime-Version: 1.0
X-Mailer: GroupWise 2014 R2
Subject: Broken mail
Date: Thu, 12 Sep 2019 09:09:48 +0200
Message-ID: <5D79EF3C020000D2000A2654@example.de>
From: "Lassen Sie sich =?UTF-8?B?VmVyd8O2aG5lbg==?="
   <Verwöhnen@example.de>
To: zammad@example.com
Content-Type: multipart/alternative; boundary="____TAYQQEUZELYJMCBZPMES____"


--____TAYQQEUZELYJMCBZPMES____
```

Process it via: `cat /path/to/your.eml | time rails r 'Channel::Driver::MailStdin.new'`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
If i saw it correctly, this mail is no longer failing during the encoding of the mail, it's not failing in the user model check mail functionality:

```
"ERROR: #<Exceptions::UnprocessableEntity: Invalid email 'verwöhnen@example.de'>"
Traceback (most recent call last):
	61: from bin/rails:9:in `<main>'
	60: from .rvm/gems/ruby-2.7.4/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	59: from .rvm/gems/ruby-2.7.4/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	58: from .rvm/gems/ruby-2.7.4/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	57: from .rvm/gems/ruby-2.7.4/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	56: from .rvm/gems/ruby-2.7.4/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	55: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/commands.rb:18:in `<main>'
	54: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/command.rb:46:in `invoke'
	53: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/command/base.rb:69:in `perform'
	52: from .rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	51: from .rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	50: from .rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	49: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	48: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	47: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	46: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/commands/runner/runner_command.rb:45:in `new'
	45: from ws/zammad-dev/app/models/channel/driver/mail_stdin.rb:30:in `initialize'
	44: from ws/zammad-dev/app/models/channel/email_parser.rb:119:in `process'
	43: from .rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	42: from .rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	41: from .rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	40: from .rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	39: from .rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
	38: from ws/zammad-dev/app/models/channel/email_parser.rb:120:in `block in process'
	37: from ws/zammad-dev/app/models/channel/email_parser.rb:156:in `_process'
	36: from ws/zammad-dev/app/models/channel/email_parser.rb:156:in `each'
	35: from ws/zammad-dev/app/models/channel/email_parser.rb:159:in `block in _process'
	34: from ws/zammad-dev/app/models/channel/filter/identify_sender.rb:53:in `run'
	33: from ws/zammad-dev/app/models/channel/filter/identify_sender.rb:157:in `user_create'
	32: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/persistence.rb:55:in `create!'
	31: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/suppressor.rb:48:in `save!'
	30: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/transactions.rb:318:in `save!'
	29: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
	28: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/transactions.rb:212:in `transaction'
	27: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
	26: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
	25: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	24: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	23: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	22: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	21: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	20: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
	19: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
	18: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
	17: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/transactions.rb:318:in `block in save!'
	16: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/validations.rb:53:in `save!'
	15: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/validations.rb:84:in `perform_validations'
	14: from .rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/validations.rb:68:in `valid?'
	13: from .rvm/gems/ruby-2.7.4/gems/activemodel-6.0.4/lib/active_model/validations.rb:337:in `valid?'
	12: from .rvm/gems/ruby-2.7.4/gems/activemodel-6.0.4/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
	11: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
	10: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:134:in `run_callbacks'
	 9: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:513:in `invoke_before'
	 8: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:513:in `each'
	 7: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
	 6: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:201:in `block in halting'
	 5: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:604:in `block in default_terminator'
	 4: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:604:in `catch'
	 3: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
	 2: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
	 1: from .rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:428:in `block in make_lambda'
ws/zammad-dev/app/models/user.rb:926:in `check_email': Invalid email 'verwöhnen@example.de' (Exceptions::UnprocessableEntity)
	18: from bin/rails:9:in `<main>'
	17: from .rvm/gems/ruby-2.7.4/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	16: from .rvm/gems/ruby-2.7.4/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	15: from .rvm/gems/ruby-2.7.4/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	14: from .rvm/gems/ruby-2.7.4/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	13: from .rvm/gems/ruby-2.7.4/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	12: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/commands.rb:18:in `<main>'
	11: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/command.rb:46:in `invoke'
	10: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/command/base.rb:69:in `perform'
	 9: from .rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	 8: from .rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	 7: from .rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	 6: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	 5: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	 4: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	 3: from .rvm/gems/ruby-2.7.4/gems/railties-6.0.4/lib/rails/commands/runner/runner_command.rb:45:in `new'
	 2: from ws/zammad-dev/app/models/channel/driver/mail_stdin.rb:30:in `initialize'
	 1: from ws/zammad-dev/app/models/channel/email_parser.rb:117:in `process'
ws/zammad-dev/app/models/channel/email_parser.rb:135:in `rescue in process': #<Exceptions::UnprocessableEntity: Invalid email 'verwöhnen@example.de'> (RuntimeError)
ws/zammad-dev/app/models/user.rb:926:in `check_email'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:428:in `block in make_lambda'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:604:in `catch'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:604:in `block in default_terminator'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:201:in `block in halting'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:513:in `each'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:513:in `invoke_before'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:134:in `run_callbacks'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
.rvm/gems/ruby-2.7.4/gems/activemodel-6.0.4/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
.rvm/gems/ruby-2.7.4/gems/activemodel-6.0.4/lib/active_model/validations.rb:337:in `valid?'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/validations.rb:68:in `valid?'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/validations.rb:84:in `perform_validations'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/validations.rb:53:in `save!'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/transactions.rb:318:in `block in save!'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
.rvm/gems/ruby-2.7.4/gems/activesupport-6.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/transactions.rb:212:in `transaction'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/transactions.rb:318:in `save!'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/suppressor.rb:48:in `save!'
.rvm/gems/ruby-2.7.4/gems/activerecord-6.0.4/lib/active_record/persistence.rb:55:in `create!'
ws/zammad-dev/app/models/channel/filter/identify_sender.rb:157:in `user_create'
ws/zammad-dev/app/models/channel/filter/identify_sender.rb:53:in `run'
ws/zammad-dev/app/models/channel/email_parser.rb:159:in `block in _process'
ws/zammad-dev/app/models/channel/email_parser.rb:156:in `each'
ws/zammad-dev/app/models/channel/email_parser.rb:156:in `_process'
ws/zammad-dev/app/models/channel/email_parser.rb:120:in `block in process'
```

**Comment by mantas** [comment]
Cannot reproduce this anymore. Looks like it is fixed while working on other issues with unicode email processing
