### ISSUE TITLE
zammad fails to start when using postgresql beta

### ISSUE THREAD

**Issue by DaAllexx** [zammad/zammad#2800]
When using postgresql beta, a version string like `12beta2` is returned which does not behave well with zammad.

### Infos:
* Used Zammad version: 3.1
* Installation method (source, package, ..): package via apt
* Operating system: Ubuntu 16.04
* Database + version: postgres (PostgreSQL) 12beta2

### Expected behavior:
* zammad should run fine with beta versions of postgresql

### Actual behavior:
* zammad fails to startup due to failing parsing a version number from postgresql which is not compatible with semantic versioning.
```
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/rubygems/version.rb:208:in `initialize': Malformed version number string 12beta2 (ArgumentError)
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/rubygems/version.rb:199:in `new'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/rubygems/version.rb:199:in `new'
	from /opt/zammad/lib/zammad/application/initializer/db_preflight_check/base.rb:18:in `check_version_compatibility'
	from /opt/zammad/lib/zammad/application/initializer/db_preflight_check/postgresql.rb:27:in `check_version_compatibility'
	from /opt/zammad/lib/zammad/application/initializer/db_preflight_check/postgresql.rb:19:in `perform'
	from /opt/zammad/lib/zammad/application/initializer/db_preflight_check.rb:11:in `perform'
	from /opt/zammad/config/initializers/db_preflight_check.rb:4:in `<main>'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:657:in `block in load_config_initializer'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:656:in `load_config_initializer'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `each'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `block in <class:Engine>'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `each'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:415:in `call'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `call'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /opt/zammad/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
	from /opt/zammad/config/environment.rb:5:in `<top (required)>'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from script/websocket-server.rb:14:in `<main>'
```
### Steps to reproduce the behavior:
* run zammad 3.1 with postgresql beta version

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mgruner** [comment]
@MrGeneration I believe this is outdated and can be closed. Zammad runs fine with more recent versions of PostgreSQL (13.4 in my case).

**Comment by MrGeneration** [comment]
I believe so too.
I believe the  `-beta` string would be the issue in this case.

**Comment by mgruner** [comment]
@MrGeneration Oh, now I see that I misunderstood the report. So it's probably still the same behaviour.
Is it really the case that Zammad should support beta versions of dependencies?

**Comment by MrGeneration** [comment]
> Is it really the case that Zammad should support beta versions of dependencies?

Supporting it is a hard wording. 
I mean it's not official tested by us and so shouldn't give any warranty
 whatsoever
