### ISSUE TITLE
mail processing failed cause e-mail already deleted?

### ISSUE THREAD

**Issue by shakalandy** [zammad/zammad#2802]
### Infos:

* Used Zammad version: zammad-3.1.0-1573129860.5878cb4b.centos7.x86_64
* Installation method (source, package, ..): RPM
* Operating system:  CentOS Linux release 7.7.1908 (Core)
* Database + version: postgresql-server-9.2.24-1.el7_5.x86_64
* Elasticsearch version: elasticsearch-5.6.16-1.noarch
* Browser + version: Chrome / Mac

### Expected behavior:

* E-Mail processed successfully

### Actual behavior:

* e-mail processing aborted
* can transmit e-mail via support if needed

### Steps to reproduce the behavior:

see zammad log output
```
2019-11-07T10:44:02.144726 #16503-70072353743800]  INFO -- : Process email with msgid '<65a9c1077b64451298e1b006fff6c8d3@blubb.com>'
I, [2019-11-07T10:44:02.224023 #16503-70072353743800]  INFO -- :  process filter support-at@support.com ...
I, [2019-11-07T10:44:02.224187 #16503-70072353743800]  INFO -- :   not matching to:'"support-de@support.com" <support-de@support.com>' on support-at@support.com, but should
I, [2019-11-07T10:44:02.224377 #16503-70072353743800]  INFO -- :  process filter support-da@support.com ...
I, [2019-11-07T10:44:02.224493 #16503-70072353743800]  INFO -- :   not matching from:'Eva <Eva@blubb.com>' on support-da@support.com, but should
I, [2019-11-07T10:44:02.224712 #16503-70072353743800]  INFO -- :  process filter support-de@support.com ...
I, [2019-11-07T10:44:02.225035 #16503-70072353743800]  INFO -- :   perform 'x-zammad-ticket-tags' = '{"operator"=>"add", "value"=>"DE"}'
I, [2019-11-07T10:44:02.225493 #16503-70072353743800]  INFO -- :  process filter support-en@support.com ...
I, [2019-11-07T10:44:02.225614 #16503-70072353743800]  INFO -- :   not matching to:'"support-de@support.com" <support-de@support.com>' on support-en@support.com, but should
I, [2019-11-07T10:44:02.225757 #16503-70072353743800]  INFO -- :  process filter support-es@support.com ...
I, [2019-11-07T10:44:02.225884 #16503-70072353743800]  INFO -- :   not matching to:'"support-de@support.com" <support-de@support.com>' on support-es@support.com, but should
I, [2019-11-07T10:44:02.225905 #16503-70072353743800]  INFO -- :  process filter support-fr@support.com ...
I, [2019-11-07T10:44:02.226028 #16503-70072353743800]  INFO -- :   not matching to:'"support-de@support.com" <support-de@support.com>' on support-fr@support.com, but should
I, [2019-11-07T10:44:02.226055 #16503-70072353743800]  INFO -- :  process filter support-it@support.com ...
I, [2019-11-07T10:44:02.226542 #16503-70072353743800]  INFO -- :   not matching to:'"support-de@support.com" <support-de@support.com>' on support-it@support.com, but should
I, [2019-11-07T10:44:02.226565 #16503-70072353743800]  INFO -- :  process filter support-nl@support.com ...
I, [2019-11-07T10:44:02.226682 #16503-70072353743800]  INFO -- :   not matching to:'"support-de@support.com" <support-de@support.com>' on support-nl@support.com, but should
I, [2019-11-07T10:44:02.226703 #16503-70072353743800]  INFO -- :  process filter support-pl@support.com ...
I, [2019-11-07T10:44:02.226805 #16503-70072353743800]  INFO -- :   not matching to:'"support-de@support.com" <support-de@support.com>' on support-pl@support.com, but should
I, [2019-11-07T10:44:02.227020 #16503-70072353743800]  INFO -- :  process filter XXX support@support.com LANG_DE ...
I, [2019-11-07T10:44:02.227227 #16503-70072353743800]  INFO -- :   not matching to:'"support-de@support.com" <support-de@support.com>' on support@support.com, but should
I, [2019-11-07T10:44:02.237094 #16503-70072353743800]  INFO -- : set_attributes_by_x_headers header x-zammad-ticket-customer_id found. Assign customer_id=30084
I, [2019-11-07T10:44:02.260915 #16503-70072353743800]  INFO -- : Enqueued SearchIndexJob (Job ID: b5f157a1-4d37-4c12-a927-025a1dfbde88) to DelayedJob(default) with arguments: "Ticket", 125901
I, [2019-11-07T10:44:02.266778 #16503-70072353743800]  INFO -- : Enqueued SearchIndexJob (Job ID: 156bbb00-5218-40c7-b911-cd0655b5b679) to DelayedJob(default) with arguments: "User", 30084
I, [2019-11-07T10:44:02.284203 #16503-70072353743800]  INFO -- : Enqueued SearchIndexJob (Job ID: c759e48c-34fe-41df-94b1-f3aa41739831) to DelayedJob(default) with arguments: "Ticket", 125901
I, [2019-11-07T10:44:02.293585 #16503-70072353743800]  INFO -- : set_attributes_by_x_headers header x-zammad-article-preferences found. Assign preferences={"send-auto-response"=>true, "is-auto-response
"=>false}
I, [2019-11-07T10:44:02.718308 #16503-70072353743800]  INFO -- : Enqueued SearchIndexJob (Job ID: 7431de61-f77d-4c6d-92b7-7b8ffd8bf420) to DelayedJob(default) with arguments: "Ticket", 125901
I, [2019-11-07T10:44:02.721632 #16503-70072353743800]  INFO -- : Enqueued SearchIndexJob (Job ID: 8b4c3224-52be-40dc-acb9-406aff8799a8) to DelayedJob(default) with arguments: "User", 30084
I, [2019-11-07T10:44:02.774956 #16503-70072353743800]  INFO -- : storge remove '/opt/zammad/storage/fs/a9d1/9bb2/73d93/269a2/fdced17/5d34f0d/9ce1bf77204f01d824983be70d1edead'
E, [2019-11-07T10:44:02.781575 #16503-70072353743800] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/17de6d09a654296d0dcb705ca4ffc058.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2019-11-07T10:44:02.781600 #16503-70072353743800] ERROR -- : No such file or directory @ rb_sysopen - /opt/zammad/storage/fs/a9d1/9bb2/73d93/269a2/fdced17/5d34f0d/9ce1bf77204f01d824983be70d1edead (Errno::ENOENT)
/opt/zammad/app/models/store/provider/file.rb:23:in `initialize'
/opt/zammad/app/models/store/provider/file.rb:23:in `new'
/opt/zammad/app/models/store/provider/file.rb:23:in `add'
/opt/zammad/app/models/store/file.rb:33:in `add'
/opt/zammad/app/models/store.rb:44:in `add'
/opt/zammad/app/models/channel/email_parser.rb:291:in `block (3 levels) in _process'
/opt/zammad/app/models/channel/email_parser.rb:286:in `each'
/opt/zammad/app/models/channel/email_parser.rb:286:in `block (2 levels) in _process'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/locking/pessimistic.rb:84:in `block in with_lock'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:301:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/locking/pessimistic.rb:82:in `with_lock'
/opt/zammad/app/models/channel/email_parser.rb:260:in `block in _process'
/opt/zammad/app/models/transaction.rb:15:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/app/models/transaction.rb:13:in `execute'
/opt/zammad/app/models/channel/email_parser.rb:174:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:115:in `block in process'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:114:in `process'
/opt/zammad/app/models/channel/driver/imap.rb:254:in `block in fetch'
/opt/zammad/app/models/channel/driver/imap.rb:211:in `each'
/opt/zammad/app/models/channel/driver/imap.rb:211:in `fetch'
/opt/zammad/app/models/channel.rb:56:in `fetch'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:286:in `eval'
/opt/zammad/app/models/scheduler.rb:286:in `_start_job'
/opt/zammad/app/models/scheduler.rb:239:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:237:in `loop'
/opt/zammad/app/models/scheduler.rb:237:in `block in start_job'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'```

maybe related to #2746

**Comment by MrGeneration** [comment]
Sorry for the wait.
Is this still current and happening with an up to date stable Zammad installation?

Personally never seen such an issue up to now.
Looks like the file Zammad is not able to find attachments in your file system (`No such file or directory @ rb_sysopen - /opt/zammad/storage/fs/a9d1/9bb2/73d93/269a2/fdced17/5d34f0d/9ce1bf77204f01d824983be70d1edead`).
The reason for this *may* be that this is an old attachment which has been lost in the filesystem but still exists as reference in the database.

---


If this still is up to date (and you still have the mail in question) feel free to send the sample to support [at] zammad [dot] com and I'll have a look.

**Comment by shakalandy** [comment]
Has not occured again, I'll close :)
