### ISSUE TITLE
Zammad doesn't work with Elasticsearch 7.5.x

### ISSUE THREAD

**Issue by mpibpc-mroose** [zammad/zammad#2824]
### Infos:

* Used Zammad version: 3.2.0-1575357814.e0ff35cb.bionic
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04 LTS
* Elasticsearch version: 7.5

### Expected behavior:

* rebuild should finish without error

### Actual behavior:

```
$> zammad run rake searchindex:rebuild

...

reload User
  - started at 2019-12-03 10:42:21 UTC
rake aborted!
Unable to send User.find(95).search_index_update_backend backend: #<RuntimeError: Unable to process post request to elasticsearch URL 'http://127.0.0.1:9200/zammad_production_user/_doc/95?pipeline=zammad284860931006'. Check the response and payload for detailed information:

Response:
#<UserAgent::Result:0x00005567972c6f10 @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"field [article] not present as part of path [article]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"field [article] not present as part of path [article]\"},\"status\":400}", @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">

Payload:
{"id"=>95, "organization_id"=>nil, "login"=>"erother3", "firstname"=>"Ellen", "lastname"=>"Rothermel", "email"=>"ellen.rothermel@mpibpc.mpg.de", "web"=>"", "phone"=>"", "fax"=>"", "mobile"=>"", "department"=>"", "street"=>"", "zip"=>"", "city"=>"", "country"=>"", "address"=>"", "vip"=>false, "verified"=>false, "active"=>true, "note"=>"", "last_login"=>nil, "out_of_office"=>false, "out_of_office_start_at"=>nil, "out_of_office_end_at"=>nil, "out_of_office_replacement_id"=>nil, "preferences"=>{}, "updated_by_id"=>1, "created_by_id"=>1, "created_at"=>Wed, 02 Oct 2019 08:53:04 UTC +00:00, "updated_at"=>Wed, 02 Oct 2019 08:53:04 UTC +00:00, "permissions"=>["user_preferences.password", "user_preferences.language", "user_preferences.linked_accounts", "user_preferences.avatar", "ticket.customer"], "role_ids"=>[3]}

Payload size: 0M>
/opt/zammad/app/models/concerns/has_search_index_backend.rb:145:in `rescue in block in search_index_reload'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:139:in `block in search_index_reload'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:134:in `each'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:134:in `search_index_reload'
/opt/zammad/lib/tasks/search_index_es.rake:143:in `block (3 levels) in <main>'
/opt/zammad/lib/tasks/search_index_es.rake:139:in `each'
/opt/zammad/lib/tasks/search_index_es.rake:139:in `block (2 levels) in <main>'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/opt/zammad/lib/tasks/search_index_es.rake:159:in `block (2 levels) in <main>'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.5.0/bin/rake:23:in `load'
/opt/zammad/vendor/bundle/ruby/2.5.0/bin/rake:23:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/opt/zammad/bin/bundle:3:in `load'
/opt/zammad/bin/bundle:3:in `<main>'

Caused by:
Unable to process post request to elasticsearch URL 'http://127.0.0.1:9200/zammad_production_user/_doc/95?pipeline=zammad284860931006'. Check the response and payload for detailed information:

Response:
#<UserAgent::Result:0x00005567972c6f10 @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"field [article] not present as part of path [article]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"field [article] not present as part of path [article]\"},\"status\":400}", @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">

Payload:
{"id"=>95, "organization_id"=>nil, "login"=>"erother3", "firstname"=>"Ellen", "lastname"=>"Rothermel", "email"=>"ellen.rothermel@mpibpc.mpg.de", "web"=>"", "phone"=>"", "fax"=>"", "mobile"=>"", "department"=>"", "street"=>"", "zip"=>"", "city"=>"", "country"=>"", "address"=>"", "vip"=>false, "verified"=>false, "active"=>true, "note"=>"", "last_login"=>nil, "out_of_office"=>false, "out_of_office_start_at"=>nil, "out_of_office_end_at"=>nil, "out_of_office_replacement_id"=>nil, "preferences"=>{}, "updated_by_id"=>1, "created_by_id"=>1, "created_at"=>Wed, 02 Oct 2019 08:53:04 UTC +00:00, "updated_at"=>Wed, 02 Oct 2019 08:53:04 UTC +00:00, "permissions"=>["user_preferences.password", "user_preferences.language", "user_preferences.linked_accounts", "user_preferences.avatar", "ticket.customer"], "role_ids"=>[3]}

Payload size: 0M
/opt/zammad/lib/search_index_backend.rb:865:in `make_request_and_validate'
/opt/zammad/lib/search_index_backend.rb:145:in `add'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:66:in `search_index_update_backend'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:140:in `block in search_index_reload'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:134:in `each'
/opt/zammad/app/models/concerns/has_search_index_backend.rb:134:in `search_index_reload'
/opt/zammad/lib/tasks/search_index_es.rake:143:in `block (3 levels) in <main>'
/opt/zammad/lib/tasks/search_index_es.rake:139:in `each'
/opt/zammad/lib/tasks/search_index_es.rake:139:in `block (2 levels) in <main>'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/opt/zammad/lib/tasks/search_index_es.rake:159:in `block (2 levels) in <main>'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.5.0/bin/rake:23:in `load'
/opt/zammad/vendor/bundle/ruby/2.5.0/bin/rake:23:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/opt/zammad/bin/bundle:3:in `load'
/opt/zammad/bin/bundle:3:in `<main>'
Tasks: TOP => searchindex:rebuild
```

### Steps to reproduce the behavior:

* for me this happens on two machines running Zammad. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Is this a fresh install of Zammad and Elasticsearch?
Also, please be aware that Zammad 3.2 currently is still in develop (Beta) and not meant for production use - just in case.

**Comment by mpibpc-mroose** [comment]
It's not a fresh install. I'm using the package repository  https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu 18.04 main
so I wonder how this could be a beta.

**Comment by MrGeneration** [comment]
Nevermind regarding the Zammad version, didn't notice it's on stable by now. Sorry for that.

I've been digging in elasticsearchs log. I noticed an extreme waiting time.
I suspected issues after upgrading (specially ES and postgreSQL service and so I rebootet).

After rebooting and trying the rebuild again, I found these cuties in elasticsearchs logfile:

```
[2019-12-03T12:57:06,128][DEBUG][o.e.a.b.T.BulkRequestModifier] [zammad] failed to execute pipeline [_none] for document [zammad_production_knowledge_base_category_translation/_doc/6]
java.lang.IllegalArgumentException: field [article] not present as part of path [article]
        at org.elasticsearch.ingest.IngestDocument.resolve(IngestDocument.java:347) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.ingest.IngestDocument.getFieldValue(IngestDocument.java:115) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.ingest.IngestDocument.getFieldValue(IngestDocument.java:132) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.ingest.common.ForEachProcessor.execute(ForEachProcessor.java:71) ~[?:?]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:137) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:123) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:137) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:123) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:100) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.ingest.IngestService.innerExecute(IngestService.java:504) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.ingest.IngestService.executePipelines(IngestService.java:409) [elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.ingest.IngestService.access$000(IngestService.java:75) [elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.ingest.IngestService$3.doRun(IngestService.java:383) [elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.0.jar:7.5.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```

This issue does seem to affect all all indices.
So as 7.5 is fairly new, I suspected an yet not seen issue, however, downgrading to 7.4.2 does not fix this issue.

Edit: ~~This seems to be an issue on ES 6.x and ES 7.x, as reindexing ES 5.6.x does work without issues. Testing further...~~

Edit2: 
I can verify that Elasticsearch 7.5.x is "broken" in combination with Zammad.
I could verify Elasticsearch 5.6.x, 6.8.x and up to 7.4.X to be working without any issues.

Please note in this combination: Downgrading does not work on ES; you need to remove your indice data and start from scratch.

**Comment by monotek** [comment]
i guess we have to pin es to 7.4 in the docker build too:
https://github.com/zammad/zammad-docker/blob/master/scripts/install-zammad.sh#L34

Or is there a quick es 7.5 fix likely?

**Comment by martini** [comment]
> Or is there a quick es 7.5 fix likely?

Fix is in CI now. @monotek

**Comment by mawo66** [comment]
Is there any way to downgrade to elasticsearch 7.4.2 and keeping zammad's data (tickets, users, ...)?

**Comment by MrGeneration** [comment]
Uninstalling elasticsearch by breaking dependencies, removing indice directories and install new followed by a rebuild.

Please note that this is a rather technical question which should be asked on the community next time. :-)

**Comment by mawo66** [comment]
Thank you very much, it is working again!

**Comment by iemsaif** [comment]
please help me 

Unable to process GET request to elasticsearch URL 'http://localhost:9200/zammad_production_ticket/_search'. Check the response and payload for detailed information:

Response:
#<UserAgent::Result:0x00007be5f687c8c0 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<EOFError: end of file reached>", @header=nil>

Payload:
{"size":0,"query":{"bool":{"must":[{"range":{"created_at":{"from":"2023-12-31T19:00:00Z","to":"2024-12-31T18:59:59Z"}}},{"bool":{"must":[{"bool":{"must_not":[{"term":{"state.name.keyword":"merged"}}]}}]}}]}},"aggs":{"time_buckets":{"date_histogram":{"field":"created_at","calendar_interval":"month","time_zone":"Asia/Karachi"}}},"sort":[{"updated_at":{"order":"desc"}},"_score"]}

Payload size: 0M

**Comment by MrGeneration** [comment]
@iemsaif please don't hijack bug reports with your technical questions.
If you have technical questions, kindly consult our community: https://community.zammad.org
