### ISSUE TITLE
Invalid stored Twitter credentials block migration

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2826]
### Infos:

* Used Zammad version: 3.2.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Unable to process db migrations/to upgrade to Zammad 3.2 

### Actual behavior:

```
rake db:migrate

== 20191107050249 Issue2460FixCorruptedTwitterIds: migrating ==================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Could not authenticate you.
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/request.rb:81:in `fail_or_return_response_body'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/request.rb:39:in `perform'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/utils.rb:50:in `perform_request'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/utils.rb:72:in `perform_request_with_object'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/utils.rb:57:in `perform_get_with_object'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/users.rb:53:in `verify_credentials'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/users.rb:237:in `user'
/home/zammad/zammad/db/migrate/20191107050249_issue_2460_fix_corrupted_twitter_ids.rb:14:in `block in up'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/home/zammad/zammad/db/migrate/20191107050249_issue_2460_fix_corrupted_twitter_ids.rb:5:in `up'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:817:in `exec_migration'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1343:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1036:in `up'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1011:in `migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/usr/local/rvm/gems/ruby-2.5.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
Twitter::Error::Unauthorized: Could not authenticate you.
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/request.rb:81:in `fail_or_return_response_body'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/request.rb:39:in `perform'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/utils.rb:50:in `perform_request'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/utils.rb:72:in `perform_request_with_object'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/utils.rb:57:in `perform_get_with_object'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/users.rb:53:in `verify_credentials'
/usr/local/rvm/gems/ruby-2.5.5/bundler/gems/twitter-844818cad07c/lib/twitter/rest/users.rb:237:in `user'
/home/zammad/zammad/db/migrate/20191107050249_issue_2460_fix_corrupted_twitter_ids.rb:14:in `block in up'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/home/zammad/zammad/db/migrate/20191107050249_issue_2460_fix_corrupted_twitter_ids.rb:5:in `up'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:817:in `exec_migration'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1343:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1036:in `up'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/migration.rb:1011:in `migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/local/rvm/gems/ruby-2.5.5/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/usr/local/rvm/gems/ruby-2.5.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by rlue** [comment]
Good looking out, guys. Sorry for not catching this the first time around.

**Comment by BertrandGouny** [comment]
hello,
i had this error, it seems to be linked to the fix 
```
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
private method `blank?' called for #<Twitter::REST::Client:0x0000558c2b4d87c8>
/home/zammad/db/migrate/20191107050249_issue_2460_fix_corrupted_twitter_ids.rb:18:in `block in up'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/home/zammad/db/migrate/20191107050249_issue_2460_fix_corrupted_twitter_ids.rb:5:in `up'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:817:in `exec_migration'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1345:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1036:in `up'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1011:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Caused by:
NoMethodError: private method `blank?' called for #<Twitter::REST::Client:0x0000558c2b4d87c8>
/home/zammad/db/migrate/20191107050249_issue_2460_fix_corrupted_twitter_ids.rb:18:in `block in up'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
/home/zammad/db/migrate/20191107050249_issue_2460_fix_corrupted_twitter_ids.rb:5:in `up'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:817:in `exec_migration'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1345:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1036:in `up'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/migration.rb:1011:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by thorsteneckel** [comment]
Thanks @BertrandGouny for reporting this! Working on a fix 🚀

**Comment by thorsteneckel** [comment]
Hi @BertrandGouny - please try again with latest stable.

**Comment by BertrandGouny** [comment]
@thorsteneckel no error with the new fix, thanks :)
