### ISSUE TITLE
websocket-server will not start 

### ISSUE THREAD

**Issue by ruben-herold** [zammad/zammad#2926]
hi,

i installed zammad on a fresh centos 8 system. I used the rpms from:

``
https://dl.packager.io/srv/rpm/zammad/zammad/stable/el/8/$basearch
``
Ist version:
``
bash-4.4# rpm -qa |grep zamm
zammad-3.2.0-1580110414.992e734c.centos8.x86_64
``

The websocket-server will not start it dies directy after start:

```
Feb 10 23:57:11 zammad systemd[1]: Started zammad-websocket-1.service.
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]: bundler: failed to load command: script/websocket-server.rb (script/websocket-server.rb)
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]: RuntimeError: no acceptor (port is in use or requires root privileges)
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]:  /opt/zammad/vendor/bundle/ruby/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_tcp_server'
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]:  /opt/zammad/vendor/bundle/ruby/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_server'
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]:  /opt/zammad/vendor/bundle/ruby/2.5.0/gems/em-websocket-0.5.1/lib/em-websocket/websocket.rb:46:in `run'
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]:  /opt/zammad/vendor/bundle/ruby/2.5.0/gems/em-websocket-0.5.1/lib/em-websocket/websocket.rb:39:in `block in start'
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]:  /opt/zammad/vendor/bundle/ruby/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:171:in `run'
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]:  /opt/zammad/vendor/bundle/ruby/2.5.0/gems/em-websocket-0.5.1/lib/em-websocket/websocket.rb:35:in `start'
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]:  script/websocket-server.rb:123:in `block in <top (required)>'
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]:  /opt/zammad/vendor/bundle/ruby/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]:  /opt/zammad/vendor/bundle/ruby/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]:  script/websocket-server.rb:122:in `<top (required)>'
Feb 10 23:57:24 zammad systemd[1]: zammad-websocket-1.service: Main process exited, code=exited, status=1/FAILURE
Feb 10 23:57:24 zammad systemd[1]: zammad-websocket-1.service: Failed with result 'exit-code'.
Feb 10 23:57:24 zammad systemd[1]: zammad-websocket-1.service: Service RestartSec=100ms expired, scheduling restart.
Feb 10 23:57:24 zammad systemd[1]: zammad-websocket-1.service: Scheduled restart job, restart counter is at 36.

```

On port 6042 nothing is listening:

```
bash-4.4# netstat -lnp
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1144/nginx: master  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1304/sshd           
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      865/puma 3.12.2 (tc 
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1111/postmaster     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1108/exim           
tcp6       0      0 127.0.0.1:9200          :::*                    LISTEN      1390/java           
tcp6       0      0 ::1:9200                :::*                    LISTEN      1390/java           
tcp6       0      0 :::80                   :::*                    LISTEN      1144/nginx: master  
tcp6       0      0 127.0.0.1:9300          :::*                    LISTEN      1390/java           
tcp6       0      0 ::1:9300                :::*                    LISTEN      1390/java           
tcp6       0      0 :::22                   :::*                    LISTEN      1304/sshd           
tcp6       0      0 ::1:5432                :::*                    LISTEN      1111/postmaster     
tcp6       0      0 ::1:25                  :::*                    LISTEN      1108/exim           
udp        0      0 127.0.0.1:323           0.0.0.0:*                           886/chronyd         
udp6       0      0 ::1:323                 :::*                                886/chronyd         
raw6       0      0 :::58                   :::*                    7           1064/NetworkManager 
Aktive Sockets in der UNIX Domäne (Nur Server)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Pfad
unix  2      [ ACC ]     STREAM     HÖRT         297      1/systemd            /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     HÖRT         24820    1111/postmaster      /tmp/.s.PGSQL.5432
unix  2      [ ACC ]     SEQPACKET  HÖRT         17723    1/systemd            /run/systemd/coredump
unix  2      [ ACC ]     SEQPACKET  HÖRT         17762    1/systemd            /run/udev/control
unix  2      [ ACC ]     STREAM     HÖRT         26422    1337/sshd: rcsadmin  /tmp/ssh-GQmazgCE1g/agent.1337
unix  2      [ ACC ]     STREAM     HÖRT         17821    1/systemd            /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     STREAM     HÖRT         24756    1111/postmaster      /var/run/postgresql/.s.PGSQL.5432
unix  2      [ ACC ]     STREAM     HÖRT         17641    1/systemd            /run/systemd/private
unix  2      [ ACC ]     STREAM     HÖRT         26353    1328/systemd         /run/user/1001/systemd/private
unix  2      [ ACC ]     STREAM     HÖRT         26360    1328/systemd         /run/user/1001/bus
unix  2      [ ACC ]     STREAM     HÖRT         20733    1/systemd            /run/dbus/system_bus_socket
Active Bluetooth connections (Nur Server)
Proto  Destination       Source            State         PSM DCID   SCID      IMTU    OMTU Security
Proto  Destination       Source            State     Channel
bash-4.4# 
```

**Comment by ruben-herold** [comment]
hi,

using the files :+1: 

script/websocket-server.rb
spec/scripts/websocket_server_spec.rb

from master and add 

export ZAMMAD_BIND_IP='[::1]'

to /etc/zammad/conf.d/other

all services started and listening on the ipv6 address. I changed my nginx config an all runs fine now.
If i try with the new files but without the [::1] it failed like before.

**Comment by MrGeneration** [comment]
Glad you could solve your issue.
For the next time, please use the Community for technical questions and/or feature requests. :)

( https://community.zammad.org )

Thank you.

**Comment by ruben-herold** [comment]
@MrGeneration  what?? I have no solution only a workaround.The default (127.0.0.1) is still not working. Also not with the new files. I used only [::1] as workaround... So from my view still a bug.

**Comment by MrGeneration** [comment]
Still, this is a technical question.
Puma is by default not listening on IPv6.

**Comment by ruben-herold** [comment]
@MrGeneration  as clarification. This is not about Ipv6. 

We have here an centos 8 installation via rpm.
The websocket don't start if it is configured to listen to 127.0.0.1 as it is by default.
error Message and so on above. 

I saw that there was changes in the git so I merged this changes to my local installation.
After this nothing changed. 

If I switch to  ipv6 all is running fine. 

So for me it is a bug that the websocket don't start o centos 8 if it tries to bind to 127.0.0.1 doesn't matter which port. 

This should be fixed!

3.2.0:     websocket don't work with 127.0.0.1 on centos 8
master:   websocket don't work with 127.0.0.1 on centos 8
master: websocket  work with [::1] on centos 8

So this should be investigated and fixed.
For me a bug and this issue should be reopend

**Comment by MrGeneration** [comment]
Please move over to the community!
This is **not a bug but a configuration issue** and thus a technical question!

Your issue basically is: `Feb 10 23:57:24 zammad zammad-websocket-1.service[11987]: RuntimeError: no acceptor (port is in use or requires root privileges)`

So the issue is that you cannot use the port on IPv4 for whatever reason.
Ignoring the fact, that we officially don't support CentOS8 as of yet ( https://docs.zammad.org/en/latest/install/centos.html )


Beside of that ....
For my own entertainment I installed a basic centos installation and followed our documentation and do not have any issues on using and installing Zammad.

I had to solve dependency issues that are solvable, because the package installer tells me what it needs. So sorry, this is a technical question, no bug and Github is thus the wrong place.

If you prove me wrong ***on the community*** I'll gladly reopen this issue.


```
[root@localhost ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```
