### ISSUE TITLE
StatusCode: 500 and undefined method `lookup'

### ISSUE THREAD

**Issue by externalservices** [zammad/zammad#2966]
### Infos:

* Used Zammad version: 3.3.0
* Installation method (source, package, ..): helm chart 2.1.0
* Operating system: GKE
* Database + version: Postgresql 11.7
* Elasticsearch version: 7.6.1
* Browser + version: Chrome  80.0.3987.132 + Firefox 74.0

### Expected behavior:

* I'm able to login into my zammad instance via web Gui

### Actual behavior:

* When I try to login I only get a error message saying "StatusCode: 500" and "{"error":"Error ID TrF1G3uK: Please contact your administrator."} - the error id value is changing.
this does not depend on the user I'm trying to login.

### Steps to reproduce the behavior:

* I've upgraded from zammad 3.2 (helm chart 1.2.1) to 3.3 (helm chart 2.1.0) by basically following the upgrade steps at https://github.com/zammad/zammad-helm/tree/master/zammad

which were:
- dumped postgresql db to a file - also backed up complete content from /opt/zammad directory 
 on the railsserver (no problems so far)
- uninstalled helm chart (also removed all pvc's)(no problems so far)
- installed new helm chart version (worked well and all pods came up without issues)
- logged into the postgresql pod, and imported my previously generated dump using psql (worked well after dropping / creating my zammad database)
- did NOT restore any content to /opt/zammad on the railsserver
- restarted zammad railsserver

in the first instance, the railsserver starts without any issues or error logs.
Once I try to login it get the said "StatusCode: 500" error in the browser and the railsserver logs says:
```
E, [2020-03-10T12:58:29.993489 #1-46919508994840] ERROR -- : undefined method `lookup' for #<Class:0x000055589900fbf8> (NoMethodError)
/usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/opt/zammad/app/models/application_model/can_assets.rb:153:in `block in assets_of_object_list'
/opt/zammad/app/models/application_model/can_assets.rb:151:in `each'
/opt/zammad/app/models/application_model/can_assets.rb:151:in `assets_of_object_list'
/opt/zammad/app/models/online_notification/assets.rb:43:in `assets'
/opt/zammad/app/controllers/sessions/collection_base.rb:16:in `block in session'
/usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/app/controllers/sessions/collection_base.rb:15:in `session'
/opt/zammad/lib/session_helper.rb:24:in `block in default_collections'
/opt/zammad/lib/session_helper.rb:22:in `each'
/opt/zammad/lib/session_helper.rb:22:in `default_collections'
/opt/zammad/lib/session_helper.rb:3:in `json_hash'
/opt/zammad/app/controllers/sessions_controller.rb:15:in `create'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/abstract_controller/base.rb:194:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:18:in `block (4 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:180:in `subscribed'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:17:in `block (3 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:180:in `subscribed'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:16:in `block (2 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/abstract_controller/base.rb:134:in `process'
/usr/local/bundle/gems/actionview-5.2.4.1/lib/action_view/rendering.rb:32:in `process'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_controller/metal.rb:191:in `dispatch'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_controller/metal.rb:252:in `dispatch'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/journey/router.rb:35:in `each'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/journey/router.rb:35:in `serve'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/routing/route_set.rb:840:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:420:in `call_app!'
/usr/local/bundle/gems/omniauth-saml-1.10.1/lib/omniauth/strategies/saml.rb:89:in `other_phase'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:190:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call'
/usr/local/bundle/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/bundle/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'
/usr/local/bundle/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/local/bundle/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/bundle/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:28:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
/usr/local/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:524:in `call'
/usr/local/bundle/gems/puma-3.12.4/lib/puma/configuration.rb:227:in `call'
/usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:675:in `handle_request'
/usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:476:in `process_client'
/usr/local/bundle/gems/puma-3.12.4/lib/puma/server.rb:334:in `block in run'
/usr/local/bundle/gems/puma-3.12.4/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
/usr/local/bundle/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2020-03-10T12:58:29.994029 #1-46919508994840] ERROR -- : Error ID O3woz_Ji: undefined method `lookup' for #<Class:0x000055589900fbf8>
I, [2020-03-10T12:58:29.994415 #1-46919508994840]  INFO -- : Completed 500 Internal Server Error in 364ms (Views: 0.2ms | ActiveRecord: 46.7ms)
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry for the wait, this went below my radar.
The error ID within the traceback and the error id in above mentioned error message to not match.

Please ensure that this is the same cause.
Please also try again with a current Zammad 3.5 as 3.3 and 3.4 are prune to security issues.

**Comment by MrGeneration** [comment]
As I haven't heard back and currently can't reproduce the described issue, I'll be closing this.
If you require technical assistance, please consult the Zammad community at https://community.zammad.org

In case you require commercial grade support, our support contracts may also help: https://zammad.com/pricing#selfhosted
