### ISSUE TITLE
/api/v1/available should not use device check because it can be used for not authenticated users

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3046]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Calling `/api/v1/available` should not require a valid user session, becuase its used to not authenticated users too.

### Actual behavior:

Calling `/api/v1/available` as will require a valid user session because of `user_device_check`. 

If it's called as nobody and in certain cases it will generate error entries like:

```
I, [2020-05-06T14:38:03.356206 #3920-104986520]  INFO -- : Started GET "/api/v1/available?_=1588673670923" for 170.224.165.5 at 2020-05-06 14:38:03 +0200
I, [2020-05-06T14:38:03.358767 #3920-104986520]  INFO -- : Processing by SessionsController#available as JSON
I, [2020-05-06T14:38:03.358797 #3920-104986520]  INFO -- :   Parameters: {"_"=>"1588673670923"}
E, [2020-05-06T14:38:03.360568 #3920-104986520] ERROR -- : Need fingerprint param! (Exceptions::UnprocessableEntity)
/home/zp_00010710/zammad/app/controllers/application_controller/handles_devices.rb:50:in `user_device_log'
/home/zp_00010710/zammad/app/controllers/application_controller/handles_devices.rb:9:in `user_device_check'
/usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
```

Proposed change:

```
--- a/app/controllers/sessions_controller.rb
+++ b/app/controllers/sessions_controller.rb
@@ -3,7 +3,7 @@
 class SessionsController < ApplicationController
   prepend_before_action -> { authentication_check && authorize! }, only: %i[switch_to_user list delete]
   skip_before_action :verify_csrf_token, only: %i[show destroy create_omniauth failure_omniauth]
-  skip_before_action :user_device_check, only: %i[create_sso]
+  skip_before_action :user_device_check, only: %i[create_sso available]
 
   # "Create" a login, aka "log the user in"
   def create
```

**Comment by mantas** [comment]
@MrGeneration are you still able to reproduce this?

**Comment by MrGeneration** [comment]
Sorry for the delay. I currently no longer can reproduce this.
