### ISSUE TITLE
Receiving Emails fails

### ISSUE THREAD

**Issue by LukasSchulz** [zammad/zammad#3047]
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): package
* Operating system: Debian Buster
* Database + version:
* Elasticsearch version:
* Browser + version: Firefox

### Expected behavior: 
Email gets recieved and processed
*

### Actual behavior:
Email gets received but fails at processing
*

### Steps to reproduce the behavior:
Sending an email to the inbound address
*

Yes I'm sure this is a bug and no feature request or a general question.

Yes, because zammad tells me to file a bug report

Contents of the .eml file:
```X-Envelope-From: <lukas.schulz@xxx.de>
X-Envelope-To: <lukas.schulz@xxx.de>
X-Delivery-Time: 1589019191
X-UID: 6418
Return-Path: <lukas.schulz@xxx.de>
Authentication-Results: strato.com; dmarc=none header.from=xxx.de
Authentication-Results: strato.com; arc=none
Authentication-Results: strato.com; dkim=pass header.d=xxx.de
Authentication-Results: strato.com; dkim-adsp=pass header.from="lukas.schulz@xxx.de"

X-RZG-Expurgate: clean/normal
X-RZG-Expurgate-ID: 149500::1589019191-00006EB9-710ECE1F/0/0
X-RZG-CLASS-ID: mi00
Received-SPF: pass
        (strato.com: domain _spf.strato.com designates 2a01:238:20a:202:5301::2 as permitted sender)
        mechanism=ip6;
        client-ip=2a01:238:20a:202:5301::2;
        helo="mo6-p01-ob.smtp.rzone.de";
        envelope-from="lukas.schulz@xxx.de";
        receiver=smtpin.rzone.de;
        identity=mailfrom;
Received: from mo6-p01-ob.smtp.rzone.de ([IPv6:2a01:238:20a:202:5301::2])
        by smtpin.rzone.de (RZmta 46.6.2 OK)
        with ESMTPS id e02483w49ADBtvD
        (using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256 bits))
        (Client CN "*.smtp.rzone.de", Issuer "TeleSec ServerPass Class 2 CA" (verified OK (+EmiG)))
        (Client hostname verified OK)
        for <lukas.schulz@xxx.de>;
        Sat, 9 May 2020 12:13:11 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; t=1589019191;
        s=strato-dkim-0002; d=xxx.de;
        h=To:Date:Message-Id:Subject:From:X-RZG-CLASS-ID:X-RZG-AUTH:From:
        Subject:Sender;
        bh=u0bRI/iK75oKQtbFDnrZ9pMRZa2U2yA0KJQ/l6ogeDg=;
        b=nDoLKRaI3cmKw3Ffp0AoyRqK57ajVO9/8IuVU4gEPcvAHq9ADpLDPFqDPsthrt7N6y
        ZQXhtNcDbBjQmQ1UBbXbOIYwCcztwo7MWHHCfpL7axfdrbdJpnjI268d8TjE861XdqNL
        X22bpg0hbljxwrFu3ujkejVndZA3ap+f+pr0q5REXUrfsDhfHwAVr1Jbnuz2WrEJJDU9
        pauw1/kM+T/0u+3bHHbmyIwppezsj/m5FMYXiMcuODSTClfx6+58CFvHgRvg4qR2At83
        fXpMidlKEiKl79hORRbLb/lAJyb40DbZHOyP49AkZHjfMgVbGzgG5iJmtICAvJtwDsaE
        lTVA==
X-RZG-AUTH: ":IHkPdFPmaPxFDXBuEzL6+hnpjFkNpHGzBLo5Gl4MhsxXjByrpPZAyVFeMTUeYOYS3kCrqdNQXGH8WLa8kQ=="
X-RZG-CLASS-ID: mo00
Received: from macbook-pro.fritz.box
        by smtp.strato.de (RZmta 46.6.2 DYNA|AUTH)
        with ESMTPSA id f0b420w49ADBzDm
        (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (curve X9_62_prime256v1 with 256 ECDH bits, eq. 3072 bits RSA))
        (Client did not present a certificate)
        for <lukas.schulz@xxx.de>;
        Sat, 9 May 2020 12:13:11 +0200 (CEST)
From: Lukas Schulz <lukas.schulz@xxx.de>
Content-Type: text/plain;
        charset=utf-8
Content-Transfer-Encoding: quoted-printable
Mime-Version: 1.0 (Mac OS X Mail 13.0 \(3608.60.0.2.5\))
Subject: Test Test
Message-Id: <4B14AF69-A074-4860-B008-BA2202B99351@simiworld.de>
Date: Sat, 9 May 2020 12:13:10 +0200
To: Lukas Schulz <lukas.schulz@xxx.de>
X-Mailer: Apple Mail (2.3608.60.0.2.5)

Test Test Test
Lorem Ipsum Dolor Sit Amet.

der 1. Summand der Normalkraft ist wie du richtig beschrieben hast =
gleich der Normalkomponente Fgn (das kommt von der Gewichtskraft Fg). =
Allerdings hast du in dieser Aufgabe noch eine zus=C3=A4tzliche Kraft =
F(rot) mit der die Kiste den Hang hinauf gezogen wird. Ein Teil von =
dieser Kraft tr=C3=A4gt jetzt dementsprechend auch zur Norm=```

**Comment by MrGeneration** [comment]
Please provide the complete traceback from your logfile that told you to do so as well.

**Comment by LukasSchulz** [comment]
Here you go ^^:
```
I, [2020-05-09T12:21:59.691503 #28958-46990493752960]  INFO -- : fetching imap (imap.strato.de/lukas.schulz@xxx.de port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=t
rue)
I, [2020-05-09T12:22:00.244258 #28958-46990493752960]  INFO -- :  - message 1/1
I, [2020-05-09T12:22:00.535892 #28958-46990493752960]  INFO -- : Process email with msgid '<XXX@xxx.de>'
E, [2020-05-09T12:22:00.553716 #28958-46990493752960] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/dabe2d0c6b83d2
509d8167d57926b1e8.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2020-05-09T12:22:00.553847 #28958-46990493752960] ERROR -- : uninitialized constant Channel::Filter::ServiceNowCheck (NameError)
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/inflector/methods.rb:285:in `const_get'/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/inflector/methods.rb:285:in `block in constantize'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/inflector/methods.rb:281:in `each'/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/inflector/methods.rb:281:in `inject'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/inflector/methods.rb:281:in `constantize'/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
/opt/zammad/app/models/channel/email_parser.rb:144:in `block in _process'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/delegation.rb:71:in `each'/opt/zammad/app/models/channel/email_parser.rb:143:in `_process'/opt/zammad/app/models/channel/email_parser.rb:115:in `block in process'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:108:in `timeout'/opt/zammad/app/models/channel/email_parser.rb:114:in `process'
/opt/zammad/app/models/channel/driver/imap.rb:278:in `block in fetch'
/opt/zammad/app/models/channel/driver/imap.rb:213:in `each'
/opt/zammad/app/models/channel/driver/imap.rb:213:in `fetch'/opt/zammad/app/models/channel.rb:56:in `fetch'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'/opt/zammad/app/models/scheduler.rb:287:in `eval'/opt/zammad/app/models/scheduler.rb:287:in `_start_job'/opt/zammad/app/models/scheduler.rb:239:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:237:in `loop'/opt/zammad/app/models/scheduler.rb:237:in `block in start_job'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2020-05-09T12:22:00.686133 #28958-46990493752960]  INFO -- : done
```

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question than a bug.
Looks like your migrations didn't go through completely.

Please consult the community for technical questions: https://community.zammad.org 

If you require commercial grade support, you can also have a look at https://zammad.com/pricing#selfhosted in case you're interested.

Closing now.
