### ISSUE TITLE
Develop: Access to calendar (ical) no longer works if being unauthenticated (Error 500)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3064]
### Infos:

* Used Zammad version: 3.4 (Develop - working in stable 3.3)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Zammads ical calendar functionality will request you to authenticate against Zammad, if you're calling one of the calendar URLs without a valid session. It will then create a session and you'll be able to get calendar information.

### Actual behavior:

If you're not authenticated against Zammad (so no valid session), Zammad will not request you to authenticate when calling an ical URL. Instead it will fail with error 500 (see traceback below).

*Note:* All calendar urls will work without issue if you're already authenticated (so e.g. in the same browser you're logged in to Zammad).

Martin suspects the latest raise on Pundit in develop to be the fault here.

**affected urls:**
```
/ical/tickets
/ical/tickets/escalation
/ical/tickets/new_open
/ical/tickets/pending
```

**Traceback:**
```
I, [2020-05-22T15:15:31.218632 #1258-80737120]  INFO -- : Started GET "/ical/tickets" for 666.6666.666.666 at 2020-05-22 15:15:31 +0200
I, [2020-05-22T15:15:31.235288 #1258-80737120]  INFO -- : Processing by CalendarSubscriptionsController#object as HTML
I, [2020-05-22T15:15:31.235412 #1258-80737120]  INFO -- :   Parameters: {"object"=>"tickets"}
I, [2020-05-22T15:15:31.236065 #1258-80737120]  INFO -- : authentication failed (Exceptions::NotAuthorized)
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/delegate.rb:85:in `call'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/delegate.rb:85:in `method_missing'
/opt/zammad/app/controllers/application_controller/authorizes.rb:42:in `permissions!'
/opt/zammad/app/policies/controllers/application_controller_policy.rb:21:in `method_missing'
/usr/local/rvm/gems/ruby-2.6.5/gems/pundit-2.0.1/lib/pundit.rb:221:in `public_send'
/usr/local/rvm/gems/ruby-2.6.5/gems/pundit-2.0.1/lib/pundit.rb:221:in `authorize'
/opt/zammad/app/controllers/application_controller/authorizes.rb:8:in `authorize!'
/opt/zammad/app/controllers/calendar_subscriptions_controller.rb:3:in `block in <class:CalendarSubscriptionsController>'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:426:in `instance_exec'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `each'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:107:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:134:in `process'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionview-5.2.4.3/lib/action_view/rendering.rb:32:in `process'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:191:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:252:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `each'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `serve'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:420:in `call_app!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-saml-1.10.1/lib/omniauth/strategies/saml.rb:89:in `other_phase'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:190:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/conditional_get.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/railtie.rb:190:in `public_send'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/railtie.rb:190:in `method_missing'
/usr/local/rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/configuration.rb:227:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/server.rb:675:in `handle_request'
/usr/local/rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/server.rb:476:in `process_client'
/usr/local/rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/server.rb:334:in `block in run'
/usr/local/rvm/gems/ruby-2.6.5/gems/puma-3.12.4/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
/usr/local/rvm/gems/ruby-2.6.5/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2020-05-22T15:15:31.239393 #1258-80737120]  INFO -- : Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)
```

### Steps to reproduce the behavior:

* login to Zammad
* go to profile -> calendar (you need permissions to view calendars [default])
  * it doesn't matter if you're agent or admin, as long as you do have agent rights
* copy one of the four ical urls
* open your calendar application (needs to support basic auth!)
  * this is the case for:
    * Thunderbird Lightning
    * MacOS Calendar app
* add the Zammad calendar
  * this is the moment where it should ask for credentials, instead Zammad returns Error 500 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mittkkoo** [comment]
Sorry, for the dump question, but how these URL may ever be of some use if you need to authenticate each time? How would an external calendar app read the data? I would expect some secret, but not username & password...
