### ISSUE TITLE
Unable to run "rails" commands (e.g. ES configuration)

### ISSUE THREAD

**Issue by marandus** [zammad/zammad#3084]
### Infos:

* Used Zammad version: 3.3.0
* Installation method (source, package, ..): source
* Operating system: CentOS 8 + RVM Ruby 2.5.5
* Database + version: PostgreSQL 10.6
* Elasticsearch version: 7.7,1 OSS
* Browser + version:

Used Ruby from RVM because of gem version collisions when using the Ruby installed from CentOS repositories. The RVM path is correctly setup, any ruby command uses the version installed via RVM (see stack trace below).

### Expected behavior:

* Run rails commands to setup Zammad with Elasticsearch: e.g. `rails r "Setting.set('es_url', 'http://localhost:9200')"`

### Actual behavior:

* Rails command fails with error message that it is unable to load the "listen" gem.
* For information on installed gems, see attached [Gemfile.lock](https://github.com/zammad/zammad/files/4780899/Gemfile.lock.txt)

```
$ rails r "Setting.set('es_url', 'http://localhost:9200')"
Traceback (most recent call last):
        60: from bin/rails:9:in `<main>'
        59: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
        58: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
        57: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
        56: from /usr/local/rvm/gems/ruby-2.5.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        55: from /usr/local/rvm/gems/ruby-2.5.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        54: from /usr/local/rvm/gems/ruby-2.5.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        53: from /usr/local/rvm/gems/ruby-2.5.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        52: from /usr/local/rvm/gems/ruby-2.5.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        51: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/commands.rb:18:in `<main>'
        50: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/command.rb:46:in `invoke'
        49: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/command/base.rb:69:in `perform'
        48: from /usr/local/rvm/gems/ruby-2.5.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        47: from /usr/local/rvm/gems/ruby-2.5.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        46: from /usr/local/rvm/gems/ruby-2.5.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        45: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/commands/runner/runner_command.rb:29:in `perform'
        44: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        43: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/command/actions.rb:28:in `require_environment!'
        42: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
        41: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
        40: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
        39: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
        38: from /usr/local/rvm/gems/ruby-2.5.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        37: from /usr/local/rvm/gems/ruby-2.5.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        36: from /usr/local/rvm/gems/ruby-2.5.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        35: from /usr/local/rvm/gems/ruby-2.5.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        34: from /usr/local/rvm/gems/ruby-2.5.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        33: from /opt/zammad/config/environment.rb:5:in `<main>'
        32: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
        31: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
        30: from /usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        29: from /usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        28: from /usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        27: from /usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `call'
        26: from /usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each'
        25: from /usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        24: from /usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        23: from /usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        22: from /usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        21: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        20: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
        19: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
        18: from /usr/local/rvm/gems/ruby-2.5.5/gems/railties-5.2.4.1/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
        17: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
        16: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
        15: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
        14: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
        13: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
        12: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
        11: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/i18n_railtie.rb:19:in `block in <class:Railtie>'
        10: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/i18n_railtie.rb:61:in `initialize_i18n'
         9: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/i18n_railtie.rb:61:in `new'
         8: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/evented_file_update_checker.rb:59:in `initialize'
         7: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/core_ext/kernel/reporting.rb:15:in `silence_warnings'
         6: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/core_ext/kernel/reporting.rb:28:in `with_warnings'
         5: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/core_ext/kernel/reporting.rb:15:in `block in silence_warnings'
         4: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/evented_file_update_checker.rb:61:in `block in initialize'
         3: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
         2: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
         1: from /usr/local/rvm/gems/ruby-2.5.5/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/rvm/gems/ruby-2.5.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': Could not load the 'listen' gem. Add `gem 'listen'` to the development group of your Gemfile (LoadError)
```

### Steps to reproduce the behavior:

* Install Zammad from source as described in https://docs.zammad.org/en/latest/install/source.html
* Use Ruby 2.5.5 from RVM
* Try to run any `rails` command inside the Zammad directory

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
@marandus do you have `RAILS_ENV=production` set in your console? Could you try to run after prepending it inline, as in `RAILS_ENV=production rails ....`

**Comment by marandus** [comment]
> 
> 
> @marandus do you have `RAILS_ENV=production` set in your console? Could you try to run after prepending it inline, as in `RAILS_ENV=production rails ....`

Ouch, now I feel dumb... It works perfectly with `RAILS_ENV=production`. Thank you very much!
