### ISSUE TITLE
Zammad can't import specific ISO-2022-JP mails

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3115]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1077341 , #1077607 , #1077341 

### Expected behavior:

Zammad imports ISO-2022-JP without issues.

### Actual behavior:

In some special cases, Zammad can't import mails encoded with ISO-2022-JP.
(you can find samples in above mentioned ticket IDs - anonymized mails usually no longer contain the issue, as the byte order is changed).

In that situations Zammad logs the following:

```
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/aa7e19b4dfa0dc04a4b6b4b35cfff7ee.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<Encoding::InvalidByteSequenceError: \"%\" followed by \" \" on ISO-2022-JP>"
Traceback (most recent call last):
        35: from bin/rails:9:in `<main>'
        34: from /usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
        33: from /usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
        32: from /usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
        31: from /usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        30: from /usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        29: from /usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        28: from /usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        27: from /usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        26: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<main>'
        25: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/command.rb:46:in `invoke'
        24: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/command/base.rb:69:in `perform'
        23: from /usr/local/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        22: from /usr/local/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        21: from /usr/local/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        20: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `perform'
        19: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `eval'
        18: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
        17: from /opt/zammad/app/models/channel/email_parser.rb:481:in `process_unprocessable_mails'
        16: from /opt/zammad/app/models/channel/email_parser.rb:481:in `glob'
        15: from /opt/zammad/app/models/channel/email_parser.rb:482:in `block in process_unprocessable_mails'
        14: from /opt/zammad/app/models/channel/email_parser.rb:117:in `process'
        13: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
        12: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `catch'
        11: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `catch'
        10: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
         9: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
         8: from /opt/zammad/app/models/channel/email_parser.rb:118:in `block in process'
         7: from /opt/zammad/app/models/channel/email_parser.rb:139:in `_process'
         6: from /opt/zammad/app/models/channel/email_parser.rb:81:in `parse'
         5: from /opt/zammad/app/models/channel/email_parser.rb:508:in `force_parts_encoding_if_needed'
         4: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
         3: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/delegate.rb:349:in `each'
         2: from /opt/zammad/app/models/channel/email_parser.rb:508:in `block in force_parts_encoding_if_needed'
         1: from /opt/zammad/app/models/channel/email_parser.rb:515:in `force_single_part_encoding_if_needed'
/opt/zammad/app/models/channel/email_parser.rb:515:in `encode': "%" followed by " " on ISO-2022-JP (Encoding::InvalidByteSequenceError)
        22: from bin/rails:9:in `<main>'
        21: from /usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
        20: from /usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
        19: from /usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
        18: from /usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        17: from /usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        16: from /usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        15: from /usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        14: from /usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        13: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<main>'
        12: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/command.rb:46:in `invoke'
        11: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/command/base.rb:69:in `perform'
        10: from /usr/local/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
         9: from /usr/local/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
         8: from /usr/local/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         7: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `perform'
         6: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `eval'
         5: from /usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
         4: from /opt/zammad/app/models/channel/email_parser.rb:481:in `process_unprocessable_mails'
         3: from /opt/zammad/app/models/channel/email_parser.rb:481:in `glob'
         2: from /opt/zammad/app/models/channel/email_parser.rb:482:in `block in process_unprocessable_mails'
         1: from /opt/zammad/app/models/channel/email_parser.rb:115:in `process'
/opt/zammad/app/models/channel/email_parser.rb:133:in `rescue in process': #<Encoding::InvalidByteSequenceError: "%" followed by " " on ISO-2022-JP> (RuntimeError)
/opt/zammad/app/models/channel/email_parser.rb:515:in `encode'
/opt/zammad/app/models/channel/email_parser.rb:515:in `force_single_part_encoding_if_needed'
/opt/zammad/app/models/channel/email_parser.rb:508:in `block in force_parts_encoding_if_needed'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/delegate.rb:349:in `each'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/opt/zammad/app/models/channel/email_parser.rb:508:in `force_parts_encoding_if_needed'
/opt/zammad/app/models/channel/email_parser.rb:81:in `parse'
/opt/zammad/app/models/channel/email_parser.rb:139:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:118:in `block in process'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:117:in `process'
/opt/zammad/app/models/channel/email_parser.rb:482:in `block in process_unprocessable_mails'
/opt/zammad/app/models/channel/email_parser.rb:481:in `glob'
/opt/zammad/app/models/channel/email_parser.rb:481:in `process_unprocessable_mails'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `eval'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `perform'
/usr/local/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/command/base.rb:69:in `perform'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/command.rb:46:in `invoke'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<main>'
/usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.5/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
bin/rails:9:in `<main>'
```

### Steps to reproduce the behavior:

* have a specific byte sequence of a ISO-2022-JP encoded mail
* try to import it

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I'm afraid we also have this variation:
```
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/82ad4edd7670b9c3ae5a06950b93fb62.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<Encoding::InvalidByteSequenceError: \"$\" followed by \" \" on ISO-2022-JP>"
```

Above mentioned tickets hold information on the affected mails.
