### ISSUE TITLE
Scheduler sometimes doesn't recover from database connection loss

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3149]
### Infos:

* Used Zammad version: 3.4 and earlier
* Installation method (source, package, ..): any, verification however is most reliable on source code installations
* Operating system: any
* Database + version: postgreSQL 10.3 (more specific a remote one on another machine, potentially local machine works too)
* Elasticsearch version: any
* Browser + version: any (not relevant to this issue)
* Ticket-ID: 1076319

### Expected behavior:

The Zammad scheduler is able to recover from situations the database connection gets lost for whatever reason.
If such an incident occurs, Zammad should keep on trying to reconnect without crashing processes.

### Actual behavior:

In very specific situations (which makes this kind of rare) a restarting postgreSQL server (process) can cause Zammads scheduler to crash. This usually happens in a moment Zammad currently does work on the database.

#### Log messages

**production.log**

```
I, [2020-08-05T01:07:24.314920 #13185-272725191980]  INFO -- : 2020-08-05T01:07:24+0200: [Worker(host:mike pid:13185)] Error while reserving job: PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly
: UPDATE "delayed_jobs" SET locked_at = '2020-08-04 23:07:24.313199', locked_by = 'host:mike pid:13185' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2020-08-04 23:07:24.312443' AND (locked_at IS NULL OR locked_at < '2020-08-04 19:07:24.312480') OR locked_by = 'host:mike pid:13185') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
I, [2020-08-05T01:07:24.348672 #13185-272640910780]  INFO -- : Scheduler stopped.
```

**scheduler_err.log**

```
FATAL:  terminating connection due to administrator command
#<Thread:0x0000007eff605a58@/opt/zammad/.rvm/gems/ruby-2.5.5/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
/opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:706:in `set_client_encoding': invalid encoding name: utf8 (PG::Error)
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:706:in `configure_connection'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:266:in `block in reconnect!'
       from /opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:263:in `reconnect!'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `verify!'
       from /opt/zammad/zammad/config/initializers/delayed_jobs_verify_db_connection.rb:7:in `recover_from'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:321:in `rescue in reserve_job'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:315:in `reserve_job'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:311:in `reserve_and_run_one_job'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:213:in `block in work_off'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:212:in `times'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:212:in `work_off'
       from /opt/zammad/zammad/app/models/scheduler.rb:372:in `block (3 levels) in worker'
       from /opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
       from /opt/zammad/zammad/app/models/scheduler.rb:370:in `block (2 levels) in worker'
       from /opt/zammad/zammad/app/models/scheduler.rb:366:in `loop'
       from /opt/zammad/zammad/app/models/scheduler.rb:366:in `block in worker'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
/opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:706:in `set_client_encoding': invalid encoding name: utf8 (PG::Error)
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:706:in `configure_connection'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:266:in `block in reconnect!'
       from /opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/postgresql_adapter.rb:263:in `reconnect!'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `verify!'
       from /opt/zammad/zammad/config/initializers/delayed_jobs_verify_db_connection.rb:7:in `recover_from'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:321:in `rescue in reserve_job'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:315:in `reserve_job'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:311:in `reserve_and_run_one_job'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:213:in `block in work_off'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:212:in `times'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/delayed_job-4.1.7/lib/delayed/worker.rb:212:in `work_off'
       from /opt/zammad/zammad/app/models/scheduler.rb:372:in `block (3 levels) in worker'
       from /opt/zammad/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
       from /opt/zammad/zammad/app/models/scheduler.rb:370:in `block (2 levels) in worker'
       from /opt/zammad/zammad/app/models/scheduler.rb:366:in `loop'
       from /opt/zammad/zammad/app/models/scheduler.rb:366:in `block in worker'
       from /opt/zammad/.rvm/gems/ruby-2.5.5/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

### Steps to reproduce the behavior:

In my test cases I could reproduce this issue if I ensured that the scheduler is really busy (this raises the chance to hit in the right moment). I did that by stopping the scheduler and pump thousands of tickets into Zammad. This causes delayed jobs for Elasticsearch indexing.

Then you can start the scheduler and, as soon as it's happily pumping data between Zammad and the database, you can either:
* kill the db
* cut the network connection
* restart the database server
* OR (my most reliable way to do) `SELECT pg_cancel_backend(pid);` by telling the PID of zammad schedulers db process to shutdown

After further inspections and a lot of waiting the customer could verify that the database server was restarted for an unknown reason. This moment was only 36ms long but was enough to cause Zammads scheduler to stop forever.

```
2020-08-05 01:07:17.623 CEST [5840] LOG:  received smart shutdown request
2020-08-05 01:07:28.276 CEST [22206] LOG:  database system was shut down at 2020-08-05 01:07:25 CEST
Und hier war dei DB dann wieder da:
2020-08-05 01:07:28.312 CEST [22204] LOG:  database system is ready to accept connections
```

This means that if you do not monitor Zammads health, you'll eventually notice this issue way too late, apart from no longer running functions like channel fetching and overview generation.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mschiff** [comment]
One additional note: 
The database was shutting down in the time between
`2020-08-05 01:07:17.623 CEST` and `2020-08-05 01:07:28.276 CEST` and therefore not accepting new connections in this timeframe

**Comment by thorsteneckel** [comment]
@mantas analysed the current implementation of the scheduler. Unfortunately the current implementation expects and requires a database connection at various places. One example: Whenever a Job fails (e.g. because of a lost DB connection) the Job record in the DB gets updated with information regarding the error. This fails again and causes the whole scheduler process to crash. There are more places like this.
Therefore we propose to install a watchdog process to automatically restart the scheduler whenever the processes crashes. This can only be a workaround for sure. However, rewriting the whole Scheduler would take 2-3 weeks of intense work on critical parts of the application including breaking changes. Therefore we postpone it for now.

**Comment by mantas** [comment]
Scheduler / Background Services refactoring should have fixed this
