### ISSUE TITLE
Endpoint api/v1/ticket_articles/by_ticket ignores X-On-Behalf-Of 

### ISSUE THREAD

**Issue by SniperSister** [zammad/zammad#3186]
### Infos:

* Used Zammad version: 3.4.x
* Installation method (source, package, ..): debian package
* Operating system: Debian 9
* Database + version:
* Elasticsearch version:
* Browser + version: 
* Ticket: 1079071

### Expected behavior:
* Querying the api/v1/ticket_articles/by_ticket endpoint with an admin-users API token and an X-On-Behalf-Of header set to the ID of the tickets' customer will return the list of articles

### Actual behavior:
* 401 returned

### Steps to reproduce the behavior:
* Create a ticket for a customer and add articles
* Make an API request using a personal access token of an admin to the mentioned endpoint: articles returned
* Set the X-On-Behalf-Of header to the id of the customer: unauthorized
* Make the API request directly as the customer (i.e. by using the basic auth login): articles returned

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Fitting error log output is this:

```
I, [2020-09-08T10:43:10.254245 #27859-85472740]  INFO -- : not allowed to show? this #<Ticket id: 77, group_id: 2, priority_id: 2, state_id: 1, organization_id: nil, number: "83077", title: "Help", owner_id: 1, customer_id: 40, note: nil, first_response_at: nil, first_re
sponse_escalation_at: nil, first_response_in_min: nil, first_response_diff_in_min: nil, close_at: nil, close_escalation_at: nil, close_in_min: nil, close_diff_in_min: nil, update_escalation_at: nil, update_in_min: nil, update_diff_in_min: nil, last_contact_at: "2020-08-2
6 08:55:44", last_contact_agent_at: nil, last_contact_customer_at: "2020-08-26 08:55:44", last_owner_update_at: nil, create_article_type_id: 11, create_article_sender_id: 2, article_count: 1, escalation_at: nil, pending_time: nil, type: nil, time_unit: nil, preferences:
{}, updated_by_id: 40, created_by_id: 40, created_at: "2020-08-26 08:55:44", updated_at: "2020-08-26 08:55:44", test: ""> (Pundit::NotAuthorizedError)
/usr/local/rvm/gems/ruby-2.6.5/gems/pundit-2.0.1/lib/pundit.rb:221:in `authorize'
/opt/zammad/app/controllers/application_controller/authorizes.rb:8:in `authorize!'
/opt/zammad/app/controllers/tickets_controller.rb:58:in `show'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:194:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:18:in `block (4 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:180:in `subscribed'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:17:in `block (3 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:180:in `subscribed'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:16:in `block (2 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:134:in `process'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionview-5.2.4.3/lib/action_view/rendering.rb:32:in `process'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:191:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:252:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `each'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `serve'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:420:in `call_app!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-saml-1.10.1/lib/omniauth/strategies/saml.rb:89:in `other_phase'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:190:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/railtie.rb:190:in `public_send'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-5.2.4.3/lib/rails/railtie.rb:190:in `method_missing'
/usr/local/rvm/gems/ruby-2.6.5/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
/usr/local/rvm/gems/ruby-2.6.5/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
/usr/local/rvm/gems/ruby-2.6.5/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
/usr/local/rvm/gems/ruby-2.6.5/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
/usr/local/rvm/gems/ruby-2.6.5/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
/usr/local/rvm/gems/ruby-2.6.5/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2020-09-08T10:43:10.254422 #27859-85472740]  INFO -- : Exceptions::NotAuthorized (Exceptions::NotAuthorized)
I, [2020-09-08T10:43:10.254787 #27859-85472740]  INFO -- : Completed 401 Unauthorized in 28ms (Views: 0.1ms | ActiveRecord: 13.0ms)
```

**Comment by MrGeneration** [comment]
This also affects ticket article creation as mentioned on issue #3192
