### ISSUE TITLE
DataPrivacyTask - Can't remove user if still referenced in Overview(s)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3220]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-Number: ~~1079746~~

### Expected behavior:

You can remove any user, no matter the references the user does have. 

### Actual behavior:

If you have a user referenced within an overview Zammad is not able to remove the user in question and fails the deletion task. 
The only thing that's left over is the user in question.

![image](https://user-images.githubusercontent.com/6549061/94428139-7f719280-0190-11eb-971e-7f4c2da140f4.png)

#### Workaround:
This issue can be workaround in two ways:

*the easy way:*
Find the overview that blocks your user from being removed and remove the user from that overview. Create a new tasks to retry.

*the harder way (console):* 
Take the referenced user ID from the user in question (in my case `6`)
   * Find all affected overviews by name: 
      `Overview.joins(:users).where(users: { id: 6 }).pluck(:name)`
       * returns: `=> ["Escalated"]`
   * Remove user from affected overviews: 
      `Overview.find_by(name: 'Escalated').users.delete(6)`
   * re-schedule DataPrivacy tasks that failed: 
      `DataPrivacyTask.where(state: 'failed').each {|task| task.preferences.update(error: ''); task.update(state: 'in process') }`
   * Clear cache if you experience the UI showing old information (should clear itself within 10 minutes): 
      `Cache.clear`

*kudos to Mantas for giving me the correct methods that are needed for above*

#### Traceback: 
```
E, [2020-09-28T13:40:04.475115 #1224-4766120] ERROR -- : PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates f
oreign key constraint "fk_rails_a217c968b0" on table "overviews_users"
DETAIL:  Key (id)=(6) is still referenced from table "overviews_users".
: DELETE FROM "users" WHERE "users"."id" = $1 (ActiveRecord::InvalidForeignKey)
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `async_exe
c'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `block (2
levels) in exec_no_cache'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurre
nt_loads'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:610:in `block in
exec_no_cache'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 le
vels) in log'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in lo
g'

/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_no_c
ache'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `execute_a
nd_clear'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:94:in
 `exec_delete'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:176:in
`delete'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `delete'
/usr/local/rvm/gems/ruby-2.6.6/gems/composite_primary_keys-11.2.0/lib/composite_primary_keys/persistence.rb:56:in `_delete_record'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:681:in `_delete_row'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:677:in `destroy_row'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/counter_cache.rb:196:in `destroy_row'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/locking/optimistic.rb:109:in `destroy_row'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:341:in `destroy'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/callbacks.rb:323:in `block in destroy'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:132:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:816:in `_run_destroy_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/callbacks.rb:323:in `destroy'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:305:in `block in destroy'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning
_status'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in
`block in transaction'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block i
n within_new_transaction'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_
new_transaction'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in
`transaction'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:305:in `destroy'
/opt/zammad/app/models/data_privacy_task.rb:30:in `perform'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:70:in `each'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:70:in `block in find_each'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:222:in `loop'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:222:in `in_batches'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:69:in `find_each'
/opt/zammad/app/jobs/data_privacy_task_job.rb:5:in `perform'
/usr/local/rvm/gems/ruby-2.6.6/gems/activejob-5.2.4.4/lib/active_job/execution.rb:39:in `block in perform_now'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/zammad/app/jobs/concerns/has_active_job_lock.rb:12:in `block (2 levels) in <module:HasActiveJobLock>'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/i18n-1.8.3/lib/i18n.rb:308:in `with_locale'
/usr/local/rvm/gems/ruby-2.6.6/gems/activejob-5.2.4.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/activejob-5.2.4.4/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/rvm/gems/ruby-2.6.6/gems/activejob-5.2.4.4/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/usr/local/rvm/gems/ruby-2.6.6/gems/activejob-5.2.4.4/lib/active_job/logging.rb:46:in `block in tag_logger'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/tagged_logging.rb:71:in `tagged'
/usr/local/rvm/gems/ruby-2.6.6/gems/activejob-5.2.4.4/lib/active_job/logging.rb:46:in `tag_logger'
/usr/local/rvm/gems/ruby-2.6.6/gems/activejob-5.2.4.4/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/activejob-5.2.4.4/lib/active_job/execution.rb:38:in `perform_now'
/usr/local/rvm/gems/ruby-2.6.6/gems/activejob-5.2.4.4/lib/active_job/execution.rb:18:in `perform_now'
(irb):2:in `rescue in irb_binding'
(irb):2:in `irb_binding'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb/workspace.rb:85:in `eval'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb/workspace.rb:85:in `evaluate'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb/context.rb:385:in `evaluate'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb.rb:493:in `block (2 levels) in eval_input'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb.rb:647:in `signal_status'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb.rb:490:in `block in eval_input'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `loop'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `catch'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb.rb:489:in `eval_input'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb.rb:428:in `block in run'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb.rb:427:in `catch'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb.rb:427:in `run'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/irb.rb:383:in `start'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.4.4/lib/rails/commands/console/console_command.rb:64:in `start'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.4.4/lib/rails/commands/console/console_command.rb:19:in `start'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.4.4/lib/rails/commands/console/console_command.rb:96:in `perform'
/usr/local/rvm/gems/ruby-2.6.6/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.6.6/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/rvm/gems/ruby-2.6.6/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.4.4/lib/rails/command/base.rb:69:in `perform'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.4.4/lib/rails/command.rb:46:in `invoke'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_wit
h_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsna
p_lfi'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
bin/rails:9:in `<main>'
I, [2020-09-28T13:40:04.491420 #1224-4766120]  INFO -- : Performed DataPrivacyTaskJob (Job ID: 66b6ea21-5111-41ef-8bcc-c37719a6609f) f
rom DelayedJob(default) in 773.37ms
```

### Steps to reproduce the behavior:

* create a user (e.g. agent)
* restrict the overview to the user in question
    ![image](https://user-images.githubusercontent.com/6549061/94428590-366e0e00-0191-11eb-8075-9363ed1a95f0.png)
* try to remove the user via data privacy task

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Hi @KoJie , this is fixed now.
