### ISSUE TITLE
OTRS Migration with merged tickets fails

### ISSUE THREAD

**Issue by delphi-sucks** [zammad/zammad#3232]
### Infos:

* Used Zammad version: 3.5.0-1601452467.437a9ac8.xenial
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 16.04.7 LTS
* Database + version: MySQL 5.7
* Elasticsearch version: 7.9.2
* Browser + version: Not applicable

### Expected behavior:

Ticket gets imported with the articles.

### Actual behavior:

Import fails with:
`ERROR: Can't extract customer from Article`

### Steps to reproduce the behavior:

1. Setup an OTRS instance
2. Create 2 Tickets
3. Merge one ticket with the other
4. Migrate from OTRS to Zammad via Command Line
=> `ERROR: Can't extract customer from Article` for merged ticket

### Cause

The cause is the missing "a_from"-Value for the article in OTRS.
Under normal circumstances the DB-field a_from in article would not be empty, but when merged a_from is empty and Zammad tries to find/create a user with the email "" (empty), which causes the import for the ticket to fail.

**Comment by MrGeneration** [comment]
Do you happen to have a full traceback of the issue? This may help to find the part within the code.

**Comment by delphi-sucks** [comment]
The stacktrace for the moment when the error gets logged would be:
```
/opt/zammad/lib/import/otrs/article_customer.rb:6:in `initialize'
/opt/zammad/lib/import/base_factory.rb:34:in `new'
/opt/zammad/lib/import/base_factory.rb:34:in `create_instance'
/opt/zammad/lib/import/base_factory.rb:10:in `block in import_action'
/opt/zammad/lib/import/base_factory.rb:38:in `each'
/opt/zammad/lib/import/base_factory.rb:38:in `import_loop'
/opt/zammad/lib/import/base_factory.rb:7:in `import_action'
/opt/zammad/lib/import/otrs/ticket.rb:36:in `import'
/opt/zammad/lib/import/otrs/ticket.rb:30:in `initialize'
/opt/zammad/lib/import/base_factory.rb:34:in `new'
/opt/zammad/lib/import/base_factory.rb:34:in `create_instance'
/opt/zammad/lib/import/base_factory.rb:10:in `block in import_action'
/opt/zammad/lib/import/base_factory.rb:38:in `each'
/opt/zammad/lib/import/base_factory.rb:38:in `import_loop'
/opt/zammad/lib/import/base_factory.rb:7:in `import_action'
/opt/zammad/lib/import/otrs.rb:146:in `import_action'
/opt/zammad/lib/import/otrs.rb:135:in `imported?'
/opt/zammad/lib/import/otrs.rb:99:in `block (3 levels) in threaded_import'
/opt/zammad/lib/import/otrs.rb:93:in `loop'
/opt/zammad/lib/import/otrs.rb:93:in `block (2 levels) in threaded_import'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

Let me know if this isn't enough additional information.

**Comment by delphi-sucks** [comment]
Well, got something better for you:
```
#<Thread:0x0000561b8f405e10@/opt/zammad/vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        54: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
        53: from /opt/zammad/lib/import/otrs.rb:93:in `block (2 levels) in threaded_import'
        52: from /opt/zammad/lib/import/otrs.rb:93:in `loop'
        51: from /opt/zammad/lib/import/otrs.rb:99:in `block (3 levels) in threaded_import'
        50: from /opt/zammad/lib/import/otrs.rb:135:in `imported?'
        49: from /opt/zammad/lib/import/otrs.rb:146:in `import_action'
        48: from /opt/zammad/lib/import/base_factory.rb:7:in `import_action'
        47: from /opt/zammad/lib/import/base_factory.rb:38:in `import_loop'
        46: from /opt/zammad/lib/import/base_factory.rb:38:in `each'
        45: from /opt/zammad/lib/import/base_factory.rb:10:in `block in import_action'
        44: from /opt/zammad/lib/import/base_factory.rb:34:in `create_instance'
        43: from /opt/zammad/lib/import/base_factory.rb:34:in `new'
        42: from /opt/zammad/lib/import/otrs/ticket.rb:30:in `initialize'
        41: from /opt/zammad/lib/import/otrs/ticket.rb:36:in `import'
        40: from /opt/zammad/lib/import/base_factory.rb:7:in `import_action'
        39: from /opt/zammad/lib/import/base_factory.rb:38:in `import_loop'
        38: from /opt/zammad/lib/import/base_factory.rb:38:in `each'
        37: from /opt/zammad/lib/import/base_factory.rb:10:in `block in import_action'
        36: from /opt/zammad/lib/import/base_factory.rb:34:in `create_instance'
        35: from /opt/zammad/lib/import/base_factory.rb:34:in `new'
        34: from /opt/zammad/lib/import/otrs/article_customer.rb:7:in `initialize'
        33: from /opt/zammad/lib/import/otrs/article_customer.rb:49:in `import'
        32: from /opt/zammad/lib/import/otrs/article_customer.rb:55:in `find_or_create'
        31: from /opt/zammad/lib/import/otrs/article_customer.rb:60:in `create'
        30: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:36:in `create'
        29: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/suppressor.rb:44:in `save'
        28: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:309:in `save'
        27: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
        26: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:310:in `block in save'
        25: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
        24: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
        23: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
        22: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
        21: from /opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
        20: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
        19: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
        18: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
        17: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
        16: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:46:in `save'
        15: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:84:in `perform_validations'
        14: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:67:in `valid?'
        13: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.4/lib/active_model/validations.rb:339:in `valid?'
        12: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.4/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
        11: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
        10: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
         9: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `invoke_before'
         8: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `each'
         7: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
         6: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:199:in `block in halting'
         5: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:605:in `block in default_terminator'
         4: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:605:in `catch'
         3: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
         2: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
         1: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/opt/zammad/app/models/user.rb:974:in `ensure_identifier': Minimum one identifier (login, firstname, lastname, phone or email) for user is required. (Exceptions::UnprocessableEntity)
```

This should probably help quite a bit.

**Comment by MrGeneration** [comment]
Mucho better. :)

Thanks!

**Comment by delphi-sucks** [comment]
Found the problem, which was because of my configuration;

The MySQL setting `max_allowed_packet` was not big enough which resulted in some threads crashing because of really big attachments.
By coincidence the tickets I checked were all merged tickets, so yeah...

### Workaround

My recommendation for anyone having similar problems:

#### MySQL max_allowed_packet

Edit die MySQL-Config für the max_allowed_packet to double of your biggest attachment size (was necessary for me):
`/etc/mysql/my.cnf`
```
[mysqld]
max_allowed_packet=128M
```

#### Only 1 Thread

The import _may_ take a bit longer (not too much for me), but you don't continue with crashed threads which results in only 7/8 of imported tickets.

Change the following line in `zammad/lib/import/otrs.rb`:
```
thread_count = args[:threads] || 8
```
to
```
thread_count = 1
```

_Is probably more easy, but don't know how and had no time_

@MrGeneration The original problem was my mistake, but the problem with the crashing thread may be worth looking at. Otherwise just close the issue.

**Comment by MrGeneration** [comment]
If you're talking about the crashing import process, as far as I'm aware, this is intended.
The root cause is a configuration issue.

The import should succeed without crashing if everything is configured correctly.
If it doesn't, this is in my opinion an independent issue. :-)
