### ISSUE TITLE
SQL query in privacy job fails

### ISSUE THREAD

**Issue by drbw** [zammad/zammad#3290]
### Infos:

* Used Zammad version: 3.6.0-1, BUT this happened with 3.5.0-8 - created job yesterday, didn't notice it failed, upgraded over night
* Installation method (source, package, ..): Docker
* Operating system: CentOS 7
* Database + version: Postgres 9.6
* Elasticsearch version: 7.9.3
* Browser + version: Firefox 82.0.2

### Expected behavior:

* GDPR job works as advertised and deletes users
* Failed jobs can be sensibly handled (e. g. deleted if they failed before doing anything)
* Useful error messages are generated

### Actual behavior:

* Job failed for an auto-generated user
* Job cannot be deleted and is not retried
* Zammad appears to be permanently unhealthy now

### Steps to reproduce the behavior:

* I'm not sure if this is reproducible and can't try because there's no way to remove the failed jobs.
* In our case, it was sufficient to created a deletion job for a user which was created automatically. (I. e. just a mail address.)
* The user had no tickets, organization, contact data, or anything else but was addressed in mails before.
* The user was a customer.

### Error messages

Rails server log:

```
E, [2020-11-17T15:49:04.502141 #1-70304369417420] ERROR -- : PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"organizations_users"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
 (ActiveRecord::StatementInvalid)
```

Same in the web interface:

![image](https://user-images.githubusercontent.com/35033835/99540023-45ae5280-29af-11eb-9cb9-f6658da4fabf.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @drbw - Thanks for reporting this. Any chance you can provide more from your log file? A traceback would be super helpful. It's currently not clear to me where this query comes from. Doesn't look like any one generated by us at first glance 🤔

**Comment by drbw** [comment]
Oops, yeah, a traceback might be helpful :X

```
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `async_exec'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `block (2 levels) in query'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:62:in `block in query'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `query'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:757:in `column_definitions'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:113:in `columns'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/schema_cache.rb:69:in `columns'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/schema_cache.rb:75:in `columns_hash'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/model_schema.rb:466:in `load_schema!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/attributes.rb:234:in `load_schema!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/model_schema.rb:459:in `block in load_schema'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/model_schema.rb:456:in `load_schema'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/model_schema.rb:346:in `attribute_types'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/model_schema.rb:370:in `type_for_attribute'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/table_metadata.rb:33:in `type'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/predicate_builder.rb:51:in `build'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/predicate_builder.rb:112:in `block in expand_from_hash'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/predicate_builder.rb:71:in `each'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/predicate_builder.rb:71:in `flat_map'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/predicate_builder.rb:71:in `expand_from_hash'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/where_clause_factory.rb:19:in `build'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/query_methods.rb:588:in `where!'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/associations/association_scope.rb:156:in `apply_scope'
/usr/local/bundle/gems/composite_primary_keys-11.2.0/lib/composite_primary_keys/associations/association_scope.rb:37:in `block in last_chain_scope'
/usr/local/bundle/gems/composite_primary_keys-11.2.0/lib/composite_primary_keys/associations/association_scope.rb:35:in `each'
/usr/local/bundle/gems/composite_primary_keys-11.2.0/lib/composite_primary_keys/associations/association_scope.rb:35:in `last_chain_scope'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/associations/association_scope.rb:124:in `add_constraints'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/associations/association_scope.rb:29:in `scope'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/associations/association_scope.rb:7:in `scope'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/associations/association.rb:90:in `association_scope'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/associations/association.rb:79:in `scope'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/associations/collection_association.rb:287:in `scope'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/associations/has_many_association.rb:100:in `delete_or_nullify_all_records'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/associations/collection_association.rb:165:in `delete_all'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/associations.rb:1840:in `destroy_associations'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/persistence.rb:338:in `destroy'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/callbacks.rb:323:in `block in destroy'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:132:in `run_callbacks'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:816:in `_run_destroy_callbacks'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/callbacks.rb:323:in `destroy'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:305:in `block in destroy'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:305:in `destroy'
/opt/zammad/app/models/data_privacy_task.rb:30:in `perform'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:70:in `each'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:70:in `block in find_each'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:222:in `loop'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:222:in `in_batches'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/usr/local/bundle/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:69:in `find_each'
/opt/zammad/app/jobs/data_privacy_task_job.rb:5:in `perform'
/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/execution.rb:39:in `block in perform_now'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/zammad/app/jobs/concerns/has_active_job_lock.rb:12:in `block (2 levels) in <module:HasActiveJobLock>'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/bundle/gems/i18n-1.8.3/lib/i18n.rb:308:in `with_locale'
/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/logging.rb:48:in `tag_logger'
/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/execution.rb:38:in `perform_now'
/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/execution.rb:18:in `perform_now'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:287:in `eval'
/opt/zammad/app/models/scheduler.rb:287:in `_start_job'
/opt/zammad/app/models/scheduler.rb:258:in `block in start_job'
/usr/local/bundle/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by thorsteneckel** [comment]
What's the result when executing `DataPrivacyTask.where(state: 'failed').map(&:perform)` on your [Zammad Rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console)?

**Comment by drbw** [comment]
I just get a [nil] back. `DataPrivacyTask.where(state: 'failed').all ` does list it, though. That _may_ have to do with the fact that the user was manually deleted in the meantime, sorry, forgot to mention that above... the address was a typo of an often-used one and I was required to nuke it. But it doesn't change anything about the task (e.g. run time) it seems and doesn't generate any new error messages.

Is there anything else to try? Otherwise, I'd remove it with the Rails console. DataPrivacyTasks wasn't listed in the searchable models so I didn't know I could do that. (Don't really know Rails.)

**Comment by thorsteneckel** [comment]
I understand. Yes. You can delete it. I'll close this issue then for now. Fingers crossed that it's not happening again 🤞 

If anyone is facing the same issue please do the same things as described above and post your result. We will then continue the investigation 🧐

**Comment by drbw** [comment]
Yeah, at least you have precedent if this happens again. Thanks for the support!
