### ISSUE TITLE
Zendesk import fails if not supported field types are present

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3314]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): any 
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Zammads Zendesk importer skips attributes that it does not support.

### Actual behavior:

A zendesk migration within Zammad will fail, if a attribute type appears it does not support.
An example of this attribute type would be `Multiselect` as an example.

### Steps to reproduce the behavior:

* Import not supported attribute fields from Zendesk to Zammad

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
For me this is a bug, because it blocks the complete import.

```
E, [2020-11-30T15:20:16.370695 #18370-92112440] ERROR -- : ImportJob 'Import::Zendesk' failed: uninitialized constant Import::Zendesk::ObjectAttribute::M
ultiselect
Did you mean?  MultiXml
E, [2020-11-30T15:20:16.370753 #18370-92112440] ERROR -- : uninitialized constant Import::Zendesk::ObjectAttribute::Multiselect
Did you mean?  MultiXml (NameError)
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:285:in `const_get'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:285:in `block in constantize'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:281:in `each'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:281:in `inject'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/inflector/methods.rb:281:in `constantize'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.4/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
/home/zammad/zammad/lib/sequencer/unit/import/zendesk/object_attribute/add.rb:18:in `backend_class'
/home/zammad/zammad/lib/sequencer/unit/import/zendesk/object_attribute/add.rb:13:in `block in process'
/home/zammad/zammad/lib/sequencer/state.rb:45:in `provide'
/home/zammad/zammad/lib/sequencer/unit/import/zendesk/object_attribute/add.rb:12:in `process'
/home/zammad/zammad/lib/sequencer/unit/import/common/model/mixin/skip/action.rb:47:in `process'
/home/zammad/zammad/lib/sequencer/unit/base.rb:249:in `process'
/home/zammad/zammad/lib/sequencer.rb:77:in `block (4 levels) in process'
/home/zammad/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/home/zammad/zammad/lib/sequencer.rb:76:in `block (3 levels) in process'
/home/zammad/zammad/lib/sequencer/state.rb:153:in `process'
/home/zammad/zammad/lib/sequencer.rb:74:in `block (2 levels) in process'
/home/zammad/zammad/lib/sequencer/units.rb:29:in `block in each'
/home/zammad/zammad/lib/sequencer/units.rb:28:in `each'
/home/zammad/zammad/lib/sequencer/units.rb:28:in `each'
/home/zammad/zammad/lib/sequencer.rb:72:in `each_with_index'
/home/zammad/zammad/lib/sequencer.rb:72:in `block in process'
/home/zammad/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/home/zammad/zammad/lib/sequencer.rb:70:in `process'
/home/zammad/zammad/lib/sequencer.rb:25:in `process'
/home/zammad/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:63:in `sub_sequence'
/home/zammad/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:58:in `expected'
/home/zammad/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:49:in `block in process_sub_sequence'
/usr/local/rvm/gems/ruby-2.6.6/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:349:in `block in _all'
/usr/local/rvm/gems/ruby-2.6.6/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:457:in `each'
/usr/local/rvm/gems/ruby-2.6.6/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:457:in `public_send'
/usr/local/rvm/gems/ruby-2.6.6/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:457:in `array_method'
/usr/local/rvm/gems/ruby-2.6.6/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:298:in `method_missing'
/usr/local/rvm/gems/ruby-2.6.6/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:342:in `_all'
/usr/local/rvm/gems/ruby-2.6.6/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:216:in `all!'
/home/zammad/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/base.rb:42:in `public_send'
/home/zammad/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/base.rb:42:in `resource_iteration'
/home/zammad/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:47:in `process_sub_sequence'
/home/zammad/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:31:in `block in process'
/home/zammad/zammad/lib/sequencer/state.rb:45:in `provide'
/home/zammad/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:30:in `process'
/home/zammad/zammad/lib/sequencer/unit/base.rb:249:in `process'
/home/zammad/zammad/lib/sequencer.rb:77:in `block (4 levels) in process'
/home/zammad/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/home/zammad/zammad/lib/sequencer.rb:76:in `block (3 levels) in process'
/home/zammad/zammad/lib/sequencer/state.rb:153:in `process'
/home/zammad/zammad/lib/sequencer.rb:74:in `block (2 levels) in process'
/home/zammad/zammad/lib/sequencer/units.rb:29:in `block in each'
/home/zammad/zammad/lib/sequencer/units.rb:28:in `each'
/home/zammad/zammad/lib/sequencer/units.rb:28:in `each'
/home/zammad/zammad/lib/sequencer.rb:72:in `each_with_index'
/home/zammad/zammad/lib/sequencer.rb:72:in `block in process'
/home/zammad/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/home/zammad/zammad/lib/sequencer.rb:70:in `process'
/home/zammad/zammad/lib/sequencer.rb:25:in `process'
/home/zammad/zammad/lib/import/mixin/sequence.rb:15:in `process'
/home/zammad/zammad/lib/import/zendesk.rb:8:in `start'
/home/zammad/zammad/app/models/import_job.rb:24:in `start'
/home/zammad/zammad/app/jobs/async_import_job.rb:3:in `perform'
```

**Comment by MrGeneration** [comment]
Due to missing logic Thorsten and I agreed on enhancing this part.
The reason why the whole import currently is blocked is the attribute not being importable because it's type is not supported by Zammd.

In future we will log a warning that we ignored the field and continue.
This will cause "data loss" which will be a lot more silent than it is up to now.

Right now you currently have to actively solve this issue by manually removing the attributes in question.
