### ISSUE TITLE
Mentions migration fails because of unexpected User notification_config matrix state.

### ISSUE THREAD

**Issue by mweinelt** [zammad/zammad#3472]
### Infos:

* Used Zammad version: 4.0.0-1616674376.a2954874.buster
* Installation method (source, package, ..): packager.io
* Operating system: Debian 10
* Database + version: Postgresql 11.10
* Elasticsearch version: 7.6.2
* Browser + version: Firefox 87.0

### Expected behavior:

* Upgrading should create all necessary tables during migrations.

### Actual behavior:

* We are missing the mentions table after the latest upgrade and cannot browse our tickets anymore.

> Status Code: 422. {"error":"PG::UndefinedTable: ERROR: relation \"mentions\" does not exist\nLINE 8: WHERE a.attrelid = '\"mentions\"'::regclass\n ^\n: SELECT a.attname, formattype(a.atttypid, a.atttypmod),\n pggetexpr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,\n c.collname, coldescription(a.attrelid, a.attnum) AS comment\n FROM pgattribute a\n LEFT JOIN pgattrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum\n LEFT JOIN pgtype t ON a.atttypid = t.oid\n LEFT JOIN pgcollation c ON a.attcollation = c.oid AND a.attcollation \u003c\u003e t.typcollation\n WHERE a.attrelid = '\"mentions\"'::regclass\n AND a.attnum \u003e 0 AND NOT a.attisdropped\n ORDER BY a.attnum\n"}

```
E, [2021-03-25T17:18:00.035535 #2107-47245987192100] ERROR -- : PG::UndefinedTable: ERROR:  relation "mentions" does not exist
LINE 8:                WHERE a.attrelid = '"mentions"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"mentions"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
 (ActiveRecord::StatementInvalid)
```

### Steps to reproduce the behavior:

* Update from 3.6.0-1615986441.da478686.buster to 4.0.0-1616674376.a2954874.buster

- [x} Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mweinelt** [comment]
From `/var/log/apt/term.log`

```
# database.yml found. Updating db...
== 20201013095141 ElasticSearchLower65Obsolete: migrating =====================
== 20201013095141 ElasticSearchLower65Obsolete: migrated (0.0625s) ============

== 20201110000001 MentionInit: migrating ======================================
-- create_table(:mentions)
   -> 0.1800s
-- add_index(:mentions, [:mentionable_id, :mentionable_type, :user_id], {:unique=>true, :name=>"index_mentions_mentionable_user"})
   -> 0.0378s
-- add_foreign_key(:mentions, :users, {:column=>:created_by_id})
   -> 0.0358s
-- add_foreign_key(:mentions, :users, {:column=>:updated_by_id})
   -> 0.0038s
-- add_foreign_key(:mentions, :users, {:column=>:user_id})
   -> 0.0045s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `[]' for nil:NilClass
/opt/zammad/db/migrate/20201110000001_mention_init.rb:58:in `block in update_user_matrix_by_user'
/opt/zammad/db/migrate/20201110000001_mention_init.rb:57:in `each'
/opt/zammad/db/migrate/20201110000001_mention_init.rb:57:in `update_user_matrix_by_user'
/opt/zammad/db/migrate/20201110000001_mention_init.rb:52:in `block in update_user_matrix'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/db/migrate/20201110000001_mention_init.rb:47:in `update_user_matrix'
/opt/zammad/db/migrate/20201110000001_mention_init.rb:21:in `change'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:814:in `exec_migration'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:797:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:796:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:977:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1343:in `ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1262:in `each'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1210:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1210:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1036:in `up'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1011:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/opt/zammad/bin/bundle:3:in `load'
/opt/zammad/bin/bundle:3:in `<main>'

Caused by:
NoMethodError: undefined method `[]' for nil:NilClass
/opt/zammad/db/migrate/20201110000001_mention_init.rb:58:in `block in update_user_matrix_by_user'
/opt/zammad/db/migrate/20201110000001_mention_init.rb:57:in `each'
/opt/zammad/db/migrate/20201110000001_mention_init.rb:57:in `update_user_matrix_by_user'
/opt/zammad/db/migrate/20201110000001_mention_init.rb:52:in `block in update_user_matrix'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/db/migrate/20201110000001_mention_init.rb:47:in `update_user_matrix'
/opt/zammad/db/migrate/20201110000001_mention_init.rb:21:in `change'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:814:in `exec_migration'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:797:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:796:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:977:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1343:in `ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1262:in `each'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1210:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1210:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1036:in `up'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:1011:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/opt/zammad/bin/bundle:3:in `load'
/opt/zammad/bin/bundle:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by thorsteneckel** [comment]
Thanks for reporting! We'll have a look right away after we've resolved the mimemagic dependency chaos ( https://www.theregister.com/2021/03/25/ruby_rails_code/ )

**Comment by martini** [comment]
Fix is in CI (but which is not working right now because of the issue above).

In the meantime you can replace `/opt/zammad/db/migrate/20201110000001_mention_init.rb` with the attached file below (inline), execute `zamamd run rake db:migrate`, restart Zammad and all should work fine.


```
class MentionInit < ActiveRecord::Migration[5.2]
  def change

    # return if it's a new setup
    return if !Setting.exists?(name: 'system_init_done')

    create_table :mentions do |t|
      t.references :mentionable,      polymorphic: true, null: false
      t.column :user_id,              :integer, null: false
      t.column :updated_by_id,        :integer, null: false
      t.column :created_by_id,        :integer, null: false
      t.timestamps limit: 3, null: false
    end
    add_index :mentions, %i[mentionable_id mentionable_type user_id], unique: true, name: 'index_mentions_mentionable_user'
    add_foreign_key :mentions, :users, column: :created_by_id
    add_foreign_key :mentions, :users, column: :updated_by_id
    add_foreign_key :mentions, :users, column: :user_id

    Mention.reset_column_information
    create_overview
    update_user_matrix
  end

  def create_overview
    Overview.create_if_not_exists(
      name:          'My subscribed Tickets',
      link:          'my_subscribed_tickets',
      prio:          1025,
      role_ids:      Role.with_permissions('ticket.agent').pluck(:id),
      condition:     { 'ticket.mention_user_ids'=>{ 'operator' => 'is', 'pre_condition' => 'current_user.id', 'value' => '', 'value_completion' => '' } },
      order:         {
        by:        'created_at',
        direction: 'ASC',
      },
      view:          {
        d:                 %w[title customer group created_at],
        s:                 %w[title customer group created_at],
        m:                 %w[number title customer group created_at],
        view_mode_default: 's',
      },
      created_by_id: 1,
      updated_by_id: 1,
    )
  end

  def update_user_matrix
    User.with_permissions('ticket.agent').each do |user|
      next if user.preferences.blank?
      next if user.preferences['notification_config'].blank?
      next if user.preferences['notification_config']['matrix'].blank?

      update_user_matrix_by_user(user)
    end
  end

  def update_user_matrix_by_user(user)
    %w[create update].each do |type|
      user.preferences['notification_config']['matrix'][type] ||= {}
      user.preferences['notification_config']['matrix'][type]['criteria'] ||= {}
      user.preferences['notification_config']['matrix'][type]['criteria']['subscribed'] = true
    end

    %w[reminder_reached escalation].each do |type|
      user.preferences['notification_config']['matrix'][type] ||= {}
      user.preferences['notification_config']['matrix'][type]['criteria'] ||= {}
      user.preferences['notification_config']['matrix'][type]['criteria']['subscribed'] = false
    end
    user.save!
  end
end
```

**Comment by mweinelt** [comment]
Thanks alot, that fixed it! Close at your own discretion.
