### ISSUE TITLE
IMAP mail fetching stops because of broken spam email (invalid Content-Transfer-Encoding header)

### ISSUE THREAD

**Issue by martini** [zammad/zammad#348]
```
/Users/me/src/zammad_git_ui/app/models/channel/email_parser.rb:389:in `rescue in process': #<Mail::UnknownEncodingType: Don't know how to decode utf-8, please call #encoded and decode it yourself.>
["/Users/me/src/zammad_git_ui/app/models/channel/email_parser.rb:670:in `decoded'",
"/Users/me/.rvm/gems/ruby-2.3.1/gems/mail-2.6.4/lib/mail/body.rb:185:in `to_s'",
"/Users/me/src/zammad_git_ui/app/models/channel/email_parser.rb:134:in `parse'", 
"/Users/me/src/zammad_git_ui/app/models/channel/email_parser.rb:397:in `_process'", 
"/Users/me/src/zammad_git_ui/app/models/channel/email_parser.rb:376:in `process'", 
"/Users/me/src/zammad_git_ui/app/models/channel/driver/mail_stdin.rb:26:in `initialize'", 
"/Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `new'", 
"/Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `<top (required)>'", 
"/Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `eval'", "/Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `<top (required)>'", 
"/Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require'", 
"/Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'", 
"/Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:90:in `runner'", 
"/Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'", 
"/Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'", "bin/rails:4:in `require'", 
"bin/rails:4:in `<main>'"] (RuntimeError)
```

Content-Transfer-Encoding header is with invalid value. :-o

```
Content-Transfer-Encoding: UTF-8
Content-Type: text/plain; charset="UTF-8"
```

**Comment by martini** [comment]
Fixed https://github.com/zammad/zammad/commit/85872a667997fc501026a42445eccc66788d7cc0
