### ISSUE TITLE
Zendesk-Import `Connection reset by peer` cancels import

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3583]
### Infos:

* Used Zammad version: 4.0/stable and 4.1/develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: (#1086899)

### Expected behavior:

Zendesk Import will finish without issues. 
If there's connectivity or e.g. SSL issues, Zammad will retry `n` times to rule out temporary issues.

### Actual behavior:

Zendesk Import gets cancelled due to a `Connection reset by peer` error. 

Traceback:
```
E, [2021-05-11T23:16:31.604221 #45070-47258842548320] ERROR -- : ImportJob 'Import::Zendesk' failed: Connection reset by peer - SSL_connect -- get https://XXXX.zendesk.com/api/v2/tickets/25405/tags
E, [2021-05-11T23:16:31.604292 #45070-47258842548320] ERROR -- : Connection reset by peer - SSL_connect -- get https://XXXX.zendesk.com/api/v2/tickets/25405/tags (ZendeskAPI::Error::NetworkError)
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:996:in `connect'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:919:in `start'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:1470:in `request'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:1228:in `get'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:85:in `perform_request'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:43:in `block in call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:38:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/middleware/request/retry.rb:20:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/middleware/request/encode_json.rb:21:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/request/multipart.rb:15:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/middleware/request/upload.rb:16:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/request/authorization.rb:37:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/middleware/response/parse_iso_dates.rb:11:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/middleware/response/logger.rb:22:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/middleware/response/callback.rb:14:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/middleware/response/raise_error.rb:8:in `call'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:400:in `get_response'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:189:in `fetch!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:341:in `_all'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:216:in `all!'
/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/base.rb:42:in `public_send'
/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/base.rb:42:in `resource_iteration'
/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/sub_object.rb:19:in `process'
/opt/zammad/lib/sequencer/unit/import/common/model/mixin/skip/action.rb:47:in `process'
/opt/zammad/lib/sequencer/unit/import/common/model/mixin/skip/action.rb:47:in `process'
/opt/zammad/lib/sequencer/unit/base.rb:249:in `process'
/opt/zammad/lib/sequencer.rb:77:in `block (4 levels) in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:76:in `block (3 levels) in process'
/opt/zammad/lib/sequencer/state.rb:153:in `process'
/opt/zammad/lib/sequencer.rb:74:in `block (2 levels) in process'
/opt/zammad/lib/sequencer/units.rb:29:in `block in each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer.rb:72:in `each_with_index'
/opt/zammad/lib/sequencer.rb:72:in `block in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:70:in `process'
/opt/zammad/lib/sequencer.rb:25:in `process'
/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:63:in `sub_sequence'
/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:58:in `expected'
/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:49:in `block in process_sub_sequence'
/opt/zammad/lib/sequencer/unit/import/zendesk/mixin/incremental_export.rb:22:in `block in resource_iteration'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:349:in `block in _all'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:457:in `each'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:457:in `public_send'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:457:in `array_method'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:298:in `method_missing'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:342:in `_all'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/zendesk_api-1.19.0/lib/zendesk_api/collection.rb:216:in `all!'
/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/base.rb:42:in `public_send'
/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/base.rb:42:in `resource_iteration'
/opt/zammad/lib/sequencer/unit/import/zendesk/mixin/incremental_export.rb:20:in `resource_iteration'
/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:47:in `process_sub_sequence'
/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:31:in `block in process'
/opt/zammad/lib/sequencer/state.rb:45:in `provide'
/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/mapped.rb:30:in `process'
/opt/zammad/lib/sequencer/unit/base.rb:249:in `process'
/opt/zammad/lib/sequencer.rb:77:in `block (4 levels) in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:76:in `block (3 levels) in process'
/opt/zammad/lib/sequencer/state.rb:153:in `process'
/opt/zammad/lib/sequencer.rb:74:in `block (2 levels) in process'
/opt/zammad/lib/sequencer/units.rb:29:in `block in each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer.rb:72:in `each_with_index'
/opt/zammad/lib/sequencer.rb:72:in `block in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:70:in `process'
/opt/zammad/lib/sequencer.rb:25:in `process'
/opt/zammad/lib/import/mixin/sequence.rb:15:in `process'
/opt/zammad/lib/import/zendesk.rb:8:in `start'
/opt/zammad/app/models/import_job.rb:24:in `start'
/opt/zammad/app/jobs/async_import_job.rb:3:in `perform'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/execution.rb:39:in `block in perform_now'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/notifications.rb:168:in `block in instrument'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/notifications.rb:168:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/logging.rb:46:in `block in tag_logger'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/tagged_logging.rb:28:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/tagged_logging.rb:71:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/logging.rb:46:in `tag_logger'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:136:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/execution.rb:38:in `perform_now'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/execution.rb:24:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/reloader.rb:73:in `block in wrap'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/reloader.rb:72:in `wrap'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:136:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/execution.rb:22:in `execute'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activejob-5.2.4.6/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:66:in `execute'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/backend/base.rb:78:in `invoke_job'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:230:in `block in run'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:229:in `run'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:66:in `execute'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:213:in `block in work_off'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:212:in `times'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:212:in `work_off'
/opt/zammad/app/models/scheduler.rb:372:in `block (3 levels) in worker'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/opt/zammad/app/models/scheduler.rb:370:in `block (2 levels) in worker'
/opt/zammad/app/models/scheduler.rb:366:in `loop'
/opt/zammad/app/models/scheduler.rb:366:in `block in worker'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

### Steps to reproduce the behavior:

* have a big zendesk installation (356k users, 26k tickets should do)
* try the import

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
@MrGeneration Can you verify if the Zendesk Import works on Zammad 4.0 if you changed the following file before starting the import?

`/opt/zammad/lib/sequencer/unit/import/zendesk/sub_sequence/base.rb`

[base.rb.txt](https://github.com/zammad/zammad/files/6575459/base.rb.txt)


Feedback is welcome!
