### ISSUE TITLE
Mail fetching: uninitialized constant Channel::Filter::InternalArticleCheck

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3595]
### Infos:

* Used Zammad version: 4.1/develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Mail processing works flawlessly.

### Actual behavior:

Mail processing fails because of missing Filter-Constant. 
The emails are fine and can be manually imported via `rails r 'Channel::EmailParser.process_unprocessable_mails'`

```
E, [2021-06-04T18:47:21.487481 #29445-107627100] ERROR -- : Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/add2f3ea3e38242ab14ae0b23d0db2c9.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2021-06-04T18:47:21.487502 #29445-107627100] ERROR -- : uninitialized constant Channel::Filter::InternalArticleCheck (NameError)
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/inflector/methods.rb:285:in `const_get'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/inflector/methods.rb:285:in `block in constantize'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/inflector/methods.rb:281:in `each'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/inflector/methods.rb:281:in `inject'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/inflector/methods.rb:281:in `constantize'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
/opt/zammad/app/models/channel/email_parser.rb:154:in `block in _process'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/app/models/channel/email_parser.rb:153:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:120:in `block in process'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:119:in `process'
/opt/zammad/app/models/channel/driver/imap.rb:320:in `block in fetch'
/opt/zammad/app/models/channel/driver/imap.rb:257:in `each'
/opt/zammad/app/models/channel/driver/imap.rb:257:in `fetch'
/opt/zammad/app/models/channel.rb:56:in `fetch'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:287:in `eval'
/opt/zammad/app/models/scheduler.rb:287:in `_start_job'
/opt/zammad/app/models/scheduler.rb:239:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:237:in `loop'
/opt/zammad/app/models/scheduler.rb:237:in `block in start_job'
/usr/local/rvm/gems/ruby-2.6.6/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2021-06-04T18:47:21.507000 #29445-107627100]  INFO -- : done
```

### Steps to reproduce the behavior:

* have current internal ´pre-release` devep/4.1

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Seems like someone didn't want to restart the scheduler correctly. 
Sorry for the noise.

**Comment by martini** [comment]
1) This issue appears if Zammad is not stopped (at least the scheduler) before starting Zammad update.
2) The documentation points out that Zammad need to be stopped first: https://docs.zammad.org/en/latest/install/update.html

So closing for now.
