### ISSUE TITLE
Scheduler dies with `PG:UnableToSend`

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#3601]
### Infos:

* Used Zammad version:  4.0 / stable and earlier (seen on 3.6 too)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Scheduler does not die on e.g. high load situations.

### Actual behavior:

* On specific situations ( I suspect load / I/O) the scheduler dies and does not recover with `PG::UnableToSend` error

### Steps to reproduce the behavior:

* ¯_(ツ)_/¯

scheduler_err.log:
```
#<Thread:0x00007fbe54354e58@/usr/local/rvm/gems/ruby-2.6.6/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
/opt/zammad/lib/sessions.rb:780:in `rescue in thread_client': STOP thread_client for client .88208440 after 10 tries (RuntimeError)
        from /opt/zammad/lib/sessions.rb:755:in `thread_client'
        from /opt/zammad/lib/sessions.rb:711:in `block (3 levels) in jobs'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `async_exec': PG::UnableToSend: server closed the connection unexpectedly (ActiveRecord::StatementInvalid)
        This probably means the server terminated abnormally
        before or while processing the request.
: SELECT  1 AS one FROM "permissions" INNER JOIN "permissions_roles" ON "permissions"."id" = "permissions_roles"."permission_id" INNER JOIN "roles" ON "permissions_roles"."role_id" = "roles"."id" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_id" WHERE "roles_users"."user_id" = $1 AND "roles"."active" = $2 AND "permissions"."active" = $3 AND ("permissions"."name") IN ($4, $5) LIMIT $6
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `block (2 levels) in exec_no_cache'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:610:in `block in exec_no_cache'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
        from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_no_cache'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `execute_and_clear'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:478:in `select'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/query_cache.rb:106:in `select_all'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:77:in `select_one'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/relation/finder_methods.rb:322:in `block in exists?'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/relation/finder_methods.rb:322:in `exists?'
        from /opt/zammad/app/models/concerns/can_be_authorized.rb:29:in `permissions?'
        from /opt/zammad/app/models/activity_stream.rb:110:in `list'
        from /opt/zammad/app/models/user.rb:267:in `activity_stream'
        from /opt/zammad/lib/sessions/backend/activity_stream.rb:17:in `load'
        from /opt/zammad/lib/sessions/backend/activity_stream.rb:54:in `push'
        from /opt/zammad/lib/sessions/client.rb:67:in `each'
        from /opt/zammad/lib/sessions/client.rb:67:in `block in fetch'
        from /opt/zammad/lib/sessions/client.rb:23:in `loop'
        from /opt/zammad/lib/sessions/client.rb:23:in `fetch'
        from /opt/zammad/lib/sessions/client.rb:7:in `initialize'
        from /opt/zammad/lib/sessions.rb:756:in `new'
        from /opt/zammad/lib/sessions.rb:756:in `thread_client'
        from /opt/zammad/lib/sessions.rb:711:in `block (3 levels) in jobs'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `async_exec': server closed the connection unexpectedly (PG::UnableToSend)
        This probably means the server terminated abnormally
        before or while processing the request.
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `block (2 levels) in exec_no_cache'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:610:in `block in exec_no_cache'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
        from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_no_cache'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `execute_and_clear'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:478:in `select'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/query_cache.rb:106:in `select_all'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:77:in `select_one'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/relation/finder_methods.rb:322:in `block in exists?'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/relation/finder_methods.rb:322:in `exists?'
        from /opt/zammad/app/models/concerns/can_be_authorized.rb:29:in `permissions?'
        from /opt/zammad/app/models/activity_stream.rb:110:in `list'
        from /opt/zammad/app/models/user.rb:267:in `activity_stream'
        from /opt/zammad/lib/sessions/backend/activity_stream.rb:17:in `load'
        from /opt/zammad/lib/sessions/backend/activity_stream.rb:54:in `push'
        from /opt/zammad/lib/sessions/client.rb:67:in `each'
        from /opt/zammad/lib/sessions/client.rb:67:in `block in fetch'
        from /opt/zammad/lib/sessions/client.rb:23:in `loop'
        from /opt/zammad/lib/sessions/client.rb:23:in `fetch'
        from /opt/zammad/lib/sessions/client.rb:7:in `initialize'
        from /opt/zammad/lib/sessions.rb:756:in `new'
        from /opt/zammad/lib/sessions.rb:756:in `thread_client'
        from /opt/zammad/lib/sessions.rb:711:in `block (3 levels) in jobs'
        from /usr/local/rvm/gems/ruby-2.6.6/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
RuntimeError: STOP thread_client for client .88208440 after 10 tries
  /opt/zammad/lib/sessions.rb:780:in `rescue in thread_client'
  /opt/zammad/lib/sessions.rb:755:in `thread_client'
  /opt/zammad/lib/sessions.rb:711:in `block (3 levels) in jobs'
  /usr/local/rvm/gems/ruby-2.6.6/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
  ```

production.log:
```
E, [2021-05-20T13:21:51.390980 #15198-70227716646700] ERROR -- : thread_client 88208440 exited with error #<ActiveRecord::StatementInvalid: PG::UnableToSend: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
: SELECT  1 AS one FROM "permissions" INNER JOIN "permissions_roles" ON "permissions"."id" = "permissions_roles"."permission_id" INNER JOIN "roles" ON "permissions_roles"."role_id" = "roles"."id" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_id" WHERE "roles_users"."user_id" = $1 AND "roles"."active" = $2 AND "permissions"."active" = $3 AND ("permissions"."name") IN ($4, $5) LIMIT $6>
E, [2021-05-20T13:21:51.391042 #15198-70227716646700] ERROR -- : /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `async_exec'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `block (2 levels) in exec_no_cache'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:610:in `block in exec_no_cache'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
  /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_no_cache'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `execute_and_clear'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:478:in `select'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/query_cache.rb:106:in `select_all'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/database_statements.rb:77:in `select_one'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/relation/finder_methods.rb:322:in `block in exists?'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'
  /usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.5/lib/active_record/relation/finder_methods.rb:322:in `exists?'
  /opt/zammad/app/models/concerns/can_be_authorized.rb:29:in `permissions?'
  /opt/zammad/app/models/activity_stream.rb:110:in `list'
  /opt/zammad/app/models/user.rb:267:in `activity_stream'
  /opt/zammad/lib/sessions/backend/activity_stream.rb:17:in `load'
  /opt/zammad/lib/sessions/backend/activity_stream.rb:54:in `push'
  /opt/zammad/lib/sessions/client.rb:67:in `each'
  /opt/zammad/lib/sessions/client.rb:67:in `block in fetch'
  /opt/zammad/lib/sessions/client.rb:23:in `loop'
  /opt/zammad/lib/sessions/client.rb:23:in `fetch'
  /opt/zammad/lib/sessions/client.rb:7:in `initialize'
  /opt/zammad/lib/sessions.rb:756:in `new'
  /opt/zammad/lib/sessions.rb:756:in `thread_client'
  /opt/zammad/lib/sessions.rb:711:in `block (3 levels) in jobs'
  /usr/local/rvm/gems/ruby-2.6.6/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2021-05-20T13:21:52.089138 #15198-16431520]  INFO -- : Scheduler running...
I, [2021-05-20T13:21:52.115744 #15198-100444560]  INFO -- : execute Ticket.process_auto_unassign (try_count 0)...
I, [2021-05-20T13:21:52.121658 #15198-100444560]  INFO -- : ended Ticket.process_auto_unassign took: 0.013620879 seconds.
I, [2021-05-20T13:21:52.484738 #15198-100098620]  INFO -- : 2021-05-20T13:21:52+0200: [Worker(host:host.tld pid:15198)] Error while reserving job: PG::UnableToSend: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
: UPDATE "delayed_jobs" SET locked_at = '2021-05-20 11:21:52.484005', locked_by = 'host:host.tld pid:15198' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2021-05-20 11:21:52.483519' AND (locked_at IS NULL OR locked_at < '2021-05-20 07:21:52.483538') OR locked_by = 'host:host.tld pid:15198') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
E, [2021-05-20T13:21:52.931773 #15198-100637540] ERROR -- : execute Channel.stream (try_count 0) exited with error #<ActiveRecord::StatementInvalid: PG::UnableToSend: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
: SELECT "channels".* FROM "channels" WHERE (active = TRUE AND area LIKE '%::Account')> in: 2123171.196019423 seconds.
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
@MrGeneration is this still a thing?

**Comment by MrGeneration** [comment]
>  @MrGeneration is this still a thing?

If it hasn't been fixed yet, yes.

**Comment by fliebe92** [comment]
@mantas > Is this issue handled by you? Just asking, because you're assigned...

**Comment by mantas** [comment]
@fliebe92 I was monitoring this, but there's no way to reproduce this yet. I've no idea what to do with this so far.
