### ISSUE TITLE
Don't keep on trying to fetch mail if scheduler has issues with database

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3603]
### Infos:

* Used Zammad version: 4.0/stable
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1088023

### Expected behavior:

If Zammad can't use the database during a fetch process, it will not keep on trying to fetch mail but instead stop that process. If needed (because mail is removed from mails server already or marked as read) Zammad will write affected mails into unprocessable mail.

### Actual behavior:

If Zammad can't use the database during a fetch process it will keep on retrieving further emails. 
As it can't add new data to the database in that situation it will write the mails to unprocessible mail instead.

In worst case you'll have 150 unprocessible mails because of that.

The pool of the affected instance was set to `80` already, max_connections of postgres is at `2000`.
```
E, [2021-06-08T08:58:11.644498 #18165-47320579945060] ERROR -- : Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/92c069d316847de03a00e3c3eb7a60e8.eml, please create an issue at https://git
hub.com/zammad/zammad/issues
E, [2021-06-08T08:58:11.644583 #18165-47320579945060] ERROR -- : execution expired (Timeout::Error)
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `async_exec'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `block (2 levels) in execute'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:74:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `execute'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/savepoints.rb:11:in `create_savepoint'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:153:in `initialize'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:203:in `new'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:203:in `block in begin_transaction'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:197:in `begin_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:238:in `block in within_new_transaction'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/app/models/ticket.rb:495:in `selectors'
/opt/zammad/app/models/ticket.rb:1327:in `block (2 levels) in perform_triggers'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/app/models/ticket.rb:1225:in `block in perform_triggers'
/opt/zammad/app/models/transaction.rb:15:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/app/models/transaction.rb:13:in `execute'
/opt/zammad/app/models/ticket.rb:1224:in `perform_triggers'
/opt/zammad/app/models/transaction/trigger.rb:40:in `perform'
/opt/zammad/app/models/observer/transaction.rb:62:in `execute_singel_backend'
/opt/zammad/app/models/observer/transaction.rb:48:in `block (3 levels) in perform'
/opt/zammad/app/models/observer/transaction.rb:47:in `each'
/opt/zammad/app/models/observer/transaction.rb:47:in `block (2 levels) in perform'
/opt/zammad/app/models/observer/transaction.rb:44:in `each_value'
/opt/zammad/app/models/observer/transaction.rb:44:in `block in perform'
/opt/zammad/app/models/observer/transaction.rb:43:in `each_value'
/opt/zammad/app/models/observer/transaction.rb:43:in `perform'
/opt/zammad/app/models/observer/transaction.rb:18:in `commit'
/opt/zammad/app/models/transaction.rb:19:in `block in execute'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/app/models/transaction.rb:13:in `execute'
/opt/zammad/app/models/channel/email_parser.rb:178:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:120:in `block in process'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:119:in `process'
/opt/zammad/app/models/channel/driver/imap.rb:320:in `block in fetch'
/opt/zammad/app/models/channel/driver/imap.rb:257:in `each'
/opt/zammad/app/models/channel/driver/imap.rb:257:in `fetch'
/opt/zammad/app/models/channel.rb:56:in `fetch'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:287:in `eval'
/opt/zammad/app/models/scheduler.rb:287:in `_start_job'
/opt/zammad/app/models/scheduler.rb:239:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:237:in `loop'
/opt/zammad/app/models/scheduler.rb:237:in `block in start_job'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2021-06-08T08:58:13.793569 #18165-47320579945060]  INFO -- :  - message 9/11

```

### Steps to reproduce the behavior:

* have a burst situation that causes postgres to either not respond in time or the pool being completely used
* try to fetch mail in exactly that situation

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
@mantas @mgruner is this still the case with the improvements for the background services?

**Comment by mantas** [comment]
I've a feeling that it's still present. The problem IMO is at specific job level, not background services as a whole.

TBH I'm not sure what would be the solution. Check DB health before fetching messages? What if it goes down in while fetching emails?

**Comment by mgruner** [comment]
@dominikklein also guess it should not be related to the background worker refactoring.
