### ISSUE TITLE
Creating and editing users via office 365 failes with Image source is invalid

### ISSUE THREAD

**Issue by fibis** [zammad/zammad#3617]
### Infos:

* Used Zammad version: 4.1.X
* Installation method (source, package, ..): helm chart
* Operating system: kubernetes / Container-Optimized OS 
* Database + version: PostgreSQL 13 
* Elasticsearch version: Version that is bundled with zammad
* Browser + version: Firefox 89
* Ticket: #1088409

### Expected behavior:

* A user account should be created for new users that login via Office/Microsoft 365/azure active directory the first time
* A user who was created via Office/Microsoft 365/azure active directory should be editable

### Actual behavior:

* Users that login via Office/Microsoft 365/azure active directory the first time will get 422 "Image source is invalid" error page
* Users who were created via Office/Microsoft 365/azure active directory will throw a 422  "Image source is invalid"  when editing this user.

### Steps to reproduce the behavior:

* Try to login the first time via Office/Microsoft 365/azure active directory in zammad

### Log
```
I, [2021-06-16T07:58:32.455599 #1-47408603520580]  INFO -- : Started PUT "/api/v1/users/8" for 10.52.7.10 at 2021-06-16 07:58:32 +0000
I, [2021-06-16T07:58:32.464278 #1-47408603520580]  INFO -- : Processing by UsersController#update as JSON
I, [2021-06-16T07:58:32.464678 #1-47408603520580]  INFO -- :   Parameters: {"login"=>"c4d43dc3-7851-44f2-8d47-e18240dd3dc3", "firstname"=>"***", "lastname"=>"***", "email"=>"***", "web"=>"", "password"=>"[FILTERED]", "phone"=>"", "fax"=>"", "mobile"=>"", "street"=>"", "zip"=>"", "city"=>"", "country"=>"", "organization_id"=>"3", "department"=>"", "note"=>"", "role_ids"=>["1", "2", "3"], "group_ids"=>{"2"=>"full", "5"=>"full"}, "active"=>true, "updated_at"=>"2021-06-14T08:11:24.177Z", "address"=>"", "vip"=>false, "industry"=>"", "id"=>"8"}
E, [2021-06-16T07:58:32.508382 #1-47408603520580] ERROR -- : Validation failed: Image source is invalid (ActiveRecord::RecordInvalid)
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/validations.rb:80:in `raise_validation_error'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/validations.rb:52:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:315:in `block in save!'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:315:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/suppressor.rb:48:in `save!'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/persistence.rb:441:in `block in update!'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/persistence.rb:439:in `update!'
/opt/zammad/app/controllers/users_controller.rb:133:in `block in update'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/locking/pessimistic.rb:84:in `block in with_lock'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:301:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/locking/pessimistic.rb:82:in `with_lock'
/opt/zammad/app/controllers/users_controller.rb:130:in `update'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/abstract_controller/base.rb:194:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:18:in `block (4 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/notifications.rb:180:in `subscribed'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:17:in `block (3 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/notifications.rb:180:in `subscribed'
/opt/zammad/app/controllers/application_controller/has_secure_content_security_policy_for_downloads.rb:16:in `block (2 levels) in <module:HasSecureContentSecurityPolicyForDownloads>'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/zammad/app/controllers/application_controller/handles_transitions.rb:14:in `handle_transaction'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/usr/local/bundle/gems/activerecord-5.2.4.6/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/abstract_controller/base.rb:134:in `process'
/usr/local/bundle/gems/actionview-5.2.4.6/lib/action_view/rendering.rb:32:in `process'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_controller/metal.rb:191:in `dispatch'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_controller/metal.rb:252:in `dispatch'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/journey/router.rb:35:in `each'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/journey/router.rb:35:in `serve'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/routing/route_set.rb:840:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:420:in `call_app!'
/usr/local/bundle/gems/omniauth-saml-1.10.1/lib/omniauth/strategies/saml.rb:89:in `other_phase'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:190:in `call!'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/builder.rb:45:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/bundle/gems/railties-5.2.4.6/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/bundle/gems/railties-5.2.4.6/lib/rails/rack/logger.rb:26:in `block in call'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/tagged_logging.rb:71:in `tagged'
/usr/local/bundle/gems/railties-5.2.4.6/lib/rails/rack/logger.rb:26:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/usr/local/bundle/gems/activesupport-5.2.4.6/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/bundle/gems/actionpack-5.2.4.6/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/usr/local/bundle/gems/railties-5.2.4.6/lib/rails/engine.rb:524:in `call'
/usr/local/bundle/gems/puma-4.3.8/lib/puma/configuration.rb:228:in `call'
/usr/local/bundle/gems/puma-4.3.8/lib/puma/server.rb:718:in `handle_request'
/usr/local/bundle/gems/puma-4.3.8/lib/puma/server.rb:472:in `process_client'
/usr/local/bundle/gems/puma-4.3.8/lib/puma/server.rb:328:in `block in run'
/usr/local/bundle/gems/puma-4.3.8/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
/usr/local/bundle/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sounds like a technical question, the authentication works without any issues on first try in my environments.
Please provide the app configuration (ensure to not provide us with secrets of your application).

**Comment by fibis** [comment]
@MrGeneration what is the best way to provide the app configuration?

**Comment by fibis** [comment]
We also use s3 as storage provider, could that be a problem?

**Comment by MrGeneration** [comment]
Please don't post technical questions on github issues. 
The best way to provide your app configuration would be screenshots of the relevant screens.

**Comment by MrGeneration** [comment]
I can't reproduce the login issue you mentioned. I can always, at any time, instantly login or register depending on the situation. 
This may be a specific constellation with your Microsoft accounts that simply doesn't fit to my account.

Any way, the root cause is another. 
Since Zammad 4.1 we're expecting valid input / data on `image_source` which could be set with invalid data earlier. 
In my reproduction the issue only affects updating users with invalid `image_source` data.

What we're going to do:
* Write a debug log entry that we ignored the `image_source` in case it's invalid (so we don't block updating the user)
* provide a migration to cleanup existing users

**Comment by ZuSe** [comment]
@MrGeneration  

We are running into the same issue. Our employees usually upload images via MS Teams. I don't know how Microsoft stores them but this seems to cause the issue.

Maybe it helps you debugging.

**Comment by rolfschmidt** [comment]
> 
> 
> @MrGeneration
> 
> We are running into the same issue. Our employees usually upload images via MS Teams. I don't know how Microsoft stores them but this seems to cause the issue.
> 
> Maybe it helps you debugging.

@ZuSe Is your system up to date? Bug should be fixed by now.

**Comment by ZuSe** [comment]
@rolfschmidt 

Is it already in the helm chart? We hosting on k8s.

**Comment by MrGeneration** [comment]
Please stop posting technical questions on this repo. 
You're hijacking a closed issue.
