### ISSUE TITLE
Migration 3.6.1 to 4.1 : No configured business hours found!

### ISSUE THREAD

**Issue by mdz0r** [zammad/zammad#3641]
### Infos:

* Used Zammad version: 3.6.1
* Installation method (source, package, ..): Source
* Operating system: Ubuntu
* Database + version: Mysql 8
* Elasticsearch version: 7.1
* Browser + version: NA

### Actual behavior:

Hello,
I'm having a problem while migrating my zammad instance from 3.6.1 to 4.1.

* Migration from 3.6.1 to 4.1 causes "No configured business hours found!" error

### Steps to reproduce the behavior:

```
$ rake db:migrate
== 20210617051913 Issue3618GoogleCalendarUrlHttps: migrating ==================
rake aborted!
Exceptions::UnprocessableEntity: No configured business hours found!
/opt/zammad/app/models/calendar.rb:417:in `validate_hours'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_t
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:605:in `catch'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:199:in `block in halting'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:513:in `each'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:513:in `invoke_before'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:131:in `run_callbacks'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:816:in `_run_update_callbacks'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/callbacks.rb:350:in `_update_record'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/timestamp.rb:114:in `_update_record'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/persistence.rb:705:in `create_or_update'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/callbacks.rb:342:in `block in create_or_update'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:98:in `run_callbacks'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activesupport-5.2.4.6/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/callbacks.rb:342:in `create_or_update'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/persistence.rb:275:in `save'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/validations.rb:46:in `save'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:387:in `block in with_transaction_re
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:385:in `with_transaction_returning_s
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:310:in `block in save'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:325:in `rollback_active_record_state
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:309:in `save'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/suppressor.rb:44:in `save'
/opt/zammad/db/migrate/20210617051913_issue_3618_google_calendar_url_https.rb:11:in `block in change'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/db/migrate/20210617051913_issue_3618_google_calendar_url_https.rb:9:in `change'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:814:in `exec_migration'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:797:in `block in migrate'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:796:in `migrate'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:977:in `migrate'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:1292:in `block in execute_migration_in_
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:1345:in `ddl_transaction'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:1291:in `execute_migration_in_transacti
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:1262:in `each'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:1210:in `block in migrate'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:1210:in `migrate'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:1036:in `up'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:1011:in `migrate'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/opt/zammad/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.4.6/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Do I have to migrate to 4.0 before going to 4.1 ?

**Comment by MrGeneration** [comment]
@mantas looks like there are no SLA calendars configured which make the migration fail?
Possibly a regression of #3618

**Comment by mantas** [comment]
Hi @mdz0r 

The issue is now fixed. If you were installing straight from source, it's available in `stable` branch now. Updated packages will be available in an hour or so.

**Comment by mdz0r** [comment]
Thanks a lot for the quick fix!
I'll try the upgrade next week and will keep you posted.
