### ISSUE TITLE
Twilio integration will crash when object manager attribute type is activated and required

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3650]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all
* Ticket#1089287

### Expected behavior:

* Incoming SMS should be created as tickets

### Actual behavior:

* Ticket creation will crash if you have the type attribute activated and required/mandatory

```
Validation failed: Type is required but missing. (ActiveRecord::RecordInvalid)
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/validations.rb:80:in `raise_validation_error'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/validations.rb:52:in `save!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:315:in `block in save!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:315:in `save!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/suppressor.rb:48:in `save!'
/opt/zammad/app/models/channel/driver/sms/twilio.rb:96:in `process'
/opt/zammad/app/models/channel.rb:293:in `process'
```

### Steps to reproduce the behavior:

* Configure twilio
* Goto admin interface -> Objects
* Activate the type field and set it as required for create_middle
* Try to send a sms to your system

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
related to https://github.com/zammad/zammad/issues/2998

**Comment by mantas** [comment]
Closed along with https://github.com/zammad/zammad/issues/2634
