### ISSUE TITLE
Locking a record with unpersisted changes is not supported. Use `save` to persist the changes, or `reload` to discard them explicitly

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3664]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all
* Ticket#1089297, Ticket#1089826
* https://community.zammad.org/t/locking-a-record-with-unpersisted-changes-is-not-supported/4861

### Expected behavior:

* Ticket are editable

### Actual behavior:

* On a ticket update the following error occurs:

```
[2021-07-19T09:35:53.493701 #14922-47175411727040] ERROR -- : Locking a record with unpersisted changes is not supported. Use `save` to persist the changes, or `reload` to discard them explicitly. (RuntimeError)
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/locking/pessimistic.rb:66:in `lock!'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/locking/pessimistic.rb:83:in `block in with_lock'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/transactions.rb:301:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/locking/pessimistic.rb:82:in `with_lock'
/opt/zammad/app/controllers/tickets_controller.rb:252:in `update'
```

### Steps to reproduce the behavior:

It happens for some self hosted systems in the migration process from 3.3 to 4.1

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Currently we dont know what is the reason for the problem. We found out that the problem is in the ticket table. The column preferences stores the escalation information in yaml format and for some reason after the upgrade it has missing spaces in the indentation of the data. It can be reproduced with the SQL attached.

[lock_bug.zip](https://github.com/zammad/zammad/files/6846784/lock_bug.zip)

The differences in the indentation of the yaml will tell Rails to have changed data after intialization of the object and this will relate to problems if you want to lock the ticket, because you only can lock the ticket if you have no changes at your object.

To find out if your ticket is matched by this problem you can run the following command:

`zammad run rails r "ticket = Ticket.find_by(number: '999999'); ticket.preferences; pp ticket.changes"`

It will deserialize the yaml store of the preferences at the ticket and in case the bug happen to you it should show changes for the ticket preferences.

The hotfix for now to solve this problem is to check all your tickets and save the correct structure of the preferences if they are stored wrong:

#### Note for busy instance

You may want to temporary stop your Zammad instance if possible. Other wise you might bump into `[...] Directory not empty @ dir_s_rmdir [...]` issues. 

If you can't, run `Cache.clear` more often.

#### Fix one ticket

```
zammad run rails r "Ticket.where(number: '999999').find_each{|t| t.preferences; next if t.changes.blank?; t.update_column(:preferences, t.preferences) }; Cache.clear"
```

#### Fix all tickets

```
zammad run rails r "Ticket.find_each{|t| t.preferences; next if t.changes.blank?; t.update_column(:preferences, t.preferences) }; Cache.clear"
```

This issue will be reopened if we find a better solution to fix it...

**Comment by xf-** [comment]
@rolfschmidt this ends up in an exception (using the file storage)
```backtrace
zammad run rails r "Ticket.find_each{|t| t.preferences; next if t.changes.blank?; t.update_column(:preferences, t.preferences) }; Cache.clear"
Traceback (most recent call last):
        31: from /opt/zammad/bin/rails:9:in `<main>'
        30: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/dependencies.rb:291:in `require'
        29: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/dependencies.rb:257:in `load_dependency'
        28: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/dependencies.rb:291:in `block in require'
        27: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        26: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        25: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        24: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        23: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        22: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/commands.rb:18:in `<main>'
        21: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/command.rb:46:in `invoke'
        20: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/command/base.rb:69:in `perform'
        19: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        18: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        17: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        16: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/commands/runner/runner_command.rb:41:in `perform'
        15: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/commands/runner/runner_command.rb:41:in `eval'
        14: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
        13: from /opt/zammad/lib/cache.rb:59:in `clear'
        12: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/cache/strategy/local_cache.rb:96:in `clear'
        11: from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/cache/file_store.rb:34:in `clear'
        10: from /opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:606:in `rm_r'
         9: from /opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:606:in `each'
         8: from /opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:610:in `block in rm_r'
         7: from /opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:758:in `remove_entry'
         6: from /opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:1480:in `postorder_traverse'
         5: from /opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:760:in `block in remove_entry'
         4: from /opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:1423:in `remove'
         3: from /opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:1430:in `remove_dir1'
         2: from /opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:1442:in `platform_support'
         1: from /opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:1431:in `block in remove_dir1'
/opt/zammad/vendor/ruby-2.6.6/lib/ruby/2.6.0/fileutils.rb:1431:in `rmdir': Directory not empty @ dir_s_rmdir - /opt/zammad/tmp/cache_file_store_production/ADC (Errno::ENOTEMPTY)
```

**Comment by MrGeneration** [comment]
@xf- this comes from `Cache.clear` and is because you did not stop Zammad. 
If your instance is busy this may happen. 

Run `Cache.clear` more often until the error disappears will help if you can't stop Zammad.

**Comment by xf-** [comment]
THX - I thought maybe the issue is different with file storage.
This fixed the issue. Just stopped the instance for a moment.

**Comment by rolfschmidt** [comment]
Currently broken situation in stable again. The reason is a data structure change in the core of rails:

https://github.com/zammad/zammad/commit/7dadccdea047297fac4083feef0471f169e20b54

https://github.com/rails/rails/commit/e74d6ee33dcbd799c1e845f63876bd8d3fe29b05 (thx @dk)

It looks like that all objects are broken now because on loading of the object with a store attribute it will automatically show changes which will disallow locks.

There might be a hotfix soon and a proper migration later which fixes the situation in the db.

### example issue view in sql

```
zp_00002266=> SELECT preferences FROM tickets WHERE id = 165;
                        preferences
-----------------------------------------------------------
 --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess  +
 form: !ruby/hash:ActiveSupport::HashWithIndifferentAccess+
   remote_ip: 195.201.98.123                              +
   fingerprint_md5: 66638aad396c60ecb24f96de1e59d913      +

(1 Zeile)

zp_00002266=> SELECT preferences FROM tickets WHERE id = 168;
                     preferences
-----------------------------------------------------
 ---                                                +
 form:                                              +
   remote_ip: 2a02:908:e55:1080:d4ce:d824:6be8:751e +
   fingerprint_md5: ab55195457eaf0b3236d343987900683+

(1 Zeile)

ticket 165 = broken
ticket 168 = fixed
```

**Comment by rolfschmidt** [comment]
realtes https://github.com/rails/rails/pull/45872#issuecomment-1261994424

**Comment by dk** [comment]
you're welcome ( EWRONGDK tho :) )

**Comment by rolfschmidt** [comment]
ah LOL sorry @dk ... i wanted to mention @dominikklein ... really sorry :D hahahahahaa
