### ISSUE TITLE
Login failed after upgrade to zammad 5.0

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3759]
### Infos:

Used Zammad version: 5.0
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* Login works

```
[1] pry(main)> ObjectLookup.by_name('User')
=> 1
```

### Actual behavior:

![grafik](https://user-images.githubusercontent.com/5445062/134197575-bfdcd2b6-546a-4c53-9edf-24cb5d3de642.png)

`Attribute &#39;activity<u>stream</u>object_id&#39; required!`

```
E, [2021-09-21T16:10:59.838886 #15137-174660] ERROR -- : PG::NotNullViolation: ERROR:  null value in column "activity_stream_object_id" violates not-null constraint
DETAIL:  Failing row contains (5, 1, null, 2, null, 3, 3, 2021-09-21 15:10:59.821, 2021-09-21 15:10:59.83).
 (ActiveRecord::NotNullViolation)
app/models/activity_stream.rb:82:in `add'
app/models/application_model/can_activity_stream_log.rb:46:in `activity_stream_log'
app/controllers/sessions_controller.rb:228:in `initiate_session_for'

```
```
#<ObjectLookup id: 1, name: "User", created_at: "2021-09-21 14:44:00", updated_at: "2021-09-21 14:44:00">
(byebug) n

[16, 25] in /workspace/git_zammad/zammad/app/models/object_lookup.rb
   16:
   17:     # lookup
   18:     lookup = self.lookup(name: name)
   19:     byebug
   20:     if lookup
=> 21:       return lookup.id
   22:     end
   23:
   24:     # create
   25:     lookup = create(name: name)
(byebug) lookup
#<ObjectLookup id: 1, name: "User", created_at: "2021-09-21 14:44:00", updated_at: "2021-09-21 14:44:00">
(byebug) lookup.id
nil
(byebug) lookup[:id]
1
(byebug) lookup.class
ObjectLookup (call 'ObjectLookup.connection' to establish a connection)
```

```
[1] pry(main)> ObjectLookup.by_name('User')
=> nil
```

### Steps to reproduce the behavior:

* Setup stable 4.1
* Upgrade to develop
* Try to login

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
# Workaround

`zammad run rails r "Cache.clear"`

**Comment by thorsteneckel** [comment]
This seems to be an issue that comes from updating Rails and/or Ruby:

```ruby
# broken_cache_write.rb
entry = ObjectLookup.find_by(name: 'User')

File.atomic_write('broken.cache') { |f| Marshal.dump(entry, f) }
```

```ruby
# broken_cache_read.rb
entry = File.open('broken.cache') { |f| Marshal.load(f) }
p entry
p entry.id
```

```
➜  zammad git:(develop) ✗ git checkout stable
➜  zammad git:(stable) ✗ rvm use 2.6.8
➜  zammad git:(stable) ✗ rails r broken_cache_write.rb
Running via Spring preloader in process 25699
➜  zammad git:(stable) ✗ rvm use 2.7.4
➜  zammad git:(stable) ✗ git checkout develop
➜  zammad git:(develop) ✗ rails r broken_cache_read.rb
Running via Spring preloader in process 26411
#<ObjectLookup id: 1, name: "User", created_at: "2021-09-21 15:03:48", updated_at: "2021-09-21 15:03:48">
nil
```
