### ISSUE TITLE
[BUG] miss spell in db/migrate/20210923172256_issue_2619_kb_header_link_color.rb

### ISSUE THREAD

**Issue by mzch** [zammad/zammad#3777]
### Infos:

* Used Zammad version: commit bf6da241d8190d29c7e0a2ad4c5f929b51faaa64
* Installation method (source, package, ..): source
* Operating system: Debian 11.0

### Expected behavior:

* Migrate database succssfully.

### Actual behavior:

* Error.
```
$ RAILS_ENV=production bundle exec rake db:migrate
== 20210914153600 Issue3194UpdatePermissions: migrating =======================
== 20210914153600 Issue3194UpdatePermissions: migrated (0.4426s) ==============

== 20210921112300 Issue3751MissingWorkflowScreens: migrating ==================
# Copyright (C) 2012-2021 Zammad Foundation, http://zammad-foundation.org/
== 20210921112300 Issue3751MissingWorkflowScreens: migrated (0.1985s) =========

== 20210922090000 Issue3759CacheClear: migrating ==============================
== 20210922090000 Issue3759CacheClear: migrated (0.3868s) =====================

== 20210923075329 RemoveOtrsDiffWorkerSchedulerEntry: migrating ===============
== 20210923075329 RemoveOtrsDiffWorkerSchedulerEntry: migrated (0.1351s) ======

== 20210923172256 Issue2619KbHeaderLinkColor: migrating =======================
-- add_column(:knowledge_bases, :color_header_link, :string, {:limit=>25, :null=>false, :default=>"hsl(206,8%,50%)"})
   -> 0.0588s
-- change_column_default(:knowledge_bases, :color_header_link, nil)
   -> 0.0196s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant Issue2619KbHeaderLinkColor::KnowledgeBasis
Did you mean?  KnowledgeBase
/srv/zammad/zammad/db/migrate/20210923172256_issue_2619_kb_header_link_color.rb:9:in `up'
/srv/zammad/.rbenv/versions/2.7.4/bin/bundle:23:in `load'
/srv/zammad/.rbenv/versions/2.7.4/bin/bundle:23:in `<main>'

Caused by:
NameError: uninitialized constant Issue2619KbHeaderLinkColor::KnowledgeBasis
Did you mean?  KnowledgeBase
/srv/zammad/zammad/db/migrate/20210923172256_issue_2619_kb_header_link_color.rb:9:in `up'
/srv/zammad/.rbenv/versions/2.7.4/bin/bundle:23:in `load'
/srv/zammad/.rbenv/versions/2.7.4/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### Steps to reproduce the behavior:

* `bundle install`
* `RAILS_ENV=production bundle exec rake db:migrate`

Yes I'm sure this is a bug and no feature request or a general question.

### Patch
```diff
--- 20210923172256_issue_2619_kb_header_link_color.rb	2021-09-29 03:08:43.658292375 -0700
+++ 20210923172256_issue_2619_kb_header_link_color.rb.fixed	2021-09-29 03:08:22.870112685 -0700
@@ -6,6 +6,6 @@

     add_column :knowledge_bases, :color_header_link, :string, limit: 25, null: false, default: 'hsl(206,8%,50%)'
     change_column_default :knowledge_bases, :color_header_link, nil
-    KnowledgeBasis.reset_column_information
+    KnowledgeBase.reset_column_information
   end
 end
```

**Comment by thorsteneckel** [comment]
Thanks for the fast report on this one @mzch 💯
