### ISSUE TITLE
UploadCacheCleanupJob does not execute

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3787]
### Infos:

* Used Zammad version: 5.0
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* It should run

### Actual behavior:

```
2.7.4 :001 > Scheduler.find_by(name: 'Delete old upload cache entries.')
 => #<Scheduler id: 25, name: "Delete old upload cache entries.", method: "UploadCacheCleanupJob.perform_now", period: 2629746, running: 0, last_run: "2021-10-04 21:27:48", prio: 2, pid: "", note: nil, error_message: "Failed to run UploadCacheCleanupJob.perform_now af...", status: "error", active: false, updated_by_id: 1, created_by_id: 1, created_at: "2021-10-04 21:20:43", updated_at: "2021-10-04 21:27:49">
2.7.4 :002 > UploadCacheCleanupJob.perform_now
Traceback (most recent call last):
        3: from (irb):2
        2: from app/jobs/upload_cache_cleanup_job.rb:7:in `perform'
        1: from app/jobs/upload_cache_cleanup_job.rb:15:in `store_object_id'
NoMethodError (undefined method `id' for nil:NilClass)
2.7.4 :003 > Store::Object.pluck(:name)
 => ["Avatar::User::Resize", "Ticket::Article"]
 ```

### Steps to reproduce the behavior:

`UploadCacheCleanupJob.perform_now`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
regression of https://github.com/zammad/zammad/commit/4ab01e36381df0fbc9e1ee892e31edeecaf9e51d
