### ISSUE TITLE
OS package upgrade fails (activity_stream_object_id)

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3797]
### Infos:

* Used Zammad version: 5.0.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Upgrade without issues

### Actual behavior:

* In certain cases OS package updates fails 

```
== 20210823112140 Issue2455FollowUpAssignment: migrating ======================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::NotNullViolation: ERROR:  null value in column "activity_stream_type_id" violates not-null constraint
DETAIL:  Failing row contains (18016, null, 5, 3, null, 2, 3, 2021-10-05 10:03:50.262, 2021-10-05 10:03:50.28).
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `async_exec'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `block (2 levels) in exec_no_cache'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:674:in `block in exec_no_cache'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:728:in `block (2 levels) in log'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:727:in `block in log'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `log'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:673:in `exec_no_cache'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:656:in `execute_and_clear'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `exec_query'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:135:in `exec_insert'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:132:in `exec_insert'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/composite_primary_keys-12.0.10/lib/composite_primary_keys/connection_adapters/abstract/database_statements.rb:6:in `insert'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/persistence.rb:375:in `_insert_record'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/composite_primary_keys-12.0.10/lib/composite_primary_keys/persistence.rb:64:in `_create_record'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/counter_cache.rb:166:in `_create_record'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/locking/optimistic.rb:79:in `_create_record'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/attribute_methods/dirty.rb:211:in `_create_record'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/callbacks.rb:331:in `block in _create_record'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:825:in `_run_create_callbacks'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/callbacks.rb:331:in `_create_record'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/timestamp.rb:110:in `_create_record'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/persistence.rb:905:in `create_or_update'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/callbacks.rb:327:in `block in create_or_update'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/callbacks.rb:327:in `create_or_update'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/timestamp.rb:128:in `create_or_update'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/persistence.rb:470:in `save'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/validations.rb:47:in `save'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:314:in `block in save'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:314:in `save'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/suppressor.rb:44:in `save'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/persistence.rb:38:in `create'
/opt/zammad/app/models/activity_stream.rb:82:in `add'
/opt/zammad/app/models/application_model/can_activity_stream_log.rb:46:in `activity_stream_log'
/opt/zammad/app/models/concerns/has_activity_stream_log.rb:49:in `activity_stream_update'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:238:in `block in halting_and_conditional'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:517:in `block in invoke_after'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:517:in `each'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:517:in `invoke_after'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:825:in `_run_update_callbacks'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/callbacks.rb:335:in `_update_record'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/timestamp.rb:123:in `_update_record'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/persistence.rb:905:in `create_or_update'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/callbacks.rb:327:in `block in create_or_update'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/autosave_association.rb:366:in `around_save_collection_association'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/callbacks.rb:327:in `create_or_update'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/timestamp.rb:128:in `create_or_update'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/persistence.rb:470:in `save'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/validations.rb:47:in `save'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:314:in `block in save'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:314:in `save'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/suppressor.rb:44:in `save'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/persistence.rb:621:in `block in update'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/persistence.rb:619:in `update'
/opt/zammad/db/migrate/20210823112140_issue_2455_follow_up_assignment.rb:9:in `block in change'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/relation/batches.rb:70:in `each'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/relation/batches.rb:70:in `block in find_each'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/relation/batches.rb:222:in `loop'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/relation/batches.rb:222:in `in_batches'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/relation/batches.rb:69:in `find_each'
/opt/zammad/db/migrate/20210823112140_issue_2455_follow_up_assignment.rb:8:in `change'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:828:in `exec_migration'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:811:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:810:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1002:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1361:in `block in ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:212:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1361:in `ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1280:in `each'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1229:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1229:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1061:in `up'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/migration.rb:1036:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/railties/databases.rake:84:in `each'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
/opt/zammad/bin/bundle:5:in `load'
/opt/zammad/bin/bundle:5:in `<main>'
```

**Comment by MrGeneration** [comment]
`Cache.clear` was run before? I didn't have this kind of issue.

**Comment by martini** [comment]
JFI: I did have it 2 times in the last 2 days.

**Comment by martini** [comment]
Just as reference https://github.com/zammad/zammad/issues/3786
