### ISSUE TITLE
ActionController::UnknownHttpMethod FRAGE

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad#3807]
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): ubuntu package
* Operating system: ubuntu 20.04
* Database + version: psotgres 13
* Elasticsearch version: 7.15.0
* Browser + version: Chrome latest

### Expected behavior:

* Ticket should close when a macro is executed

### Actual behavior:

* Nothing happens!
In Log i found:
```
I, [2021-10-13T09:15:39.385335 #2269309-187240]  INFO -- : Processing by TagsController#add as JSON
I, [2021-10-13T09:15:39.385387 #2269309-187240]  INFO -- :   Parameters: {"object"=>"Ticket", "o_id"=>28917, "item"=>"DeleteAfter2Months"}
F, [2021-10-13T09:15:39.387520 #2269309-174480] FATAL -- :
[c8e8823b-340e-4855-b9f1-02ebf22490c5] ActionController::UnknownHttpMethod (FRAGE, accepted HTTP methods are OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE, CONNECT, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK, VERSION-CONTROL, REPORT, CHECKOUT, CHECKIN, UNCHECKOUT, MKWORKSPACE, UPDATE, LABEL, MERGE, BASELINE-CONTROL, MKACTIVITY, ORDERPATCH, ACL, SEARCH, MKCALENDAR, and PATCH):
[c8e8823b-340e-4855-b9f1-02ebf22490c5]
[c8e8823b-340e-4855-b9f1-02ebf22490c5] actionpack (6.0.4.1) lib/action_dispatch/http/request.rb:433:in `check_method'
[c8e8823b-340e-4855-b9f1-02ebf22490c5] actionpack (6.0.4.1) lib/action_dispatch/http/request.rb:145:in `request_method'
[c8e8823b-340e-4855-b9f1-02ebf22490c5] rack (2.2.3) lib/rack/request.rb:187:in `head?'
[c8e8823b-340e-4855-b9f1-02ebf22490c5] actionpack (6.0.4.1) lib/action_dispatch/journey/router.rb:113:in `find_routes'
[c8e8823b-340e-4855-b9f1-02ebf22490c5] actionpack (6.0.4.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[c8e8823b-340e-4855-b9f1-02ebf22490c5] actionpack (6.0.4.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
[c8e8823b-340e-4855-b9f1-02ebf22490c5] omniauth (1.9.1) lib/omniauth/strategy.rb:420:in `call_app!'
```

### Steps to reproduce the behavior:

* execute a makro by drag & drop

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by ThePatzen** [comment]
I found out that a custom field added to the ticket object type called "type" causes this issue!

**Comment by MrGeneration** [comment]
> I found out that a custom field added to the ticket object type called "type" causes this issue!

Would you care to provide said fields configuration so someone has the chance to try and reproduce it?

**Comment by ThePatzen** [comment]
Hi! For sure!

![image](https://user-images.githubusercontent.com/4540135/137153634-f1c818dc-4705-45e8-aa96-27230535dbd1.png)

After this is configured try to execute such a macro:
![image](https://user-images.githubusercontent.com/4540135/137153849-79e1b623-b7f0-45a7-a1a8-a1af1042fdcc.png)

It seems the Macro-Request uses this "type" as the HTTP Method!

**Comment by MrGeneration** [comment]
~~I'm sorry, however I'm unable to reproduce this with the given information.
To double tab and ensure SaaS and Debian is not the "saving" factor I even installed a fresh Ubuntu 20.04 as per documentation and tried to reproduce it there.~~

~~It's working in my environments and thus I'm suspecting the issue lays somewhere else.~~

**Comment by ThePatzen** [comment]
@MrGeneration have you now been able to reproduce it?

**Comment by MrGeneration** [comment]
Sorry I have to correct myself.
This requires the following situations to apply:
* available ticket object `type` (default field which is inactive by default)
* `type` set to any value that does not have special characters or spacings
* you *have to* use the ticket view's run macro functionality. This does not happen in ticket zooms
* the actions your macro runs do not matter

As example:
Set the ticket in question to type value `burn` (`frage` as in original`).
Now go to your overview and drop the affected ticket on any macro you want to and have a look into your production log.


```
I, [2021-10-13T17:05:51.751993 #670-174880]  INFO -- : Started POST "/api/v1/tags/add" for 192.168.2.19 at 2021-10-13 17:05:51 +0000
I, [2021-10-13T17:05:51.753672 #670-174820]  INFO -- : Started FRAGE "/api/v1/tickets/1" for 192.168.2.19 at 2021-10-13 17:05:51 +0000
I, [2021-10-13T17:05:51.756594 #670-174880]  INFO -- : Processing by TagsController#add as JSON
I, [2021-10-13T17:05:51.756653 #670-174880]  INFO -- :   Parameters: {"object"=>"Ticket", "o_id"=>1, "item"=>"Ticket löschen"}
F, [2021-10-13T17:05:51.758517 #670-174820] FATAL -- :
[312be095-af4a-4e25-b280-bfad07be55bc] ActionController::UnknownHttpMethod (FRAGE, accepted HTTP methods are OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE, CONNECT, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK, VERSION-CONTROL, REPORT, CHECKOUT, CHECKIN, UNCHECKOUT, MKWORKSPACE, UPDATE, LABEL, MERGE, BASELINE-CONTROL, MKACTIVITY, ORDERPATCH, ACL, SEARCH, MKCALENDAR, and PATCH):
[312be095-af4a-4e25-b280-bfad07be55bc]
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/http/request.rb:433:in `check_method'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/http/request.rb:145:in `request_method'
[312be095-af4a-4e25-b280-bfad07be55bc] rack (2.2.3) lib/rack/request.rb:187:in `head?'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/journey/router.rb:113:in `find_routes'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:420:in `call_app!'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth-saml (1.10.3) lib/omniauth/strategies/saml.rb:86:in `other_phase'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:190:in `call!'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] rack (2.2.3) lib/rack/etag.rb:27:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] rack (2.2.3) lib/rack/head.rb:12:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
[312be095-af4a-4e25-b280-bfad07be55bc] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/middleware/cookies.rb:654:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[312be095-af4a-4e25-b280-bfad07be55bc] activesupport (6.0.4.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] railties (6.0.4.1) lib/rails/rack/logger.rb:37:in `call_app'
[312be095-af4a-4e25-b280-bfad07be55bc] railties (6.0.4.1) lib/rails/rack/logger.rb:26:in `block in call'
[312be095-af4a-4e25-b280-bfad07be55bc] activesupport (6.0.4.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
[312be095-af4a-4e25-b280-bfad07be55bc] activesupport (6.0.4.1) lib/active_support/tagged_logging.rb:28:in `tagged'
[312be095-af4a-4e25-b280-bfad07be55bc] activesupport (6.0.4.1) lib/active_support/tagged_logging.rb:80:in `tagged'
[312be095-af4a-4e25-b280-bfad07be55bc] railties (6.0.4.1) lib/rails/rack/logger.rb:26:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] activesupport (6.0.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/middleware/static.rb:126:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] actionpack (6.0.4.1) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] railties (6.0.4.1) lib/rails/engine.rb:527:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] railties (6.0.4.1) lib/rails/railtie.rb:190:in `public_send'
[312be095-af4a-4e25-b280-bfad07be55bc] railties (6.0.4.1) lib/rails/railtie.rb:190:in `method_missing'
[312be095-af4a-4e25-b280-bfad07be55bc] puma (4.3.10) lib/puma/configuration.rb:228:in `call'
[312be095-af4a-4e25-b280-bfad07be55bc] puma (4.3.10) lib/puma/server.rb:718:in `handle_request'
[312be095-af4a-4e25-b280-bfad07be55bc] puma (4.3.10) lib/puma/server.rb:472:in `process_client'
[312be095-af4a-4e25-b280-bfad07be55bc] puma (4.3.10) lib/puma/server.rb:328:in `block in run'
[312be095-af4a-4e25-b280-bfad07be55bc] puma (4.3.10) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
W, [2021-10-13T17:05:51.779434 #670-174880]  WARN -- : Scoped order is ignored, it's forced to be batch order.
I, [2021-10-13T17:05:51.799172 #670-174880]  INFO -- : Completed 201 Created in 42ms (Views: 0.2ms | ActiveRecord: 15.9ms | Allocations: 16832)
I, [2021-10-13T17:05:52.596095 #670-174920]  INFO -- : Started GET "/api/v1/tickets/1?full=true&_=1634144722117" for 192.168.2.19 at 2021-10-13 17:05:52 +0000
```

Just for entertainment reasons I added a new value "Burn" which works amazingly good:
```
I, [2021-10-13T17:09:09.279417 #670-174880]  INFO -- : Started POST "/api/v1/tags/add" for 192.168.2.19 at 2021-10-13 17:09:09 +0000
I, [2021-10-13T17:09:09.281895 #670-173660]  INFO -- : Started BURN "/api/v1/tickets/1" for 192.168.2.19 at 2021-10-13 17:09:09 +0000
I, [2021-10-13T17:09:09.285945 #670-174880]  INFO -- : Processing by TagsController#add as JSON
I, [2021-10-13T17:09:09.286324 #670-174880]  INFO -- :   Parameters: {"object"=>"Ticket", "o_id"=>1, "item"=>"Ticket löschen"}
F, [2021-10-13T17:09:09.288641 #670-173660] FATAL -- :
[71bfc7e9-2237-4707-957a-f5077ce2786e] ActionController::UnknownHttpMethod (BURN, accepted HTTP methods are OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE, CONNECT, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK, VERSION-CONTROL, REPORT, CHECKOUT, CHECKIN, UNCHECKOUT, MKWORKSPACE, UPDATE, LABEL, MERGE, BASELINE-CONTROL, MKACTIVITY, ORDERPATCH, ACL, SEARCH, MKCALENDAR, and PATCH):
[71bfc7e9-2237-4707-957a-f5077ce2786e]
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/http/request.rb:433:in `check_method'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/http/request.rb:145:in `request_method'
[71bfc7e9-2237-4707-957a-f5077ce2786e] rack (2.2.3) lib/rack/request.rb:187:in `head?'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/journey/router.rb:113:in `find_routes'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:420:in `call_app!'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth-saml (1.10.3) lib/omniauth/strategies/saml.rb:86:in `other_phase'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:190:in `call!'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] rack (2.2.3) lib/rack/etag.rb:27:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] rack (2.2.3) lib/rack/head.rb:12:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
[71bfc7e9-2237-4707-957a-f5077ce2786e] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/middleware/cookies.rb:654:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] activesupport (6.0.4.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] railties (6.0.4.1) lib/rails/rack/logger.rb:37:in `call_app'
[71bfc7e9-2237-4707-957a-f5077ce2786e] railties (6.0.4.1) lib/rails/rack/logger.rb:26:in `block in call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] activesupport (6.0.4.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
[71bfc7e9-2237-4707-957a-f5077ce2786e] activesupport (6.0.4.1) lib/active_support/tagged_logging.rb:28:in `tagged'
[71bfc7e9-2237-4707-957a-f5077ce2786e] activesupport (6.0.4.1) lib/active_support/tagged_logging.rb:80:in `tagged'
[71bfc7e9-2237-4707-957a-f5077ce2786e] railties (6.0.4.1) lib/rails/rack/logger.rb:26:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] activesupport (6.0.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/middleware/static.rb:126:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] actionpack (6.0.4.1) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] railties (6.0.4.1) lib/rails/engine.rb:527:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] railties (6.0.4.1) lib/rails/railtie.rb:190:in `public_send'
[71bfc7e9-2237-4707-957a-f5077ce2786e] railties (6.0.4.1) lib/rails/railtie.rb:190:in `method_missing'
[71bfc7e9-2237-4707-957a-f5077ce2786e] puma (4.3.10) lib/puma/configuration.rb:228:in `call'
[71bfc7e9-2237-4707-957a-f5077ce2786e] puma (4.3.10) lib/puma/server.rb:718:in `handle_request'
[71bfc7e9-2237-4707-957a-f5077ce2786e] puma (4.3.10) lib/puma/server.rb:472:in `process_client'
[71bfc7e9-2237-4707-957a-f5077ce2786e] puma (4.3.10) lib/puma/server.rb:328:in `block in run'
[71bfc7e9-2237-4707-957a-f5077ce2786e] puma (4.3.10) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
W, [2021-10-13T17:09:09.333412 #670-174880]  WARN -- : Scoped order is ignored, it's forced to be batch order.
I, [2021-10-13T17:09:09.351861 #670-174880]  INFO -- : Completed 201 Created in 65ms (Views: 0.1ms | ActiveRecord: 34.4ms | Allocations: 16828)
```

**Comment by MrGeneration** [comment]
Side note for developers, this seems to come from JS context not rails:
```
BURN /api/v1/tickets/1 HTTP/1.1
Host: 172.16.16.67
Connection: keep-alive
Content-Length: 231
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/javascript, */*; q=0.01
X-CSRF-Token: XXXXXXXX
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
Content-Type: application/json
Origin: http://172.16.16.67
Referer: http://172.16.16.67/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,de;q=0.8
Cookie: _zammad_session_XXXXXXX
```

**Comment by mantas** [comment]
Yes, looks like Spine issue

**Comment by MrGeneration** [comment]
Just cross checked against Zammad 4.1: It was introduced with 5.x

**Comment by mantas** [comment]
Interesting. I'm testing a possible fix now which is not related to 5.x at all :(

**Comment by mantas** [comment]
Actually, it was introduced in 5.x and my initial fix was just trying to counteract that... :|

**Comment by rolfschmidt** [comment]
Hi @ThePatzen ,
fix should be available tomorrow maybe you can update and try if the bulk action works then for you :)
