### ISSUE TITLE
Scheduler crashes immediately after starting because of uninitialized constant TicketCreateScreenJob

### ISSUE THREAD

**Issue by TokkCorp** [zammad/zammad#3847]
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 18.04 Kernel 4.15.0
* Database + version: mysql  5.7.36
* Elasticsearch version: 7.15.2
* Browser + version: Chrome 95.0.4

### Expected behavior:

* Scheduler should start without error

### Actual behavior:

* Scheduler starts, crashes. Cycle continues 

sceduler_err.log shows the following: 

```
bundler: failed to load command: script/scheduler.rb (script/scheduler.rb)
/opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/inflector/methods.rb:282:in `const_get': uninitialized constant TicketCreateScreenJob (NameError)
Did you mean?  TicketUserTicketCounterJob
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/inflector/methods.rb:282:in `block in constantize'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/inflector/methods.rb:280:in `each'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/inflector/methods.rb:280:in `inject'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/inflector/methods.rb:280:in `constantize'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.4.1/lib/active_job/core.rb:51:in `deserialize'
        from /opt/zammad/config/initializers/delayed_jobs_ensure_active_job_lock_removal.rb:15:in `remove_active_job_lock'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:428:in `block in make_lambda'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:238:in `block in halting_and_conditional'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:517:in `block in invoke_after'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:517:in `each'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:517:in `invoke_after'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/callbacks.rb:825:in `_run_destroy_callbacks'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/callbacks.rb:309:in `destroy'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:310:in `block in destroy'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:212:in `transaction'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/transactions.rb:310:in `destroy'
        from /opt/zammad/app/models/scheduler.rb:197:in `cleanup_delayed'
        from /opt/zammad/app/models/scheduler.rb:147:in `block (3 levels) in cleanup_delayed_jobs'
        from /opt/zammad/lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
        from /opt/zammad/app/models/scheduler.rb:146:in `block (2 levels) in cleanup_delayed_jobs'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/relation/delegation.rb:88:in `each'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.4.1/lib/active_record/relation/delegation.rb:88:in `each'
        from /opt/zammad/app/models/scheduler.rb:145:in `block in cleanup_delayed_jobs'
        from /opt/zammad/lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
        from /opt/zammad/app/models/scheduler.rb:143:in `cleanup_delayed_jobs'
        from /opt/zammad/app/models/scheduler.rb:130:in `cleanup'
        from /opt/zammad/app/models/scheduler.rb:27:in `threads'
        from script/scheduler.rb:75:in `block in <top (required)>'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/daemons-1.4.1/lib/daemons/application.rb:277:in `block in start_proc'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/daemons-1.4.1/lib/daemons/application.rb:286:in `start_proc'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/daemons-1.4.1/lib/daemons/application.rb:307:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/daemons-1.4.1/lib/daemons/controller.rb:56:in `run'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/daemons-1.4.1/lib/daemons.rb:199:in `block in run_proc'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/daemons-1.4.1/lib/daemons/cmdline.rb:124:in `catch_exceptions'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/daemons-1.4.1/lib/daemons.rb:198:in `run_proc'
        from script/scheduler.rb:55:in `<top (required)>'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
        from /opt/zammad/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
        from /opt/zammad/bin/bundle:5:in `load'
        from /opt/zammad/bin/bundle:5:in `<main>'
```

production.log consists of the following blocks: 

```
I, [2021-11-11T11:40:22.421776 #14821-5220]  INFO -- : Using File as web socket session store.
I, [2021-11-11T11:40:22.510900 #14821-5220]  INFO -- : Setting.set('product_logo', "2c51d667d7e2edb3d9cdaaecf56e778e.png")
I, [2021-11-11T11:40:23.670407 #14821-5220]  INFO -- : Setting.set('models_searchable', ["KnowledgeBase::Answer::Translation", "Chat::Session", "Ticket", "Organization", "User"])
I, [2021-11-11T11:40:24.209289 #14821-5220]  INFO -- : Scheduler started.
I, [2021-11-11T11:40:24.210629 #14821-5220]  INFO -- : Cleanup of left over locked delayed jobs 2021-11-11 10:40:24 UTC started.
I, [2021-11-11T11:40:24.217748 #14821-5220]  INFO -- : Checking left over delayed job #<Delayed::Backend::ActiveRecord::Job id: 439, priority: 200, attempts: 0, handler: "--- !ruby/object:ActiveJob::QueueAdapters::Delayed...", last_error: nil, run_at: "2021-11-04 10:35:57", locked_at: "2021-11-11 09:36:37", failed_at: nil, locked_by: "host:<our host> pid:4056", queue: "default", created_at: "2021-11-04 10:35:47", updated_at: "2021-11-04 10:35:47"> started.
I, [2021-11-11T11:40:24.220710 #14821-5220]  INFO -- : script/scheduler.rb stopped.
I, [2021-11-11T11:40:25.427706 #14848-5220]  INFO -- : Using Zammad's file store as Rails cache store.
I, [2021-11-11T11:40:25.427763 #14848-5220]  INFO -- : Using File as web socket session store.
I, [2021-11-11T11:40:25.516147 #14848-5220]  INFO -- : Setting.set('product_logo', "2c51d667d7e2edb3d9cdaaecf56e778e.png")
I, [2021-11-11T11:40:26.678792 #14848-5220]  INFO -- : Setting.set('models_searchable', ["KnowledgeBase::Answer::Translation", "Chat::Session", "Ticket", "Organization", "User"])
I, [2021-11-11T11:40:27.264027 #14848-5220]  INFO -- : Scheduler started.
I, [2021-11-11T11:40:27.266262 #14848-5220]  INFO -- : Cleanup of left over locked delayed jobs 2021-11-11 10:40:27 UTC started.
I, [2021-11-11T11:40:27.301127 #14848-5220]  INFO -- : Checking left over delayed job #<Delayed::Backend::ActiveRecord::Job id: 439, priority: 200, attempts: 0, handler: "--- !ruby/object:ActiveJob::QueueAdapters::Delayed...", last_error: nil, run_at: "2021-11-04 10:35:57", locked_at: "2021-11-11 09:36:37", failed_at: nil, locked_by: "host:<our host> pid:4056", queue: "default", created_at: "2021-11-04 10:35:47", updated_at: "2021-11-04 10:35:47"> started.
I, [2021-11-11T11:40:27.304146 #14848-5220]  INFO -- : script/scheduler.rb stopped.
```

### Steps to reproduce the behavior:

* I don't know, sorry

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
That's caused by a stuck delayed job that was created during or before upgrade.

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by TokkCorp** [comment]
@MrGeneration yes there is this job, but the problem lies elsewhere. I can't even delete this job from the cli without getting the same error message
```
irb(main):015:0> Delayed::Job.find(439).destroy
Traceback (most recent call last):
        2: from (irb):15
        1: from config/initializers/delayed_jobs_ensure_active_job_lock_removal.rb:15:in `remove_active_job_lock'
NameError (uninitialized constant TicketCreateScreenJob)
Did you mean?  TicketUserTicketCounterJob
```

**Comment by MrGeneration** [comment]
This is a technical question. It really is.
You're deleting wrong.
