### ISSUE TITLE
undefined method error for the incoming telegram messages

### ISSUE THREAD

**Issue by nimaadib** [zammad/zammad#3948]
### Infos:

* Used Zammad version: 5.1.x 
* Installation method (source, package, ..): Source (develop branch)
* Operating system: Ubuntu 16.04.7 LTS
* Database + version: Postgresql 11.9
* Elasticsearch version: 7.17.0 amd64
* Browser + version: Google chrome 97

### Expected behavior:

* I have added a telegram bot and an email address as the incoming channels. 

### Actual behavior:

* I'm getting these error messages reportedly:
```
E, [2022-02-02T17:26:22.874797 #13551-808060] ERROR -- : undefined method `[]' for nil:NilClass (NoMethodError)
lib/telegram.rb:719:in `to_group'
app/controllers/channels_telegram_controller.rb:71:in `webhook'
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2022-02-02T17:26:22.891287 #13551-808060] ERROR -- : Error ID yIr7Rtjf: undefined method `[]' for nil:NilClass
E, [2022-02-02T17:26:24.166352 #13551-807060] ERROR -- : undefined method `[]' for nil:NilClass (NoMethodError)
lib/telegram.rb:719:in `to_group'
app/controllers/channels_telegram_controller.rb:71:in `webhook'
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2022-02-02T17:26:24.187825 #13551-807060] ERROR -- : Error ID 0kWungOL: undefined method `[]' for nil:NilClass
E, [2022-02-02T17:26:26.709197 #13551-913860] ERROR -- : PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
 (ActiveRecord::StatementInvalid)
lib/transaction_dispatcher.rb:33:in `perform'
lib/transaction_dispatcher.rb:17:in `commit'
app/models/transaction.rb:51:in `finish_transaction'
app/models/transaction.rb:19:in `ensure in block in execute'
app/models/transaction.rb:19:in `block in execute'
app/models/transaction.rb:14:in `execute'
app/models/transaction.rb:26:in `execute'
lib/telegram.rb:747:in `to_group'
```
* Also, I could not reply to the tickets that have been created before upgrading zammad. I have been getting this error message:
```
Attribute 'activestreamtype_id' is required!
```

### Steps to reproduce the behavior:

* I deployed zammad from source with a DB from an older zammad version (3.2) and ran db:migrate during the deployment. I checked `bundle exec rake db:migrate:status` and all of the migrations were `up`. This is the last entry in the list: `up     20220131135531  Issue3940 add index`. 
* I ran `ActiveRecord::Base.connection.execute 'ROLLBACK'` command on `rails console` and this was the output: 
```
WARNING:  there is no transaction in progress
 => #<PG::Result:0x0000000008b07338 status=PGRES_COMMAND_OK ntuples=0 nfields=0 cmd_tuples=0>
 ```
 * another test:
 ```
 2.7.4 :002"> ActiveRecord::Base.connection.execute("
2.7.4 :003">   SELECT COUNT(*)
2.7.4 :004">     FROM pg_class c
2.7.4 :005">       LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
2.7.4 :006">         WHERE c.relkind IN ('r','v','m')
2.7.4 :007">           AND c.relname = 'schema_migrations'
2.7.4 :008">             AND n.nspname = ANY (current_schemas(false))
2.7.4 :009 >               ")
 => #<PG::Result:0x000000000698aac0 status=PGRES_TUPLES_OK ntuples=1 nfields=1 cmd_tuples=1>
 ```

It seems the Telegram library cannot handle this type of Telegram messages:  [my_chat_member](https://core.telegram.org/bots/api#chatmemberupdated)

Yes I'm sure this is a bug and no feature request or a general question.

### update
Error logs on DB side:
```
2022-02-02 20:49:20 UTC:10.0.0.193(37188):redacted@redacted:[30423]:ERROR: null value in column "activity_stream_type_id" violates not-null constraint
2022-02-02 20:49:20 UTC:10.0.0.193(37188):redacted@redacted:[30423]:DETAIL: Failing row contains (291832, null, 8, null, 5, 57787, 14763, 2022-02-02 20:49:20.962, 2022-02-02 20:49:20.99).
2022-02-02 20:49:20 UTC:10.0.0.193(37188):redacted@redacted:[30423]:STATEMENT: INSERT INTO "activity_streams" ("activity_stream_object_id", "group_id", "o_id", "created_by_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"
2022-02-02 20:49:20 UTC:10.0.0.193(37188):redacted@redacted:[30423]:ERROR: current transaction is aborted, commands ignored until end of transaction block
2022-02-02 20:49:20 UTC:10.0.0.193(37188):redacted@redacted:[30423]:STATEMENT: SELECT "settings".* FROM "settings" WHERE "settings"."area" = $1 ORDER BY "settings"."name" ASC
```

### update 2
after these steps the `activity_stream_type_id` issue has been resolved.
* zammad run rails Cache.clear
* zammad run rake db:migrate

but this error is still hapenning:
```
E, [2022-02-02T21:22:00.439499 #23765-175560] ERROR -- : undefined method `[]' for nil:NilClass (NoMethodError)
lib/telegram.rb:719:in `to_group'
app/controllers/channels_telegram_controller.rb:71:in `webhook'
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2022-02-02T21:22:00.443194 #23765-175560] ERROR -- : Error ID aGJAGz9T: undefined method `[]' for nil:NilClass
```

**Comment by acrix** [comment]
same for me
zammad  5.2.1-1662030964.bd64be79.bullseye

when zammad send message to bot:

```
INFO -- : Started POST "/api/v1/channels_telegram_webhook/4hg_PsqMvzX-LA?bid=5605209461" for ***
INFO -- : Processing by ChannelsTelegramController#webhook as HTML
INFO -- :   Parameters: {***}
ERROR -- : undefined method `[]' for nil:NilClass (NoMethodError)
lib/telegram.rb:720:in `to_group'
app/controllers/channels_telegram_controller.rb:71:in `webhook'
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
ERROR -- : Error ID ****: undefined method `[]' for nil:NilClass
INFO -- :   Rendered inline template (Duration: 0.2ms | Allocations: 236)
INFO -- : Completed 500 Internal Server Error in 8ms (Views: 0.4ms | ActiveRecord: 2.9ms | Allocations: 4136)

```

and no messages in telegram
from telegram to zammad messages ok

**Comment by irl** [comment]
Hi, I just started seeing this on my helpdesk today. It was working fine but now no new messages are coming in.

**Comment by irl** [comment]
It seems 24 hours after the failure, that update was dropped by Telegram which then tried to send the next update in the queue. The next update was accepted without issue and then the rest of the queue was submitted. It'd be neat to find a way to get Telegram to just drop the first event from the queue so that you can unblock this manually, or have a way to get Zammad to just blindly accept and drop the next update to get it to unblock.

Otherwise I see there were some updates 9 days ago that changed the gem used for the Telegram API and I'm hoping that those could fix this issue. The commit message didn't really have much context but I guess this new gem is more actively maintained?

I don't know how to cause these my_chat_member messages to be generated so not sure how to reproduce the issue.

Any advice on workarounds or reproduction of the error would be appreciated.

**Comment by cautopartes** [comment]
Cannot verify this issue with a current Zammad version (5.3.1-1672324740.71dd35f8.bullseye). 
Receiving and sending of Telegram messages is doing fine.

**Comment by martini** [comment]
@nimaadib @acrix @irl to be able to verify this, we need an example payload which is/was sent form telegram to Zammad.

The parameters section from `log/production.log`:

```
INFO -- :   Parameters: {***}
```

Without this we can't reproduce it.
