### ISSUE TITLE
API calls on shared draft endpoints return ugly error messages if draft does not exist

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4011]
### Infos:

* Used Zammad version: develop 5.1 (as on 13th March)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Trying to retrieve non exisisting shared drafts provides a meaningful error message.

### Actual behavior:

When trying to retrieve a not existing shared draft, Zammad returns this:

```
{
    "error": "Couldn't find Ticket::SharedDraftStart with 'id'=2 [WHERE \"ticket_shared_draft_starts\".\"group_id\" IN ($1, $2, $3)]",
    "error_human": "Couldn't find Ticket::SharedDraftStart with 'id'=2 [WHERE \"ticket_shared_draft_starts\".\"group_id\" IN ($1, $2, $3)]"
}
```

The log output is also chunkier than it would need to be in my opinion.
```
I, [2022-03-13T22:00:33.309967 #8504-188960] INFO -- : Started GET "/api/v1/tickets/shared_drafts/2" for 127.0.0.1 at 2022-03-13 22:00:33 +0100
I, [2022-03-13T22:00:33.313701 #8504-188960] INFO -- : Processing by TicketsSharedDraftStartsController#show as */*
I, [2022-03-13T22:00:33.313740 #8504-188960] INFO -- : Parameters: {"id"=>"2"}
E, [2022-03-13T22:00:33.345059 #8504-188960] ERROR -- : Couldn't find Ticket::SharedDraftStart with 'id'=2 [WHERE "ticket_shared_draft_starts"."group_id" IN ($1, $2, $3)] (ActiveRecord::RecordNotFound)
app/controllers/tickets_shared_draft_starts_controller.rb:17:in `show'
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
I, [2022-03-13T22:00:33.345992 #8504-188960] INFO -- : Completed 404 Not Found in 32ms (Views: 0.1ms | ActiveRecord: 13.7ms | Allocations: 12939)
```

### Steps to reproduce the behavior:

* Query shared drafts endpoint with an ID that's not yet existing. On fresh systems this will do: `/api/v1/tickets/shared_drafts/666`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
This cosmetic issue will be solved by GraphQL migration in the future. Proper fix would be too complicated at the moment.
