### ISSUE TITLE
Custom sort on select returns "undefined method `merge' " for older objects

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4086]
### Infos:

* Used Zammad version: 5.1.1 / stable (as of 13th March)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on Firefox and Opera
* Ticket: #10106518

### Expected behavior:

You can update any attribute that supports custom ordering after upgrading to Zammad 5.1.

### Actual behavior:

Updating an existing select field (pre 5.1) with custom order seems to break the data model and thus causes Zammad to not update the object in question.

Traceback:
```
I, [2022-05-13T18:21:53.924188 #31793-187140]  INFO -- : Processing by ObjectManagerAttributesController#execute_migrations as JSON
E, [2022-05-13T18:21:53.935580 #31793-187140] ERROR -- : undefined method `merge' for #<Array:0x000055a6b2cdd698> (NoMethodError)
app/models/object_manager/attribute.rb:540:in `attribute_historic_options'
app/models/object_manager/attribute.rb:601:in `block in migration_execute'
app/models/object_manager/attribute.rb:583:in `migration_execute'
app/controllers/object_manager_attributes_controller.rb:69:in `execute_migrations'
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
I, [2022-05-13T18:21:53.938464 #31793-187140]  INFO -- : Completed 500 Internal Server Error in 14ms (Views: 0.1ms | ActiveRecord: 3.6ms | Allocations: 10968)
```

The affect object is configured like so:
```
#<ObjectManager::Attribute:0x00005559d43d0df0
 id: 53,
 object_lookup_id: 2,
 name: "kategorie",
 display: "Problemart",
 data_type: "select",
 data_option:
  {"options"=>
    [{"name"=>"Sonstiges", "value"=>"Sonstiges"},
     {"name"=>"Hardware", "value"=>"Hardware"},
     {"name"=>"Software", "value"=>"Software"}],
   "default"=>"Sonstiges",
   "customsort"=>"on",
   "linktemplate"=>"",
   "null"=>true,
   "relation"=>"",
   "nulloption"=>true,
   "maxlength"=>255,
   "historical_options"=>
    [{"name"=>"Sonstiges", "value"=>"Sonstiges"},
     {"name"=>"Hardware", "value"=>"Hardware"},
     {"name"=>"Software", "value"=>"Software"}]},
 data_option_new:
  {"options"=>
    [{"name"=>"AHG_Farm", "value"=>"AHG_Farm"},
     {"name"=>"Hardware", "value"=>"Hardware"},
     {"name"=>"Lizenzen", "value"=>"Lizenzen"},
     {"name"=>"Locosoft", "value"=>"Locosoft"},
     {"name"=>"Office365", "value"=>"Office365"},
     {"name"=>"Software", "value"=>"Software"},
     {"name"=>"Sonstiges", "value"=>"Sonstiges"}],
   "default"=>"Sonstiges",
   "customsort"=>"on",
   "linktemplate"=>"",
   "null"=>true,
   "relation"=>"",
   "nulloption"=>true,
   "maxlength"=>255},
 editable: true,
 active: true,
 screens:
  {"create_middle"=>
    {"ticket.customer"=>
      {"shown"=>true, "required"=>false, "item_class"=>"column"},
     "ticket.agent"=>
      {"shown"=>true, "required"=>false, "item_class"=>"column"}},
   "edit"=>
    {"ticket.customer"=>{"shown"=>true, "required"=>false},
     "ticket.agent"=>{"shown"=>true, "required"=>false}}},
 to_create: false,
 to_migrate: false,
 to_delete: false,
 to_config: true,
 position: 902,
 created_by_id: 3,
 updated_by_id: 9,
 created_at: Mon, 14 Mar 2022 13:19:04 UTC +00:00,
 updated_at: Wed, 11 May 2022 11:47:14 UTC +00:00>
 ```

### Steps to reproduce the behavior:

* have Zammad 5 with a select object
* upgrade Zammad to 5.1
* update the select object to use custom order (shuffle your order)

Note: 
I am not sure if this is caused by previously set default values as the default check is being lost during dragging the order.
I explicetely had to copy `data_option` from the customers instance to be able to cause above error.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
This is related to https://github.com/zammad/zammad/issues/4027. Looks like my fix only fixes the situation for the new data but in the time it was broken it  broke the data in existing fields -> historical_options. I will try to fix this asap.
