### ISSUE TITLE
Latest upgrade to 5.1 is not possible

### ISSUE THREAD

**Issue by martini** [zammad/zammad#4097]
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* execute `zammad run rake db:migrate` without any issues

### Actual behavior:

* `zammad run rake db:migrate`
```
 rake db:migrate
== 20220524074118 Issue4089FixDraftAttribute: migrating =======================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `update' for nil:NilClass
db/migrate/20220524074118_issue4089_fix_draft_attribute.rb:8:in `change'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:828:in `exec_migration'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:811:in `block in migrate'
gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:810:in `migrate'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1002:in `migrate'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1361:in `block in ddl_transaction'
gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
gems/activesupport-6.0.4.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
gems/activesupport-6.0.4.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
gems/activesupport-6.0.4.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
gems/activesupport-6.0.4.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
gems/activesupport-6.0.4.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
gems/activerecord-6.0.4.8/lib/active_record/transactions.rb:212:in `transaction'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1361:in `ddl_transaction'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1280:in `each'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1280:in `migrate_without_lock'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1229:in `block in migrate'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1382:in `with_advisory_lock'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1229:in `migrate'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1061:in `up'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1036:in `migrate'
gems/activerecord-6.0.4.8/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
gems/activerecord-6.0.4.8/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
gems/activerecord-6.0.4.8/lib/active_record/railties/databases.rake:84:in `each'
gems/activerecord-6.0.4.8/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
bin/ruby_executable_hooks:22:in `eval'
bin/ruby_executable_hooks:22:in `<main>'

Caused by:
NoMethodError: undefined method `update' for nil:NilClass
db/migrate/20220524074118_issue4089_fix_draft_attribute.rb:8:in `change'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:828:in `exec_migration'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:811:in `block in migrate'
gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:810:in `migrate'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1002:in `migrate'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1361:in `block in ddl_transaction'
gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
gems/activesupport-6.0.4.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
gems/activesupport-6.0.4.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
gems/activesupport-6.0.4.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
gems/activesupport-6.0.4.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
gems/activesupport-6.0.4.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
gems/activerecord-6.0.4.8/lib/active_record/transactions.rb:212:in `transaction'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1361:in `ddl_transaction'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1280:in `each'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1280:in `migrate_without_lock'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1229:in `block in migrate'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1382:in `with_advisory_lock'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1229:in `migrate'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1061:in `up'
gems/activerecord-6.0.4.8/lib/active_record/migration.rb:1036:in `migrate'
gems/activerecord-6.0.4.8/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
gems/activerecord-6.0.4.8/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
gems/activerecord-6.0.4.8/lib/active_record/railties/databases.rake:84:in `each'
gems/activerecord-6.0.4.8/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
bin/ruby_executable_hooks:22:in `eval'
bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
$ 
```

### Steps to reproduce the behavior:

* install earlier version of Zammad 5.1
* delete field `groups.shared_drafts` in the meantime (because it is editable)
* upgrade to latest Zammad 5.1

**Comment by rolfschmidt** [comment]
### Workaround (readd the field)

- Open console `zammad run rails c`

- Add field:

```ruby
UserInfo.current_user_id = 1
ObjectManager::Attribute.add(
  force:       true,
  object:      'Group',
  name:        'shared_drafts',
  display:     __('Shared Drafts'),
  data_type:   'active',
  data_option: {
    null:       false,
    default:    true,
    permission: ['admin.group'],
  },
  editable:    false,
  active:      true,
  screens:     {
    create: {
      '-all-' => {
        null: true,
      },
    },
    edit:   {
      '-all-': {
        null: false,
      },
    },
    view:   {
      '-all-' => {
        shown: false,
      },
    },
  },
  to_create:   false,
  to_migrate:  false,
  to_delete:   false,
  position:    1400,
)
ObjectManager::Attribute.migration_execute
```

Users are not supposed to delete this field, it was mistakenly set as editable.
