### ISSUE TITLE
bundle install error: imlib2 development headers are missing

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4228]
### Infos:

* Used Zammad version: develop (9aedb414d02efe8a26956eb5dce6d76a6c90714f)
* Installation method (source, package, ..): source
* Operating system: ubuntu 22.04
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* bundle install runs

### Actual behavior:

* bundle install returns error:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/rszr-1.3.0/ext/rszr
/home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/bin/ruby -I /home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0 -r
./siteconf20220826-8355-5vlj0t.rb extconf.rb
checking for Imlib2.h... no
imlib2 development headers are missing
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/bin/$(RUBY_BASE_NAME)
        --with-imlib2-config
        --without-imlib2-config
        --with-pkg-config
        --without-pkg-config

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/extensions/x86_64-linux/3.0.0/rszr-1.3.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/rszr-1.3.0 for inspection.
Results logged to /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/extensions/x86_64-linux/3.0.0/rszr-1.3.0/gem_make.out

  /home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:93:in `run'
  /home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:159:in `build_extension'
  /home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /home/ubuntu-rs/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/rubygems/installer.rb:837:in `build_extensions'
  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/source/rubygems.rb:207:in `install'
  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
/home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/installer/parallel_installer.rb:177:in `block in
worker_pool'
  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/worker.rb:62:in `apply_func'
  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/worker.rb:54:in `loop'
  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/worker.rb:54:in `process_queue'
  /home/ubuntu-rs/.rvm/gems/ruby-3.0.4/gems/bundler-2.3.16/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing rszr (1.3.0), and Bundler cannot continue.
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
`sudo apt-get install libimlib2-dev`

solves the issue
