### ISSUE TITLE
procmail failure Debian 8

### ISSUE THREAD

**Issue by symptog** [zammad/zammad#425]
Hi,

I want to use procmail to pipe mails into zammad, but I'm getting the follwing error:

```
procmail: Couldn't determine implicit lockfile from "rails"
/opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/zammad/config/boot.rb:3:in `<top (required)>'
        from /opt/zammad/bin/rails:3:in `require_relative'
        from /opt/zammad/bin/rails:3:in `<main>'
From root@localhost  Tue Nov 15 23:13:34 2016
 Subject: hdgdhktp
  Folder: /var/mail/zammad
```

.procmailrc
```
# --
# Pipe all emails into Zammad
# --
LOGFILE=$HOME/procmail.log
PATH=/opt/zammad/bin:/opt/zammad/vendor/bundle/bin:/sbin:/bin:/usr/sbin:/usr/bin:
:0 :
| rails r 'Channel::Driver::MailStdin.new(trusted: true)'
```

Did I miss anything?

**Comment by monotek** [comment]
Are you running the command as the zammad user?

**Comment by symptog** [comment]
as the procmail.log is created with `zammad:zammad` I assume that the procmailrc is run as user zammad.

I tested something:

I've created the rvm like in the [docs](https://zammad.org/documentation/appendix/install-source-debian) even as I installed zammad via the repo.
I've created the .bashrc:
```
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
source /home/zammad/.rvm/scripts/rvm
rvm --default use 2.3.1
```

and then running `rails r 'Channel::Driver::MailStdin.new(trusted: true)'` in an interactive shell workes fine.

However, not in procmail.

**Comment by monotek** [comment]
Could you try to change ":0 :" to ":0" in .procmailrc

**Comment by symptog** [comment]
the log shows this:
```
From tobias@localhost  Wed Nov 16 00:00:30 2016
 Subject: foobarbatz
  Folder: rails r Channel::Driver::MailStdin.new(trusted: true)             505
/opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/zammad/config/boot.rb:3:in `<top (required)>'
        from /opt/zammad/bin/rails:3:in `require_relative'
        from /opt/zammad/bin/rails:3:in `<main>'

```

**Comment by monotek** [comment]
To be honest, i did not tried it until now. Just started the docu and thinking it would work like on OTRS.
I'll try it tomorrow.

**Comment by monotek** [comment]
Just update the docs: https://docs.zammad.org/en/latest/channel-fetchmail.html

You have to add: the following lines to .procmailrc:

```
RAILS_ENV=production
GEM_PATH=/opt/zammad/vendor/bundle/ruby/2.3.0/
```
