### ISSUE TITLE
TypeError: params[(attribute.name + "_is_display_warning")] is not a function

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4309]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): all
* Operating system: all 
* Database + version: v
* Elasticsearch version: all
* Browser + version: chrome

### Expected behavior:

* No js error

### Actual behavior:

```
application.js:86395 Uncaught TypeError: params[(attribute.name + "_is_display_warning")] is not a function
    at App.UiElement.select.select.shouldDisplayWarn (application.js:86395:60)
    at App.UiElement.select.select.bindWarnDisplayListener (application.js:86384:27)
    at HTMLDivElement.<anonymous> (application.js:86375:26)
    at HTMLDivElement.dispatch (application.js:5431:27)
    at elemData.handle (application.js:5235:28)
```

### Steps to reproduce the behavior:

* Setup development system
* Open groups
* Create new group
* Set signature to default

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
probably regression of https://github.com/zammad/zammad/commit/250d0bbd5ed787ec2bd18af0739aaca9d665daca
