### ISSUE TITLE
Zammad assumes caller_locations's path exists on disk

### ISSUE THREAD

**Issue by eregon** [zammad/zammad#4356]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): source
* Operating system: RockyLinux 9
* Database + version: Postgresql 14
* Elasticsearch version:
* Browser + version:

https://github.com/zammad/zammad/blob/312d9168410f55c03fcb92a946bdfd388208d113/lib/mixin/required_sub_paths.rb#L7
assumes the first caller_locations's path exists on disk.
But this is not a guarantee, and for instance it fails like below on TruffleRuby.

It is also not a guarantee on CRuby, for instance:
```
$ ruby -v -e 'self.then { p caller_locations(1..1).first.path }'
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
"<internal:kernel>"
```

So that code needs to account for that possibility, either checking if the file exists or skipping callers which start with `<internal:`.

```
=> Booting Puma
=> Rails 6.1.7 application starting in production 
=> Run `bin/rails server --help` for more startup options
Exiting
<internal:core> core/errno.rb:48:in `handle': No such file or directory - <internal:core> core/module (Errno::ENOENT)
	from <internal:core> core/dir.rb:45:in `initialize'
	from <internal:core> core/dir.rb:154:in `open'
	from <internal:core> core/dir.rb:183:in `entries'
	from /opt/zammad/lib/mixin/required_sub_paths.rb:19:in `eager_load_recursive'
	from /opt/zammad/lib/mixin/required_sub_paths.rb:9:in `included'
	from <internal:core> core/module.rb:84:in `block in include'
	from <internal:core> core/array.rb:952:in `reverse_each'
	from <internal:core> core/module.rb:78:in `include'
	from /opt/zammad/app/models/form_schema/form.rb:4:in `<class:Form>'
	from /opt/zammad/app/models/form_schema/form.rb:3:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /usr/local/rvm/gems/ext-truffleruby/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
	from <internal:core> core/module.rb:108:in `const_get'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:288:in `block in constantize'
	from <internal:core> core/enumerable.rb:494:in `inject'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:284:in `constantize'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
	from /opt/zammad/lib/models.rb:44:in `block in all'
	from <internal:core> core/dir.rb:261:in `each'
	from <internal:core> core/dir.rb:261:in `glob'
	from /opt/zammad/lib/models.rb:34:in `all'
	from /opt/zammad/lib/models.rb:79:in `searchable'
	from /opt/zammad/config/initializers/models_searchable.rb:9:in `block in <top (required)>'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `instance_exec'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
	from <internal:core> core/throw_catch.rb:36:in `catch'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:199:in `block in halting'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `each'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `invoke_before'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/reloader.rb:88:in `prepare!'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /opt/zammad/graalvm/graalvm-ce-java17-22.3.0/languages/ruby/lib/mri/tsort.rb:228:in `block in tsort_each'
	from /opt/zammad/graalvm/graalvm-ce-java17-22.3.0/languages/ruby/lib/mri/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /opt/zammad/graalvm/graalvm-ce-java17-22.3.0/languages/ruby/lib/mri/tsort.rb:431:in `each_strongly_connected_component_from'
	from /opt/zammad/graalvm/graalvm-ce-java17-22.3.0/languages/ruby/lib/mri/tsort.rb:349:in `block in each_strongly_connected_component'
	from /opt/zammad/graalvm/graalvm-ce-java17-22.3.0/languages/ruby/lib/mri/tsort.rb:347:in `each'
	from /opt/zammad/graalvm/graalvm-ce-java17-22.3.0/languages/ruby/lib/mri/tsort.rb:347:in `each_strongly_connected_component'
	from /opt/zammad/graalvm/graalvm-ce-java17-22.3.0/languages/ruby/lib/mri/tsort.rb:226:in `tsort_each'
	from /opt/zammad/graalvm/graalvm-ce-java17-22.3.0/languages/ruby/lib/mri/tsort.rb:205:in `tsort_each'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
	from /opt/zammad/config/environment.rb:7:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /usr/local/rvm/gems/ext-truffleruby/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /usr/local/rvm/gems/ext-truffleruby/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
	from config.ru:5:in `<top (required)>'
	from /usr/local/rvm/gems/ext-truffleruby/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
	from /usr/local/rvm/gems/ext-truffleruby/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
	from /usr/local/rvm/gems/ext-truffleruby/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
	from /usr/local/rvm/gems/ext-truffleruby/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /usr/local/rvm/gems/ext-truffleruby/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
	from /usr/local/rvm/gems/ext-truffleruby/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
	from /usr/local/rvm/gems/ext-truffleruby/gems/rack-2.2.4/lib/rack/server.rb:312:in `block in start'
	from /usr/local/rvm/gems/ext-truffleruby/gems/rack-2.2.4/lib/rack/server.rb:379:in `handle_profiling'
	from /usr/local/rvm/gems/ext-truffleruby/gems/rack-2.2.4/lib/rack/server.rb:311:in `start'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:39:in `start'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	from <internal:core> core/kernel.rb:510:in `tap'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:135:in `perform'
	from /usr/local/rvm/gems/ext-truffleruby/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ext-truffleruby/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/rvm/gems/ext-truffleruby/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/command/base.rb:69:in `perform'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/command.rb:48:in `invoke'
	from /usr/local/rvm/gems/ext-truffleruby/gems/railties-6.1.7/lib/rails/commands.rb:18:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from bin/rails:10:in `<main>'
```

### Expected behavior:

*

### Actual behavior:

*

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by trnapster** [comment]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): source
* Operating system: RockyLinux 9
* Database + version: Postgresql 14

**Comment by mgruner** [comment]
Hi @eregon, thanks for the report. This should be fixed, by no longer using `caller_locations` any longer. May I ask how you found this, do you test software compatibility of certain Ruby programs with TruffleRuby?

**Comment by eregon** [comment]
@trnapster reported the issue to the GraalVM/TruffleRuby Slack channel
