### ISSUE TITLE
Can not use RSS feed in Microsoft Teams (invalid url)

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4403]
### Infos:

* Used Zammad version: 5.3.x.
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all
* Ticket#10119690

### Expected behavior:

* It should be possible to add the KB rss feed in microsoft teams

### Actual behavior:

* It shows that the URL is not valid

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
```
E, [2022-12-08T10:42:07.025181 #21482-102873760] ERROR -- : undefined local variable or method `given_token' for #<KnowledgeBase::FeedsController:0x0000000c5475e8> (NameError)
app/controllers/knowledge_base/feeds_controller.rb:59:in `effective_user'
app/controllers/knowledge_base/feeds_controller.rb:49:in `granular_scope'
app/controllers/knowledge_base/feeds_controller.rb:15:in `root'
config/initializers/ser_sla.rb:70:in `ser_sla_rebuild'
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
```
