### ISSUE TITLE
Email processing of messages with a lot of empty space results in a timeout

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad#4463]
### Used Zammad Version

5.3

### Environment

- Installation method: any
- Operating system: MacOS 13.1
- Database + version:  PostgreSQL 10.21
- Elasticsearch version: 7.14.2
- Browser + version: any

### Actual behaviour

When trying to import [test.eml.txt](https://github.com/zammad/zammad/files/10413385/test.eml.txt) HTML email a timeout is reached with the following error message:

```log
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/ae73599d9933855195eff6eb1e4a6057.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<Timeout::Error: execution expired>"
/opt/zammad/app/models/channel/email_parser.rb:138:in `rescue in process': #<Timeout::Error: execution expired> (RuntimeError)
/opt/zammad/lib/core_ext/string.rb:24:in `sub!'
/opt/zammad/lib/core_ext/string.rb:24:in `strip'
/opt/zammad/lib/core_ext/string.rb:328:in `html2html_strict'
/opt/zammad/app/models/channel/email_parser.rb:673:in `body_text'
/opt/zammad/app/models/channel/email_parser.rb:616:in `message_body_hash'
/opt/zammad/app/models/channel/email_parser.rb:89:in `parse'
/opt/zammad/app/models/channel/email_parser.rb:144:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:123:in `block in process'
/Users/user/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.1/lib/timeout.rb:189:in `block in timeout'
/Users/user/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.1/lib/timeout.rb:36:in `block in catch'
/Users/user/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.1/lib/timeout.rb:36:in `catch'
/Users/user/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.1/lib/timeout.rb:36:in `catch'
/Users/user/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.1/lib/timeout.rb:198:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:122:in `process'
/opt/zammad/app/models/channel/driver/mail_stdin.rb:30:in `initialize'
/Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `new'
/Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
/Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `eval'
/Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `perform'
/Users/user/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/Users/user/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/user/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/command/base.rb:69:in `perform'
/Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/command.rb:48:in `invoke'
/Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands.rb:18:in `<main>'
/Users/user/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/user/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:5:in `<main>'
	from /opt/zammad/app/models/channel/email_parser.rb:120:in `process'
	from /opt/zammad/app/models/channel/driver/mail_stdin.rb:30:in `initialize'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `new'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/command/base.rb:69:in `perform'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/command.rb:48:in `invoke'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands.rb:18:in `<main>'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:5:in `<main>'
/opt/zammad/lib/core_ext/string.rb:24:in `sub!': execution expired (Timeout::Error)
	from /opt/zammad/lib/core_ext/string.rb:24:in `strip'
	from /opt/zammad/lib/core_ext/string.rb:328:in `html2html_strict'
	from /opt/zammad/app/models/channel/email_parser.rb:673:in `body_text'
	from /opt/zammad/app/models/channel/email_parser.rb:616:in `message_body_hash'
	from /opt/zammad/app/models/channel/email_parser.rb:89:in `parse'
	from /opt/zammad/app/models/channel/email_parser.rb:144:in `_process'
	from /opt/zammad/app/models/channel/email_parser.rb:123:in `block in process'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.1/lib/timeout.rb:189:in `block in timeout'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.1/lib/timeout.rb:36:in `block in catch'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.1/lib/timeout.rb:36:in `catch'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.1/lib/timeout.rb:36:in `catch'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.1/lib/timeout.rb:198:in `timeout'
	from /opt/zammad/app/models/channel/email_parser.rb:122:in `process'
	from /opt/zammad/app/models/channel/driver/mail_stdin.rb:30:in `initialize'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `new'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/command/base.rb:69:in `perform'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/command.rb:48:in `invoke'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7/lib/rails/commands.rb:18:in `<main>'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/user/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:5:in `<main>'
```

### Expected behaviour

Even if an HTML email contains a lot of empty spaces (think multiple MiBs), it should still be handled and imported by Zammad in a reasonable time frame.

### Steps to reproduce the behaviour

1. Download [test.eml.txt](https://github.com/zammad/zammad/files/10413385/test.eml.txt).
2. Run the following command:

    ```sh
    cat test.eml.txt | rails r Channel::Driver::MailStdin.new
    ```

3. Observe the error above after the timeout is reached (approx. 3 minutes).

The processing seems to hang on https://github.com/zammad/zammad/blob/develop/lib/core_ext/string.rb#L24

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
Is there a related support ticket? Not sure, for me this looks like a case which should lead to a timeout in the sanitizer. This mail looks like an actual attack ^^ It is crazy how much time the stripping costs.

**Comment by dvuckovic** [comment]
No support ticket AFAIK, this behavior was caught via error logs within the hosted environment.

**Comment by martini** [comment]
Just verified on Zammad 6.3, it's working now without any issue :-o

Closing for now, please re-open if it appears again.

```
$ time cat ~/Downloads/test.em.txtl | rails r Channel::Driver::MailStdin.new

real	0m4.238s
user	0m3.705s
sys	0m0.380s
$
```

![Screenshot from 2024-08-09 10-44-16](https://github.com/user-attachments/assets/791a73b2-d691-46cf-9a21-1ef046819ede)
