### ISSUE TITLE
Unable to process email with invalid "Date" header 

### ISSUE THREAD

**Issue by martini** [zammad/zammad#4567]
### Used Zammad Version

5.4

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Unable to process email with invalid `Date` header.

```
$ cat ~/Downloads/test.eml | rails r 'Channel::Driver::MailStdin.new'
"ERROR: Can't process email, you will find it for bug reporting under /home/zammad/var/spool/unprocessable_mail/41ecca3020ed600c877b9e9fbd731231.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<ArgumentError: string length (184) exceeds the limit 128>"
/home/zammad/app/models/channel/email_parser.rb:141:in `rescue in process': #<ArgumentError: string length (184) exceeds the limit 128> (RuntimeError)
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:17:in `parse'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:17:in `normalize_datetime'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:31:in `initialize'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/fields/common_field.rb:12:in `new'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/fields/common_field.rb:12:in `parse'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/field.rb:265:in `parse_field'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/field.rb:254:in `create_field'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/field.rb:187:in `field'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/field.rb:233:in `method_missing'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/field_list.rb:23:in `add_field'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/header.rb:100:in `block in fields='
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/header.rb:98:in `each'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/header.rb:98:in `fields='
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/header.rb:228:in `split_header'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/header.rb:56:in `initialize'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/message.rb:429:in `new'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/message.rb:429:in `header='
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/message.rb:1981:in `parse_message'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/message.rb:2119:in `init_with_string'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/message.rb:135:in `initialize'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/mail.rb:51:in `new'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/mail.rb:51:in `new'
/home/zammad/app/models/channel/email_parser.rb:85:in `parse'
/home/zammad/app/models/channel/email_parser.rb:147:in `_process'
/home/zammad/app/models/channel/email_parser.rb:126:in `block in process'
/home/me/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
/home/me/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.2/lib/timeout.rb:36:in `block in catch'
/home/me/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
/home/me/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
/home/me/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.2/lib/timeout.rb:198:in `timeout'
/home/zammad/app/models/channel/email_parser.rb:125:in `process'
/home/zammad/app/models/channel/driver/mail_stdin.rb:30:in `initialize'
/home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `new'
/home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
/home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `eval'
/home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `perform'
/home/me/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/home/me/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/home/me/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
/home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
/home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
/home/me/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/me/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:5:in `<main>'
	from /home/zammad/app/models/channel/email_parser.rb:123:in `process'
	from /home/zammad/app/models/channel/driver/mail_stdin.rb:30:in `initialize'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `new'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:5:in `<main>'
/home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:17:in `parse': string length (184) exceeds the limit 128 (ArgumentError)
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:17:in `normalize_datetime'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/fields/common_date_field.rb:31:in `initialize'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/fields/common_field.rb:12:in `new'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/fields/common_field.rb:12:in `parse'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/field.rb:265:in `parse_field'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/field.rb:254:in `create_field'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/field.rb:187:in `field'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/field.rb:233:in `method_missing'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/field_list.rb:23:in `add_field'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/header.rb:100:in `block in fields='
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/header.rb:98:in `each'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/header.rb:98:in `fields='
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/header.rb:228:in `split_header'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/header.rb:56:in `initialize'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/message.rb:429:in `new'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/message.rb:429:in `header='
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/message.rb:1981:in `parse_message'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/message.rb:2119:in `init_with_string'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/message.rb:135:in `initialize'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/mail.rb:51:in `new'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/mail-2.8.1/lib/mail/mail.rb:51:in `new'
	from /home/zammad/app/models/channel/email_parser.rb:85:in `parse'
	from /home/zammad/app/models/channel/email_parser.rb:147:in `_process'
	from /home/zammad/app/models/channel/email_parser.rb:126:in `block in process'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.2/lib/timeout.rb:36:in `block in catch'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.2/lib/timeout.rb:36:in `catch'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/timeout-0.3.2/lib/timeout.rb:198:in `timeout'
	from /home/zammad/app/models/channel/email_parser.rb:125:in `process'
	from /home/zammad/app/models/channel/driver/mail_stdin.rb:30:in `initialize'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `new'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/me/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:5:in `<main>'
```

[test.eml.txt](https://github.com/zammad/zammad/files/11183500/test.eml.txt)

### Expected behaviour

Process email event in date header is invalid.

### Steps to reproduce the behaviour

cat ~/Downloads/test.eml.txt | zammad run rails r 'Channel::Driver::MailStdin.new'

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mantas** [comment]
After working out my incomplete fix, I found out there's a PR sitting there since december - https://github.com/mikel/mail/pull/1469 .

Fixing this in our code would be a mess.

Can we close this as wont-fix since it will be addressed by the gem sooner or later? I doubt we want to fork again...

@martini @mgruner do you agree?

**Comment by mgruner** [comment]
@mantas I'm not sure, we don't know how long this will take. Would it be feasible to monkey patch this in Zammad and remove that once the new version of the gem with the fix is there?

**Comment by mantas** [comment]
@mgruner monkeypatching my quick fix would be easy.

Monkeypatching a proper fix (as I learned from that PR) would be more difficult since it digs into internals more. I'm afraid it may accidentally break something when an update is eventually release and we forget to remove monkeypatch.

We could do the quick fix and see if nothing explodes... Maybe it's good enough for most common cases.

**Comment by mgruner** [comment]
Then let's give that a try, as a temporary solution.
