### ISSUE TITLE
SAML Single Logout Service not working correctly

### ISSUE THREAD

**Issue by Emergency1999** [zammad/zammad#4571]
### Used Zammad Version

5.4.0

### Environment

- Installation method: docker-compose: https://github.com/zammad/zammad-docker-compose.git
- Operating system ubuntu 22.04 on host, but using docker
- Database + version:  docker image postgres:15.1-alpine
- Elasticsearch version: docker image bitnami/elasticsearch:8.5.1
- Browser + version: firefox 105, chrome (I don't think this is relevant)

### Actual behaviour

SSO works fine, SLO initiated from Zammad works (even when logged in to other servies)

But when I try to logout from another service and it calls zammad in the logout-chain, this error shows:
![image](https://user-images.githubusercontent.com/37804385/232015243-ac17c56e-7380-4ecd-a742-f9caacfd806f.png)
And this is in the logs from the railserver:
[_zammaddockercompose_zammad-railsserver_1_logs.txt](https://github.com/zammad/zammad/files/11231647/_zammaddockercompose_zammad-railsserver_1_logs.txt)
Here is the parsed log out request:
[auth0_saml_slo_request.txt](https://github.com/zammad/zammad/files/11231651/auth0_saml_slo_request.txt)

(I replaced a few things with "...")

### Expected behaviour

the session of the user should be deleted in zammad and the slo service sould call back Auth0 to finish the logout process.

### Steps to reproduce the behaviour

connect zammad via SAML (to Auth0):
Zammad Config:
- IDP SSO target URL: https://...eu.auth0.com/samlp/...
- IDP Single Logout target URL: https://...eu.auth0.com/samlp/.../logout
- IDP certificate fingerprint: DD:90:36:FC:79:04:E1:4C:89:9F:90:14:8F:B6:46:AF:BF:38:F0:F1
- Name Identifier Format: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
- UID Attribute Name: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress

Auth0 config:
- Login URI https://zammad..de/login
- Callback URL https://zammad...de/auth/saml/callback
- SAML config:
`{
  "mappings": {
    "email": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
    "name": "name"
  },
  "passthroughClaimsWithNoMapping": false,
  "logout": {
    "callback": "https://zammad...de/auth/saml/slo",
    "slo_enabled": true
  },
  "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
  "nameIdentifierFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
  "nameIdentifierProbes": [
    "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
  ]
}`

Then:
- log in to zammad an a different service also using SAML
- log out of the other service.
  - it redirects to zammad and then the error is thrown.

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by Bozo0511** [comment]
Hi,

I tried to reproduce the issue.
I used keycloak as the IDP, but was not able to to reproduce the issue.

Can you please clarify for me what you mean with:

"log in to zammad an a different service also using SAML
log out of the other service.
it redirects to zammad and then the error is thrown."

I am not sure what exactly you mean by this.

**Comment by Emergency1999** [comment]
Hey!

sorry for the late reply, I need to get used to reading my github notifications.

SAML has a feature in which it logs you out in all logged in services that you were using.
So lets imagine you are using SAML on Zammad and Nextcloud and you log in to both services.
When you log out on Nextcloud the SAML provider will redirect you to Zammad and send a logout request there and (if successfull) redirect to nextcloud and end the session there as well. (I am using Auth0, but keykloak most likely works in the same way).
But in this exact scenario zammad throws an error instead of ending the session and the logout from nextcloud does not succeed.

**Comment by Gianluke** [comment]
Hi there,
I have the same problem with Zammad v. 6.3.1, configured in SSO with other SAML2 Service Providers: when I start the logout process on other SP, SLO process hangs on Zammad with the error page reported above.
The error traced in the logs is the following:

`I, [2025-04-16T14:30:23.762557#1-150100]  INFO -- : Started GET "/auth/saml/slo?SAMLRequest=tZLLTsMwEEV%2FJfI%2BD%2BfRNFYTUalCqlSoVBALNsipndYisYtnIsHf44QCpYju2M7cuXPmambAuzY%2BsJXZmR438qWXgN5r12pgH62S9FYzw0EB07yTwHDL7uY3KxYHETtYg2ZrWuIt3KDSHJXRJdkjHoCFIWIg1E61vPbR9YNW6WfoMFAY8h734bAihNYQb7koyVNSp5M8a6aUNkk8qdNpIl0pyotY8CIvCicD6OVSA3KNJYmjOPOj1KeTe5qyJGJxEmQ5fSTercG1Xtt5g9L%2B0mXfuo3kMABfurEds2E9SEu8B2lhPNF1SDUbM2IjlT2N7bIjB%2Bc1JEW8a2M7jpflQ0UJvxmlTGpU%2BEYqAPNXuLPwlOuT8tbZLBf%2FQkkDek7ZcdXOhbASgFRcdEpfHWlPAD%2BQjoAHdufEbt9SC%2FlaiayhSbYtfDptGj%2BdiNSv47z2h68Q06Qocpodfc4mv6o%2Fvrp6Bw%3D%3D&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=L%2B0sHxl2k4ZmAtu3zFOTHZyXZgThYBD0lS4lu4rYklFD3VWow6bH9ZXy6veHvG7W8k%2FKnxNy7YEMp6nA4vUwnusFy%2B1849Hi9y24XI0lswW67bxTwLZadi4m5rt8JihQnHZuGrBohKVoSG0jWwBiNVElmXUHj4%2BxQ972RZEDidAZXosO7NUFKWvuO6Cp%2B8FX2gT54fTkcJNWB5TXUWwIg1EMMv2FXEahiL67jGYjWnQcLvnhw%2FmcFpk3N5S2CxhFjZExXdSlPuSlt%2FdZi5DKRPu89ageJ2VhQV61QSqMi%2BQY%2Fd25MeeRcupgJf34eSFQe3%2BBPThDWbecZ3rhV0Ba0xjP7Yr39wDf8GL0AX%2BVoeHGoYoRmcbLCQg8PUOl4CP0HZmEnkTVWAot1Or17F7Gr1IlvBO4BvobGVFjrfBweI1LlqmWVYt4omEC64AfjfjA8%2F0L%2BzMa82V8%2BO8hmith3oBP%2BPW0HSmz6vWJC7zpr28HcnJOEDmMa80CxRTRLl3lBXo90fu9Mra5y65C1o7R3YD9dUhFbowyNVO0pL%2B4En6dymG2NuWMFDbTniQkctNuN11Llrk9w%2Bqew8MU1xeIdR1hivY%2BEjMsriSdZd8l%2B8o5%2FFv1XcgO6fUCLtypUrvB2co3oi%2BJKPbECgOLWqZ7MZpiAc1Llxm66K9iHBCD7PQ%3D" for 10.100.164.226 at 2025-04-16 14:30:23 +0000
F, [2025-04-16T14:30:23.771904#1-150100] FATAL -- :
[65b4cec52b65416094cbedae4f8f0e07] OmniAuth::Strategies::SAML::ValidationError (SAML failed to process LogoutRequest):
[65b4cec52b65416094cbedae4f8f0e07]
[65b4cec52b65416094cbedae4f8f0e07] omniauth-saml (2.1.0) lib/omniauth/strategies/saml.rb:193:in `handle_logout_request'
[65b4cec52b65416094cbedae4f8f0e07] omniauth-saml (2.1.0) lib/omniauth/strategies/saml.rb:259:in `block in other_phase_for_slo'
[65b4cec52b65416094cbedae4f8f0e07] omniauth-saml (2.1.0) lib/omniauth/strategies/saml.rb:218:in `with_settings'
[65b4cec52b65416094cbedae4f8f0e07] omniauth-saml (2.1.0) lib/omniauth/strategies/saml.rb:255:in `other_phase_for_slo'
[65b4cec52b65416094cbedae4f8f0e07] omniauth-saml (2.1.0) lib/omniauth/strategies/saml.rb:79:in `other_phase'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:195:in `call!'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
[65b4cec52b65416094cbedae4f8f0e07] omniauth (2.1.2) lib/omniauth/builder.rb:44:in `call'`

Any help on this matter would be appreciated.

Thanks in advance.

**Comment by Ajan-Thiru** [comment]
Is there any update in this?

**Comment by Gianluke** [comment]
Hi all,
are there any updates regarding this issue?

Regards.

**Comment by MrGeneration** [comment]
How is the logout configured in your IDP exactly? Does it depend on the users browser?

**Comment by Gianluke** [comment]
> How is the logout configured in your IDP exactly? Does it depend on the users browser?

Hi MrGeneration,
I tested all the possible SLO combinations available on the WSO2 IS IDP (Front Channel HTTP Redirect, Front Channel HTTP Post, Back Channel), but none worked. I should point out that the SAML login process works correctly, as does the logout initiated by Zammad.
