### ISSUE TITLE
PGP: undefined method `disposition' while answering in ticket

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4736]
### Used Zammad Version

6.1

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

```
E, [2023-07-31T11:02:35.002719#18448-121580] ERROR -- : Can't use Channel::Driver::Sendmail: #<NoMethodError: undefined method `disposition' for #<Mail::Part:366360, Multipart: false, Headers: <Content-Type: image/jpeg>, <Content-Transfer-Encoding: base64>, <Content-Disposition: inline>, <Content-ID: <xxx@support.zammad.com>>>>
E, [2023-07-31T11:02:35.002777#18448-121580] ERROR -- : undefined method `disposition' for #<Mail::Part:366360, Multipart: false, Headers: <Content-Type: image/jpeg>, <Content-Transfer-Encoding: base64>, <Content-Disposition: inline>, <Content-ID: <xxx@support.zammad.com>>> (NoMethodError)
lib/secure_mailing/pgp/outgoing.rb:46:in `block in encoded_body_part'
lib/secure_mailing/pgp/outgoing.rb:30:in `new'
lib/secure_mailing/pgp/outgoing.rb:30:in `encoded_body_part'
lib/secure_mailing/pgp/outgoing.rb:40:in `block (2 levels) in encoded_body_part'
lib/secure_mailing/pgp/outgoing.rb:39:in `block in encoded_body_part'
--
```

### Expected behaviour

No error on answering mails from ticket zoom.

### Steps to reproduce the behaviour

see Ticket#10135399

### Support Ticket

Ticket#10135399

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
Maybe because we are using inline images in the signature?
