### ISSUE TITLE
Mobile UI does deny adding a new note when S/MIME / PGP is active

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4793]
### Used Zammad Version

6.1 (pre-release, SaaS)

### Environment

- Installation method: SaaS
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any; pgsql
- Elasticsearch version: any
- Browser + version: verified on Desktop Firefox and iPhone Safari

### Actual behaviour

Adding a new note via mobile UI is not possible (it does work via Desktop though)

https://github.com/zammad/zammad/assets/6549061/97f6e016-1d32-4e13-92b5-1a8cb6b3b912

Log:
``` txt
I, [2023-09-01T17:06:53.029796#3010-26134280]  INFO -- : GraphqlChannel#execute({"query"=>"query formUpdater($formUpdaterId: EnumFormUpdaterId!, $meta: FormUpdaterMetaInput!, $data: JSON!, $relationFields: [FormUpdaterRelationField!]!, $id: ID) {\n  formUpdater(\n    formUpdaterId: $formUpdaterId\n    meta: $meta\n    data: $data\n    relationFields: $relationFields\n    id: $id\n  )\n}", "variables"=>{"id"=>"gid://zammad/Ticket/132520", "formUpdaterId"=>"FormUpdater__Updater__Ticket__Edit", "data"=>{"article"=>{"articleType"=>"note", "internal"=>true, "body"=>"<p>XXX</p>"}, "title"=>"YYYY", "group_id"=>3, "owner_id"=>36035, "state_id"=>3, "pending_time"=>"2023-09-18T06:00:00Z", "priority_id"=>2, "body"=>"<p>XXX</p>"}, "meta"=>{"requestId"=>"be0754bb-3598-4b8e-8447-3813cd3ed8a2", "formId"=>"713594082", "changedField"=>{"name"=>"body", "newValue"=>"<p>XXX</p>", "oldValue"=>""}}, "relationFields"=>[{"name"=>"group_id", "relation"=>"Group"}, {"name"=>"owner_id", "relation"=>"User"}, {"name"=>"state_id", "relation"=>"TicketState", "filterIds"=>[3, 4, 7, 2]}, {"name"=>"priority_id", "relation"=>"TicketPriority"}]}, "operationName"=>"formUpdater"})
I, [2023-09-01T17:06:53.128173#3010-26134280]  INFO -- : Unsubscribing from channel: {"channel":"GraphqlChannel","channelId":"18a5148fe2c"}
I, [2023-09-01T17:06:54.429134#2963-25943620]  INFO -- : Started POST "/graphql" for 127.0.0.1 at 2023-09-01 17:06:54 +0200
I, [2023-09-01T17:06:54.434941#2963-25943620]  INFO -- : Processing by GraphqlController#execute as */*
I, [2023-09-01T17:06:54.435105#2963-25943620]  INFO -- :   Parameters: {"_json"=>[{"operationName"=>"ticketUpdate", "variables"=>{"ticketId"=>"gid://zammad/Ticket/132520", "input"=>{"title"=>"YYY", "groupId"=>"gid://zammad/Group/3", "ownerId"=>"gid://zammad/User/36035", "stateId"=>"gid://zammad/Ticket::State/3", "pendingTime"=>"2023-09-18T06:00:00Z", "priorityId"=>"gid://zammad/Ticket::Priority/2", ], "article"=>{"type"=>"note", "body"=>"[FILTERED]", "internal"=>true, "contentType"=>"text/html", "attachments"=>nil}}}, "query"=>"mutation ticketUpdate($ticketId: ID!, $input: TicketUpdateInput!) {\n  ticketUpdate(ticketId: $ticketId, input: $input) {\n    ticket {\n      ...ticketAttributes\n      __typename\n    }\n    errors {\n      ...errors\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment ticketAttributes on Ticket {\n  id\n  internalId\n  number\n  title\n  createdAt\n  escalationAt\n  updatedAt\n  pendingTime\n  owner {\n    id\n    internalId\n    firstname\n    lastname\n    __typename\n  }\n  customer {\n    id\n    internalId\n    firstname\n    lastname\n    fullname\n    image\n    vip\n    active\n    outOfOffice\n    email\n    organization {\n      id\n      internalId\n      name\n      active\n      objectAttributeValues {\n        ...objectAttributeValues\n        __typename\n      }\n      __typename\n    }\n    hasSecondaryOrganizations\n    policy {\n      update\n      __typename\n    }\n    __typename\n  }\n  organization {\n    id\n    internalId\n    name\n    vip\n    active\n    __typename\n  }\n  state {\n    id\n    name\n    stateType {\n      name\n      __typename\n    }\n    __typename\n  }\n  group {\n    id\n    name\n    emailAddress {\n      name\n      emailAddress\n      __typename\n    }\n    __typename\n  }\n  priority {\n    id\n    name\n    defaultCreate\n    uiColor\n    __typename\n  }\n  objectAttributeValues {\n    ...objectAttributeValues\n    __typename\n  }\n  policy {\n    update\n    agentReadAccess\n    __typename\n  }\n  tags\n  timeUnit\n  timeUnitsPerType {\n    name\n    timeUnit\n    __typename\n  }\n  subscribed\n  preferences\n  stateColorCode\n  __typename\n}\n\nfragment objectAttributeValues on ObjectAttributeValue {\n  attribute {\n    name\n    display\n    __typename\n  }\n  value\n  renderedLink\n  __typename\n}\n\nfragment errors on UserError {\n  message\n  field\n  __typename\n}"}]}
I, [2023-09-01T17:06:54.461746#2963-25943620]  INFO -- : Completed 200 OK in 27ms (Views: 0.1ms | ActiveRecord: 6.4ms | Allocations: 16269)
```

### Expected behaviour

Users can easily add articles via mobile UI without issues.

### Steps to reproduce the behaviour

- activate S/MIME and/or PGP in the system
- open mobile UI as agent
- open any ticket you may write to
- try to add a new article

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Seems only to be the case, when SMIME or/and PGP is: activated in the system:

```
error.ts:53 [GraphQL error - NoMethodError]: undefined method `[]' for nil:NilClass

        'type'       => security[:method],
                                ^^^^^^^^^, Path: ticketUpdate (12) ["app/graphql/gql/types/input/ticket/article_input_type.rb:58:in `security_preference'", "app/graphql/gql/types/input/ticket/article_input_type.rb:45:in `transform_security'", "app/graphql/gql/types/base_input_object.rb:37:in `block in prepare'", "app/graphql/gql/types/base_input_object.rb:36:in `each'", "app/graphql/gql/types/base_input_object.rb:36:in `reduce'", "app/graphql/gql/types/base_input_object.rb:36:in `prepare'", "app/controllers/graphql_controller.rb:38:in `multiplex'", "app/controllers/graphql_controller.rb:17:in `execute'", "app/controllers/application_controller/has_downloa…:17:in `block (4 levels) in <module:HasDownload>'", "app/controllers/application_controller/has_downloa…:16:in `block (3 levels) in <module:HasDownload>'", "app/controllers/application_controller/has_downloa…:15:in `block (2 levels) in <module:HasDownload>'", "app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'"]
```
