### ISSUE TITLE
Unprocessible mail output for mails with missing from should have a specific output

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4826]
### Used Zammad Version

6.1.0.35b356c51.saas

### Environment

- Installation method: SaaS, any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  postgresql, any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When the `from` header is missing in an email, the Traceback is cryptic and suggest to create a bug report.

```
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/var/spool/unprocessable_mail/038315fa77e7ec348ef292a953d1330d.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<NoMethodError: undefined method `match?' for nil:NilClass\n\n    if attrs[:email].match?(%r{\\S\\s+\\S}) || attrs[:email].match?(%r{^<|>$})\n                    ^^^^^^^>"
/opt/zammad/app/models/channel/email_parser.rb:141:in `rescue in process': #<NoMethodError: undefined method `match?' for nil:NilClass (RuntimeError)

    if attrs[:email].match?(%r{\\S\\s+\\S}) || attrs[:email].match?(%r{^<|>$})
                    ^^^^^^^>
/opt/zammad/app/models/channel/filter/identify_sender.rb:172:in `populate_attributes!'
/opt/zammad/app/models/channel/filter/identify_sender.rb:156:in `user_create'
/opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'
/opt/zammad/app/models/channel/email_parser.rb:165:in `block in _process'
/opt/zammad/app/models/channel/email_parser.rb:162:in `each'
/opt/zammad/app/models/channel/email_parser.rb:162:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:126:in `block in process'
/usr/local/rvm/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:186:in `block in timeout'
/usr/local/rvm/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:41:in `handle_timeout'
/usr/local/rvm/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:195:in `timeout'
/opt/zammad/app/models/channel/email_parser.rb:125:in `process'
/opt/zammad/app/models/channel/email_parser.rb:512:in `block in process_unprocessable_mails'
<internal:dir>:220:in `glob'
/opt/zammad/app/models/channel/email_parser.rb:511:in `process_unprocessable_mails'
/usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
/usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `eval'
/usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `perform'
/usr/local/rvm/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/rvm/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command/base.rb:69:in `perform'
/usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command.rb:48:in `invoke'
/usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands.rb:18:in `<main>'
/usr/local/rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:5:in `<main>'
        from /opt/zammad/app/models/channel/email_parser.rb:123:in `process'
        from /opt/zammad/app/models/channel/email_parser.rb:512:in `block in process_unprocessable_mails'
        from <internal:dir>:220:in `glob'
        from /opt/zammad/app/models/channel/email_parser.rb:511:in `process_unprocessable_mails'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `eval'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `perform'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command/base.rb:69:in `perform'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command.rb:48:in `invoke'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands.rb:18:in `<main>'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:5:in `<main>'
/opt/zammad/app/models/channel/filter/identify_sender.rb:172:in `populate_attributes!': undefined method `match?' for nil:NilClass (NoMethodError)

    if attrs[:email].match?(%r{\\S\\s+\\S}) || attrs[:email].match?(%r{^<|>$})
                    ^^^^^^^
        from /opt/zammad/app/models/channel/filter/identify_sender.rb:156:in `user_create'
        from /opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'
        from /opt/zammad/app/models/channel/email_parser.rb:165:in `block in _process'
        from /opt/zammad/app/models/channel/email_parser.rb:162:in `each'
        from /opt/zammad/app/models/channel/email_parser.rb:162:in `_process'
        from /opt/zammad/app/models/channel/email_parser.rb:126:in `block in process'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:186:in `block in timeout'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:41:in `handle_timeout'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:195:in `timeout'
        from /opt/zammad/app/models/channel/email_parser.rb:125:in `process'
        from /opt/zammad/app/models/channel/email_parser.rb:512:in `block in process_unprocessable_mails'
        from <internal:dir>:220:in `glob'
        from /opt/zammad/app/models/channel/email_parser.rb:511:in `process_unprocessable_mails'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `eval'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `perform'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command/base.rb:69:in `perform'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command.rb:48:in `invoke'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands.rb:18:in `<main>'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/local/rvm/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:5:in `<main>'
```

### Expected behaviour

As `from` headers currently are a hard requirement, Zammad should provide a slim and clean error message on why the mail can't be important (as we actually "know").

This should reduce confusion on that regard.

Maybe something like "ERROR: Could not find any valid FROM / Reply-To header. From and/or Reply-To headers are a hard requirement for Zammads customer detection."

Sureley the wording could be better.

### Steps to reproduce the behaviour

Have a mail that has a the usual headers except for Reply-To and From and try to fetch said mail.

### Support Ticket

Ticket#10140805

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
I have a failing mail that contains a from header (which is intact and correct) but fails:
```
$ rake zammad:email_parser:failed_email:import /opt/zammad/tmp/failed-email-c7a6817e-1142-41bb-956e-0cfb44fbb1f1/2.eml
ERROR: Can't reprocess failed email '2'. This was attempt # 2.
ERROR: #<Exceptions::MissingAttribute: Could not parse any sender attribute from the email. Checked fields: From, Reply-To, Return-Path, Sender>
/opt/zammad/tmp/failed-email-c7a6817e-1142-41bb-956e-0cfb44fbb1f1/2.eml was not imported and reprocessed successfully.
```


```
Return-Path: <>
Delivered-To: hostmaster+dmarc_reports@receiver-domain.tld
Received: from mx2.receiver-domain.tld
        by mx2.zammad.com with LMTP
        id EAF7MpW9zmaG8QwAABwAvw
        (envelope-from <>)
        for <hostmaster+dmarc_reports@receiver-domain.tld>; Wed, 28 Aug 2024 06:03:01 +0000
Date: Wed, 28 Aug 2024 08:02:58 +0200
From: MAILER-DAEMON <MAILER-DAEMON@sender-domain.tld>
Subject: Undelivered Mail Returned to Sender
To: hostmaster+dmarc_reports@receiver-domain.tld
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
        boundary="5177111E282.1374149209_antispameurope"
X-cloud-security:Statusmail
X-cloud-security:Orig-msgid:8bc440e585c2e66daca4932dff1adda0-ef4d792cd53b5bee3288831bb07d7d08

...
```
