### ISSUE TITLE
Editing the Knowledge Base throws:  'no implicit conversion of Symbol into Integer (TypeError)'

### ISSUE THREAD

**Issue by t-shehab** [zammad/zammad#4833]
### Used Zammad Version

6.2 (Develop - SaaS)

### Environment

- Installation method: SaaS
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Editing an answer in the knowledge base throws the following Error:

```
I, [2023-09-20T12:20:15.314053#3838-16070480]  INFO -- : Processing by KnowledgeBasesController#visible_ids as JSON
I, [2023-09-20T12:20:15.314121#3838-16070480]  INFO -- :   Parameters: {"_"=>"1695185889484"}
E, [2023-09-20T12:20:15.595956#3838-16070480] ERROR -- : no implicit conversion of Symbol into Integer (TypeError)
lib/knowledge_base/internal_assets.rb:46:in `all_category_ids'
lib/knowledge_base/internal_assets.rb:52:in `visible_ids'
app/controllers/knowledge_bases_controller.rb:27:in `calculate_visible_ids'
app/controllers/knowledge_bases_controller.rb:9:in `visible_ids'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2023-09-20T12:20:15.599094#3838-16070480] ERROR -- : Error ID USDPyH2d: no implicit conversion of Symbol into Integer
```

### Expected behaviour

Editing an answer in the Knowledge Base throws no errors.

### Steps to reproduce the behaviour

Edit an answer in the Knowledge Base.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
This looks like a blocker issue. Maybe someone can check it in the next sprint?

/cc @dominikklein @mantas
