### ISSUE TITLE
Time accounting check crashing when no group is selected

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4835]
### Used Zammad Version

6.1

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

```
E, [2023-09-22T16:24:51.345929#32187-5700] ERROR -- : Error performing Core Workflow engine.
E, [2023-09-22T16:24:51.345981#32187-5700] ERROR -- : undefined method `id' for nil:NilClass

    user.group_access?(record.group.id, access)
                                   ^^^ (NoMethodError)
app/policies/ticket_policy.rb:87:in `agent_access?'
app/policies/ticket_policy.rb:57:in `agent_update_access?'
app/models/core_workflow/custom/ticket_time_accounting_check.rb:21:in `available_for_user?'
app/models/core_workflow/custom/ticket_time_accounting_check.rb:17:in `enabled?'
app/models/core_workflow/custom/ticket_time_accounting_check.rb:5:in `saved_attribute_match?'
app/models/core_workflow/condition/match_all_modules.rb:13:in `block (2 levels) in match'
app/models/core_workflow/condition/match_all_modules.rb:10:in `each'
```

### Expected behaviour

No errors

### Steps to reproduce the behaviour

Select empty group on support instance.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
`TicketPolicy.new(current_user, selected).agent_update_access?` should be done the with saved ticket.

https://github.com/zammad/zammad/blob/5b6ad994b209403e1364169b42d42d097576426b/app/models/core_workflow/custom/ticket_time_accounting_check.rb#L21
