### ISSUE TITLE
Email processing with S3 backend is broken

### ISSUE THREAD

**Issue by martini** [zammad/zammad#4855]
### Used Zammad Version

develop

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Unable to process emails:

```
$ cat test/fixtures/mail67.box | rails r 'Channel::Driver::MailStdin.new'
"ERROR: Can't process email, you will find it for bug reporting under /home/me/src/zammad/var/spool/unprocessable_mail/f3063a833cdb8827f0669c7528454ce7.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<ArgumentError: wrong number of arguments (given 3, expected 2)>"
/home/me/src/zammad/app/models/channel/email_parser.rb:140:in `rescue in process': #<ArgumentError: wrong number of arguments (given 3, expected 2)> (RuntimeError)
/home/me/src/zammad/app/models/store/provider/s3.rb:11:in `add'
/home/me/src/zammad/app/models/store/file.rb:33:in `add'
/home/me/src/zammad/app/models/store.rb:29:in `set_store_file'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:603:in `catch'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:199:in `block in halting'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `each'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `invoke_before'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:824:in `_run_create_callbacks'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/callbacks.rb:461:in `_create_record'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/timestamp.rb:108:in `_create_record'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/persistence.rb:900:in `create_or_update'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/callbacks.rb:457:in `block in create_or_update'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:106:in `run_callbacks'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/callbacks.rb:457:in `create_or_update'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/timestamp.rb:126:in `create_or_update'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/persistence.rb:507:in `save!'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/validations.rb:53:in `save!'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/transactions.rb:302:in `block in save!'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/database_statements.rb:318:in `transaction'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/transactions.rb:302:in `save!'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/suppressor.rb:48:in `save!'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/persistence.rb:55:in `create!'
/home/me/src/zammad/app/models/ticket/article.rb:254:in `save_as_raw'
/home/me/src/zammad/app/models/channel/email_parser.rb:299:in `block in _process'
/home/me/src/zammad/app/models/transaction.rb:17:in `block in execute'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/transactions.rb:209:in `transaction'
/home/me/src/zammad/app/models/transaction.rb:14:in `execute'
/home/me/src/zammad/app/models/transaction.rb:26:in `execute'
/home/me/src/zammad/app/models/channel/email_parser.rb:186:in `_process'
/home/me/src/zammad/app/models/channel/email_parser.rb:125:in `block in process'
/path/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:186:in `block in timeout'
/path/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:41:in `handle_timeout'
/path/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:195:in `timeout'
/home/me/src/zammad/app/models/channel/email_parser.rb:124:in `process'
/home/me/src/zammad/app/models/channel/driver/mail_stdin.rb:30:in `initialize'
/path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `new'
/path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
/path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `eval'
/path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `perform'
/path/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/path/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/path/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command/base.rb:69:in `perform'
/path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command.rb:48:in `invoke'
/path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands.rb:18:in `<main>'
/path/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/path/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:5:in `<main>'
	from /home/me/src/zammad/app/models/channel/email_parser.rb:122:in `process'
	from /home/me/src/zammad/app/models/channel/driver/mail_stdin.rb:30:in `initialize'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `new'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	from /path/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /path/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /path/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command/base.rb:69:in `perform'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command.rb:48:in `invoke'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands.rb:18:in `<main>'
	from /path/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /path/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:5:in `<main>'
/home/me/src/zammad/app/models/store/provider/s3.rb:11:in `add': wrong number of arguments (given 3, expected 2) (ArgumentError)
	from /home/me/src/zammad/app/models/store/file.rb:33:in `add'
	from /home/me/src/zammad/app/models/store.rb:29:in `set_store_file'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:603:in `catch'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:199:in `block in halting'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `each'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:512:in `invoke_before'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:105:in `run_callbacks'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:824:in `_run_create_callbacks'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/callbacks.rb:461:in `_create_record'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/timestamp.rb:108:in `_create_record'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/persistence.rb:900:in `create_or_update'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/callbacks.rb:457:in `block in create_or_update'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:106:in `run_callbacks'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/callbacks.rb:457:in `create_or_update'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/timestamp.rb:126:in `create_or_update'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/persistence.rb:507:in `save!'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/validations.rb:53:in `save!'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/transactions.rb:302:in `block in save!'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/database_statements.rb:318:in `transaction'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/transactions.rb:302:in `save!'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/suppressor.rb:48:in `save!'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/persistence.rb:55:in `create!'
	from /home/me/src/zammad/app/models/ticket/article.rb:254:in `save_as_raw'
	from /home/me/src/zammad/app/models/channel/email_parser.rb:299:in `block in _process'
	from /home/me/src/zammad/app/models/transaction.rb:17:in `block in execute'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	from /path/gems/ruby-3.1.3/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
	from /path/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/transactions.rb:209:in `transaction'
	from /home/me/src/zammad/app/models/transaction.rb:14:in `execute'
	from /home/me/src/zammad/app/models/transaction.rb:26:in `execute'
	from /home/me/src/zammad/app/models/channel/email_parser.rb:186:in `_process'
	from /home/me/src/zammad/app/models/channel/email_parser.rb:125:in `block in process'
	from /path/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:186:in `block in timeout'
	from /path/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:41:in `handle_timeout'
	from /path/gems/ruby-3.1.3/gems/timeout-0.4.0/lib/timeout.rb:195:in `timeout'
	from /home/me/src/zammad/app/models/channel/email_parser.rb:124:in `process'
	from /home/me/src/zammad/app/models/channel/driver/mail_stdin.rb:30:in `initialize'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `new'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `<main>'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `eval'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands/runner/runner_command.rb:45:in `perform'
	from /path/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /path/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /path/gems/ruby-3.1.3/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command/base.rb:69:in `perform'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/command.rb:48:in `invoke'
	from /path/gems/ruby-3.1.3/gems/railties-6.1.7.6/lib/rails/commands.rb:18:in `<main>'
	from /path/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /path/gems/ruby-3.1.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:5:in `<main>'
````

### Expected behaviour

Spool mails if S3 backend is not available and if it is available reprocess it.

### Steps to reproduce the behaviour

Try to process an example email, e. g. via `$ cat test/fixtures/mail67.box | rails r 'Channel::Driver::MailStdin.new'`

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@martini I think because of that or? https://github.com/zammad/zammad/issues/4854

**Comment by martini** [comment]
@dominikklein thanks for the hint. Just verified it on the bugfix branch. Now I get the error message:

```
$ cat test/fixtures/mail67.box | rails r 'Channel::Driver::MailStdin.new'
"ERROR: Can't process email, you will find it for bug reporting under /home/me/src/zammad/var/spool/unprocessable_mail/51c77ffc1bcda8bb9f73dd564158f0f3.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<Store::Provider::S3::Error: Simple Storage Service configuration not found or invalid.>"
/home/me/src/zammad/app/models/channel/email_parser.rb:140:in `rescue in process': #<Store::Provider::S3::Error: Simple Storage Service configuration not found or invalid.> (RuntimeError)
/home/me/src/zammad/app/models/store/provider/s3/config.rb:48:in `settings'
/home/me/src/zammad/app/models/store/provider/s3/config.rb:15:in `max_chunk_size'
/home/me/src/zammad/app/models/store/provider/s3.rb:12:in `add'
/home/me/src/zammad/app/models/store/file.rb:33:in `add'
/home/me/src/zammad/app/models/store.rb:29:in `set_store_file'
```

I can understand the error message. The question from a product point of view is:

a) What can we do/prevent against incorrect S3 configuration?
b) What should Zammad do if S3 is temporarily unavailable for some reason (use the DB backend as fallback)?

**Comment by dominikklein** [comment]
What is Zammad currently doing when the database is not reachable or when there are problems with saving inside the file system?

**Comment by MrGeneration** [comment]
> when the database is not reachable

it's crashing / hopefully trying to reconnect but basically is out of order. Can't speak for the FS part.

**Comment by dominikklein** [comment]
When I understand it correctly, it will be the same for all three storage types. In the case it's not reachable, it will be added to the unprocessable_mail folder.

**Comment by dominikklein** [comment]
Will be handled in general at some point.
