### ISSUE TITLE
Calendar non functional with activated 2fa authentication

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4858]
### Used Zammad Version

6.1.0.876840eb8.saas

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any, verified on Outlook 365 and Thunderbird

### Actual behaviour

2fa is blocking the access to calendar functionality (ical) due to non existing support for HTTP BasicAuth.
Removing any 2fa authenticator for the affected user immediately restores the calendar subscription functionality.

```
I, [2023-10-04T14:39:27.487864#13614-66900] INFO -- : Authentication against Auth::Backend::Internal for user chris@chrispresso.com ok.
I, [2023-10-04T14:39:27.498083#13614-66900] INFO -- : Two-factor authentication is not supported with HTTP BasicAuth. (Exceptions::NotAuthorized)
app/controllers/application_controller/authenticates.rb:128:in `authentication_check_only'
app/controllers/application_controller/authenticates.rb:9:in `authentication_check'
app/controllers/calendar_subscriptions_controller.rb:4:in `block in <class:CalendarSubscriptionsController>'
I, [2023-10-04T14:39:27.499588#13614-66900] INFO -- : Rendered inline template (Duration: 0.2ms | Allocations: 308)
```

### Expected behaviour

The calendar endpoints for subscribing with personal email clients or calendar tools works regardless of 2fa being active or not.

We may want to have a token that can be reset or something like that to overcome all these basic authentication issues. This would also drastically raise the supported applications that can use Zammads calendar.

### Steps to reproduce the behaviour

- enable 2fa
- try to hook the ical URL of the affected user to Outlook or Thunderbird

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Memurame** [comment]
Is there already a solution?
I also have the problem that I cannot integrate iCal because I have activated 2FA.

I have Zammad Version 6.4.1 (Docker)

**Comment by MrGeneration** [comment]
This issue is open, so no.
