### ISSUE TITLE
Invalid email '@example.com' - Parser fails for emails that only contain "" in the local part

### ISSUE THREAD

**Issue by KarimGeiger** [zammad/zammad#4896]
### Used Zammad Version

6.1.0

### Environment

- Installation method: Ubuntu package
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 20.04
- Database + version:  postgres
- Elasticsearch version: n/a
- Browser + version: n/a

### Actual behaviour

Unfortunately, someone though sending us a spam email from `""@xxx.yy.zz.example` would be a great idea... (note the "" in before the @)

In this case, the parsing fails:

```
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/var/spool/unprocessable_mail/xxx.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<ActiveRecord::RecordInvalid: Validation failed: Invalid email '@xxx.yy.zz.example'>"
/opt/zammad/app/models/channel/email_parser.rb:141:in `rescue in process': #<ActiveRecord::RecordInvalid: Validation failed: Invalid email '@xxx.yy.zz.example'> (RuntimeError)
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-6.1.7.6/lib/active_record/validations.rb:80:in `raise_validation_error'
```

### Expected behaviour

Parsing succeeds as it seems to be a valid email address (at least I would assume so, since Gmail delivered it).

### Steps to reproduce the behaviour

Send an email from `""@xxx.yy.zz.example` to an inbox monitored by Zammad.

### Support Ticket

(Ticket#10144753), Ticket#10145733

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
I think the issue can't be handled without an example email. Maybe you can send us an `*.eml` to support@zammad.com with a link to this issue? Then we could have a look and see what's wrong. From the error message it looks like that the mail address is wrong. Maybe tho it was not parsed properly.

**Comment by KarimGeiger** [comment]
Thanks for looking into it, @rolfschmidt. I have forwarded you the email in question. Please make sure to check your spam folder, as the email attached was classified as spam previously.

**Comment by rolfschmidt** [comment]
thx for the example mail @KarimGeiger. The From and To field of it is definitely invalid and should not be processed. For us zammad behaves correctly in this case.

**Comment by KarimGeiger** [comment]
Respectfully, I disagree, @rolfschmidt. `""@example.com` is a valid email address as per RFC822, and it is being processed by at least some email providers, evidently. You can try and validate the email address for example here: http://sphinx.mythic-beasts.com/~pdw/cgi-bin/emailvalidate

Since it is a valid email address, it should not cause Zammad to fail.

The error message does not contain the `""` local part, so I would assume that double-quotes get evaluated somewhere earlier, causing the [regex](https://github.com/zammad/zammad/blob/362d437c2ef33ba1cebe949e1d29b02c43fdf2a2/app/models/channel/email_parser.rb#L9C1-L10C1) to fail, which should not happen.

**Comment by rolfschmidt** [comment]
```ruby
[2] pry(main)> EmailAddressValidator.error(%Q[""@example.com], host_validation: :syntax)
=> "Mailbox name too short"
```

Our lib does currently not accept your address. But If you want, I can ask some colleagues for different opinions on this topic:

@mgruner @fliebe92 @tschaefer @MrGeneration

**Comment by tschaefer** [comment]
After some further research, I must say it is a valid email address.

It is called the *quoted string format* of the local part. It is not widely implemented in SMTP servers, because it has many downsides and obstacles on the server side. The idea of the *quoted string format* is to allow the usage of further special characters.

`john..doe@example.com` is not a valid address. The consecutive use of dots `.` is not allowed.
`"john..doe"@example.com` is a valid address. The local part is quoted.

:exploding_head: 

So, even a quoted empty string as a local part is allowed.

* https://en.wikipedia.org/wiki/Email_address#Local-part
* https://www.rfc-editor.org/rfc/rfc3696
* https://www.rfc-editor.org/rfc/rfc5321.html

**Comment by MrGeneration** [comment]
Wouldn't the email address with "empty" local part be an issue in Zammad in combination with the unique email address detection? It's like logging in as `@example.com` which feels kind of wrong.

Maybe that's just me though.

**Comment by tschaefer** [comment]
The quotes are literally part of the alias, so the resulting User email (login) attribute value is `""@example.com`. I proved the named email address is valid, conformed to the listed RFCs. The handling in Zammad is a product decision.

**Comment by dominikklein** [comment]
@YetAnotherGerrit Do you think we should allow such email addresses (which are valid from RFC perspective) and spend this effort to improve the current situation? Or do we think it makes no sense to allow such email addresses in our context?

**Comment by YetAnotherGerrit** [comment]
If it's valid in RFC we should make sure to support it.

**Comment by tschaefer** [comment]
🥳  
`cat quoted_string_email_address.rb`
```ruby
[
  %(''@example.com),
  %(""@example.com),
  %(' '@example.com),
  %(" "@example.com),
  %('john..doe'@example.com),
  %("john..doe"@example.com),
].each do |addr|
  valid = EmailAddressValidator.new(addr, host_validation: :syntax).valid? ? 'valid' : 'invalid'
  puts printf('%{addr}: %{valid}', addr: addr, valid: valid)
end
```
`rails runner quoted_string_email_address.rb`
```ruby
''@example.com: valid
""@example.com: invalid
' '@example.com: invalid
" "@example.com: valid
'john..doe'@example.com: invalid
"john..doe"@example.com: valid
```

**Comment by KarimGeiger** [comment]
After reading this thread again, I'd like to add the following: As a user I don't care whether this email address is allowed or not. Obviously, nobody is ever going to use an address like this and expects to get a response.

The reason I opened this issue was because this is a potential DoS vector. Sending an email from an address like that causes Zammad's ingest system to fail. In our case, it failed in a way that it stopped parsing other emails, leading to us missing a few valid tickets.

If instead an email like this can just be rejected without having to dig through the CLI and database to delete the invalid record, then that's an (in my opinion) very valid way to handle emails like this.

**Comment by mantas** [comment]
Looks like this could be solved by improving email validation library. Pushed a [PR](https://github.com/afair/email_address/pull/113) upstream. Let's see how it goes.
