### ISSUE TITLE
Email processing stuck

### ISSUE THREAD

**Issue by hydrapolic** [zammad/zammad#4935]
### Used Zammad Version

5.4.1

### Environment

- Installation method: source
- Operating system: Linux Gentoo
- Database + version:  PostgreSQL 15.4
- Elasticsearch version: 8.9.2
- Browser + version: Firefox 119

### Actual behaviour

Hello, ocasionally it happens that Zammad tries to open too many connections to the IMAP server and thus is blocked:

```
I, [2023-11-15T03:13:16.812754#4737-232304460]  INFO -- : fetching imap (mail.server.com/hello@domain.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=false,auth_type=LOGIN)
E, [2023-11-15T03:13:16.863810#4737-232304460] ERROR -- : Can't use Channel::Driver::Imap: #<Net::IMAP::NoResponseError: Maximum number of connections from user+IP exceeded (mail_max_userip_connecti
ons=40)>
E, [2023-11-15T03:13:16.863963#4737-232304460] ERROR -- : Maximum number of connections from user+IP exceeded (mail_max_userip_connections=40) (Net::IMAP::NoResponseError)
app/models/channel/driver/imap.rb:126:in `block in fetch'
app/models/channel/driver/imap.rb:580:in `timeout'
app/models/channel/driver/imap.rb:122:in `fetch'
app/models/channel.rb:56:in `fetch'
app/models/channel.rb:30:in `fetch'
(eval):1:in `eval_job_method'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval_job_method'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:23:in `execute'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:16:in `block in run_loop'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:15:in `times'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:15:in `run_loop'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:8:in `run'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:10:in `run'
lib/background_services/service/process_scheduled_jobs/manager.rb:84:in `block in start_in_thread'
lib/application_handle_info.rb:19:in `use'
lib/background_services/service/process_scheduled_jobs/manager.rb:82:in `start_in_thread'
lib/background_services/service/process_scheduled_jobs/manager.rb:73:in `block (2 levels) in start'
lib/background_services/service/process_scheduled_jobs/manager.rb:72:in `block in start'
I, [2023-11-15T03:13:16.880549#4737-232304460]  INFO -- : ended Channel.fetch took: 0.255273221 seconds.
```

The problem is that it remains stuck and cannot use IMAP at all, so no new messages are processed by Zammad:
```
E, [2023-11-15T03:15:17.960453#4737-232304460] ERROR -- : Can't use Channel::Driver::Imap: #<Errno::EIO: Input/output error @ io_writev - <STDOUT>>
E, [2023-11-15T03:15:17.960502#4737-232304460] ERROR -- : Input/output error @ io_writev - <STDOUT> (Errno::EIO)
app/models/channel/email_parser.rb:131:in `p'
app/models/channel/email_parser.rb:131:in `rescue in process'
app/models/channel/email_parser.rb:120:in `process'
app/models/channel/driver/imap.rb:318:in `block in fetch'
app/models/channel/driver/imap.rb:255:in `each'
app/models/channel/driver/imap.rb:255:in `fetch'
app/models/channel.rb:56:in `fetch'
app/models/channel.rb:30:in `fetch'
(eval):1:in `eval_job_method'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval_job_method'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:23:in `execute'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:16:in `block in run_loop'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:15:in `times'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:15:in `run_loop'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:8:in `run'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:10:in `run'
lib/background_services/service/process_scheduled_jobs/manager.rb:84:in `block in start_in_thread'
lib/application_handle_info.rb:19:in `use'
lib/background_services/service/process_scheduled_jobs/manager.rb:82:in `start_in_thread'
lib/background_services/service/process_scheduled_jobs/manager.rb:73:in `block (2 levels) in start'
lib/background_services/service/process_scheduled_jobs/manager.rb:72:in `block in start'
I, [2023-11-15T03:15:17.970124#4737-232304460]  INFO -- : ended Channel.fetch took: 0.359630469 seconds.
I, [2023-11-15T03:15:20.196603#4737-112200]  INFO -- : ProcessScheduledJobs running...
```

A zammad restart helps of course.

### Expected behaviour

Seems like the connections are not closed in the event of an error. Maybe it would be possible to close stale / dead connections and try to open them fresh?

### Steps to reproduce the behaviour

Unsure how to safely reproduce, however the mail server gets busy sometimes when sending bulk emails. I'd say a combination of a busy mail server and lots of messages to Zammad.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Zammad 5.4 is outdated, please consider updating asap.

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
