### ISSUE TITLE
S3 ignores custom CA certificates from Zammad

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4964]
### Used Zammad Version

6.2.0-alpha-1701379637.7db46b69.bullseye

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian 11
- Database + version:  psql 13.11
- Elasticsearch version: 7.17
- Browser + version: any

### Actual behaviour

Adding a custom, self signed CA certificate to Zammads CA function has no effect on S3.

Upon verify it dies with:
```
E, [2023-12-03T14:23:27.956177#2761-141940] ERROR -- : Store::Provider::S3: SSL_connect returned=1 errno=0 peeraddr=172.16.16.47:443 state=error: certificate verify failed (unable to get local issuer certificate)
E, [2023-12-03T14:23:27.956332#2761-141940] ERROR -- : Simple Storage Service malfunction. Please contact your Zammad administrator. (Store::Provider::S3::Error)
app/models/store/provider/s3.rb:86:in `log_and_raise'
app/models/store/provider/s3.rb:92:in `rescue in request'
app/models/store/provider/s3.rb:89:in `request'
app/models/store/provider/s3.rb:33:in `get'
app/models/store/file.rb:62:in `content'
app/models/store.rb:139:in `content_preview'
app/controllers/application_controller/has_download/download_file.rb:28:in `content'
app/controllers/ticket_articles_controller.rb:182:in `attachment'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
I, [2023-12-03T14:23:27.957605#2761-141940]  INFO -- :   Rendered inline template (Duration: 0.3ms | Allocations: 332)
I, [2023-12-03T14:23:27.957711#2761-141940]  INFO -- : Completed 422 Unprocessable Entity in 2237ms (Views: 0.6ms | ActiveRecord: 19.3ms | Allocations: 675902)
```

### Expected behaviour

Adding custom CA certificates to Zammad affects *all* SSL relevant parts of Zammad.
Not just email channels and LDAP, but also internal functions like... let's say S3.

### Steps to reproduce the behaviour

- Create a custom CA and a custom certificate from it
- spin a selfhosted minio instance
- use the certificate for the minio vhost
- to not add the CA to the systems CA store but add it to Zammads CA menu
- prepare the S3 configuration
- restart Zammad, just to be sure
- Now test the configuration and fail

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Not sure how to understand this response I'm afraid.
Are you trying to tell me that the whole CA thing implementation is "garberage" and "wrong" and thus a lot of other places don't work or that I generally shouldn't rely on certificate certifications outside of the OSes scope?
