### ISSUE TITLE
Zammad Worker fails to start with railtie error

### ISSUE THREAD

**Issue by svenseeberg** [zammad/zammad#4977]
### Used Zammad Version

6.2.0

### Environment

- Installation method: package
- Operating system: Ubuntu 20.04
- Database + version:  PostgreSQL 12.17
- Elasticsearch version: 7.17.15
- Browser + version: N/A

### Actual behaviour

`zammad-worker-1.service` fails to start and shows the following trace in the journal:

```
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]: bundler: failed to load command: script/background-worker.rb (script/background-worker.rb)
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]: /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require': cannot load such file -- action_dispatch/railtie (LoadError)
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-7.0.8/lib/rails.rb:17:in `<main>'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/railties-7.0.8/lib/rails/all.rb:5:in `<main>'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/config/application.rb:5:in `<top (required)>'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/config/environment.rb:4:in `require_relative'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/config/environment.rb:4:in `<top (required)>'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from script/background-worker.rb:8:in `require'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from script/background-worker.rb:8:in `<top (required)>'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/3.1.0/bundler/cli.rb:486:in `exec'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:48:in `block in <top (required)>'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/vendor/ruby-3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:36:in `<top (required)>'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/bin/bundle:121:in `load'
Dec 10 23:15:42 zammad.example.com zammad-worker-1.service[2218]:         from /opt/zammad/bin/bundle:121:in `<main>'
Dec 10 23:15:42 zammad.example.com systemd[1]: zammad-worker-1.service: Main process exited, code=exited, status=1/FAILURE
```

The same stack trace is shown in many steps while the package is being installed, for example between `# Clear cache...` and `# database.yml found. Updating db...` messages.

This seems to have happened after installing the latest version on Friday (2023-12-08).

### Expected behaviour

No stack trace.

### Steps to reproduce the behaviour

t.b.d.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by support-criegerde** [comment]
same for me after update to 6.2.0-1702303938.81e0c1fd
'zammad is already the newest version (6.2.0-1702303938.81e0c1fd.jammy)'

![grafik](https://github.com/zammad/zammad/assets/134060911/b8a3b48e-3125-48bf-94e6-d918da38e057)
`zammad run rails c`
`/opt/zammad/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in 'require': cannot load such file -- action_dispatch/railtie (LoadError)`

**Comment by support-criegerde** [comment]
Root cause: Bootsnap did not invalidate its cache.
Solution: 
`cd /opt/zammad/tmp/cache`
`rm -rf *`
Restart/Reboot and zammad is back again.

**Comment by svenseeberg** [comment]
> Root cause: Bootsnap did not invalidate its cache. Solution: `cd /opt/zammad/tmp/cache` `rm -rf *` Restart/Reboot and zammad is back again.

Thanks, that worked!
