### ISSUE TITLE
Zammad worker experiences query errors under high load (PG::UnableToSend)

### ISSUE THREAD

**Issue by jackwurth** [zammad/zammad#4986]
### Used Zammad Version

6.1

### Environment

- Installation method: [e.g. source, package]
Package, Ubuntu

- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
Ubuntu 22.04

- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
Postgres 16 (Latest)
- Elasticsearch version: [e.g. 7.17]
7.17.15
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]
Latest (Not relevant)

### Actual behaviour

Zammad worker crashes with a variety of different bad connection related errors seen in output of `journalctl -e`. These errors become more common as database.yml connection pool setting is increased. In this case we have it at 40, higher numbers seem to make this more common.

In this example the database is hosted on a separate server. Doing a bit of research this seems to be a race condition type bug with having multiple threads sharing the same database pool.

https://github.com/sidekiq/sidekiq/issues/3128#issuecomment-377172609
According to mperham in this issue, this can happen if the processes are re-using the same sockets. I'd assume the queries are getting overlapped/overwritten as they are being sent/received?

Also potentially relevant:
https://github.com/zammad/zammad/issues/3601#issue-914733494

Zammad config settings for workers:
```
WEB_CONCURRENCY=100
ZAMMAD_SESSION_JOBS_CONCURRENT=120
```

**Logs:** 
```
PG::ConnectionBad: PQconsumeInput() could not receive data from server: Connection timed out (ActiveRecord::StatementInvalid)
PQconsumeInput() could not receive data from server: Connection timed out (PG::ConnectionBad)
PQconsumeInput() could not receive data from server: Connection timed out (ActiveRecord::StatementInvalid)
PG::UnableToSend: server closed the connection unexpectedly
```

```
PQconsumeInput() could not receive data from server: Connection timed out (ActiveRecord::StatementInvalid)
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:783:in `block (2 levels) in exec_cache'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:782:in `block in exec_cache'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract_adapter.rb:752:in `block in log'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract_adapter.rb:743:in `log'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:781:in `exec_cache'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:747:in `execute_and_clear'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/querying.rb:54:in `_query_by_sql'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/querying.rb:50:in `find_by_sql'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/statement_cache.rb:150:in `execute'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/core.rb:323:in `find_by'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/app/models/application_model/can_lookup.rb:29:in `lookup'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/sessions.rb:438:in `block (2 levels) in jobs'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/sessions.rb:427:in `each'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/sessions.rb:427:in `block in jobs'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/sessions.rb:414:in `loop'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/sessions.rb:414:in `jobs'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/sessions.rb:375:in `block (2 levels) in jobs'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/sessions.rb:369:in `fork'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/sessions.rb:369:in `block in jobs'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/core_ext/range/each.rb:9:in `each'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/core_ext/range/each.rb:9:in `each'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/sessions.rb:368:in `jobs'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from (eval):1:in `eval_job_method'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval_job_method'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/job_executor.rb:23:in `execute'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:16:in `block in run_loop'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:15:in `times'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:15:in `run_loop'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:8:in `run'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/job_executor.rb:10:in `run'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/manager.rb:84:in `block in start_in_thread'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/application_handle_info.rb:19:in `use'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/manager.rb:82:in `start_in_thread'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/manager.rb:73:in `block (2 levels) in start'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.8/lib/active_support/execution_wrapper.rb:92:in `wrap'
Dec 19 02:42:27 supportdesk zammad-worker-1.service[187158]:         from /opt/zammad/lib/background_services/service/process_scheduled_jobs/manager.rb:72:in `block in start'
```

### Expected behaviour

Zammad workers don't crash. 

### Steps to reproduce the behaviour

Have zammad setup with an external database with

Database.yml
```
adapter: postgresql
host: [removed]
database: zammad
pool: 40
timeout: 7200
encoding: utf8
```

Config:
```
WEB_CONCURRENCY=100
ZAMMAD_SESSION_JOBS_CONCURRENT=120
```

This bug only happens under a high load when database queries are more likely to be running at the same time. 
Our session count is sitting at around 75 sessions
Sessions::Node.registered.count is sitting at 120

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Zammad 5.3 is over 12 months old and your performance configuration is much over the top for good.

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by jackwurth** [comment]
Apologies I entered the wrong version. this happens on the latest 6.1

This is actually a bug, this issue can happen with lower concurrency settings however it is just less likely to occur.

I know zammad intentionally does not provide what the concurrency config values should be. but it means that I just have to guess. what actually is a sensible value for WEB_CONCURRENCY and ZAMMAD_SESSION_JOBS_CONCURRENT for a server of approx 100 users?

**Comment by MrGeneration** [comment]
> I know zammad intentionally does not provide what the concurrency config values should be. but it means that I just have to guess. what actually is a sensible value for WEB_CONCURRENCY and ZAMMAD_SESSION_JOBS_CONCURRENT for a server of approx 100 users?

That is a technical question.

**Comment by jackwurth** [comment]
Okay I'll fill that one out over there. Is it okay if I resubmit this without that aspect in mind?

I know the values are over the top, but there is actually a reproducible bug present here regardless of that. It's possible this bug can happen with lower values, but like most race condition issues this bug is just much more likely to appear with a higher number of threads.

Sorry if I'm being a bit of a nuisance about this, this bug has been haunting me for a while.
