### ISSUE TITLE
Core Workflow: Removing groups with re-adding some discards all permissions the user has

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#5002]
### Used Zammad Version

6.2.0.0e7f99e15.saas

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: verified on current Vivaldi (Win)

### Actual behaviour

Agents cannot create or update any ticket if there's two core workflows in place:
- one that removes all available groups
- one that adds specific groups (depending on the use case)

Doing so will cause Zammad to throw

```
E, [2024-01-07T23:41:04.671145#12472-145300] ERROR -- : Invalid value '7' for field 'owner_id'! (Exceptions::ApplicationModel)
app/models/concerns/checks_core_workflow.rb:50:in `block in check_restrict_values'
app/models/concerns/checks_core_workflow.rb:45:in `each_key'
app/models/concerns/checks_core_workflow.rb:45:in `check_restrict_values'
app/models/concerns/checks_core_workflow.rb:40:in `validate_workflows'
app/controllers/tickets_controller.rb:165:in `block in create'
app/models/transaction.rb:17:in `block in execute'
app/models/transaction.rb:14:in `execute'
app/models/transaction.rb:26:in `execute'
app/controllers/tickets_controller.rb:85:in `create'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2024-01-07T23:41:04.673090#12472-145300] ERROR -- : Error ID MoggpXLQ: Invalid value '7' for field 'owner_id'!
```

Even though the agent does have all the required permissions to do so.
The information regarding the users permission seems to be lost during the check.

![feature_group_removal_breaks_owner_check](https://github.com/zammad/zammad/assets/6549061/0a0b3c4d-9490-4839-bb30-0a1d4a6cf863)

### Expected behaviour

You can remove non relevant groups and add them as per requirement via Core Workflows without issues.

### Steps to reproduce the behaviour

- create a Core workflow that removes all groups
- create a Core workflow with lower priority that adds one or two specific groups
- try to add a new ticket or update any existing one that fits the requirements

### Support Ticket

Ticket#10149151

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by bahusafoo** [comment]
Potential fix (We don't have access to submit pull requests in git):
**/opt/zammad/app/models/concerns/checks_core_workflow.rb** 

```
# Copyright (C) 2012-2023 Zammad Foundation, https://zammad-foundation.org/

module ChecksCoreWorkflow
  extend ActiveSupport::Concern

  included do
    before_create :validate_workflows
    before_update :validate_workflows

    attr_accessor :screen
  end

  private

  class_methods do

    # defines the screens which core workflow executes
    def core_workflow_screens(*screens)
      @core_workflow_screens ||= screens
    end

    # defines the screens which are configurable via admin interface
    def core_workflow_admin_screens(*screens)
      @core_workflow_admin_screens ||= screens
    end
  end

  def validate_workflows
    return if !screen
    return if !UserInfo.current_user_id

    perform_result = CoreWorkflow.perform(payload: {
                                            'event'      => 'core_workflow',
                                            'request_id' => 'ChecksCoreWorkflow.validate_workflows',
                                            'class_name' => self.class.to_s,
                                            'screen'     => screen,
                                            'params'     => attributes
                                          }, user: User.find(UserInfo.current_user_id), assets: false)

    check_restrict_values(perform_result)
    check_mandatory(perform_result)
  end


  def check_restrict_values(perform_result)

    merged_restrict_values = merge_changes_into_restrict_values(perform_result[:restrict_values], changes)
    changes.each_key do |key|
      Rails.logger.warn "SWIFT_KEV Restricted Values Key :::: #{merged_restrict_values}"
      Rails.logger.warn "SWIFT_KEV perform_result Key :::: #{perform_result}"

      # Check if merged_restrict_values is not nil and key is present
      next if merged_restrict_values&.[](key)&.any? { |value| value.to_s == self[key].to_s }
      next if self[key].blank?
      next if restricted_value?(perform_result, key)

      raise Exceptions::ApplicationModel.new(self, "Invalid value '#{self[key]}' for field '#{key}'!")
    end
  end

  def merge_changes_into_restrict_values(restrict_values, changes)
    return restrict_values unless restrict_values.is_a?(Hash) && changes.is_a?(Hash)

    # Iterate through changes and merge each value into the corresponding key in restrict_values
    changes.each do |key, value|
      restrict_values[key] ||= []
      restrict_values[key] |= Array(value).map(&:to_s)
    end

    restrict_values
  end



  def restricted_value?(perform_result, key)
    if self[key].is_a?(Array)
      (self[key].map(&:to_s) - perform_result[:restrict_values][key].map(&:to_s)).blank?
    else
      perform_result[:restrict_values][key].any? { |value| value.to_s == self[key].to_s }
    end
  end

  def check_mandatory(perform_result)
    perform_result[:mandatory].each_key do |key|
      next if field_visible?(perform_result, key)
      next if !field_mandatory?(perform_result, key)
      next if !column_empty?(key)
      next if !colum_default?(key)

      raise Exceptions::ApplicationModel.new(self, "Missing required value for field '#{key}'!")
    end
  end

  def field_visible?(perform_result, key)
    %w[hide remove].include?(perform_result[:visibility][key])
  end

  def field_mandatory?(perform_result, key)
    perform_result[:mandatory][key]
  end

  def column_empty?(key)
    self[key].nil? || ([true, false].exclude?(self[key]) && self[key].blank?)
  end

  def colum_default?(key)
    self.class.column_defaults[key].nil?
  end
end
```

**Comment by MrGeneration** [comment]
Fork the repo and create the PR from there please.

**Comment by bahusafoo** [comment]
https://github.com/zammad/zammad/pull/5003

**Comment by bahusafoo** [comment]
Corrected some extra blank line errors in PR validation.

**Comment by bahusafoo** [comment]
Offenses:

app/models/concerns/checks_core_workflow.rb:60:5: C: Zammad/PreferNegatedIfOverUnless: Favor if !foobar over unless foobar for negative conditions.
    return restrict_values unless restrict_values.is_a?(Hash) && changes.is_a?(Hash)
    
 Seems like the check is quite picky about how it wants this.  Changed it to use an if format.
