### ISSUE TITLE
No possibility to set the base DN manually in LDAP configuration with Placetel

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5009]
### Used Zammad Version

6.2.0.bba4f84a3.saas 

### Environment

- Installation method: SaaS

### Actual behaviour

I wan’t to connect the Placetel LDAP addressbook, but i couldn’t set the Base DN by hand and i get no Base DN automatically from Placetel. 

https://www.placetel.de/hilfe/telefonanlage/ldap-telefonbuch

![Bildschirmfoto 2024-01-17 um 14 17 23](https://github.com/zammad/zammad/assets/129729908/eb817fab-0fcb-4e6b-b300-f39970b5ca64)

![Bildschirmfoto 2024-01-17 um 14 03 25](https://github.com/zammad/zammad/assets/129729908/476e3fc5-932a-499f-91d0-161a727f2446)

And i can't leave this field blank because then i get this error. 

![Bildschirmfoto 2024-01-17 um 14 22 18](https://github.com/zammad/zammad/assets/129729908/c4a28270-3431-424d-899f-389344c8ee6b)

```
I, [2024-01-16T10:35:35.755933#2740086-145740] INFO -- : Started GET "/api/v1/integration/ldap/job_start?_=1705400009871" for 46.89.229.150 at 2024-01-16 10:35:35 +0000
I, [2024-01-16T10:35:35.760829#2740086-145740] INFO -- : Processing by Integration::LdapController#job_start_index as JSON
I, [2024-01-16T10:35:35.760876#2740086-145740] INFO -- : Parameters: {"_"=>"1705400009871"}
I, [2024-01-16T10:35:35.773319#2740086-145740] INFO -- : Completed 200 OK in 12ms (Views: 0.2ms | ActiveRecord: 2.7ms | Allocations: 5653)
I, [2024-01-16T10:35:36.929942#2740086-145300] INFO -- : Started POST "/api/v1/integration/ldap/bind" for 46.89.229.150 at 2024-01-16 10:35:36 +0000
I, [2024-01-16T10:35:36.934707#2740086-145300] INFO -- : Processing by Integration::LdapController#bind as JSON
I, [2024-01-16T10:35:36.934758#2740086-145300] INFO -- : Parameters: {"base_dn"=>"", "bind_user"=>"XXX@XXX", "bind_pw"=>"[FILTERED]", "host"=>"directory.placetel.de", "ssl"=>"ssl", "ssl_verify"=>true}
E, [2024-01-16T10:35:36.976449#2740086-145300] ERROR -- : Can't bind to 'directory.placetel.de', 34, Invalid DN Syntax (Exceptions::UnprocessableEntity)
lib/ldap.rb:132:in `binded_connection'
lib/ldap.rb:114:in `connection'
lib/ldap.rb:33:in `initialize'
app/controllers/integration/ldap_controller.rb:32:in `new'
app/controllers/integration/ldap_controller.rb:32:in `block in bind'
app/controllers/concerns/integration/import_job_base.rb:45:in `answer_with'
app/controllers/integration/ldap_controller.rb:28:in `bind'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2024-01-16T10:35:36.977225#2740086-145300] ERROR -- : Can't connect to 'directory.placetel.de' on port '636', Can't bind to 'directory.placetel.de', 34, Invalid DN Syntax (Exceptions::UnprocessableEntity)
lib/ldap.rb:135:in `rescue in binded_connection'
lib/ldap.rb:120:in `binded_connection'
lib/ldap.rb:114:in `connection'
lib/ldap.rb:33:in `initialize'
app/controllers/integration/ldap_controller.rb:32:in `new'
app/controllers/integration/ldap_controller.rb:32:in `block in bind'
app/controllers/concerns/integration/import_job_base.rb:45:in `answer_with'
app/controllers/integration/ldap_controller.rb:28:in `bind'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
```

### Expected behaviour

If I don't automatically get a base DN from the LDAP Server that I can set it manually or leave it blank.

### Steps to reproduce the behaviour

- Create a new LDAP Connection 

![Bildschirmfoto 2024-01-17 um 14 17 23](https://github.com/zammad/zammad/assets/129729908/239940af-b675-4fe9-bf8b-edddbdc145a1)

### Support Ticket

Ticket#10149639
Ticket#10151055
Ticket#10212102

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by YetAnotherGerrit** [comment]
Custom BaseDN is (currently) only possible if the LDAP-server does not allow unauthorized connections.

> Now, if your LDAP system restricts anonymous bind, Zammad 6.2 is equipped to identify this constraint. Consequently, instead of a pre-filled select field, Zammad presents users with an editable "Base DN" text field.

Source: https://zammad.com/en/releases/6-2#2-security-enhancements

**Comment by MrGeneration** [comment]
I believe the bug tag is much more suitable than the enhancement tag on this issue, because our release note claims it's not a drop down - but it still is.

![image](https://github.com/zammad/zammad/assets/6549061/fc689d85-bc28-43bf-aa1f-89efcac52d0a)

**Comment by dominikklein** [comment]
Currently, it's working the same for allowed anonymous LDAP connections. It's showing the dropdown and only when we are detecting not allowed anonymous LDAP connections are we showing a simple text field.
I think we could always go the way of showing a simple text field when we are not able to fetch the same base DN.
But his error message looks also to me like we have some general problem here. Maybe placetel is doing it in a way we are currently not supporting.

**Comment by MrGeneration** [comment]
Or we provide what we found (if we found anything) and allow the admin to adjust the DN if the admin knows better.

**Comment by thecube13** [comment]
The same behavior when trying to connect to the Zimbra LDAP server. The base DN field allows you to insert text, but when you click on the next field, the base DN is cleared.

**Comment by byPARSE** [comment]
Same issue here in V6.4. I need to manually change the BaseDN in order to filter a specific OU. 
I do not want to filter the OU later in the "User filter" field, as it creates more load on the system when using wildcards.

**Comment by TomGem** [comment]
I've run into the same problem. If you apply the attached patch the LDAP wizard "Base DN" field changes from a dropdown to a textfield. This way you can enter the correct Base DN of your LDAP server.

`patch /opt/zammad/app/assets/javascripts/app/controllers/_integration/ldap.coffee ldap.coffee.patch`

[ldap.coffee.patch](https://github.com/user-attachments/files/24821863/ldap.coffee.patch)
