### ISSUE TITLE
Missing value for 'body', but set in request.

### ISSUE THREAD

**Issue by rtheys** [zammad/zammad#5039]
### Used Zammad Version

6.2.0-1706884711.0ecb2b87.bookworm

### Environment

- Installation method: Debian package 6.2.0-1706884711.0ecb2b87.bookworm
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian 12
- Database + version:  postgresql 15
- Elasticsearch version: 8.12
- Browser + version: Firefox, but also happens using API

### Actual behaviour

Then a new ticket is creating using the + sign, and created as a "received call", the submission fails with the error that the body field is not provided. This is incorrect as the field is filled in. The same happens when we create a ticket using the API.

### Expected behaviour

Creation of a new ticket as was possible in previous versions.

### Steps to reproduce the behaviour

While creating a new ticket using the API, the following is logged.

```
I, [2024-02-03T19:53:33.529560#75064-142760]  INFO -- : Started POST "/api/v1/tickets" for 134.58.58.10 at 2024-02-03 19:53:33 +0100
I, [2024-02-03T19:53:33.533982#75064-142760]  INFO -- : Processing by TicketsController#create as HTML
I, [2024-02-03T19:53:33.534055#75064-142760]  INFO -- :   Parameters: {"group"=>"IT", "priority_id"=>2, "state"=>"new", "customer_id"=>158, "title"=>"test test", "type"=>"email", "article"=>{"type_id"=>1, "subject"=>"test test", "body"=>"[FILTERED]", "content_type"=>"text/html", "type"=>"email", "internal"=>false, "sender"=>"Customer", "origin_by_id"=>158, "from"=>"Rik Theys <rik.theys@esat.kuleuven.be>", "created_by"=>"rik.theys@esat.kuleuven.be", "cc"=>""}}
E, [2024-02-03T19:53:33.661804#75064-142760] ERROR -- : Missing required value for field 'body'! (Exceptions::ApplicationModel)
app/models/concerns/checks_core_workflow.rb:69:in `block in check_mandatory'
app/models/concerns/checks_core_workflow.rb:63:in `each_key'
app/models/concerns/checks_core_workflow.rb:63:in `check_mandatory'
app/models/concerns/checks_core_workflow.rb:41:in `validate_workflows'
app/controllers/tickets_controller.rb:165:in `block in create'
app/models/transaction.rb:17:in `block in execute'
app/models/transaction.rb:14:in `execute'
app/models/transaction.rb:26:in `execute'
app/controllers/tickets_controller.rb:85:in `create'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2024-02-03T19:53:33.665857#75064-142760] ERROR -- : Error ID j6kmeGy6: Missing required value for field 'body'!
```

The same happens when submitted using the form:
```
I, [2024-02-03T19:49:09.058545#73429-142900]  INFO -- : Started PUT "/api/v1/taskbar/1704" for 84.193.38.21 at 2024-02-03 19:49:09 +0100
I, [2024-02-03T19:49:09.062352#73429-142900]  INFO -- : Processing by TaskbarController#update as JSON
I, [2024-02-03T19:49:09.062407#73429-142900]  INFO -- :   Parameters: {"key"=>"TicketCreateScreen-7517", "callback"=>"TicketCreate", "state"=>{"body"=>"[FILTERED]", "formSenderType"=
>"phone-in", "shared_draft_id"=>"", "form_id"=>"986210770", "title"=>"test", "customer_id"=>"158", "customer_id_completion"=>"Rik Theys <rik.theys@esat.kuleuven.be>", "organization_i
d"=>"2", "cc"=>"", "group_id"=>"1", "owner_id"=>"", "state_id"=>"2", "priority_id"=>"2", "tags"=>""}, "params"=>{"id"=>"7517", "shown"=>true}, "prio"=>2, "notify"=>false, "active"=>t
rue, "attachments"=>[], "updated_at"=>"2024-02-03T18:48:57.667Z", "id"=>"1704"}
I, [2024-02-03T19:49:09.082875#73429-142900]  INFO -- : Completed 200 OK in 20ms (Views: 0.3ms | ActiveRecord: 3.9ms | Allocations: 12307)
I, [2024-02-03T19:49:09.324760#73429-149140]  INFO -- : Started POST "/api/v1/tickets" for 84.193.38.21 at 2024-02-03 19:49:09 +0100
I, [2024-02-03T19:49:09.328675#73429-149140]  INFO -- : Processing by TicketsController#create as JSON
I, [2024-02-03T19:49:09.328723#73429-149140]  INFO -- :   Parameters: {"title"=>"test", "group_id"=>"1", "owner_id"=>"", "customer_id"=>"158", "state_id"=>"2", "priority_id"=>"2", "a
rticle"=>{"to"=>"IT", "from"=>"Rik Theys <rik.theys@esat.kuleuven.be>", "body"=>"[FILTERED]", "type_id"=>5, "sender_id"=>2, "form_id"=>"986210770", "content_type"=>"text/html"}, "tag
s"=>"", "organization_id"=>"2", "id"=>"c-84"}
E, [2024-02-03T19:49:09.593517#73429-149140] ERROR -- : Missing required value for field 'body'! (Exceptions::ApplicationModel)
app/models/concerns/checks_core_workflow.rb:69:in `block in check_mandatory'
app/models/concerns/checks_core_workflow.rb:63:in `each_key'
app/models/concerns/checks_core_workflow.rb:63:in `check_mandatory'
app/models/concerns/checks_core_workflow.rb:41:in `validate_workflows'
app/controllers/tickets_controller.rb:165:in `block in create'
app/models/transaction.rb:17:in `block in execute'
app/models/transaction.rb:14:in `execute'
app/models/transaction.rb:26:in `execute'
app/controllers/tickets_controller.rb:85:in `create'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
```

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dlc-letelier** [comment]
I confirm the same error using the last version. Same log output. Users cannot create tickets anymore.

**Comment by rolfschmidt** [comment]
hey guys, sorry will fix it asap.

**Comment by rolfschmidt** [comment]
Hotfix

```
root> zammad run rails c
rails> field = ObjectManager::Attribute.for_object('TicketArticle').find_by(name: 'body')
rails> field.screens.delete('create_middle')
rails> field.save!
root> systemctl restart zammad
```

**Comment by rtheys** [comment]
Thanks for your quick response! I can confirm the hotfix allows us to create tickets again.

**Comment by rolfschmidt** [comment]
Packager will take a couple of hours until the update is ready.

**commits**

https://github.com/zammad/zammad/commit/5ca5217f03cc02105e1025fd7bda29c1adb9cf9b

https://github.com/zammad/zammad/commit/eaf7d5b3bad4b2647046e70c6118edb0d773cbf8
