### ISSUE TITLE
OTRS Migration fails

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#506]
I tried to import our KIX into Zammad on the command line. 
Used OTRS 5.0.14 sources and the KIX DB.
Installed Znuny Repo & Zammad Migrator via: 

```
su www-data -s /bin/bash -c "./otrs.Console.pl Admin::Package::Install --force /tmp/Znuny4OTRS-Repo-5.0.15.opm"
su www-data -s /bin/bash -c "./otrs.Console.pl Admin::Package::Install --force /tmp/Znuny4OTRS-ZammadMigrator-1.2.1.opm"
```
Executing "Import::OTRS.start" gives the following Error after some seconds:

```
.
.
.
thread#-: update Group.find_by(id: 14)
thread#-: update Group.find_by(id: 763)
thread#-: update Group.find_by(id: 593)
thread#-: update Group.find_by(id: 289)
thread#-: update Group.find_by(id: 277)
thread#-: update Group.find_by(id: 558)
thread#-: update Group.find_by(id: 947)
thread#-: loading User...
thread#-: POST: http://kix-test.intdmz.h1.mdd/otrs/public.pl?Action=ZammadMigrator
thread#-: PARAMS: {:Subaction=>"Export", :Object=>"User", :Limit=>"", :Offset=>"", :Diff=>0, :Action=>"ZammadMigrator", :Key=>"XHBrT9f1YfGix0lppyQ6caBSxsAX494d9tmuzaPX"}
thread#-: POST: http://kix-test.intdmz.h1.mdd/otrs/public.pl?Action=ZammadMigrator
thread#-: PARAMS: {:Subaction=>"Export", :Object=>"Group", :Limit=>"", :Offset=>"", :Diff=>0, :Action=>"ZammadMigrator", :Key=>"XHBrT9f1YfGix0lppyQ6caBSxsAX494d9tmuzaPX"}
thread#-: POST: http://kix-test.intdmz.h1.mdd/otrs/public.pl?Action=ZammadMigrator
thread#-: PARAMS: {:Subaction=>"Export", :Object=>"Role", :Limit=>"", :Offset=>"", :Diff=>0, :Action=>"ZammadMigrator", :Key=>"XHBrT9f1YfGix0lppyQ6caBSxsAX494d9tmuzaPX"}
thread#-: POST: http://kix-test.intdmz.h1.mdd/otrs/public.pl?Action=ZammadMigrator
thread#-: PARAMS: {:Subaction=>"Export", :Object=>"Queue", :Limit=>"", :Offset=>"", :Diff=>0, :Action=>"ZammadMigrator", :Key=>"XHBrT9f1YfGix0lppyQ6caBSxsAX494d9tmuzaPX"}
thread#-: update User.find_by(id: 201)
thread#-: update User.find_by(id: 154)
thread#-: update User.find_by(id: 146)
thread#-: update User.find_by(id: 74)
thread#-: update User.find_by(id: 24)
TypeError: no implicit conversion of String into Integer
	from /opt/zammad/lib/import/otrs/user.rb:141:in `[]'
	from /opt/zammad/lib/import/otrs/user.rb:141:in `groups_from_otrs_group'
	from /opt/zammad/lib/import/otrs/user.rb:133:in `block in groups_from_groups'
	from /opt/zammad/lib/import/otrs/user.rb:132:in `each'
	from /opt/zammad/lib/import/otrs/user.rb:132:in `groups_from_groups'
	from /opt/zammad/lib/import/otrs/user.rb:161:in `block in groups_from_otrs_roles'
	from /opt/zammad/lib/import/otrs/user.rb:159:in `each'
	from /opt/zammad/lib/import/otrs/user.rb:159:in `groups_from_otrs_roles'
	from /opt/zammad/lib/import/otrs/user.rb:121:in `roles'
	from /opt/zammad/lib/import/otrs/user.rb:110:in `role_ids'
	from /opt/zammad/lib/import/otrs/user.rb:74:in `map'
	from /opt/zammad/lib/import/otrs/user.rb:27:in `import'
	from /opt/zammad/lib/import/otrs/user.rb:21:in `initialize'
	from /opt/zammad/lib/import/factory.rb:12:in `new'
	from /opt/zammad/lib/import/factory.rb:12:in `block in import'
	from /opt/zammad/lib/import/factory.rb:10:in `each'
	from /opt/zammad/lib/import/factory.rb:10:in `import'
	from /opt/zammad/lib/import/otrs.rb:141:in `import_action'
	from /opt/zammad/lib/import/otrs.rb:72:in `import'
	from /opt/zammad/lib/import/otrs.rb:158:in `updateable_objects'
	from /opt/zammad/lib/import/otrs.rb:43:in `start'
	from (irb):1
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /opt/zammad/bin/rails:4:in `require'
	from /opt/zammad/bin/rails:4:in `<main>'
irb(main):002:0> 
```
In production.log i see errors like:

```
E, [2016-12-05T10:15:24.551453 #12392] ERROR -- : execute Import::OTRS.diff_worker (try_count 4) exited with error #<TypeError: no implicit conversion of String into Integer>
E, [2016-12-05T10:15:25.972558 #12392] ERROR -- : execute Import::OTRS.diff_worker (try_count 5) exited with error #<Exceptions::UnprocessableEntity: Invalid email>

```

**Comment by thorsteneckel** [comment]
@monotek could you please provide me the result of this call:
`https://your.tld/otrs/public.pl?Action=ZammadMigrator;Key=*supersecretkey*;Subaction=Export;Object=Role``

to support@zammad.com

Thanks!

**Comment by monotek** [comment]
You've got mail ;-)

**Comment by thorsteneckel** [comment]
Thanks! The next one please to support@zammad.com ;)

**Comment by thorsteneckel** [comment]
@monotek - can't reproduce or reconstruct the issue yet. Could you please send the output of the following calls too:

`https://your.tld/otrs/public.pl?Action=ZammadMigrator;Key=*supersecretkey*;Subaction=Export;Object=User`
`https://your.tld/otrs/public.pl?Action=ZammadMigrator;Key=*supersecretkey*;Subaction=Export;Object=Group`
`https://your.tld/otrs/public.pl?Action=ZammadMigrator;Key=*supersecretkey*;Subaction=Export;Object=Queue`

To support@zammad.com

Thanks!

**Comment by monotek** [comment]
You've got mail again :-)

**Comment by thorsteneckel** [comment]
I can't reproduce this issue with the provided data 🤕  I get an error with your user with UserID '339' which has no valid email stored in UserEmail. I added an exception to see if there is another possible issue but it wasn't. I tried it multiple times without any success. Can you reproduce it?
Is your system accessible via the internet? Would it be possible to paste me the import credentials via email so i can work with the real dataset? You can send it anytime to support@zammad.com
Otherwise it would be great to take a look at it via Teamviewer or so?
