### ISSUE TITLE
Customer search guess should not throw errors

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#5132]
### Used Zammad Version

6.2

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

```
E, [2024-04-18T11:20:00.355032#1141758-3535860] ERROR -- : Couldn't find User with 'id'=guess:xxx@xxx (ActiveRecord::RecordNotFound)
app/controllers/users_controller.rb:66:in `show'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
```

### Expected behaviour

No errors in log when user is not found.

### Steps to reproduce the behaviour

- Search for customer which does not exist in ticket create mask and switch group for example.

### Support Ticket

Ticket#10150826

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@rolfschmidt Can you add maybe some more details here? It's difficult to follow what is the problem about.
