### ISSUE TITLE
Duplicate articles created when sending multiple pictures over WhatsApp

### ISSUE THREAD

**Issue by Mirtaaa** [zammad/zammad#5164]
### Used Zammad Version

6.3

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

When I send multiple pictures over WhatsApp to my Zammad instance, every picture is apearing twice in the ticket as 2 separate articles.

![Screenshot 2024-05-07 140650](https://github.com/zammad/zammad/assets/103510339/98c9882e-ea73-4c33-8ca2-6952dfcefe66)

### Expected behaviour

When sending multiple Pictures over WhatsApp to my Zammad instance, every picture should appear only once.

### Steps to reproduce the behaviour

Send multiple pictures at once over WhatsApp to your Zammad Instance.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment]
This looks like to be caused by multiple webhook calls made by WhatsApp Business platform, in my case spaced by about 3 seconds. The trouble is they contain the exact same payload, so it looks like it's triggered multiple times for the same message.

```
I, [2024-09-24T10:54:14.961123#45308-25680]  INFO -- : Started POST "/api/v1/channels_whatsapp_webhook/***" for *** at 2024-09-24 10:54:14 +0100
I, [2024-09-24T10:54:14.963754#45308-25680]  INFO -- : Processing by ChannelsWhatsappController#perform_webhook as */*
I, [2024-09-24T10:54:14.963888#45308-25680]  INFO -- :   Parameters: {"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"***", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"***", "phone_number_id"=>"***"}, "contacts"=>[{"profile"=>{"name"=>"***"}, "wa_id"=>"***"}], "messages"=>[{"from"=>"***", "id"=>"wamid.HBgMNDQ3Mzc3MTE0OTg5FQIAEhggMkM1NkFBRjVGQUNBMzlBNzVEQTY2Mzg0RjY3MUQ5OTMA", "timestamp"=>"1727171652", "type"=>"image", "image"=>{"mime_type"=>"image/jpeg", "sha256"=>"yQN584y7rWZ4G4PF9DGvqhH2/2rz1lnrGhEVNsY8RHI=", "id"=>"4054991114777496"}}]}, "field"=>"messages"}]}], "callback_url_uuid"=>"***"}
```

```
I, [2024-09-24T10:54:17.083232#45308-158840]  INFO -- : Started POST "/api/v1/channels_whatsapp_webhook/***" for 2a03:2880:ff:28::face:b00c at 2024-09-24 10:54:17 +0100
I, [2024-09-24T10:54:17.096077#45308-158840]  INFO -- : Processing by ChannelsWhatsappController#perform_webhook as */*
I, [2024-09-24T10:54:17.096518#45308-158840]  INFO -- :   Parameters: {"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"***", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"***", "phone_number_id"=>"***"}, "contacts"=>[{"profile"=>{"name"=>"***"}, "wa_id"=>"***"}], "messages"=>[{"from"=>"***", "id"=>"wamid.HBgMNDQ3Mzc3MTE0OTg5FQIAEhggMkM1NkFBRjVGQUNBMzlBNzVEQTY2Mzg0RjY3MUQ5OTMA", "timestamp"=>"1727171652", "type"=>"image", "image"=>{"mime_type"=>"image/jpeg", "sha256"=>"yQN584y7rWZ4G4PF9DGvqhH2/2rz1lnrGhEVNsY8RHI=", "id"=>"4054991114777496"}}]}, "field"=>"messages"}]}], "callback_url_uuid"=>"***"}
```

We might need to put some duplicate prevention in place for these requests not to result in multiple articles, because I doubt we can change this on WhatsApp side.

**Comment by dvuckovic** [comment]
After brilliant detective work from @fliebe92 we realized the subsequent triggers were caused by errors emitted to the webhook response:

```
E, [2024-09-24T10:54:16.275712#45308-25680] ERROR -- : undefined method `provider_job_id' for false:FalseClass (NoMethodError)
lib/whatsapp/webhook/message.rb:259:in `schedule_reminder_job'
lib/whatsapp/webhook/message.rb:20:in `process'
lib/whatsapp/webhook/payload.rb:44:in `process_message'
lib/whatsapp/webhook/payload.rb:27:in `process'
app/controllers/channels_whatsapp_controller.rb:25:in `perform_webhook'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
D, [2024-09-24T10:54:16.277346#45308-159260] DEBUG -- :   Ticket::StateType Load (2.4ms)  SELECT "ticket_state_types".* FROM "ticket_state_types" WHERE "ticket_state_types"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
D, [2024-09-24T10:54:16.279033#45308-159260] DEBUG -- :   ↳ app/models/application_model/can_lookup.rb:30:in `block in lookup'
D, [2024-09-24T10:54:16.279537#45308-25680] DEBUG -- :   User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT $1  [["LIMIT", 1]]
D, [2024-09-24T10:54:16.279673#45308-25680] DEBUG -- :   ↳ app/models/application_model/can_lookup.rb:30:in `block in lookup'
D, [2024-09-24T10:54:16.279780#45308-159260] DEBUG -- :   User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]
E, [2024-09-24T10:54:16.280843#45308-25680] ERROR -- : Error ID b-GmiLQr: undefined method `provider_job_id' for false:FalseClass
D, [2024-09-24T10:54:16.280950#45308-159260] DEBUG -- :   ↳ app/models/ticket.rb:668:in `check_default_organization'
I, [2024-09-24T10:54:16.283685#45308-25680]  INFO -- : Completed 500 Internal Server Error in 1319ms (Views: 0.4ms | ActiveRecord: 214.7ms | Allocations: 90440)
```
