### ISSUE TITLE
Starting OTRS import a second time is raising an exeption

### ISSUE THREAD

**Issue by martini** [zammad/zammad#526]
Source: vz599.demo.znuny.com

Import via console works fine at first time. After executing "Import::OTRS.start" again, I get the following error message:

```
NameError: undefined local variable or method `user' for #<Import::OTRS::CustomerUser:0x007ff032eec030>
	from /Users/me/src/zammad_git_ui/lib/import/otrs/customer_user.rb:51:in `updated?'
	from /Users/me/src/zammad_git_ui/lib/import/otrs/customer_user.rb:38:in `create_or_update'
	from /Users/me/src/zammad_git_ui/lib/import/otrs/customer_user.rb:34:in `import'
	from /Users/me/src/zammad_git_ui/lib/import/otrs/customer_user.rb:28:in `initialize'
	from /Users/me/src/zammad_git_ui/lib/import/factory.rb:12:in `new'
	from /Users/me/src/zammad_git_ui/lib/import/factory.rb:12:in `block in import'
	from /Users/me/src/zammad_git_ui/lib/import/factory.rb:10:in `each'
	from /Users/me/src/zammad_git_ui/lib/import/factory.rb:10:in `import'
	from /Users/me/src/zammad_git_ui/lib/import/otrs.rb:141:in `import_action'
	from /Users/me/src/zammad_git_ui/lib/import/otrs.rb:131:in `imported?'
	from /Users/me/src/zammad_git_ui/lib/import/otrs.rb:118:in `block in limit_import'
	from /Users/me/src/zammad_git_ui/lib/import/otrs.rb:116:in `loop'
	from /Users/me/src/zammad_git_ui/lib/import/otrs.rb:116:in `limit_import'
	from /Users/me/src/zammad_git_ui/lib/import/otrs.rb:167:in `customer_user'
	from /Users/me/src/zammad_git_ui/lib/import/otrs.rb:45:in `start'
	from (irb):13
	from /Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/me/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by thorsteneckel** [comment]
Fixed with commit above. Thanks!
