### ISSUE TITLE
LDAP Monitoring error message missleading

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#5262]
### Used Zammad Version

6.3.1.d9607d662.saas

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: n/a

### Actual behaviour

Zammad issues the monitoring message `Stuck import backend 'Import::Ldap' detected. Last update: 2024-07-12 11:25:17 UTC` which can mean a lot like "not finishing the job" - but the actual log in the error is a connection time out:

```
E, [2024-07-12T09:25:16.834664#754326-20443720] ERROR -- : Connection timed out - user specified timeout (Net::LDAP::Error)
lib/ldap.rb:129:in `binded_connection'
lib/ldap.rb:114:in `connection'
lib/ldap.rb:33:in `initialize'
lib/sequencer/unit/ldap/connection.rb:11:in `new'
lib/sequencer/unit/ldap/connection.rb:11:in `ldap_connection'
lib/sequencer/unit/common/provider/attribute.rb:25:in `value'
lib/sequencer/unit/common/provider/attribute.rb:30:in `ignore?'
lib/sequencer/unit/common/provider/fallback.rb:8:in `ignore?'
lib/sequencer/unit/common/provider/attribute.rb:6:in `process'
lib/sequencer/unit/base.rb:247:in `process'
lib/sequencer.rb:76:in `block (4 levels) in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:75:in `block (3 levels) in process'
lib/sequencer/state.rb:151:in `process'
lib/sequencer.rb:73:in `block (2 levels) in process'
lib/sequencer/units.rb:27:in `block in each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer.rb:71:in `each_with_index'
lib/sequencer.rb:71:in `block in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:69:in `process'
lib/sequencer.rb:24:in `process'
lib/sequencer/unit/import/common/sub_sequence/mixin/base.rb:26:in `sequence_resource'
lib/sequencer/unit/import/ldap/sources/sub_sequence.rb:12:in `block in process'
lib/sequencer/unit/import/ldap/sources/sub_sequence.rb:11:in `each'
lib/sequencer/unit/import/ldap/sources/sub_sequence.rb:11:in `process'
lib/sequencer/unit/base.rb:247:in `process'
lib/sequencer.rb:76:in `block (4 levels) in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:75:in `block (3 levels) in process'
lib/sequencer/state.rb:151:in `process'
lib/sequencer.rb:73:in `block (2 levels) in process'
lib/sequencer/units.rb:27:in `block in each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer.rb:71:in `each_with_index'
lib/sequencer.rb:71:in `block in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:69:in `process'
lib/sequencer.rb:24:in `process'
lib/import/mixin/sequence.rb:17:in `process'
lib/import/integration_base.rb:94:in `start'
app/models/import_job.rb:26:in `start'
app/models/import_job.rb:107:in `start'
app/models/import_job.rb:97:in `start_registered'
(eval):1:in `eval_job_method'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval_job_method'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:23:in `execute'
lib/background_services/service/process_scheduled_jobs/job_executor/one_time.rb:6:in `run'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:10:in `run'
lib/background_services/service/process_scheduled_jobs/manager.rb:84:in `block in start_in_thread'
lib/application_handle_info.rb:19:in `use'
lib/background_services/service/process_scheduled_jobs/manager.rb:82:in `start_in_thread'
lib/background_services/service/process_scheduled_jobs/manager.rb:73:in `block (2 levels) in start'
lib/background_services/service/process_scheduled_jobs/manager.rb:72:in `block in start'
E, [2024-07-12T09:25:16.835106#754326-20443720] ERROR -- : ImportJob 'Import::Ldap' failed: Can't connect to 'ldap.example.com' on port '636', Connection timed out - user specified timeout
E, [2024-07-12T09:25:16.835141#754326-20443720] ERROR -- : Can't connect to 'ldap.example.com' on port '636', Connection timed out - user specified timeout (Exceptions::UnprocessableEntity)
lib/ldap.rb:135:in `rescue in binded_connection'
lib/ldap.rb:135:in `rescue in binded_connection'
lib/ldap.rb:120:in `binded_connection'
lib/ldap.rb:114:in `connection'
lib/ldap.rb:33:in `initialize'
lib/sequencer/unit/ldap/connection.rb:11:in `new'
lib/sequencer/unit/ldap/connection.rb:11:in `ldap_connection'
lib/sequencer/unit/common/provider/attribute.rb:25:in `value'
lib/sequencer/unit/common/provider/attribute.rb:30:in `ignore?'
lib/sequencer/unit/common/provider/fallback.rb:8:in `ignore?'
lib/sequencer/unit/common/provider/attribute.rb:6:in `process'
lib/sequencer/unit/base.rb:247:in `process'
lib/sequencer.rb:76:in `block (4 levels) in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:75:in `block (3 levels) in process'
lib/sequencer/state.rb:151:in `process'
lib/sequencer.rb:73:in `block (2 levels) in process'
lib/sequencer/units.rb:27:in `block in each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer.rb:71:in `each_with_index'
lib/sequencer.rb:71:in `block in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:69:in `process'
lib/sequencer.rb:24:in `process'
lib/sequencer/unit/import/common/sub_sequence/mixin/base.rb:26:in `sequence_resource'
lib/sequencer/unit/import/ldap/sources/sub_sequence.rb:12:in `block in process'
lib/sequencer/unit/import/ldap/sources/sub_sequence.rb:11:in `each'
lib/sequencer/unit/import/ldap/sources/sub_sequence.rb:11:in `process'
lib/sequencer/unit/base.rb:247:in `process'
lib/sequencer.rb:76:in `block (4 levels) in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:75:in `block (3 levels) in process'
lib/sequencer/state.rb:151:in `process'
lib/sequencer.rb:73:in `block (2 levels) in process'
lib/sequencer/units.rb:27:in `block in each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer.rb:71:in `each_with_index'
lib/sequencer.rb:71:in `block in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:69:in `process'
lib/sequencer.rb:24:in `process'
lib/import/mixin/sequence.rb:17:in `process'
lib/import/integration_base.rb:94:in `start'
app/models/import_job.rb:26:in `start'
app/models/import_job.rb:107:in `start'
app/models/import_job.rb:97:in `start_registered'
(eval):1:in `eval_job_method'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval_job_method'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:23:in `execute'
lib/background_services/service/process_scheduled_jobs/job_executor/one_time.rb:6:in `run'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:10:in `run'
lib/background_services/service/process_scheduled_jobs/manager.rb:84:in `block in start_in_thread'
lib/application_handle_info.rb:19:in `use'
lib/background_services/service/process_scheduled_jobs/manager.rb:82:in `start_in_thread'
lib/background_services/service/process_scheduled_jobs/manager.rb:73:in `block (2 levels) in start'
lib/background_services/service/process_scheduled_jobs/manager.rb:72:in `block in start'
I, [2024-07-12T09:25:16.840349#754326-20443720]  INFO -- : ended ImportJob.start_registered took: 10.612399851 seconds.
```

### Expected behaviour

Zammad reflects if an LDAP job is stuck (as in not finishing since let's say an hour) or is the connection is not successful due e.g. timeout, connection refused or maybe also due to incorrect authentication information.

### Steps to reproduce the behaviour

- Successfully configure LDAP
- let it sync
- disable the LDAP service so it won't answer to Zammad
- wait for the next LDAP sync run or enforce it yourself
- check the monitoring page of Zammad

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by binsky08** [comment]
When I try to reproduce it, exactly following your steps to reproduce (trying both multiple times, waiting for the next LDAP sync run and enforcing it myself), I get a connection time out error, but nothing like "Stuck import ..."

In Monitoring:
![grafik](https://github.com/user-attachments/assets/f5dd5d11-f6ff-4ca8-bc29-187c206e8339)

In LDAP Settings:
![grafik](https://github.com/user-attachments/assets/9cd7b927-e562-4600-926a-55814d948594)

Any other idea to get that reproduced?

**Comment by MrGeneration** [comment]
No sorry. I can't remember stuff that's older than two weeks for various reasons.
Usually these type of tickets arrive due to internal monitoring stuff. Most often this is all input I have so I'll just close this.
