### ISSUE TITLE
Conflict with the extended follow-up detection - which cannot be deactivated

### ISSUE THREAD

**Issue by martini** [zammad/zammad#5286]
### Used Zammad Version

6.3

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

This problem only occurs in certain situations.

In Zammad there is an extended follow up detection.

**When is this active?**
If an e-mail is sent to Zammad that has not led to successful FollowUp detection in Zammad, this is also applied.

**What does this additional follow-up detection do?**
It checks whether:
a) An article already exists in Zammad, which has a message id that is present in the refrences header of the incoming e-mail.
b) This article in Zammad has the same subject. 

**Use case:**
a) A customer sends an e-mail to Zammad.
b) 2 minutes later, the customer goes to the sent order and sends a second e-mail afterwards.

Result: By means of this extended follow-up recognition, *no* second ticket is opened, but a follow-up to the first ticket is recognized.

**What is the problem?**

In special cases, you want to deactivate this extended followup detection because it triggers unexpected behavior in certain cases. However, there is currently no option to disable this extended follow-up detection.

### Expected behaviour

It should be possible to deactivate the extended follow-up detection.

### Steps to reproduce the behaviour

See Actual behaviour -> Use case

### Support Ticket

Ticket#10142189

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Based on the initial report, this sounds like an enhancement to me... 🤔

**Comment by martini** [comment]
> Based on the initial report, this sounds like an enhancement to me... 🤔

It's a bug, because the feature can not get disabled and raises not expected side effects (in certain use cases).

**Comment by dominikklein** [comment]
For me I see also no broken behavior, only a use case which is currently not covered.

**Comment by MrGeneration** [comment]
The migration on an existing instance for this functionality fails on me:

```
$ rake db:migrate
== 20240802143314 AddSettingOptionForPostmasterFollowUpSearchIn: migrating ====
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

undefined method `push' for "references":String
/opt/zammad/db/migrate/20240802143314_add_setting_option_for_postmaster_follow_up_search_in.rb:27:in `change'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:905:in `exec_migration'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:889:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:888:in `block in migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:887:in `migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1095:in `migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1409:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/transactions.rb:209:in `transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1460:in `ddl_transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1408:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1382:in `each'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1382:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1331:in `block in migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1481:in `block in with_advisory_lock'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1496:in `with_advisory_lock_connection'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1477:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1331:in `migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1166:in `up'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1141:in `migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <main>'
/usr/local/rvm/gems/ruby-3.2.4/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-3.2.4/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.2.4/bin/ruby_executable_hooks:22:in `<main>'

Caused by:
NoMethodError: undefined method `push' for "references":String (NoMethodError)

    current.push('subject_references')
           ^^^^^
/opt/zammad/db/migrate/20240802143314_add_setting_option_for_postmaster_follow_up_search_in.rb:27:in `change'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:905:in `exec_migration'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:889:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:888:in `block in migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:887:in `migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1095:in `migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1409:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-7.0.8.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/transactions.rb:209:in `transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1460:in `ddl_transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1408:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1382:in `each'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1382:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1331:in `block in migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1481:in `block in with_advisory_lock'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1496:in `with_advisory_lock_connection'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1477:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1331:in `migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1166:in `up'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/migration.rb:1141:in `migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/usr/local/rvm/gems/ruby-3.2.4/gems/activerecord-7.0.8.4/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <main>'
/usr/local/rvm/gems/ruby-3.2.4/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-3.2.4/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.2.4/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

That's because the setting is not an Hash on my instance:

```
[1] pry(main)> Setting.get('postmaster_follow_up_search_in')
=> "references"
```

**Comment by martini** [comment]
Migration issue fixed.
