### ISSUE TITLE
Empty SMS are not allowed

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#5289]
### Used Zammad Version

6.3.1.b6ba68bf7.saas

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Incoming SMS with an empty body (or possibly just a "space") cannot be received due to Zammad requiring body content:

```
I, [2024-08-05T20:36:53.021629#12675-3219260]  INFO -- : Started POST "/api/v1/sms_webhook/XXXXX" for 127.0.0.1 at 2024-08-05 20:36:53 +0200
I, [2024-08-05T20:36:53.037896#12675-3219260]  INFO -- : Processing by ChannelsSmsController#webhook as */*
I, [2024-08-05T20:36:53.037971#12675-3219260]  INFO -- :   Parameters: {"ToCountry"=>"US", "MediaContentType0"=>"image/jpeg", "ToState"=>"", "SmsMessageSid"=>"XXXXXX", "NumMedia"=>"1", "ToCity"=>"", "FromZip"=>"XXXXX", "SmsSid"=>"XXXXX", "FromState"=>"TX", "SmsStatus"=>"received", "FromCity"=>"XXX XXX", "Body"=>"[FILTERED]", "FromCountry"=>"US", "To"=>"+18XXXXXX", "ToZip"=>"", "NumSegments"=>"1", "MessageSid"=>"XXXXXXX", "AccountSid"=>"XXXXXX", "From"=>"+13XXXXXXX", "MediaUrl0"=>"https://api.twilio.com/2010-04-01/Accounts/XXXXXX/Messages/XXXXXXX/Media/XXXXXX", "ApiVersion"=>"2010-04-01", "token"=>"XXXXXX"}
I, [2024-08-05T20:36:53.049010#12675-3219260]  INFO -- : Receiving SMS frim recipient +13XXXXXX
E, [2024-08-05T20:36:53.153793#12675-3219260] ERROR -- : Can't use Channel::Driver::Sms::Twilio: #<ActiveRecord::RecordInvalid: Validation failed: Need at least an 'article body' field.>
E, [2024-08-05T20:36:53.153838#12675-3219260] ERROR -- : Validation failed: Need at least an 'article body' field. (ActiveRecord::RecordInvalid)
app/models/channel/driver/sms/twilio.rb:78:in `create_article'
app/models/channel/driver/sms/base.rb:57:in `process_ticket'
app/models/channel/driver/sms/twilio.rb:50:in `process'
app/models/channel.rb:312:in `process'
app/controllers/channels_sms_controller.rb:73:in `block in webhook'
lib/application_handle_info.rb:34:in `in_context'
app/controllers/channels_sms_controller.rb:58:in `webhook'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2024-08-05T20:36:53.157283#12675-3219260] ERROR -- : Can't use Channel::Driver::Sms::Twilio: #<ActiveRecord::RecordInvalid: Validation failed: Need at least an 'article body' field.> (ActiveRecord::RecordInvalid)
```

### Expected behaviour

If Zammad received an SMS with empty message, the empty body will be replaced with e.g. `(no content)` to allow the creation of the SMS article.

### Steps to reproduce the behaviour

- set up twilio
- receive an SMS with empty content

### Support Ticket

Ticket#10159331

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment]
It's unclear what is the use-case with an empty text message, but supposedly this could be another message type (MMS?). In this case, a suitable error message should be shown, unless Zammad decides to implement support for such rich media messages.

**Comment by dvuckovic** [comment]
We decided to just fix the reported issue, so the article can be created (no fatal errors anymore).

But the support for additional message types should be considered an enhancement, and will be handled as a separate process. Stay tuned!
