### ISSUE TITLE
Migration is not working: 20241113154014 Issue5409WrongDbColumnArrayType: undefined method `type' for nil:NilClass

### ISSUE THREAD

**Issue by martini** [zammad/zammad#5430]
### Used Zammad Version

6.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Update within 6.4 release not possible. Migration is not processing:

```
$ rake db:migrate
== 20241113154014 Issue5409WrongDbColumnArrayType: migrating ==================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

undefined method `type' for nil:NilClass
/opt/zammad/db/migrate/20241113154014_issue5409_wrong_db_column_array_type.rb:57:in `block in migrate_object_attribute_columns'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/relation/delegation.rb:100:in `each'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/relation/delegation.rb:100:in `each'
/opt/zammad/db/migrate/20241113154014_issue5409_wrong_db_column_array_type.rb:52:in `migrate_object_attribute_columns'
/opt/zammad/db/migrate/20241113154014_issue5409_wrong_db_column_array_type.rb:44:in `migrate_object_attribute_multiselect_columns'
/opt/zammad/db/migrate/20241113154014_issue5409_wrong_db_column_array_type.rb:13:in `change'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:986:in `exec_migration'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:970:in `block (2 levels) in migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:969:in `block in migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:227:in `with_connection'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:968:in `migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1178:in `migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1529:in `block in execute_migration_in_transaction'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/opt/zammad/.../ruby-3.2.4/gems/activesupport-7.1.4.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1580:in `ddl_transaction'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1528:in `execute_migration_in_transaction'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1503:in `each'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1503:in `migrate_without_lock'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1448:in `block in migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1600:in `with_advisory_lock'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1448:in `migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1274:in `up'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1249:in `migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/tasks/database_tasks.rb:251:in `migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/railties/databases.rake:93:in `block (2 levels) in <main>'
/opt/zammad/.../ruby-3.2.4/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/zammad/.../ruby-3.2.4/bin/ruby_executable_hooks:22:in `eval'
/opt/zammad/.../ruby-3.2.4/bin/ruby_executable_hooks:22:in `<main>'

Caused by:
NoMethodError: undefined method `type' for nil:NilClass (NoMethodError)

      next if table_column.type == :string
                          ^^^^^
/opt/zammad/db/migrate/20241113154014_issue5409_wrong_db_column_array_type.rb:57:in `block in migrate_object_attribute_columns'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/relation/delegation.rb:100:in `each'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/relation/delegation.rb:100:in `each'
/opt/zammad/db/migrate/20241113154014_issue5409_wrong_db_column_array_type.rb:52:in `migrate_object_attribute_columns'
/opt/zammad/db/migrate/20241113154014_issue5409_wrong_db_column_array_type.rb:44:in `migrate_object_attribute_multiselect_columns'
/opt/zammad/db/migrate/20241113154014_issue5409_wrong_db_column_array_type.rb:13:in `change'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:986:in `exec_migration'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:970:in `block (2 levels) in migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:969:in `block in migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:227:in `with_connection'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:968:in `migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1178:in `migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1529:in `block in execute_migration_in_transaction'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/opt/zammad/.../ruby-3.2.4/gems/activesupport-7.1.4.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1580:in `ddl_transaction'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1528:in `execute_migration_in_transaction'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1503:in `each'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1503:in `migrate_without_lock'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1448:in `block in migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1600:in `with_advisory_lock'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1448:in `migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1274:in `up'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1249:in `migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/tasks/database_tasks.rb:251:in `migrate'
/opt/zammad/.../ruby-3.2.4/gems/activerecord-7.1.4.1/lib/active_record/railties/databases.rake:93:in `block (2 levels) in <main>'
/opt/zammad/.../ruby-3.2.4/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/zammad/.../ruby-3.2.4/bin/ruby_executable_hooks:22:in `eval'
/opt/zammad/.../ruby-3.2.4/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
$ 
```

### Expected behaviour

Update should go through without any problems.

### Steps to reproduce the behaviour

* create field e. g. `custom_product` but do not execute changes in admin interface/database

e.g.:
```
#<ObjectManager::Attribute id: 105, object_lookup_id: 2, name: "custom_product", display: "PRODUCT", data_type: "multiselect", data_option: {"options"=>{"aaa"=>"AAA", "bbb"=>"BBB"}, "default"=>["aaa"], "linktemplate"=>"", "translate"=>false, "null"=>true, "relation"=>"", "nulloption"=>true, "maxlength"=>255, "multiple"=>true}, data_option_new: {}, editable: true, active: false, screens: {"create_middle"=>{"ticket.agent"=>{"shown"=>true, "required"=>true, "item_class"=>"column"}, "ticket.customer"=>{"shown"=>false, "required"=>false, "item_class"=>"column"}}, "edit"=>{"ticket.agent"=>{"shown"=>true, "required"=>true}, "ticket.customer"=>{"shown"=>false, "required"=>false}}}, to_create: true, to_migrate: true, to_delete: false, to_config: false, position: 25, created_by_id: 116, updated_by_id: 116, created_at: "2024-11-21 08:28:38.658000000 +0000", updated_at: "2024-11-21 08:28:38.658000000 +0000">
```

* upgrade to Zammad version where `db/migrate/20241113154014_issue5409_wrong_db_column_array_type.rb` is new
* execute `rake db:migrate`

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment]
Regression of #5409
