### ISSUE TITLE
Admin user login via Oauth

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [zammad/zammad#602]
### Infos:

* Used Zammad version: Latest `zammad/zammad-docker-compose:zammad` docker image
* Operating system: Rancher on Ubuntu 16.04
* Browser + version: Chrome 55.0.2883.87

### Expected behavior:

* Admin user sign in via Google Oauth can operate

### Actual behavior:

* `422: The change you wanted was rejected.` error after login.

### Steps to reproduce the behavior:

* User Sign up via Google Oauth.
* Change user permissions to Admin and Agent
* User receives the 422 error.
Or
* User links the Google account in Profile
* Login via Google
* 422 error

**Comment by Ilya-Kuchaev** [comment]
Here is the peace of production.log
```
I, [2017-01-10T18:52:39.870635 #19]  INFO -- : Started GET "/" for <IP address> at 2017-01-10 18:52:39 +0000
I, [2017-01-10T18:52:39.872390 #19]  INFO -- : Processing by InitController#index as HTML
E, [2017-01-10T18:52:39.876840 #19] ERROR -- : Need fingerprint param!
E, [2017-01-10T18:52:39.877104 #19] ERROR -- : ["/home/zammad/app/controllers/application_controller.rb:211:in `user_device_log'", "/home/zammad/app/controllers/application_controller.rb:173:in `user_device_check'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in `block in halting'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'", "/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'", "/usr/local/bundle/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'", "/usr/local/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'", "/usr/local/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'", "/usr/local/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'", "/usr/local/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'", "/usr/local/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'", "/usr/local/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'", "/usr/local/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'", "/usr/local/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'", "/usr/local/bundle/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'", "/usr/local/bundle/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'", "/usr/local/bundle/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'", "/usr/local/bundle/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'", "/usr/local/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'", "/usr/local/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'", "/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'", "/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'", "/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'", "/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'", "/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'", "/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'", "/usr/local/bundle/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'", "/usr/local/bundle/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'", "/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'", "/usr/local/bundle/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'", "/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'", "/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'", "/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'", "/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'", "/usr/local/bundle/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'", "/usr/local/bundle/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'", "/usr/local/bundle/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'", "/usr/local/bundle/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'", "/usr/local/bundle/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'"]
I, [2017-01-10T18:52:39.877906 #19]  INFO -- :   Rendered inline template (0.4ms)
I, [2017-01-10T18:52:39.878032 #19]  INFO -- : Completed 422 Unprocessable Entity in 6ms (Views: 0.7ms | ActiveRecord: 1.0ms)
```

**Comment by martini** [comment]
Thanks for very good description. Was able to reproduce it.

**Comment by martini** [comment]
@Ilya-Kuchaev It's fixed in develop branch now. I'll improve the ui now...

**Comment by martini** [comment]
JFI: UI improvement will be done in other issue.
