### ISSUE TITLE
Unable to run rake assets:precompile (To modify a file)

### ISSUE THREAD

**Issue by madd86** [zammad/zammad#716]
Trying to modify login.jst.eco

This is the error message when I run `rake assets:precompile` on /opt/zammad folder:

```
root@zammad:/opt/zammad# rake assets:precompile
rake aborted!
NameError: uninitialized constant Rack::LiveReload
/opt/zammad/config/environments/development.rb:37:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `instance_eval'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `configure'
/opt/zammad/config/environments/development.rb:1:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/opt/zammad/config/environment.rb:5:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)
root@zammad:/opt/zammad#
```

**Comment by martini** [comment]
What is your RAILS_ENV?

```
shell> echo $RAILS_ENV
```

Try it this way:

```
shell> export RAILS_ENV=production
shell> rake assets:precompile
```

**Comment by martini** [comment]
PS: Marked as question, it's no Zammad/Rails issue. It's a setup issue.

**Comment by madd86** [comment]
By doing that I get:

```
root@zammad:/opt/zammad# rake assets:precompile
rake aborted!
PG::ConnectionBad: FATAL:  Peer authentication failed for user "zammad"

```

**Comment by madd86** [comment]
PS. I setup using apt-get on ubuntu, exactly as described.

**Comment by martini** [comment]
> PS. I setup using apt-get on ubuntu, exactly as described.

I'm on centos, so I need to install ubuntu first to help you out.

Anyway, if you install Zammad via the packages, you should execute it as Zammad user, not as root(!).

What it you enter:

`zammad run rake assets:precompile `

**Comment by madd86** [comment]
You're right, wasn't aware of that. I'm completely new to ruby (the structure looks a bit like laravel)..

By running the rommand with zammad run I got:

```
root@zammad:/opt/zammad# zammad run rake assets:precompile
I, [2017-02-02T13:35:59.191139 #4709]  INFO -- : Writing /opt/zammad/public/assets/application-print-db172409c8422225ac73dfd79ca9fe0994704e3813ebdd759e19cc0e3b0eff6a.css
I, [2017-02-02T13:35:59.191615 #4709]  INFO -- : Writing /opt/zammad/public/assets/application-print-db172409c8422225ac73dfd79ca9fe0994704e3813ebdd759e19cc0e3b0eff6a.css.gz
I, [2017-02-02T13:35:59.192812 #4709]  INFO -- : Writing /opt/zammad/public/assets/print-57d400c28213ca8fb1fc899cd1f3cd91ec5073d4947e60b0b37f2dc2c9937140.css
I, [2017-02-02T13:35:59.192990 #4709]  INFO -- : Writing /opt/zammad/public/assets/print-57d400c28213ca8fb1fc899cd1f3cd91ec5073d4947e60b0b37f2dc2c9937140.css.gz
I, [2017-02-02T13:38:34.958430 #4709]  INFO -- : Writing /opt/zammad/public/assets/application-2956725072f30ede2019e79434864f8f8a7578a282ce971157ceafd72caf34c1.js
I, [2017-02-02T13:38:34.959893 #4709]  INFO -- : Writing /opt/zammad/public/assets/application-2956725072f30ede2019e79434864f8f8a7578a282ce971157ceafd72caf34c1.js.gz
I, [2017-02-02T13:38:37.740639 #4709]  INFO -- : Writing /opt/zammad/public/assets/application-7a377d84e901cbbc2316ae6e3aec3e5ef86019623be00bb8c52e073046c6bff7.css
I, [2017-02-02T13:38:37.741109 #4709]  INFO -- : Writing /opt/zammad/public/assets/application-7a377d84e901cbbc2316ae6e3aec3e5ef86019623be00bb8c52e073046c6bff7.css.gz
I, [2017-02-02T13:38:37.951181 #4709]  INFO -- : Writing /opt/zammad/public/assets/doorkeeper/admin/application-f4a06ae62dea85a8dc643adfe77c180557fce949a63bd48ac83d105b0b4079ba.css
I, [2017-02-02T13:38:37.951620 #4709]  INFO -- : Writing /opt/zammad/public/assets/doorkeeper/admin/application-f4a06ae62dea85a8dc643adfe77c180557fce949a63bd48ac83d105b0b4079ba.css.gz
I, [2017-02-02T13:38:37.986879 #4709]  INFO -- : Writing /opt/zammad/public/assets/doorkeeper/application-2bdd8c8beea5b11d4fa32d0152ce69416773f53459d07d7b0f7d5363bd0f3123.css
I, [2017-02-02T13:38:37.987093 #4709]  INFO -- : Writing /opt/zammad/public/assets/doorkeeper/application-2bdd8c8beea5b11d4fa32d0152ce69416773f53459d07d7b0f7d5363bd0f3123.css.gz

```

I guess it worked but my modifications didn't show up?

**Comment by madd86** [comment]
It did after I stopped zammad & apache & restarted

**Comment by martini** [comment]
> I guess it worked but my modifications didn't show up?

Did you restart the rails application server after recompiling?

`sudo systemctl restart zammad`

**Comment by martini** [comment]
You are faster :-D Now it only can be a caching issue in browser or you created a backup file of login.jst.eco - no other ideas anymore.

**Comment by madd86** [comment]
Thanks man, loving Zammad. You can close this issue I guess.

**Comment by martini** [comment]
@madd86 Where are your from?

**Comment by madd86** [comment]
Brazil, working in UK, assuming you're german?

**Comment by martini** [comment]
Just asking to have some 🍺
