### ISSUE TITLE
Unprocessable emails

### ISSUE THREAD

**Issue by raphaelm** [zammad/zammad#795]
Hi,

I regularly find unprocessable emails in the log. Up to now, all of them were spam so I did not actually want to get them, but having them unprocessable is still annoying becuase they make the healthcheck go bad and the monitoring will ping me ;)

At first, most of the mails hat invalid ``To`` or ``From`` headers, e.g. ``From: Name`` without an address. All of them were spam, but I'm not sure if there are valid mails like this, think for example ``To: undisclosed-recipients;`` for a Bcc-only mail in many clients.

I now block those emails in the SMTP server. Today, however, I got a number of unprocessable emails where the reason is unclear to me, broken Unicode maybe?

The log:
```
E, [2017-02-20T00:57:29.531396 #4678] ERROR -- : can't run postmaster pre filter Channel::Filter::IdentifySender
E, [2017-02-20T00:57:29.531508 #4678] ERROR -- : #<Exceptions::UnprocessableEntity: Attribute 'login' required!>
E, [2017-02-20T00:57:29.532180 #4678] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//d9ea6abf7574f2400e6dc8a50ab35bd7.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2017-02-20T00:57:29.532218 #4678] ERROR -- : ERROR: #<Exceptions::UnprocessableEntity: Attribute 'login' required!>
E, [2017-02-20T00:57:29.532339 #4678] ERROR -- : ERROR: ["/opt/zammad/app/models/user.rb:840:in `check_login'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in `block in halting'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.7.1/lib/active_model/validations/callbacks.rb:113:in `run_validations!'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.7.1/lib/active_model/validations.rb:338:in `valid?'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:58:in `valid?'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:83:in `perform_validations'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:37:in `save'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block (2 levels) in save'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block in save'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:285:in `save'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:34:in `create'", "/opt/zammad/app/models/channel/filter/identify_sender.rb:163:in `user_create'", "/opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'", "/opt/zammad/app/models/channel/email_parser.rb:424:in `block in _process'", "/opt/zammad/app/models/channel/email_parser.rb:421:in `each'", "/opt/zammad/app/models/channel/email_parser.rb:421:in `_process'", "/opt/zammad/app/models/channel/email_parser.rb:389:in `process'", "/opt/zammad/app/models/channel/driver/imap.rb:194:in `block in fetch'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `each'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `fetch'", "/opt/zammad/app/models/channel.rb:62:in `fetch'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/app/models/channel.rb:30:in `fetch'", "(eval):1:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:90:in `eval'", "/opt/zammad/app/models/scheduler.rb:90:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:57:in `block (2 levels) in start_job'", "/opt/zammad/app/models/scheduler.rb:56:in `loop'", "/opt/zammad/app/models/scheduler.rb:56:in `block in start_job'"]
```

The email:
```
root@hedwig:~# cat /opt/zammad/tmp/unprocessable_mail//d9ea6abf7574f2400e6dc8a50ab35bd7.eml
Received: from localhost by hedwig.rami.io
	with SpamAssassin (version 3.4.0);
	Mon, 20 Feb 2017 00:57:23 +0100
From: "��̩����" <hubvdys9747@xgeneration.net>
To: <info@opacapp.de>
Subject: 2017�Ͷ���ͬ�ù��������������ɷ��շ���
Date: Mon, 20 Feb 2017 07:57:18 +0800
Message-Id: <SAK20170220$7841D106.$0948B123@xgeneration.net>
X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on hedwig.rami.io
X-Spam-Flag: YES
X-Spam-Level: ************
X-Spam-Status: Yes, score=12.2 required=5.0 tests=BODY_SINGLE_URI,
	HELO_DYNAMIC_IPADDR,HTML_MESSAGE,MIME_HTML_MOSTLY,MPART_ALT_DIFF,
	RCVD_IN_BRBL_LASTEXT,RCVD_IN_PBL,RCVD_IN_XBL,RDNS_NONE,SPF_SOFTFAIL,
	SUBJECT_NEEDS_ENCODING,SUBJ_ILLEGAL_CHARS,URIBL_BLOCKED autolearn=no
	autolearn_force=no version=3.4.0
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----------=_58AA30E3.A9A09FC9"

This is a multi-part message in MIME format.

------------=_58AA30E3.A9A09FC9
Content-Type: text/plain; charset=iso-8859-1
Content-Disposition: inline
Content-Transfer-Encoding: 8bit

Software zur Erkennung von "Spam" auf dem Rechner

    hedwig.rami.io

hat die eingegangene E-mail als m�gliche "Spam"-Nachricht identifiziert.
Die urspr�ngliche Nachricht wurde an diesen Bericht angeh�ngt, so dass
Sie sie anschauen k�nnen (falls es doch eine legitime E-Mail ist) oder
�hnliche unerw�nschte Nachrichten in Zukunft markieren k�nnen.
Bei Fragen zu diesem Vorgang wenden Sie sich bitte an

    the administrator of that system

Vorschau: info@opacapp.de�����ã� [...] 

Inhaltsanalyse im Detail:   (12.2 Punkte, 5.0 ben�tigt)

Pkte Regelname              Beschreibung
---- ---------------------- --------------------------------------------------
 0.0 URIBL_BLOCKED          ADMINISTRATOR NOTICE: The query to URIBL was blocked.
                            See
                            http://wiki.apache.org/spamassassin/DnsBlocklists#dnsbl-block
                             for more information.
                            [URIs: opacapp.de]
 0.7 RCVD_IN_XBL            RBL: Transportiert via Rechner in XBL-Liste
                            (http://www.spamhaus.org/xbl/)
                            [116.207.5.167 listed in zen.spamhaus.org]
 1.0 RCVD_IN_PBL            RBL: Received via a relay in Spamhaus PBL
 1.6 RCVD_IN_BRBL_LASTEXT   RBL: No description available.
                            [116.207.5.167 listed in bb.barracudacentral.org]
 1.0 SPF_SOFTFAIL           Senderechner entspricht nicht SPF-Datensatz (softfail)
 0.0 MIME_HTML_MOSTLY       BODY: Mehrteilige MIME-Nachricht �berwiegend in HTML
 0.0 HTML_MESSAGE           BODY: Nachricht enth�lt HTML
 0.7 MPART_ALT_DIFF         BODY: Nachrichtentext im Text- und HTML-Format
                            unterscheiden sich
 1.6 RDNS_NONE              Delivered to internal network by a host with no rDNS
 1.1 SUBJ_ILLEGAL_CHARS     Betreff enth�lt zu viele ung�ltige Zeichen
 0.1 SUBJECT_NEEDS_ENCODING Subject is encoded but does not specify the
                            encoding
 3.2 HELO_DYNAMIC_IPADDR    HELO-Rechnername verd�chtig (IP-Adresse 1)
 1.1 BODY_SINGLE_URI        Message body is only a URI

Die urspr�ngliche Nachricht enthielt nicht ausschlie�lich Klartext
(plain text) und kann eventuell eine Gefahr f�r einige E-Mail-Programme
darstellen (falls sie z.B. einen Computervirus enth�lt).
M�chten Sie die Nachricht dennoch ansehen, ist es wahrscheinlich
sicherer, sie zuerst in einer Datei zu speichern und diese Datei danach
mit einem Texteditor zu �ffnen.


------------=_58AA30E3.A9A09FC9
Content-Type: message/rfc822; x-spam-type=original
Content-Description: original message before SpamAssassin
Content-Disposition: attachment
Content-Transfer-Encoding: 8bit

Return-Path: <hubvdys9747@xgeneration.net>
Delivered-To: info@opacapp.de
Received: from E3C9C040C60E4E4.yinksoft.com (unknown [116.207.5.167])
	by mail.rami.io (Postfix) with SMTP id 963EA6E221
	for <info@opacapp.de>; Mon, 20 Feb 2017 00:57:18 +0100 (CET)
Date: Mon, 20 Feb 2017 07:57:18 +0800
Subject: 2017�Ͷ���ͬ�ù��������������ɷ��շ���
From: "��̩����" <hubvdys9747@xgeneration.net>
Reply-To: "��̩����" <hubvdys9747@xgeneration.net>
To: <info@opacapp.de>
Message-ID: <SAK20170220$7841D106.$0948B123@xgeneration.net>
Content-Type: multipart/alternative;
	boundary="----=_SAKbound_07_5718_20170220_4EDDC3B1.10CC9A7A"
Content-Transfer-Encoding: quoted-printable
X-Priority: 3
Author: yinksoft

---- Original mail message -----
������:������<hubvdys9747@xgeneration.net>
�ռ���:<info@opacapp.de>
����ʱ��:1992-09-15 

MIME-Version: 1.0

This is a multi-part message in MIME format.

------=_SAKbound_07_5718_20170220_4EDDC3B1.10CC9A7A
Content-Type: text/plain;
	charset="gb2312"
Content-Transfer-Encoding: quoted-printable


------=_SAKbound_07_5718_20170220_4EDDC3B1.10CC9A7A
Content-Type: text/html;
	charset="gb2312"
Content-Transfer-Encoding: quoted-printable


<BODY><P>info@opacapp.de=A3=BA=C4=FA=BA=C3=A3=A1</P>
<P>&nbsp;</P><FONT style=3D"DISPLAY: none" color=3D#000050 size=3D=BF=AA=
=CD=D8=D0=C2=B3=CC=D4=C6=C5=F4=D5=B9=B3=E1=A3=BB=D5=F1=D0=CB=BB=AA=CF=C4=
=CC=EC=E6=F7=B3=D2=B2=C5=A1=A3></FONT><INPUT id=3D=A1=B0And you, boy?=A1=
=B1border=3D0 align=3Dbaseline src=3D"https://img.alicdn.com/imgextra/i=
3/521413897/TB2ih7cfbBmpuFjSZFuXXaG_XXa_!!521413897.png" type=3Dimage> =
</BODY>


------=_SAKbound_07_5718_20170220_4EDDC3B1.10CC9A7A--



------------=_58AA30E3.A9A09FC9--
```

**Comment by maege** [comment]
We have actual the same Problem, but with customer mails not spam.

[2017-03-13T16:05:42.742612 #17021] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//4741acd1fb91260ca7c971a1bd8af874.eml

[2017-03-13T12:02:59.382414 #17021] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//84d4f19568002358200a518c38ba2f55.eml

[2017-03-13T16:05:42.742612 #17021] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//4741acd1fb91260ca7c971a1bd8af874.eml

If needed i can send the complete .eml Files in a private message.

Thank you

**Comment by martini** [comment]
@raphaelm I tried to reproduce it with your pasted mail. It seems that it's really a charset issue, but I can't reproduce it with the c&p message above.

@raphaelm @maege I would be happy the get the complete .eml files somewhere for download or just send it with the issue #795 to support at zammad dot com. Thanks!

**Comment by raphaelm** [comment]
I haven't kept this one but I get the error message once every 3-4 days. I'll send you the next one :)

**Comment by martini** [comment]
@raphaelm thank for the example. The problem is, that the mails has wrong mail header encoding.

We will improve the email parsing to handle this.

**Comment by martini** [comment]
Thanks for the problem email. This kind of emails can now be handled by Zammad. :)

**Comment by kilakewe** [comment]
I have more of these :(

**Comment by raphaelm** [comment]
Same here, but only spam mails.

```
I, [2017-08-23T13:30:31.269666 #27655]  INFO -- :  - message 3/3
E, [2017-08-23T13:30:31.422204 #27655] ERROR -- : ERROR: SenderIsSystemAddress: #<NoMethodError: undefined method `addrs' for #<Mail::UnstructuredField:0x007f2f80020790>>
E, [2017-08-23T13:30:31.444774 #27655] ERROR -- : can't run postmaster pre filter Channel::Filter::IdentifySender
E, [2017-08-23T13:30:31.444875 #27655] ERROR -- : #<Exceptions::UnprocessableEntity: Invalid email>
E, [2017-08-23T13:30:31.446659 #27655] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//7530d5b9c38e480848d3c437f497f2e8.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2017-08-23T13:30:31.446746 #27655] ERROR -- : Invalid email (Exceptions::UnprocessableEntity)
/opt/zammad/app/models/user.rb:845:in `check_email'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in `block in halting'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.7.1/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.7.1/lib/active_model/validations.rb:338:in `valid?'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:58:in `valid?'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:83:in `perform_validations'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:37:in `save'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block in save'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:285:in `save'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:34:in `create'
/opt/zammad/app/models/channel/filter/identify_sender.rb:167:in `user_create'
/opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'
/opt/zammad/app/models/channel/email_parser.rb:452:in `block in _process'
/opt/zammad/app/models/channel/email_parser.rb:449:in `each'
/opt/zammad/app/models/channel/email_parser.rb:449:in `_process'
/opt/zammad/app/models/channel/email_parser.rb:418:in `process'
/opt/zammad/app/models/channel/driver/imap.rb:188:in `block in fetch'
/opt/zammad/app/models/channel/driver/imap.rb:168:in `each'
/opt/zammad/app/models/channel/driver/imap.rb:168:in `fetch'
/opt/zammad/app/models/channel.rb:62:in `fetch'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:176:in `eval'
/opt/zammad/app/models/scheduler.rb:176:in `_start_job'
/opt/zammad/app/models/scheduler.rb:143:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:142:in `loop'
/opt/zammad/app/models/scheduler.rb:142:in `block in start_job'
I, [2017-08-23T13:30:31.530992 #27655]  INFO -- : done
```

I think it is due to a space in the mail address:
```
From: "Lottery-Dominator CB" <Lottery_Dominator CB@sfetx.us>
```

**Comment by martini** [comment]
> I think it is due to a space in the mail address:

Wow. Yes. This is here the reason. Sometimes I can't believe what issues (invalid options) spam emails have. :-o

But one more question @raphaelm and @kilakewe you both use postgresql?

**Comment by raphaelm** [comment]
@martini Well, actually… deciding whether an email adddress is just hard: https://en.wikipedia.org/wiki/Email_address#Local-part

And no, I apparently use MariaDB

**Comment by martini** [comment]
@raphaelm how many unprocessable emails do you have in one week?

**Comment by raphaelm** [comment]
@martini Around 2-5, so not that much, but it's annoying because my monitoring fires every time ;)

**Comment by martini** [comment]
> but it's annoying because my monitoring fires every time ;)

I can under stand this. If you want, just send me 4 weeks all unprocessable emails (without comments) and we will improved it.

**Comment by raphaelm** [comment]
> I can under stand this. If you want, just send me 4 weeks all unprocessable emails (without comments) and we will improved it.

That's nice of you <3 As far as I can see it right now (I deleted most of them) its either:

* Spaces etc. in the ``From`` address
* No ``From`` header at all (I block these on postfix level now)

**Comment by Kocooour** [comment]
Hi, 
I also got this message in Zammad monitoring, but the effect is that no e-mail gets processed at all.

How do I solve this? Do I need to delete all e-mails from IMAP and restart the server or do I need to delete some cached data somewhere?

BTW, I have 2.4.0 version installed...

**Comment by thorsteneckel** [comment]
Hi @Kocooour - please ask technical questions over at our [community board](http://community.zammad.org/)
