### ISSUE TITLE
Unprocessable Email (without email address in from header)

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#811]
### Infos:

* Used Zammad version: 1.3.x (deb)
* Operating system: ubuntu:16.04

### Expected behavior:

* should process email

### Actual behavior:

Log:

```
- message 1/1 
can't run postmaster pre filter Channel::Filter::IdentifySender 
#<Exceptions::UnprocessableEntity: Invalid email> 
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//7d4fc3539166445679c5cf0eec9ea0f6.eml, please create an issue at https://github.com/zammad/zammad/issues" 
"ERROR: #<Exceptions::UnprocessableEntity: Invalid email>" 
ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//7d4fc3539166445679c5cf0eec9ea0f6.eml, please create an issue at https://github.com/zammad/zammad/issues 
ERROR: #<Exceptions::UnprocessableEntity: Invalid email> 
ERROR: ["/opt/zammad/app/models/user.rb:820:in `check_email'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in `block in halting'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.7.1/lib/active_model/validations/callbacks.rb:113:in `run_validations!'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activemodel-4.2.7.1/lib/active_model/validations.rb:338:in `valid?'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:58:in `valid?'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:83:in `perform_validations'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:37:in `save'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block (2 levels) in save'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block in save'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:285:in `save'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:34:in `create'", "/opt/zammad/app/models/channel/filter/identify_sender.rb:163:in `user_create'", "/opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'", "/opt/zammad/app/models/channel/email_parser.rb:430:in `block in _process'", "/opt/zammad/app/models/channel/email_parser.rb:427:in `each'", "/opt/zammad/app/models/channel/email_parser.rb:427:in `_process'", "/opt/zammad/app/models/channel/email_parser.rb:395:in `process'", "/opt/zammad/app/models/channel/driver/imap.rb:194:in `block in fetch'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `each'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `fetch'", "/opt/zammad/app/models/channel.rb:62:in `fetch'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/app/models/channel.rb:30:in `fetch'", "(eval):1:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:90:in `eval'", "/opt/zammad/app/models/scheduler.rb:90:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:57:in `block (2 levels) in start_job'", "/opt/zammad/app/models/scheduler.rb:56:in `loop'", "/opt/zammad/app/models/scheduler.rb:56:in `block in start_job'"] 

```

Email (private information XXX'ed, can provide original file if required):
```
cat /opt/zammad/tmp/unprocessable_mail/7d4fc3539166445679c5cf0eec9ea0f6.eml
Delivered-To: feedback_en@XXX.com
Return-Path: <>
Delivered-To: feedback_en@XXX.com
Received: from director15.mail.dfw1a.XXX.net ([172.20.1.228])
        by store512a.mail.iad3a.XXX.net (Dovecot) with LMTP id ZXf9G3t1tFhAbgAA7aV/mQ
        for <feedback_en@XXX.com>; Mon, 27 Feb 2017 13:52:43 -0500
Received: from smtp20.gate.dfw1a ([172.20.100.20])
        (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
        by director15.mail.dfw1a.XXX.net (Dovecot) with LMTP id wnMQKQhztFggHQAAREf9Rg
        ; Mon, 27 Feb 2017 13:52:43 -0500
Return-Path: <>
X-Spam-Threshold: 95
X-Spam-Score: 0
X-Spam-Flag: NO
X-Virus-Scanned: OK
X-MessageSniffer-Scan-Result: 0
X-MessageSniffer-Rules: 0-0-0-7364-c
X-CMAE-Scan-Result: 0
X-CNFS-Analysis: v=2.2 cv=IuBcS/3g c=1 sm=1 tr=0 a=scmLJpidNJD1CDJrwSPlCg==:117 a=KiCxJD0x+Pe5VASQKmYoJrcyuOo=:19 a=HpWyMqnf4hoA:10 a=HFcG5fkciocA:10 a=n2v9WMKugxEA:10 a=ZZnuYtJkoWoA:10 a=vX-N2HuyvEP-EhXdXtwA:9 a=GF4HiIEFAAAA:8 a=l1aLL7fvAAAA:8 a=m9wmmNRzG3RnX796Uw4A:9 a=CjuIK1q_8ugA:10 a=fSRcLqLQAAAA:8 a=n3WKkpLOXN7oL6whe2YA:9 a=oWI6YT3fg6wA:10 a=JGRhF4uQAAAA:8 a=YoI8Y-owAAAA:8 a=xW0offs3AAAA:8 a=cuXalqQTuEIKHF7dZIwA:9 a=hHE8zlonNCKEIyoE4Yab:22 a=NPV240f7YeaO3CCHy0GZ:22 a=6Ojsp-TqxlhusgkSIWu7:22 a=kcHpxALSlUaRulRdPvIa:22 a=-zJbGfyDzD99htaT2oAx:22 a=_3VCzNpgjGu_f5hyB7JW:22
X-Orig-To: feedback@XXX.com
X-Originating-Ip: [XX.XXX.XXX.XXX]
Authentication-Results: smtp20.gate.dfw1a.XXX.net; iprev=pass policy.iprev="XX.XXX.XXX.XXX"; spf=neutral smtp.mailfrom="" smtp.helo="smtp136.dfw.XXX.com"; dkim=none (message not signed) header.d=none
X-Classification-ID: ebb2f874-fd1d-11e6-968d-001ec95b9664-1-1
Received: from [XX.XXX.XXX.XXX] ([XX.XXX.XXX.XXX:58318] helo=smtp136.dfw.XXX.com)
        by smtp20.gate.dfw1a.XXX.net (envelope-from <>)
        (ecelerity 4.2.1.56364 r(Core:4.2.1.14)) with ESMTPS (cipher=DHE-RSA-AES256-GCM-SHA384)
        id 50/40-17519-B7574B85; Mon, 27 Feb 2017 13:52:43 -0500
Received: by smtp30.relay.dfw1a.XXX.com (SMTP Server)
        id 23593E043D; Mon, 27 Feb 2017 13:52:43 -0500 (EST)
Date: Mon, 27 Feb 2017 13:52:43 -0500 (EST)
From: MAILER-DAEMON (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: feedback@XXX.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
        boundary="342ADE03AD.1488221563/smtp30.relay.dfw1a.XXX.com"
Message-Id: <20170227185243.23593E043D@smtp30.relay.dfw1a.XXX.com>

This is a MIME-encapsulated message.

--342ADE03AD.1488221563/smtp30.relay.dfw1a.XXX.com
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host smtp30.relay.dfw1a.XXX.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john_XXX@XXX.com>: connect to XXX.com[XX.XXX.XXX.XXX]:25: Connection timed
    out

--342ADE03AD.1488221563/smtp30.relay.dfw1a.XXX.com
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; smtp30.relay.dfw1a.XXX.com
X-SMTP-Server-Queue-ID: 342ADE03AD
X-SMTP-Server-Sender: rfc822; feedback@XXX.com
Arrival-Date: Mon, 27 Feb 2017 05:35:21 -0500 (EST)

Final-Recipient: rfc822; john_XXX@XXX.com
Original-Recipient: rfc822;john_XXX@XXX.com
Action: failed
Status: 4.4.1
Diagnostic-Code: X-SMTP-Server; connect to XXX.com[XX.XXX.XXX.XXX]:25:
    Connection timed out

--342ADE03AD.1488221563/smtp30.relay.dfw1a.XXX.com
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers

Return-Path: <feedback@XXX.com>
Received: from smtp30.relay.dfw1a.XXX.com (localhost [127.0.0.1])
        by smtp30.relay.dfw1a.XXX.com (SMTP Server) with ESMTP id 342ADE03AD
        for <john_XXX@XXX.com>; Mon, 27 Feb 2017 05:35:21 -0500 (EST)
X-Auth-ID: feedback_en@XXX.com
Received: by smtp30.relay.dfw1a.XXX.com (Authenticated sender: feedback_en-AT-XXX.com) with ESMTPSA id BC4C5E016E
        for <john_XXX@XXX.com>; Mon, 27 Feb 2017 05:35:20 -0500 (EST)
X-Sender-Id: feedback_en@XXX.com
Received: from help.XXX.com (XXX.node.dockerapp.io [XXX.XXX.XXX.XXX])
        (using TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384)
        by 0.0.0.0:25 (trex/5.7.12);
        Mon, 27 Feb 2017 05:35:21 -0500
Date: Mon, 27 Feb 2017 10:35:19 +0000
From: Oliver Grahl | Support <feedback@XXX.com>
To: John Stewart <john_XXX@XXX.com>
Message-ID: <20170227103514.188.920664@help.XXX.com>
In-Reply-To: <92a8950479d35e18cb39263e9a35de3b@www.XXX.com>
References: <92a8950479d35e18cb39263e9a35de3b@www.XXX.com>
 <92a8950479d35e18cb39263e9a35de3b@www.XXX.com>
Subject: RE: Feedback after Uninstallation [Ticket#62188]
Mime-Version: 1.0
Content-Type: multipart/mixed;
 boundary="--==_mimepart_58b400e72487d_32c43ffa32ed5c3010848";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Organization: XXX
X-Powered-By: Zammad - Helpdesk/Support (https://zammad.org/)
X-Mailer: Zammad Mail Service

--342ADE03AD.1488221563/smtp30.relay.dfw1a.XXX.com--

```

I understand that this one failed because the sender's SMTP server does not reply. But should this really result in an error condition / unprocessable email?

**Comment by martini** [comment]
Hi @olivergrahl 

the problem is the following line:

From: MAILER-DAEMON (Mail Delivery System)

Zammad can not find the sender email, because there is no sender email. :-/

Just thinking about to handle this. Any ideas are welcome.

 -Martin

**Comment by dnauck** [comment]
Maybe: Display an info that the mail returned including the error message (or just a button to open the original MAILER-DAEMON mail) in the ticket with a warning icon.

**Comment by olivergrahl** [comment]
Currently, unprocessable emails can get overseen when no monitoring has been set up. 

Also, currently only Admins can review unprocessable emails, and their intervention is required to remove unprocessable emails.

My understanding is that there will always be a chance for unprocessable emails. No admin intervention should be required to review/remove them. 

Maybe Zammad could create some kind of dummy ticket for those cases, where the raw email content gets stored together with a notice including the error message raised when trying to parse the email. That way, even agents could possibly review those messages. In above example, this would probably require dealing with required fields, like sender email, by either setting them to some dummy or internal values.

But my main point is that unprocessable email should not require Admin intervention.

**Comment by martini** [comment]
It's fix in stable now (Zammad now process the emails without valid sender address too). Thanks for your help/support! ❤️
