### ISSUE TITLE
libv8 doesn't install on FreeBSD 11

### ISSUE THREAD

**Issue by ntinti** [zammad/zammad#827]
```
5 warnings and 3 errors generated.
gmake[1]: *** [tools/gyp/v8_base.target.x64.mk:219: /usr/local/lib/ruby/gems/2.3/gems/libv8-3.16.14.15/vendor/v8/out/x64.release/obj.target/v8_base/src/platform-freebsd.o] Fehler 1
gmake[1]: Verzeichnis „/usr/local/lib/ruby/gems/2.3/gems/libv8-3.16.14.15/vendor/v8/out“ wird verlassen
gmake: *** [Makefile:195: x64.release] Fehler 2
/usr/local/lib/ruby/gems/2.3/gems/libv8-3.16.14.15/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive
'/usr/local/lib/ruby/gems/2.3/gems/libv8-3.16.14.15/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
        from /usr/local/lib/ruby/gems/2.3/gems/libv8-3.16.14.15/ext/libv8/location.rb:35:in `each'
        from /usr/local/lib/ruby/gems/2.3/gems/libv8-3.16.14.15/ext/libv8/location.rb:35:in `verify_installation!'
        from /usr/local/lib/ruby/gems/2.3/gems/libv8-3.16.14.15/ext/libv8/location.rb:26:in `install!'
        from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.3/gems/libv8-3.16.14.15 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.3/extensions/amd64-freebsd-11/2.3/libv8-3.16.14.15/gem_make.out
```

Und nix geht mehr ...

### Infos:

* Used Zammad version: 1.3
* Operating system: FreeBSD 11.0
* Ruby version 2.3.3

**Comment by ntinti** [comment]
Siehe:
https://github.com/cowboyd/libv8/issues/231
https://github.com/cowboyd/libv8/commit/e60906ce62a3305406b1be7a0d6f333cf67138aa

**Comment by martini** [comment]
@ntinti Thanks for reporting this issue. Since it's not Zammad related I'll close it.

Feel free to reopen if you don't feel so.

**Comment by ntinti** [comment]
Zammad can't be installed on FreeBSD with this version of libV8. Maybe you are not interested on FreeBSD. But if you want that zammad is installable you should make a little patch on "platform-freebsd.cc" or use another version of libV8 for zammad.
