### ISSUE TITLE
Uncaught TypeError: Cannot read property 'state_current' of null

### ISSUE THREAD

**Issue by LukasReschke** [zammad/zammad#830]
### Infos:

* Used Zammad version: 1.3.0-1488535173.5bfe87f.xenial
* Operating system: Ubuntu 16.04
* Browser: Chrome 56.0.2924.87 on OS X

### Expected behavior:

* Menu point works fine

### Actual behavior:

* JS error is thrown:

```
application-6d90a18….js:22 Uncaught TypeError: Cannot read property 'state_current' of null
    at Function.App.Setting.n.get (https://support.domain.com/assets/application-6d90a180f260ee9691993abf45eb1afe33644d5fd89a5459cf0057511fe8b17e.js:22:24648)
    at o.render (https://support.domain.com/assets/application-6d90a180f260ee9691993abf45eb1afe33644d5fd89a5459cf0057511fe8b17e.js:40:20231)
    at https://support.domain.com/assets/application-6d90a180f260ee9691993abf45eb1afe33644d5fd89a5459cf0057511fe8b17e.js:40:18191
    at Function.<anonymous> (https://support.domain.com/assets/application-6d90a180f260ee9691993abf45eb1afe33644d5fd89a5459cf0057511fe8b17e.js:21:22866)
    at Function.trigger (https://support.domain.com/assets/application-6d90a180f260ee9691993abf45eb1afe33644d5fd89a5459cf0057511fe8b17e.js:7:26082)
    at Function.i.refresh (https://support.domain.com/assets/application-6d90a180f260ee9691993abf45eb1afe33644d5fd89a5459cf0057511fe8b17e.js:7:30249)
    at Object.e.force.App.(anonymous function).count.App.Ajax.request.success (https://support.domain.com/assets/application-6d90a180f260ee9691993abf45eb1afe33644d5fd89a5459cf0057511fe8b17e.js:21:27528)
    at c (https://support.domain.com/assets/application-6d90a180f260ee9691993abf45eb1afe33644d5fd89a5459cf0057511fe8b17e.js:2:8518)
    at Object.fireWith [as resolveWith] (https://support.domain.com/assets/application-6d90a180f260ee9691993abf45eb1afe33644d5fd89a5459cf0057511fe8b17e.js:2:9286)
    at i (https://support.domain.com/assets/application-6d90a180f260ee9691993abf45eb1afe33644d5fd89a5459cf0057511fe8b17e.js:3:11415)
```

### Steps to reproduce the behavior:

* Open "Time Accounting" in admin interface

**Comment by LukasReschke** [comment]
Related to https://github.com/zammad/zammad/issues/829
