### ISSUE TITLE
unprocessable mails

### ISSUE THREAD

**Issue by celevra** [zammad/zammad#848]
* Used Zammad version: 1.3.0
* Operating system: Ubuntu 16.04

```
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//f012014f9dcfee5fd6e0c56157a19a9f.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'ticket_states.default_create' in 'where clause': SELECT  `ticket_states`.* FROM `ticket_states` WHERE `ticket_states`.`default_create` = 1 LIMIT 1>"
^C
root@7ed88131cb17:/opt/zammad/log# cat /opt/zammad/tmp/unprocessable_mail//f012014f9dcfee5fd6e0c56157a19a9f.eml
Received: from exchange.zeitschel.net (2a01:4f8:201:8065::12) by
 exchange.zeitschel.net (2a01:4f8:201:8065::12) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.1.669.32 via Mailbox Transport; Thu, 16 Mar 2017 10:32:38 +0100
Received: from exchange.zeitschel.net (2a01:4f8:201:8065::12) by
 exchange.zeitschel.net (2a01:4f8:201:8065::12) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.1.669.32; Thu, 16 Mar 2017 10:32:38 +0100
Received: from exchange.zeitschel.net ([fe80::4c18:466c:6a14:d04]) by
 exchange.zeitschel.net ([fe80::4c18:466c:6a14:d04%12]) with mapi id
 15.01.0669.032; Thu, 16 Mar 2017 10:32:38 +0100
From: Philipp Zeitschel <philipp@zeitschel.net>
To: Lion Keen Support <help@lionkeen.net>
Subject: test
Thread-Topic: test
Thread-Index: AdKeOC4zeSIa1dNQQI6m+LZNGCoZ7w==
Date: Thu, 16 Mar 2017 10:32:37 +0100
Message-ID: <8daf90008ca44b91b959646c196b2c66@zeitschel.net>
Accept-Language: de-DE, en-US
Content-Language: de-DE
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 04
X-MS-Exchange-Organization-AuthSource: exchange.zeitschel.net
X-MS-Has-Attach:
X-MS-Exchange-Organization-Network-Message-Id:
        0da2aedb-38d2-489c-2a49-08d46c4f62b5
X-MS-Exchange-Organization-SCL: -1
X-MS-TNEF-Correlator:
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0

test

```

regards

**Comment by martini** [comment]
Hi @celevra 

a migration was not running. Your issue seems to be a duplicate of #829 

Can you execute "rake db:migrate" as zammad user? What is the output?

 -Martin

**Comment by celevra** [comment]
can i run db:migrate on every start? Or is there an indicator when i have to run db:migrate?

```
root@7ed88131cb17:/opt/zammad# rake db:migrate
rake aborted!
NameError: uninitialized constant Rack::LiveReload
/opt/zammad/config/environments/development.rb:37:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `instance_eval'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `configure'
/opt/zammad/config/environments/development.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `each'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/opt/zammad/config/environment.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by martini** [comment]
> can i run db:migrate on every start? 

Yes, you could do so.

**Normally** you just need to run "rake db:migrate" if you upgraded your Zammad application, to do the database upgrade for the upgraded Zammad version.

Anyway: You can execute "rake db:migrate" multiple times without problems.

**Comment by celevra** [comment]
thank you for the fast answers, great service!

**Comment by martini** [comment]
One more note:

> root@7ed88131cb17:/opt/zammad# rake db:migrate
rake aborted!
NameError: uninitialized constant Rack::LiveReload

You need to set your RAILS_ENV to production first. It seems that it is unset.

export RAILS_ENV=production

Then execute rake and so on.

Thanks for feedback.

**Comment by celevra** [comment]
yep, i posted to fast, thats why i edited my comment. rake db:migrate helped
