### ISSUE TITLE
Misconfigured Trigger can cause silent failures/backtrace

### ISSUE THREAD

**Issue by eliasp** [zammad/zammad#874]
### Infos:

* Used Zammad version: 1.4.0
* Operating system: Debian 8.7
* Browser + version: doesn't matter

### Expected behavior:

* Misconfiguring a trigger should:
  - let the user know in the UI about the configuration issue and prevent saving it
  - not crash the backend and log a meaningful message about the configuration issue instead
  - log the configuration issue in a web-accessible eventlog so a sysadmin isn't required to investigate a user-caused issue

### Actual behavior:

* The trigger will silently fail and log a backtrace in `production.log` (reformatted for better readability):
```
E, [2017-03-22T13:40:04.604155 #13367] ERROR -- : ERROR: Transaction::Trigger
E, [2017-03-22T13:40:04.605364 #13367] ERROR -- : ERROR: #<NoMethodError: undefined method `zero?' for nil:NilClass>
E, [2017-03-22T13:40:04.605511 #13367] ERROR -- : [
    "/opt/zammad/app/models/transaction/trigger.rb:133:in `block (2 levels) in perform'",
    "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'",
    "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'",
    "/opt/zammad/app/models/transaction/trigger.rb:48:in `block in perform'",
    "/opt/zammad/app/models/transaction.rb:12:in `block in execute'",
    "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'",
    "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'",
    "/opt/zammad/app/models/transaction.rb:10:in `execute'",
    "/opt/zammad/app/models/transaction/trigger.rb:47:in `perform'",
    "/opt/zammad/app/models/observer/transaction.rb:57:in `execute_singel_backend'",
    "/opt/zammad/app/models/observer/transaction.rb:43:in `block (3 levels) in perform'",
    "/opt/zammad/app/models/observer/transaction.rb:42:in `each'",
    "/opt/zammad/app/models/observer/transaction.rb:42:in `block (2 levels) in perform'",
    "/opt/zammad/app/models/observer/transaction.rb:39:in `each'",
    "/opt/zammad/app/models/observer/transaction.rb:39:in `block in perform'",
    "/opt/zammad/app/models/observer/transaction.rb:38:in `each'",
    "/opt/zammad/app/models/observer/transaction.rb:38:in `perform'",
    "/opt/zammad/app/models/observer/transaction.rb:14:in `commit'",
    "/opt/zammad/app/models/transaction.rb:16:in `block in execute'",
    "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'",
    "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'",
    "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'",
    "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'",
    "/opt/zammad/app/models/transaction.rb:10:in `execute'",
    "/opt/zammad/app/models/channel/email_parser.rb:470:in `_process'",
    "/opt/zammad/app/models/channel/email_parser.rb:413:in `process'",
    "/opt/zammad/app/models/channel/driver/imap.rb:188:in `block in fetch'",
    "/opt/zammad/app/models/channel/driver/imap.rb:168:in `each'",
    "/opt/zammad/app/models/channel/driver/imap.rb:168:in `fetch'",
    "/opt/zammad/app/models/channel.rb:62:in `fetch'",
    "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'",
    "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'",
    "/opt/zammad/app/models/channel.rb:30:in `fetch'",
    "(eval):1:in `_start_job'",
    "/opt/zammad/app/models/scheduler.rb:90:in `eval'",
    "/opt/zammad/app/models/scheduler.rb:90:in `_start_job'",
    "/opt/zammad/app/models/scheduler.rb:57:in `block (2 levels) in start_job'",
    "/opt/zammad/app/models/scheduler.rb:56:in `loop'",
    "/opt/zammad/app/models/scheduler.rb:56:in `block in start_job'"
]
```

### Steps to reproduce the behavior:

* Open the configuration of the default `auto reply (on new tickets)` Trigger
* Click the `+` button in the condition list which will add:
![spectacle cf6323](https://cloud.githubusercontent.com/assets/48491/24201485/724bb98a-0f10-11e7-8230-00442d7cd3e8.png) (yes, this configuration doesn't make sense, but that's what the UI should warn the user about)
* Click **Submit** to save the configuration
* Send a new mail to the system and monitor `production.log`

**Comment by rolfschmidt** [comment]
Hi @eliasp 
we added a new check for trigger, overviews, jobs and slas to check the validity of the conditions. In case of a invalid condition you will now have an error message:

![grafik](https://cloud.githubusercontent.com/assets/5445062/25487811/973aa118-2b65-11e7-99b2-c0e9ba76eed3.png)

Trigger transactions are also improved to handle invalid conditions and it should not crash anymore in your case.

Thank you very much for report! The changes are merged to the develop branch.

-Rolf
